alloc_cbm_var – CABLE
alloc_cbm_var Interface
3 statements
Source File
public interface alloc_cbm_var
Calls
Called by
Contents
Module Procedures
alloc_balances_type alloc_soil_parameter_type alloc_soil_snow_type alloc_veg_parameter_type alloc_canopy_type alloc_radiation_type alloc_roughness_type alloc_air_type alloc_met_type alloc_sum_flux_type alloc_bgc_pool_type alloc_climate_type
Module Procedures
public subroutine alloc_balances_type(var, mp)
Arguments
Type Intent Optional Attributes Name
type(balances_type), intent(inout) :: var
integer, intent(in) :: mp
public subroutine alloc_soil_parameter_type(var, mp)
Arguments
Type Intent Optional Attributes Name
type(soil_parameter_type), intent(inout) :: var
integer, intent(in) :: mp
public subroutine alloc_soil_snow_type(var, mp)
Arguments
Type Intent Optional Attributes Name
type(soil_snow_type), intent(inout) :: var
integer, intent(in) :: mp
public subroutine alloc_veg_parameter_type(var, mp)
Arguments
Type Intent Optional Attributes Name
type(veg_parameter_type), intent(inout) :: var
integer, intent(in) :: mp
public subroutine alloc_canopy_type(var, mp)
Arguments
Type Intent Optional Attributes Name
type(canopy_type), intent(inout) :: var
integer, intent(in) :: mp
public subroutine alloc_radiation_type(var, mp)
Arguments
Type Intent Optional Attributes Name
type(radiation_type), intent(inout) :: var
integer, intent(in) :: mp
public subroutine alloc_roughness_type(var, mp)
Arguments
Type Intent Optional Attributes Name
type(roughness_type), intent(inout) :: var
integer, intent(in) :: mp
public subroutine alloc_air_type(var, mp)
Arguments
Type Intent Optional Attributes Name
type(air_type), intent(inout) :: var
integer, intent(in) :: mp
public subroutine alloc_met_type(var, mp)
Arguments
Type Intent Optional Attributes Name
type(met_type), intent(inout) :: var
integer, intent(in) :: mp
public subroutine alloc_sum_flux_type(var, mp)
Arguments
Type Intent Optional Attributes Name
type(sum_flux_type), intent(inout) :: var
integer, intent(in) :: mp
private subroutine alloc_bgc_pool_type(var, mp)
Arguments
Type Intent Optional Attributes Name
type(bgc_pool_type), intent(inout) :: var
integer, intent(in) :: mp
public subroutine alloc_climate_type(var, mp)
Arguments
Type Intent Optional Attributes Name
type(climate_type), intent(inout) :: var
integer, intent(in) :: mp
Call graph
alloc_cbm_var calls alloc_air_type, alloc_balances_type, alloc_bgc_pool_type, alloc_canopy_type, alloc_climate_type, alloc_met_type, alloc_radiation_type, alloc_roughness_type, alloc_soil_parameter_type, alloc_soil_snow_type, alloc_sum_flux_type, alloc_veg_parameter_type
alloc_canopy_type calls sublayer_dz
alloc_soil_parameter_type calls bch_vec, clay_vec, drain_dens, elev, elev_std, gwbch_vec, gwdz, gwhyds_vec, gwrhosoil_vec, gwssat_vec, gwsucs_vec, gwwatr, gwz, hyds_vec, org_vec, rhosoil_vec, sand_vec, sfc_vec, silt_vec, slope, slope_std, ssat_vec, sucs_vec, swilt_vec, watr
alloc_soil_snow_type calls dhkdw, dsmpdw, evapfbl, fland, fracice, gwdhkdw, gwdsmpdw, gwhk, gwsmp, gwwb, gwwbeq, gwzq, hk, icefrac, ifland, otgg, otss, otss_0, owetfac, qasrf, qfsrf, qhlev, qhz, qrecharge, qssrf, qstss, rh_srf, rt_qh_sublayer, rtevap_sat, rtevap_unsat, satfrac, sinfil, smp, t_snwlr, tevap, tggav, tilefrac, totenbal, totenbal2, totwblake, tprecip, trnoff, wb_lake, wbeq, wbfice, wbliq, wbtot, wbtot1, wbtot2, wetfac, wmice, wmliq, wmtot, wtd, zq
alloc_veg_parameter_type calls a1gs, alpha, cfrd, conkc0, conko0, convex, d0gs, deciduous, ekc, eko, extkn, froot, gswmin, refl, taul, vlaimax, wai
allocate_cable_vars calls alloc_cbm_var
climate_init calls alloc_cbm_var
mpidrv_master calls alloc_cbm_var, load_parameters, master_climate_types
load_parameters calls allocate_cable_vars
master_climate_types calls climate_init
worker_cable_params calls allocate_cable_vars
worker_climate_types calls climate_init
cable_offline_driver calls climate_init, load_parameters
mpi_driver calls mpidrv_master, mpidrv_worker
mpidrv_worker calls worker_cable_params, worker_climate_types