dealloc_cbm_var – CABLE
dealloc_cbm_var Interface
3 statements
Source File
public interface dealloc_cbm_var
Calls
Contents
Module Procedures
dealloc_balances_type dealloc_soil_parameter_type dealloc_soil_snow_type dealloc_veg_parameter_type dealloc_canopy_type dealloc_radiation_type dealloc_roughness_type dealloc_air_type dealloc_met_type dealloc_sum_flux_type dealloc_bgc_pool_type
Module Procedures
public subroutine dealloc_balances_type(var)
Arguments
Type Intent Optional Attributes Name
type(balances_type), intent(inout) :: var
public subroutine dealloc_soil_parameter_type(var)
Arguments
Type Intent Optional Attributes Name
type(soil_parameter_type), intent(inout) :: var
public subroutine dealloc_soil_snow_type(var)
Arguments
Type Intent Optional Attributes Name
type(soil_snow_type), intent(inout) :: var
public subroutine dealloc_veg_parameter_type(var)
Arguments
Type Intent Optional Attributes Name
type(veg_parameter_type), intent(inout) :: var
public subroutine dealloc_canopy_type(var)
Arguments
Type Intent Optional Attributes Name
type(canopy_type), intent(inout) :: var
public subroutine dealloc_radiation_type(var)
Arguments
Type Intent Optional Attributes Name
type(radiation_type), intent(inout) :: var
public subroutine dealloc_roughness_type(var)
Arguments
Type Intent Optional Attributes Name
type(roughness_type), intent(inout) :: var
public subroutine dealloc_air_type(var)
Arguments
Type Intent Optional Attributes Name
type(air_type), intent(inout) :: var
public subroutine dealloc_met_type(var)
Arguments
Type Intent Optional Attributes Name
type(met_type), intent(inout) :: var
public subroutine dealloc_sum_flux_type(var)
Arguments
Type Intent Optional Attributes Name
type(sum_flux_type), intent(inout) :: var
private subroutine dealloc_bgc_pool_type(var)
Arguments
Type Intent Optional Attributes Name
type(bgc_pool_type), intent(inout) :: var
Call graph
dealloc_cbm_var calls dealloc_air_type, dealloc_balances_type, dealloc_bgc_pool_type, dealloc_canopy_type, dealloc_met_type, dealloc_radiation_type, dealloc_roughness_type, dealloc_soil_parameter_type, dealloc_soil_snow_type, dealloc_sum_flux_type, dealloc_veg_parameter_type