define_ovar – CABLE
define_ovar Interface
6 statements
Source File
public interface define_ovar
Calls
Called by
Contents
Module Procedures
define_output_variable_r1 define_output_variable_r2 define_output_parameter_r1 define_output_parameter_r2
Module Procedures
private subroutine define_output_variable_r1(ncid, varID, vname, vunits, longname, writepatch, dimswitch, xID, yID, zID, landID, patchID, tID)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncid
integer, intent(out) :: varID
character(len=*), intent(in) :: vname
character(len=*), intent(in) :: vunits
character(len=*), intent(in) :: longname
logical, intent(in) :: writepatch
character(len=*), intent(in) :: dimswitch
integer, intent(in) :: xID
integer, intent(in) :: yID
integer, intent(in) :: zID
integer, intent(in) :: landID
integer, intent(in) :: patchID
integer, intent(in) :: tID
private subroutine define_output_variable_r2(ncid, varID, vname, vunits, longname, writepatch, dimswitch, xID, yID, zID, landID, patchID, othdimID, tID)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncid
integer, intent(out) :: varID
character(len=*), intent(in) :: vname
character(len=*), intent(in) :: vunits
character(len=*), intent(in) :: longname
logical, intent(in) :: writepatch
character(len=*), intent(in) :: dimswitch
integer, intent(in) :: xID
integer, intent(in) :: yID
integer, intent(in) :: zID
integer, intent(in) :: landID
integer, intent(in) :: patchID
integer, intent(in) :: othdimID
integer, intent(in) :: tID
private subroutine define_output_parameter_r1(ncid, parID, pname, punits, longname, writepatch, dimswitch, xID, yID, zID, landID, patchID, restart)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncid
integer, intent(out) :: parID
character(len=*), intent(in) :: pname
character(len=*), intent(in) :: punits
character(len=*), intent(in) :: longname
logical, intent(in) :: writepatch
character(len=*), intent(in) :: dimswitch
integer, intent(in) :: xID
integer, intent(in) :: yID
integer, intent(in) :: zID
integer, intent(in) :: landID
integer, intent(in) :: patchID
logical, intent(in), optional :: restart
private subroutine define_output_parameter_r2(ncid, parID, pname, punits, longname, writepatch, othdimID, dimswitch, xID, yID, zID, landID, patchID, restart)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncid
integer, intent(out) :: parID
character(len=*), intent(in) :: pname
character(len=*), intent(in) :: punits
character(len=*), intent(in) :: longname
logical, intent(in) :: writepatch
integer, intent(in) :: othdimID
character(len=*), intent(in) :: dimswitch
integer, intent(in) :: xID
integer, intent(in) :: yID
integer, intent(in) :: zID
integer, intent(in) :: landID
integer, intent(in) :: patchID
logical, intent(in), optional :: restart
Call graph
define_ovar calls define_output_parameter_r1, define_output_parameter_r2, define_output_variable_r1, define_output_variable_r2
define_output_parameter_r1 calls grid, nf90_def_var, nf90_put_att, nc_abort
define_output_parameter_r2 calls grid, nf90_def_var, nf90_put_att, nc_abort
define_output_variable_r1 calls grid, nf90_def_var, nf90_put_att, nc_abort
define_output_variable_r2 calls grid, nf90_def_var, nf90_put_att, nc_abort
nc_abort calls nf90_strerror
create_landuse_cable_restart calls define_ovar
create_restart calls define_ovar
open_output_file calls define_ovar
mpidrv_master calls create_landuse_cable_restart, create_restart, open_output_file
cable_offline_driver calls create_landuse_cable_restart, create_restart, open_output_file
mpi_driver calls mpidrv_master