generic_thomas – CABLE
generic_thomas Interface
4 statements
Source File
public interface generic_thomas
Calls
Called by
Contents
Module Procedures
generic_thomas_1d generic_thomas_2d
Module Procedures
private subroutine generic_thomas_1d(n, A, B, C, r, u, err)
Arguments
Type Intent Optional Attributes Name
integer(kind=i_d), intent(in) :: n
real(kind=r_2), intent(in), DIMENSION(1:n,1:2,1:2) :: A
real(kind=r_2), intent(in), DIMENSION(1:n,1:2,1:2) :: B
real(kind=r_2), intent(in), DIMENSION(1:n,1:2,1:2) :: C
real(kind=r_2), intent(in), DIMENSION(1:n,1:2) :: r
real(kind=r_2), intent(out), DIMENSION(1:n,1:2) :: u
integer(kind=i_d), intent(out), optional :: err
private subroutine generic_thomas_2d(mp, n, A, B, C, r, u, err)
Arguments
Type Intent Optional Attributes Name
integer(kind=i_d), intent(in) :: mp
integer(kind=i_d), intent(in) :: n
real(kind=r_2), intent(in), DIMENSION(1:mp,1:n,1:2,1:2) :: A
real(kind=r_2), intent(in), DIMENSION(1:mp,1:n,1:2,1:2) :: B
real(kind=r_2), intent(in), DIMENSION(1:mp,1:n,1:2,1:2) :: C
real(kind=r_2), intent(in), DIMENSION(1:mp,1:n,1:2) :: r
real(kind=r_2), intent(out), DIMENSION(1:mp,1:n,1:2) :: u
integer(kind=i_d), intent(out), optional :: err
Call graph
generic_thomas calls generic_thomas_1d, generic_thomas_2d
massman_sparse_1d calls generic_thomas
massman_sparse_2d calls generic_thomas
massman_sparse calls massman_sparse_1d, massman_sparse_2d
get_and_solve_eqn calls massman_sparse
iflux_loop calls get_and_solve_eqn
timestep_loop calls iflux_loop
solve calls timestep_loop
sli_main calls solve