get_var_nc – CABLE
get_var_nc Interface
3 statements
Source File
public interface get_var_nc
Calls
Contents
Module Procedures
get_var_ncr2 get_var_ncr3
Module Procedures
public subroutine get_var_ncr2(ncid, var_name, var, n_call)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncid
character(len=*), intent(in) :: var_name
real(kind=r_2), intent(out), dimension(:) :: var
integer :: n_call
public subroutine get_var_ncr3(ncid, var_name, var, n_call, nl)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncid
character(len=*), intent(in) :: var_name
real(kind=r_2), intent(out), dimension(:,:) :: var
integer, intent(in) :: n_call
integer, intent(in) :: nl
Call graph
get_var_nc calls get_var_ncr2, get_var_ncr3
get_var_ncr2 calls nf90_get_var, nf90_inq_varid, stderr_nc
get_var_ncr3 calls nf90_get_var, nf90_inq_varid, stderr_nc
stderr_nc calls nf90_strerror