massman_sparse – CABLE
massman_sparse Interface
4 statements
Source File
public interface massman_sparse
Calls
Called by
Contents
Module Procedures
massman_sparse_1d massman_sparse_2d
Module Procedures
private subroutine massman_sparse_1d(aa, aah, bb, bbh, cc, cch, dd, ddh, ee, eeh, ff, ffh, gg, ggh, dy, dT, condition, err)
Arguments
Type Intent Optional Attributes Name
real(kind=r_2), intent(in), DIMENSION(:) :: aa
real(kind=r_2), intent(in), DIMENSION(:) :: aah
real(kind=r_2), intent(in), DIMENSION(:) :: bb
real(kind=r_2), intent(in), DIMENSION(:) :: bbh
real(kind=r_2), intent(in), DIMENSION(:) :: cc
real(kind=r_2), intent(in), DIMENSION(:) :: cch
real(kind=r_2), intent(in), DIMENSION(:) :: dd
real(kind=r_2), intent(in), DIMENSION(:) :: ddh
real(kind=r_2), intent(in), DIMENSION(:) :: ee
real(kind=r_2), intent(in), DIMENSION(:) :: eeh
real(kind=r_2), intent(in), DIMENSION(:) :: ff
real(kind=r_2), intent(in), DIMENSION(:) :: ffh
real(kind=r_2), intent(in), DIMENSION(:) :: gg
real(kind=r_2), intent(in), DIMENSION(:) :: ggh
real(kind=r_2), intent(out), DIMENSION(:) :: dy
real(kind=r_2), intent(out), DIMENSION(:) :: dT
integer(kind=i_d), intent(in), optional :: condition
integer(kind=i_d), intent(out), optional :: err
private subroutine massman_sparse_2d(aa, aah, bb, bbh, cc, cch, dd, ddh, ee, eeh, ff, ffh, gg, ggh, dy, dT, condition, err)
Arguments
Type Intent Optional Attributes Name
real(kind=r_2), intent(in), DIMENSION(:,:) :: aa
real(kind=r_2), intent(in), DIMENSION(:,:) :: aah
real(kind=r_2), intent(in), DIMENSION(:,:) :: bb
real(kind=r_2), intent(in), DIMENSION(:,:) :: bbh
real(kind=r_2), intent(in), DIMENSION(:,:) :: cc
real(kind=r_2), intent(in), DIMENSION(:,:) :: cch
real(kind=r_2), intent(in), DIMENSION(:,:) :: dd
real(kind=r_2), intent(in), DIMENSION(:,:) :: ddh
real(kind=r_2), intent(in), DIMENSION(:,:) :: ee
real(kind=r_2), intent(in), DIMENSION(:,:) :: eeh
real(kind=r_2), intent(in), DIMENSION(:,:) :: ff
real(kind=r_2), intent(in), DIMENSION(:,:) :: ffh
real(kind=r_2), intent(in), DIMENSION(:,:) :: gg
real(kind=r_2), intent(in), DIMENSION(:,:) :: ggh
real(kind=r_2), intent(out), DIMENSION(:,:) :: dy
real(kind=r_2), intent(out), DIMENSION(:,:) :: dT
integer(kind=i_d), intent(in), optional :: condition
integer(kind=i_d), intent(out), optional :: err
Call graph
massman_sparse calls massman_sparse_1d, massman_sparse_2d
massman_sparse_1d calls generic_thomas
massman_sparse_2d calls generic_thomas
generic_thomas calls generic_thomas_1d, generic_thomas_2d
get_and_solve_eqn calls massman_sparse
iflux_loop calls get_and_solve_eqn
timestep_loop calls iflux_loop
solve calls timestep_loop
sli_main calls solve