readpar – CABLE
readpar Interface
7 statements
Source File
public interface readpar
Calls
Called by
Contents
Module Procedures
readpar_i readpar_r readpar_rd readpar_r2 readpar_r2d
Module Procedures
private subroutine readpar_i(ncid, parname, completeSet, var_i, filename, npatch, dimswitch, from_restart, INpatch)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncid
character(len=*), intent(in) :: parname
logical, intent(inout) :: completeSet
integer, intent(inout), DIMENSION(:) :: var_i
character(len=*), intent(in) :: filename
integer, intent(in) :: npatch
character(len=*), intent(in) :: dimswitch
logical, intent(in), optional :: from_restart
integer, intent(in), optional :: INpatch
private subroutine readpar_r(ncid, parname, completeSet, var_r, filename, npatch, dimswitch, from_restart, INpatch)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncid
character(len=*), intent(in) :: parname
logical, intent(inout) :: completeSet
real(kind=4), intent(inout), DIMENSION(:) :: var_r
character(len=*), intent(in) :: filename
integer, intent(in) :: npatch
character(len=*), intent(in) :: dimswitch
logical, intent(in), optional :: from_restart
integer, intent(in), optional :: INpatch
private subroutine readpar_rd(ncid, parname, completeSet, var_rd, filename, npatch, dimswitch, from_restart, INpatch)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncid
character(len=*), intent(in) :: parname
logical, intent(inout) :: completeSet
real(kind=r_2), intent(inout), DIMENSION(:) :: var_rd
character(len=*), intent(in) :: filename
integer, intent(in) :: npatch
character(len=*), intent(in) :: dimswitch
logical, intent(in), optional :: from_restart
integer, intent(in), optional :: INpatch
private subroutine readpar_r2(ncid, parname, completeSet, var_r2, filename, npatch, dimswitch, from_restart, INpatch)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncid
character(len=*), intent(in) :: parname
logical, intent(inout) :: completeSet
real(kind=4), intent(inout), DIMENSION(:,:) :: var_r2
character(len=*), intent(in) :: filename
integer, intent(in) :: npatch
character(len=*), intent(in) :: dimswitch
logical, intent(in), optional :: from_restart
integer, intent(in), optional :: INpatch
private subroutine readpar_r2d(ncid, parname, completeSet, var_r2d, filename, npatch, dimswitch, from_restart, INpatch)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncid
character(len=*), intent(in) :: parname
logical, intent(inout) :: completeSet
real(kind=r_2), intent(inout), DIMENSION(:, :) :: var_r2d
character(len=*), intent(in) :: filename
integer, intent(in) :: npatch
character(len=*), intent(in) :: dimswitch
logical, intent(in), optional :: from_restart
integer, intent(in), optional :: INpatch
Call graph
readpar calls readpar_i, readpar_r, readpar_r2, readpar_r2d, readpar_rd
readpar_i calls nf90_get_var, nf90_inq_varid, nf90_inquire_variable, nc_abort
readpar_r calls nf90_get_var, nf90_inq_varid, nf90_inquire_variable, nc_abort
readpar_r2 calls nf90_get_var, nf90_inq_varid, nf90_inquire_variable, nc_abort
readpar_r2d calls nf90_get_var, nf90_inq_varid, nf90_inquire_variable, nc_abort
readpar_rd calls nf90_get_var, nf90_inq_varid, nf90_inquire_variable, nc_abort
nc_abort calls nf90_strerror
extrarestart calls readpar
get_parameters_met calls readpar
get_restart_data calls readpar, extrarestart
load_parameters calls get_parameters_met, get_restart_data
mpidrv_master calls load_parameters
cable_offline_driver calls load_parameters
mpi_driver calls mpidrv_master