write_ovar – CABLE
write_ovar Interface
8 statements
Source File
public interface write_ovar
Calls
Called by
Contents
Module Procedures
write_output_variable_r1 write_output_variable_r2 write_output_parameter_r1 write_output_parameter_r1d write_output_parameter_r2 write_output_parameter_r2d
Module Procedures
private subroutine write_output_variable_r1(ktau, ncid, varID, vname, var_r1, vrange, writepatch, dimswitch, met)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ktau
integer, intent(in) :: ncid
integer, intent(in) :: varID
character(len=*), intent(in) :: vname
real(kind=4), intent(in), DIMENSION(:) :: var_r1
real, intent(in), DIMENSION(2) :: vrange
logical, intent(in) :: writepatch
character(len=*), intent(in) :: dimswitch
type(met_type), intent(in) :: met
private subroutine write_output_variable_r2(ktau, ncid, varID, vname, var_r2, vrange, writepatch, dimswitch, met)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ktau
integer, intent(in) :: ncid
integer, intent(in) :: varID
character(len=*), intent(in) :: vname
real(kind=4), intent(in), DIMENSION(:, :) :: var_r2
real, intent(in), DIMENSION(2) :: vrange
logical, intent(in) :: writepatch
character(len=*), intent(in) :: dimswitch
type(met_type), intent(in) :: met
private subroutine write_output_parameter_r1(ncid, parID, pname, par_r1, prange, writepatch, dimswitch, restart)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncid
integer, intent(in) :: parID
character(len=*), intent(in) :: pname
real(kind=4), intent(in), DIMENSION(:) :: par_r1
real, intent(in), DIMENSION(2) :: prange
logical, intent(in) :: writepatch
character(len=*), intent(in) :: dimswitch
logical, intent(in), optional :: restart
private subroutine write_output_parameter_r1d(ncid, parID, pname, par_r1d, prange, writepatch, dimswitch, restart)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncid
integer, intent(in) :: parID
character(len=*), intent(in) :: pname
real(kind=r_2), intent(in), DIMENSION(:) :: par_r1d
real, intent(in), DIMENSION(2) :: prange
logical, intent(in) :: writepatch
character(len=*), intent(in) :: dimswitch
logical, intent(in), optional :: restart
private subroutine write_output_parameter_r2(ncid, parID, pname, par_r2, prange, writepatch, dimswitch, restart)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncid
integer, intent(in) :: parID
character(len=*), intent(in) :: pname
real(kind=4), intent(in), DIMENSION(:, :) :: par_r2
real, intent(in), DIMENSION(2) :: prange
logical, intent(in) :: writepatch
character(len=*), intent(in) :: dimswitch
logical, intent(in), optional :: restart
private subroutine write_output_parameter_r2d(ncid, parID, pname, par_r2d, prange, writepatch, dimswitch, restart)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncid
integer, intent(in) :: parID
character(len=*), intent(in) :: pname
real(kind=r_2), intent(in), DIMENSION(:, :) :: par_r2d
real, intent(in), DIMENSION(2) :: prange
logical, intent(in) :: writepatch
character(len=*), intent(in) :: dimswitch
logical, intent(in), optional :: restart
Call graph
write_ovar calls write_output_parameter_r1, write_output_parameter_r1d, write_output_parameter_r2, write_output_parameter_r2d, write_output_variable_r1, write_output_variable_r2
write_output_parameter_r1 calls grid, nf90_put_var, nc_abort
write_output_parameter_r1d calls nf90_put_var, nc_abort
write_output_parameter_r2 calls grid, nf90_put_var, nc_abort
write_output_parameter_r2d calls nf90_put_var, nc_abort
write_output_variable_r1 calls grid, nf90_put_var, nc_abort, range_abort
write_output_variable_r2 calls grid, nf90_put_var, nc_abort, range_abort
nc_abort calls nf90_strerror
range_abort calls doy, hod, year
create_landuse_cable_restart calls write_ovar
create_restart calls write_ovar
open_output_file calls write_ovar
write_output calls write_ovar
mpidrv_master calls create_landuse_cable_restart, create_restart, open_output_file, write_output
cable_offline_driver calls create_landuse_cable_restart, create_restart, open_output_file, write_output
mpi_driver calls mpidrv_master