cable_offline_driver – CABLE
cable_offline_driver Program
642 statements
Source File
Uses
cable_namelist_util
casa_ncdf_module
casadimension
bgcdriver_mod
CABLE_site
casa_offline_inout_module
casavariable
phenvariable
cable_IO_vars_module
CABLE_CRU
cable_common_module
casa_inout_module
cable_write_module
POP_Types
cbl_soil_snow_init_special_module
CABLE_PLUME_MIP
POP_Constants
cable_def_types_mod
cable_input_module
CABLE_LUC_EXPT
cable_output_module
F90_UNIX
casa_cable
cable_cbm_module
landuse_constant
POPLUC_Module
POPLUC_Types
landuse_variable
cable_phys_constants_mod
cable_climate_mod
Calls
Contents
Variables
kstart mloop LALLOC ktau ktau_tot kend koffset koffset_met ktauday idoy nyear casa_it YYYY RYEAR RRRR NRRRR ctime LOY count_sum_casa wlogn dels GSWP_MID dum str1 str2 str3 met air canopy rad rough bal ssnow climate soil veg sum_flux bgc casabiome casapool casaflux sum_casapool sum_casaflux casamet casabal phen POP POPLUC PLUME CRU site LUC_EXPT lucmp cyear ncfile vegparmnew spinup spinConv spincasa l_casacnp l_landuse l_laiFeedbk l_vcmaxFeedbk CASAONLY CALL1 SPINon delsoilM delsoilT Metyear Y LOYtmp delgwM soilMtemp soilTtemp GWtemp etime heat_cap_lower_limit i x kk m np ivt Ftrunk_sumbal Fnew_sumbal trunk_sumbal new_sumbal new_sumfpn new_sumfe c1 rhoch xk nkend ioerror count_bal mlon mlat mpx luc_atransit luc_fharvw luc_xluh2cable arealand landmask cstart cend nap patchfrac_new
Variables
Type Attributes Name Initial
integer, parameter :: kstart = 1
integer, parameter :: mloop = 30
integer :: LALLOC
integer :: ktau
integer :: ktau_tot
integer :: kend
integer :: koffset = 0
integer :: koffset_met = 0
integer :: ktauday
integer :: idoy
integer :: nyear
integer :: casa_it
integer :: YYYY
integer :: RYEAR
integer :: RRRR
integer :: NRRRR
integer :: ctime
integer :: LOY
integer :: count_sum_casa
integer :: wlogn = 10001
real :: dels
integer, DIMENSION(:,:), ALLOCATABLE :: GSWP_MID
character(len=1) :: dum*9
character(len=1) :: str1*9
character(len=1) :: str2*9
character(len=1) :: str3*9
type(met_type) :: met
type(air_type) :: air
type(canopy_type) :: canopy
type(radiation_type) :: rad
type(roughness_type) :: rough
type(balances_type) :: bal
type(soil_snow_type) :: ssnow
type(climate_type) :: climate
type(soil_parameter_type) :: soil
type(veg_parameter_type) :: veg
type(sum_flux_type) :: sum_flux
type(bgc_pool_type) :: bgc
type(casa_biome) :: casabiome
type(casa_pool) :: casapool
type(casa_flux) :: casaflux
type(casa_pool) :: sum_casapool
type(casa_flux) :: sum_casaflux
type(casa_met) :: casamet
type(casa_balance) :: casabal
type(phen_variable) :: phen
type(POP_TYPE) :: POP
type(POPLUC_TYPE) :: POPLUC
type(PLUME_MIP_TYPE) :: PLUME
type(CRU_TYPE) :: CRU
type(site_TYPE) :: site
type(LUC_EXPT_TYPE) :: LUC_EXPT
type(landuse_mp) :: lucmp
character(len=1) :: cyear*4
character(len=1) :: ncfile*99
logical, SAVE :: vegparmnew = .FALSE.
logical, SAVE :: spinup = .FALSE.
logical, SAVE :: spinConv = .FALSE.
logical, SAVE :: spincasa = .FALSE.
logical, SAVE :: l_casacnp = .FALSE.
logical, SAVE :: l_landuse = .FALSE.
logical, SAVE :: l_laiFeedbk = .FALSE.
logical, SAVE :: l_vcmaxFeedbk = .FALSE.
logical, SAVE :: CASAONLY = .FALSE.
logical, SAVE :: CALL1 = .TRUE.
logical, SAVE :: SPINon = .TRUE.
real :: delsoilM
real :: delsoilT
integer :: Metyear
integer :: Y
integer :: LOYtmp
real :: delgwM = 1e-4
real, ALLOCATABLE, DIMENSION(:,:) :: soilMtemp
real, ALLOCATABLE, DIMENSION(:,:) :: soilTtemp
real, ALLOCATABLE, DIMENSION(:) :: GWtemp
real :: etime
real, allocatable :: heat_cap_lower_limit(:,:)
integer :: i
integer :: x
integer :: kk
integer :: m
integer :: np
integer :: ivt
character(len=30), parameter :: Ftrunk_sumbal = ".trunk_sumbal"
character(len=30), parameter :: Fnew_sumbal = "new_sumbal"
double precision :: trunk_sumbal = 0.0
double precision :: new_sumbal = 0.0
double precision :: new_sumfpn = 0.0
double precision :: new_sumfe = 0.0
real, ALLOCATABLE, SAVE :: c1(:,:)
real, ALLOCATABLE, SAVE :: rhoch(:,:)
real, ALLOCATABLE, SAVE :: xk(:,:)
integer :: nkend = 0
integer :: ioerror
integer :: count_bal = 0
integer :: mlon
integer :: mlat
integer :: mpx
real(kind=r_2), dimension(:,:,:), allocatable, save :: luc_atransit
real(kind=r_2), dimension(:,:), allocatable, save :: luc_fharvw
real(kind=r_2), dimension(:,:,:), allocatable, save :: luc_xluh2cable
real(kind=r_2), dimension(:), allocatable, save :: arealand
integer, dimension(:,:), allocatable, save :: landmask
integer, dimension(:), allocatable, save :: cstart
integer, dimension(:), allocatable, save :: cend
integer, dimension(:), allocatable, save :: nap
real(kind=r_2), dimension(:,:,:), allocatable, save :: patchfrac_new
Call graph
cable_offline_driver calls bgcdriver, cable_climate, casa_cnpflux, casa_feedback, casa_fluxout, casaonly_luc, cbm, climate_init, close_met_file, close_output_file, create_landuse_cable_restart, create_new_gridinfo, create_restart, cru_get_subdiurnal_met, cru_init, get_met_data, get_namelist_file_name, is_casa_time, is_leapyear, landuse_data, landuse_deallocate_mp, landuse_driver, load_parameters, luc_expt_init, lucdriver, nullify_write, open_met_file, open_output_file, plume_mip_get_met, plume_mip_init, pop_io, pop_luc_casa_transfer, popdriver, popluc_set_patchfrac, preparefiles, read_casa_dump, read_climate_restart_nc, site_get_co2_ndep, site_init, spec_init_soil_snow, spincasacnp, sumcflux, update_sum_casa, write_casa_dump, write_casa_output_nc, write_casa_restart_nc, write_climate_restart_nc, write_landuse_casa_restart_nc, write_luc_output_nc, write_luc_restart_nc, write_output, zero_sum_casa
bgcdriver calls cplant, float, fraccalloc, biogeochem, cable_phenology_clim
cable_climate calls alpha_pt_20, dmoist_31, dtemp_31, dtemp_91, float, mtemp_max_20, mtemp_min_20, biome1_pft, epsif
casa_cnpflux calls crgplant, crmplant, fcrmleafyear, fcrmrootyear, fcrmwoodyear
casa_feedback calls cplant, glai, glaimin, iveg, iveg2, nintercept, nplant, nslope, pplant, vcmax_np, rationcplantmax, rationcplantmin, sla, vcmax
casa_fluxout calls 100, 5, areacell, fcgppyear, fcneeyear, fcnppyear, fcrgrowyear, fcrmleafyear, fcrmrootyear, fcrmwoodyear, fcrsyear, float, fndepyear, fnfixyear, fnleachyear, fnlossyear, fnsnetyear, fnupyear, fpdustyear, fpleachyear, fplossyear, fpsnetyear, fpupyear, fpweayear, isoilm, isorder, iveg, lat, lon
casaonly_luc calls is_casa_time, pop_io, pop_luc_casa_transfer, popdriver, popluc_set_patchfrac, read_casa_dump, update_sum_casa, write_casa_output_nc, write_luc_restart_nc, zero_sum_casa, cgppspin, cplant, crmplantspin_1, crmplantspin_2, crmplantspin_3, doyphasespin_1, doyphasespin_2, doyphasespin_3, doyphasespin_4, frac_forest, fraccalloc, ilu, input, iveg, iwood, moistspin_1, moistspin_2, moistspin_3, moistspin_4, moistspin_5, moistspin_6, mtempspin, phasespin, prim_only, primf, biogeochem, pop_init_single, popluc_weights_transfer, poplucstep, read_luh2, write_luc_output_grid_nc, rationcplantmin, ratiopcplantmin, tairkspin, tsoilspin_1, tsoilspin_2, tsoilspin_3, tsoilspin_4, tsoilspin_5, tsoilspin_6
cbm calls fsd, albedo, carbon_pl, define_air, define_canopy, fsunlit_mask, fsunlit_veg_mask, fveg_mask, init_radiation, plantcarb, ruff_resist, snow_aging, soil_snow, soilcarb, tgg, tggsn
climate_init calls read_climate_restart_nc, alloc_cbm_var
close_met_file calls nf90_close, nc_abort
close_output_file calls ebal_tot, nf90_close, nc_abort, wbal_tot
create_landuse_cable_restart calls define_ovar, write_ovar, nf90_close, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_put_att, nf90_put_var, nf90_redef, nc_abort
create_new_gridinfo calls nf90_close, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_get_var, nf90_inq_varid, nf90_open, nf90_put_att, nf90_put_var, nc_abort, rangechk2, rangechk3, sort
create_restart calls define_ovar, write_ovar, nf90_close, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_put_att, nf90_put_var, nf90_redef, nc_abort
cru_get_subdiurnal_met calls avg_lwdn, coszen, doy, f_id, hod, metfile, ndepvals, nf90_close, phild, phisd, precip, cru_get_daily_met, doysod2ymdhms, get_cru_co2, get_cru_ndep, handle_err, open_cru_met, wgen_daily_constants, wgen_init, wgen_subdiurnal_met, temp, wind
cru_init calls avg_lwdn, met, ndepvals, nf90_close, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_open, get_unit, handle_err
get_met_data calls is_leapyear, doy, fsd, hod, lwdown, moy, nf90_get_var, nf90_inquire_variable, pmb, precip, precip_sn, nc_abort, rh_sh, sinbet, psurf, qair, qv, rainf, swdown, tair, tk, ua, wind, year
is_casa_time calls is_leapyear
landuse_data calls nf90_close, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_open, landuse_getdata, landuse_getxluh2, nc_abort
landuse_driver calls landuse_deallocate_mp, albedo, albsoil, albsoilsn, aphen, cansto, clabile, clitter, cplant, csoil, cwoodprod, dgdtg, doyphase, fes, fev, fhs, frac_sapwood, ga, gammzz, ghflux, gwwb, isflag, isoilm, isorder, iveg, nlitter, nplant, nsoil, nsoilmin, nwoodprod, osnowd, osnowd0, patchfrac_y, phase, plitter, pplant, landuse_allocate_mland, landuse_allocate_mp, landuse_checks, landuse_deallocate_mland, landuse_land2mpx, landuse_mp2land, landuse_transitx, landuse_update_mland, psoil, psoillab, psoilocc, psoilsorb, pwoodprod, rnof1, rnof2, runoff, sapwood_area, sdepth, sghflux, sla, smass, snage, snowd, ssdn, ssdnn, sumcbal, sumnbal, sumpbal, tgg, tggsn, trad, tss, vlai, wb, wbice, wbtot0
load_parameters calls pop_io, disturbance_interval, iveg, iveg2, nf90_inq_dimid, nf90_inquire_dimension, nf90_open, alloc_casavariable, alloc_phenvariable, alloc_sum_casavariable, allocate_cable_vars, casa_init, casa_readbiome, casa_readphen, check_parameter_values, derived_parameters, get_default_params, get_parameters_met, get_restart_data, handle_err, nc_abort, pop_init, popluc_init, report_parameters, write_cnp_params, write_default_params
luc_expt_init calls biome, f_id, grass, input, ivegp, mtemp_min20, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_open, prim_only, primaryf, get_unit, handle_err, read_climatefile, secdf, transfile, v_id, var_name
lucdriver calls cplant, frac_forest, frac_primf, input, iveg, iwood, prim_only, pop_init_single, popluc_weights_transfer, poplucstep, read_luh2, rationcplantmin, ratiopcplantmin
open_met_file calls is_leapyear, co2air, elev, lwdown, nf90_get_att, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_inquire_variable, nf90_open, doysod2ymdhms, find_metvarid, handle_err, nc_abort, ymdhms2doysod, psurf, qair, rainf, swdown, tair, wind
open_output_file calls albedo, area, autoresp, averaging, baresoilt, canopint, cant, co2air, dcdt, ebal, ecanop, esoil, evap, fwsoil, gpp, gwmoist, heteroresp, hsoil, hveg, define_ovar, write_ovar, lai, landuseflux, leafresp, littcarbcwd, littcarbmetabolic, littcarbstructural, lwdown, lwnet, nbp, nee, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_put_att, nf90_put_var, nf90_redef, niralbedo, npp, plantcarbfineroot, plantcarbleaf, plantcarbwood, plantturnover, plantturnoverfineroot, plantturnoverleaf, plantturnoverwood, plantturnoverwoodcrowding, plantturnoverwooddist, plantturnoverwoodresourcelim, nc_abort, psurf, qair, qg, qh, qle, qmom, qrecharge, qs, qsb, qscrn, radt, rainf, rnet, rnetsoil, rootresp, satfrac, snowdepth, snowf, snowmelt, snowt, soilcarbfast, soilcarbpassive, soilcarbslow, soilmoist, soilmoistice, soiltemp, stemresp, swdown, swe, swnet, tair, tdaymn, tdaymx, tmn, tmx, tnn, totlittcarb, totlivbiomass, totsoilcarb, tscrn, tveg, txx, vegt, visalbedo, wattable, wbal, wind
plume_mip_get_met calls avg_lwdn, coszen, doy, f_id, hod, metfile, nf90_close, phild, phisd, precip, doysod2ymdhms, file_switch, get_plume_co2, handle_err, open_plume_met, plume_get_daily_met, wgen_daily_constants, wgen_init, wgen_subdiurnal_met, temp
plume_mip_init calls avg_lwdn, met, nf90_close, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_open, get_unit, handle_err
pop_io calls lat, lon, nf90_close, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_open, nf90_put_att, nf90_put_var, nf90_redef, pop_grid, handle_err
pop_luc_casa_transfer calls 1166, clabile, clearprod, clearprodloss, clitter, cplant, csoil, ctransferluc, fclearance, fcneeyear, fharvest, fracclearprod, fracclearresid, fracharvprod, fracharvresid, fracharvsecresid, grass, harvprod, harvprodloss, iwood, nlitter, nplant, nsoil, nsoilmin, plitter, pop_grid, pplant, prim_only, psoil, smharv, syharv
popdriver calls disturbance_intensity, disturbance_interval, popstep
popluc_set_patchfrac calls grass, prim_only, primf
preparefiles calls renamefiles
read_casa_dump calls nf90_close, nf90_open, get_var_ncr2, get_var_ncr3, stderr_nc
read_climate_restart_nc calls nf90_close, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_open, handle_err
site_get_co2_ndep calls co2vals, ndepvals, pdepvals, get_unit
site_init calls get_unit
spec_init_soil_snow calls tgg, wb, wbice, zse
spincasacnp calls casa_fluxout, popdriver, read_casa_dump, 100, 20, cgppspin, cplant, crmplantspin_1, crmplantspin_2, crmplantspin_3, doyphasespin_1, doyphasespin_2, doyphasespin_3, doyphasespin_4, fraccalloc, kplant, moistspin_1, moistspin_2, moistspin_3, moistspin_4, moistspin_5, moistspin_6, mtempspin, phasespin, analyticpool, biogeochem, rationcsoilnew, tairkspin, tsoilspin_1, tsoilspin_2, tsoilspin_3, tsoilspin_4, tsoilspin_5, tsoilspin_6
sumcflux calls clabloss, crgplant, crsoil
write_casa_dump calls doyphase, nf90_close, nf90_create, nf90_enddef, def_dims, def_vars, put_var_ncr1, put_var_ncr2, put_var_ncr3, stderr_nc
write_casa_output_nc calls fcrgrowyear, fcrmleafyear, fcrmrootyear, fcrmwoodyear, nf90_close, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_inq_dimid, nf90_inq_varid, nf90_open, nf90_put_att, nf90_put_var, nf90_redef, handle_err
write_casa_restart_nc calls doyphase, nf90_close, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_put_att, nf90_put_var, nf90_redef, handle_err
write_climate_restart_nc calls nf90_close, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_put_att, nf90_put_var, nf90_redef, handle_err
write_landuse_casa_restart_nc calls nf90_close, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_put_att, nf90_put_var, nf90_redef, handle_err
write_luc_output_nc calls nf90_close, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_put_att, nf90_put_var, nf90_redef, handle_err
write_luc_restart_nc calls nf90_close, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_put_att, nf90_put_var, nf90_redef, handle_err
write_output calls is_leapyear, albedo, averaging, clitter, cplant, cplant_turnover, crmplant, csoil, fsd, write_ovar, nf90_put_var, nf90_sync, energy_balance, mass_balance, nc_abort, qcan, tdaymn, tdaymx, tgg, tggsn, tnn, tscrn, txx, year
alloc_cbm_var calls alloc_air_type, alloc_balances_type, alloc_bgc_pool_type, alloc_canopy_type, alloc_climate_type, alloc_met_type, alloc_radiation_type, alloc_roughness_type, alloc_soil_parameter_type, alloc_soil_snow_type, alloc_sum_flux_type, alloc_veg_parameter_type
define_ovar calls define_output_parameter_r1, define_output_parameter_r2, define_output_variable_r1, define_output_variable_r2
write_ovar calls write_output_parameter_r1, write_output_parameter_r1d, write_output_parameter_r2, write_output_parameter_r2d, write_output_variable_r1, write_output_variable_r2
albedo calls canopyreflectance, canopytransmitance, effectivesurfacereflectance, fbeamradalbedo, surface_albedosn
alloc_casavariable calls areacell, cgppspin, clabile, clabloss, clitter, cplant, cplant_turnover, crgplant, crmplant, crmplantspin_1, crmplantspin_2, crmplantspin_3, crsoil, csoil, ctransferluc, cwoodprod, fcgppyear, fcneeyear, fcnppyear, fcrgrowyear, fcrmleafyear, fcrmrootyear, fcrmwoodyear, fcrsyear, fndepyear, fnfixyear, fnleachyear, fnlossyear, fnsnetyear, fnupyear, fpdustyear, fpleachyear, fplossyear, fpsnetyear, fpupyear, fpweayear, frac_sapwood, fraccalloc, glai, glaimin, isorder, iveg2, kplant, lat, lon, moistspin_1, moistspin_2, moistspin_3, moistspin_4, moistspin_5, moistspin_6, mtempspin, nintercept, nlitter, nplant, nslope, nsoil, nsoilmin, nwoodprod, plitter, pplant, precip, psoil, psoillab, psoilocc, psoilsorb, pwoodprod, rationcplantmax, rationcplantmin, rationcsoilnew, ratiopcplantmin, sapwood_area, sla, sumcbal, sumnbal, sumpbal, tairkspin, tsoilspin_1, tsoilspin_2, tsoilspin_3, tsoilspin_4, tsoilspin_5, tsoilspin_6, btran, cbalance, cgpp, clabilelast, cleafmean, clitterlast, cnep, cnpp, costnpup, cplant_turnover_crowding, cplant_turnover_disturbance, cplant_turnover_resource_limitation, cplantlast, crootmean, crp, csoillast, ctot, ctot_0, dcdtyear, dclabiledt, dclitterdt, dcplantdt, dcsoildt, dnlitterdt, dnplantdt, dnsoildt, dnsoilmindt, dplitterdt, dpplantdt, dpsoildt, dpsoillabdt, dpsoiloccdt, dpsoilsorbdt, fcrpyear, fluxctoclear, fluxctoco2, fluxctohwp, fluxctolitter, fluxctosoil, fluxntoclear, fluxntohwp, fluxntolitter, fluxntosoil, fluxptoclear, fluxptohwp, fluxptolitter, fluxptosoil, fnminleach, fnminloss, fpleach, fracclabile, fraclabile, fraclignin, fracligninplant, fracnalloc, fracnpptop, fracpalloc, fromltoco2, fromltos, fromptol, fromstoco2, fromstos, ftransnptol, ftranspptol, glaimax, glaimon, glaimonx, ijgcm, ivt2, kclabrate, klitter, kminn, kmlabp, kplab, kpocc, kpsorb, kroot, krootlen, ksoil, kuplabp, kuptake, laimax, litterrate, lnonwood, maxcwd, maxfinelitter, meangpp, meanrleaf, moist, moistavg, nbalance, nlitterlast, nlittermin, nmindep, nminfix, nminleach, nminloss, nminuptake, nplantlast, nsimm, nsmin, nsnet, nsoillast, nsoilminlast, nupland, pbalance, pdep, plabuptake, plantrate, pleach, plitterlast, plittermin, ploss, pplantlast, prodptase, psimm, psmin, psnet, psoillablast, psoillast, psoilocclast, psoilsorblast, psorbmax, pupland, pwea, q10soil, ratiofrootleaf, rationclitter, rationcplant, rationcsoil, rationcsoilmax, rationcsoilmin, rationplitter, rationpplant, rationpplantmax, rationpplantmin, rationpsoil, ratiopclitter, ratiopcplant, ratiopcplantmax, ratiopcsoil, rmplant, rootdepth, soilrate, stemnpp, tairk, tsoil, tsoilavg, xkleafcoldexp, xkleafcoldmax, xkleafdryexp, xkleafdrymax, xkoptlitter, xkoptsoil, xkplab, xkpocc, xkpsorb, xnpmax
alloc_phenvariable calls aphen, doyphase, doyphasespin_1, doyphasespin_2, doyphasespin_3, doyphasespin_4, phase, phasespin, tkshed
alloc_sum_casavariable calls clabile, clabloss, clitter, cplant, cplant_turnover, crgplant, crmplant, crsoil, csoil, frac_sapwood, fraccalloc, kplant, nlitter, nplant, nsoil, nsoilmin, plitter, pplant, psoil, psoillab, psoilocc, psoilsorb, rationcsoilnew, sapwood_area, cgpp, cnep, cnpp, cplant_turnover_crowding, cplant_turnover_disturbance, cplant_turnover_resource_limitation, crp, dclabiledt, dclitterdt, dcplantdt, dcsoildt, dnlitterdt, dnplantdt, dnsoildt, dnsoilmindt, dplitterdt, dpplantdt, dpsoildt, dpsoillabdt, dpsoiloccdt, dpsoilsorbdt, fluxctoco2, fluxctolitter, fluxctosoil, fluxntolitter, fluxntosoil, fluxptolitter, fluxptosoil, fnminleach, fnminloss, fpleach, fracclabile, fracnalloc, fracpalloc, fromltoco2, fromltos, fromptol, fromstoco2, fromstos, klitter, kmlabp, kplab, kpocc, kpsorb, ksoil, nlittermin, nmindep, nminfix, nminleach, nminloss, nminuptake, nsimm, nsmin, nsnet, nupland, pdep, plabuptake, pleach, plittermin, ploss, psimm, psmin, psnet, psorbmax, pupland, pwea, rationclitter, rationcplant, rationcsoil, rationcsoilmax, rationcsoilmin, rationplitter, rationpplant, rationpsoil, ratiopclitter, ratiopcplant, ratiopcsoil, stemnpp
allocate_cable_vars calls alloc_cbm_var
analyticpool calls clitter, csoil, isorder, iveg, iveg2, nlitter, nsoil, psoillab, clay, fracligninplant, fromltos, fromstos, klitter, kmlabp, ksoil, litterrate, psorbmax, rationclitter, rationcsoil, rationplitter, rationpsoil, silt, soilrate
biogeochem calls casa_cnpflux, cplant_turnover, disturbance_interval, pop_grid, klitter, avgsoil, casa_allocation, casa_cnpbal, casa_cnpcycle, casa_coeffplant, casa_coeffsoil, casa_delplant, casa_delsoil, casa_ndummy, casa_nuptake, casa_pdummy, casa_puptake, casa_rplant, casa_rplant1, casa_xkn, casa_xnp, casa_xrateplant, casa_xratesoil, phenology
biome1_pft calls biome, iveg, mtemp_min20, agdd0, agdd5, mtemp_max20
cable_phenology_clim calls aphen, doyphase, iveg, phase, chilldays, dmoist, gdd5
carbon_pl calls cplant, csoil
casa_init calls 100, 5, 2, read_casa_restart_nc, rationcplant, rationcsoil, rationpsoil
casa_readbiome calls clitter, cplant, csoil, glaimin, isorder, iveg, iveg2, nlitter, psoillab, rationcplantmax, rationcplantmin, ratiopcplantmin, sla, zse, fracligninplant, fracnpptop, ftransnptol, ftranspptol, glaimax, ivt2, kminn, kmlabp, kroot, krootlen, kuplabp, kuptake, psorbmax, rationclitter, rationcplant, rationcsoil, rationcsoilmax, rationpplantmin, ratiopclitter, ratiopcplant, ratiopcsoil, rmplant, rootdepth, tkshed, xkleafcoldexp, xkleafdryexp
casa_readphen calls doyphase, iveg, lat
check_parameter_values calls isoilm, iveg, clay, froot, sand, sfc, silt, ssat, swilt
cru_get_daily_met calls f_id, met, metfile, nf90_close, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_open, handle_err, v_id, var_name, cru_get_filename
def_dims calls nf90_def_dim, stderr_nc
def_vars calls nf90_def_var, stderr_nc
define_canopy calls fes, fev, define_air, ruff_resist, qv, satfrac, tgg, tggsn, tk, tss, wb, wbice, zse, cmolar, coexp, disp, dleaf, evapfbl, extkb, fevw_pot, fvlai, gswx, hruff, lwabv, potev, comp_friction_vel, dryleaf, humidity_deficit_method, latent_heat_flux, penman_monteith, psim, psis, qsatfjh, radiation, surf_wetness_fact, update_zetar, wetleaf, within_canopy, rghlai, rt0us, rt1, rt1usa, rt1usb, rt_qh_sublayer, rtevap_sat, rtevap_unsat, rtsoil, shelrb, transd, tvrad, us, usuh, visc, vlaiw, wetfac, wetfac_cs, z0soilsn, zetar, zetash, zref_tq, zruffs
derived_parameters calls iveg, wb, wbice, zse, bch_vec, clay_vec, hyds_vec, org_vec, sand_vec, sfc, sfc_vec, slope, slope_std, ssat_vec, sucs_vec, swilt, swilt_vec, watr
doysod2ymdhms calls is_leapyear
energy_balance calls albedo, fsd, qcan
find_metvarid calls nf90_inq_varid
get_cru_co2 calls co2vals, get_unit
get_cru_ndep calls nf90_get_var, nf90_inq_varid, nf90_open, handle_err
get_default_params calls cable_pft_params, cable_soil_params, countpatch, get_land_index, luc_expt_set_tiles, read_gridinfo, read_soilcolor, spatialsoil
get_parameters_met calls nf90_inq_varid, readpar
get_plume_co2 calls co2vals, get_unit
get_restart_data calls nf90_close, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nc_abort, readpar, extrarestart
get_var_ncr2 calls nf90_get_var, nf90_inq_varid, stderr_nc
get_var_ncr3 calls nf90_get_var, nf90_inq_varid, stderr_nc
handle_err calls nf90_strerror
init_radiation calls beamfraction, common_initrad_scalings, effectiveextinctcoeffs, extinctioncoeff
landuse_allocate_mland calls patchfrac_y, albedo_x, albedo_y, albsoil_x, albsoil_y, albsoilsn_x, albsoilsn_y, aphen_x, aphen_y, atransit, cansto_x, cansto_y, clabile_x, clabile_y, clitter_x, clitter_y, cplant_x, cplant_y, cplantx_x, cplantx_y, csoil_x, csoil_y, csoilx_x, csoilx_y, cwoodprod_x, cwoodprod_y, dgdtg_x, dgdtg_y, doyphase3_x, doyphase3_y, fes_x, fes_y, fev_x, fev_y, fharvw, fhs_x, fhs_y, frac_sapwood_x, frac_sapwood_y, ga_x, ga_y, gammzz_x, gammzz_y, ghflux_x, ghflux_y, gwwb_x, gwwb_y, isflag_x, isflag_y, isoil_x, isoil_y, iveg_x, iveg_y, lai_x, lai_y, nlitter_x, nlitter_y, nplant_x, nplant_y, nsoil_x, nsoil_y, nsoilmin_x, nsoilmin_y, nwoodprod_x, nwoodprod_y, osnowd0_x, osnowd0_y, osnowd_x, osnowd_y, patchfrac_x, pftfrac, phase_x, phase_y, phen_x, phen_y, plitter_x, plitter_y, pplant_x, pplant_y, psoil_x, psoil_y, psoillab_x, psoillab_y, psoilocc_x, psoilocc_y, psoilsorb_x, psoilsorb_y, pwoodprod_x, pwoodprod_y, rnof1_x, rnof1_y, rnof2_x, rnof2_y, rtsoil_x, rtsoil_y, runoff_x, runoff_y, sapwood_area_x, sapwood_area_y, sdepth_x, sdepth_y, sghflux_x, sghflux_y, sla_x, sla_y, smass_x, smass_y, snage_x, snage_y, snowd_x, snowd_y, soilorder_x, soilorder_y, ssdn_x, ssdn_y, ssdnn_x, ssdnn_y, tgg_x, tgg_y, tggsn_x, tggsn_y, trad_x, trad_y, tss_x, tss_y, wb_x, wb_y, wbice_x, wbice_y, wbtot0_x, wbtot0_y, xluh2cable
landuse_allocate_mp calls albedo, albsoil, albsoilsn, aphen, areacell, cansto, clabile, clitter, cplant, csoil, cwoodprod, dgdtg, fes, fev, fhs, frac_sapwood, ga, gammzz, ghflux, gwwb, isflag, iveg, lai, lat, lon, nlitter, nplant, nsoil, nsoilmin, nwoodprod, osnowd, osnowd0, phase, plitter, pplant, psoil, psoillab, psoilocc, psoilsorb, pwoodprod, rnof1, rnof2, runoff, sapwood_area, sdepth, sghflux, sla, smass, snage, snowd, ssdn, ssdnn, sumcbal, sumnbal, sumpbal, tgg, tggsn, trad, tss, wb, wbice, wbtot0, cplantx, csoilx, doyphase3, isoil, patchfrac, phen, rtsoil, soilorder
landuse_checks calls 20, patchfrac_y, clabile_y, clitter_y, cplant_y, csoil_y, cwoodprod_y, nlitter_y, nplant_y, nsoil_y, nsoilmin_y, nwoodprod_y, plitter_y, pplant_y, psoil_y, psoillab_y, psoilocc_y, psoilsorb_y, pwoodprod_y
landuse_getdata calls nf90_close, nf90_get_var, nf90_inq_varid, nf90_open
landuse_getxluh2 calls nf90_close, nf90_get_var, nf90_inq_varid, nf90_open
landuse_land2mpx calls patchfrac_y, albedo_y, albsoil_y, albsoilsn_y, aphen_y, cansto_y, clabile_y, clitter_y, cplant_y, cplantx_y, csoil_y, csoilx_y, cwoodprod_y, dgdtg_y, doyphase3_y, fes_y, fev_y, fhs_y, frac_sapwood_y, ga_y, gammzz_y, ghflux_y, gwwb_y, isflag_y, isoil_y, lai_y, nlitter_y, nplant_y, nsoil_y, nsoilmin_y, nwoodprod_y, osnowd0_y, osnowd_y, patchfrac_x, phase_y, phen_y, plitter_y, pplant_y, psoil_y, psoillab_y, psoilocc_y, psoilsorb_y, pwoodprod_y, rnof1_y, rnof2_y, rtsoil_y, runoff_y, sapwood_area_y, sdepth_y, sghflux_y, sla_y, smass_y, snage_y, snowd_y, soilorder_y, ssdn_y, ssdnn_y, tgg_y, tggsn_y, trad_y, tss_y, wb_y, wbice_y, wbtot0_y
landuse_mp2land calls albedo, albsoil, albsoilsn, aphen, cansto, clabile, clitter, cplant, csoil, cwoodprod, dgdtg, fes, fev, fhs, frac_sapwood, ga, gammzz, ghflux, gwwb, isflag, iveg, lai, nlitter, nplant, nsoil, nsoilmin, nwoodprod, osnowd, osnowd0, phase, plitter, pplant, psoil, psoillab, psoilocc, psoilsorb, pwoodprod, rnof1, rnof2, runoff, sapwood_area, sdepth, sghflux, sla, smass, snage, snowd, ssdn, ssdnn, tgg, tggsn, trad, tss, wb, wbice, wbtot0, cplantx, csoilx, doyphase3, isoil, patchfrac, phen, rtsoil, soilorder
landuse_transitx calls patchfrac_y, rationcplantmax, albedo_x, albsoil_x, albsoilsn_x, aphen_x, atransit, cansto_x, clabile_x, clitter_x, cplant_x, cplant_y, cplantx_x, csoil_x, csoilx_x, cwoodprod_x, dgdtg_x, doyphase3_x, doyphase3_y, fes_x, fev_x, fharvw, fhs_x, frac_sapwood_x, fracligninplant, ftransnptol, ga_x, gammzz_x, ghflux_x, gwwb_x, isoil_x, isoil_y, nlitter_x, nplant_x, nplant_y, nsoil_x, nsoilmin_x, nwoodprod_x, osnowd0_x, osnowd_x, patchfrac_x, phase_x, phase_y, phen_x, plitter_x, pplant_x, landuse_redistribution, psoil_x, psoillab_x, psoilocc_x, psoilsorb_x, pwoodprod_x, rationpplantmin, rnof1_x, rnof2_x, rtsoil_x, runoff_x, sapwood_area_x, sdepth_x, sghflux_x, sla_x, sla_y, smass_x, smass_y, snage_x, snowd_x, soilorder_x, soilorder_y, ssdn_x, ssdnn_x, tgg_x, tggsn_x, trad_x, tss_x, wb_x, wbice_x, wbtot0_x, xluh2cable
nc_abort calls nf90_strerror
open_cru_met calls f_id, metfile, nf90_inq_varid, nf90_open, handle_err, v_id, var_name, cru_get_filename
open_plume_met calls f_id, metfile, nf90_get_att, nf90_inq_varid, nf90_open, handle_err, v_id, var_name, leap_day, plume_get_filename
plantcarb calls cplant, tk, ratecp
plume_get_daily_met calls f_id, met, metfile, nf90_close, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_open, handle_err, v_id, var_name, plume_get_filename
pop_init calls alloc_pop, initpop2d_poisson, layer_recruitment_single_patch, zeropop
pop_init_single calls initpop2d_poisson, layer_recruitment_single_patch, zeropop
popluc_init calls cplant, iwood, prim_only, pop_init_single, rationcplantmin, ratiopcplantmin, alloc_popluc, popluc_set_params, read_luc_restart_nc, zeropopluc
popluc_weights_transfer calls iwood, prim_only, freq_age_secondary
poplucstep calls primf, freq_age_secondary, gtop, gtos, execute_luc_event, increment_age, ptog, ptos, stog
popstep calls pop_grid, getdiagnostics, getpatchfrequencies, getuniqueagefrequencies, patch_disturb, patch_partial_disturb, patch_partial_disturb2, patchannualdynamics
put_var_ncr1 calls nf90_inq_varid, nf90_put_var, stderr_nc
put_var_ncr2 calls nf90_inq_varid, nf90_put_var, stderr_nc
put_var_ncr3 calls nf90_inq_varid, nf90_put_var, stderr_nc
read_climatefile calls nf90_close, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_open, handle_err
read_luh2 calls f_id, input, nf90_get_var, handle_err, transfile, v_id
report_parameters calls albsoil, albsoilsn, areacell, cansto, clabile, clitter, cplant, csoil, glai, isflag, isoilm, isorder, iveg, iveg2, nlitter, nplant, nsoil, nsoilmin, osnowd, phase, plitter, pplant, psoil, psoillab, psoilocc, psoilsorb, rnof1, rnof2, runoff, smass, snage, snowd, ssdn, ssdnn, tgg, tggsn, vcmax, wb, wbice, a1gs, bch, canst1, clay, css, d0gs, dleaf, ejmax, frac4, froot, hc, hyds, nmindep, nminfix, pdep, cable_pft_params, cable_soil_params, pwea, ratecp, ratecs, rhosoil, rp20, rpcoef, rs20, rtsoil, sand, sfc, shelrb, silt, ssat, sucs, swilt, tmaxvj, tminvj, vbeta, xalbnir, xfang, za_tq, za_uv
rh_sh calls svp
ruff_resist calls coexp, disp, hruff, hgtabovesnow, lai_eff, rghlai, rt1usb, term2, term3, term5, usuh, vlaiw, z0m, z0soilsn, za_tq, za_uv, zref_tq, zref_uv, zruffs
soil_snow calls gammzz, tgg, tggsn, wb, wbice, zse, css, dtmlt, hydraulic_redistribution, remove_trans, snow_accum, snow_melting, snowcheck, snowdensity, snowl_adjust, soilfreeze, stempv, surfbv, rhosoil
soilcarb calls tgg, wb, froot
stderr_nc calls nf90_strerror
wgen_init calls coszen, phild, phisd, pmb, precip, temp, wind, daylength, latdeg, latrad, pmbday, precipday, snow, snowday, solarmjday, solarnorm, tempmaxday, tempmaxdayprev, tempminday, tempmindaynext, tempnightrate, tempnightrateprev, temprangeaft, temprangeday, tempsunset, tempsunsetprev, timemaxtemp, timesunrise, timesunset, timesunsetprev, vappmb, winddark, windday, windlite
write_cnp_params calls iveg, nmindep, pdep
write_default_params calls isoilm, iveg, snowd, tgg, vcmax, wb, bch, clay, cplant1, cplant2, cplant3, csoil1, csoil2, css, hyds, init_veg_from_vegin, ratecp1, ratecp2, ratecp3, ratecs1, ratecs2, rhosoil, sand, sfc, silt, ssat, sucs, swilt, watr
write_luc_output_grid_nc calls clearprod, clearprodloss, csoil, fclearance, fharvest, harvprod, harvprodloss, nf90_close, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_put_att, nf90_put_var, nf90_redef, handle_err, cbiomass, clitt, fnep, ftransfergross, ftransfernet
ymdhms2doysod calls is_leapyear
readpar calls readpar_i, readpar_r, readpar_r2, readpar_r2d, readpar_rd
alloc_canopy_type calls sublayer_dz
alloc_pop calls iwood, pop_grid, it_pop
alloc_popluc calls clearprod, clearprodloss, csoil, fclearance, fharvest, frac_forest, frac_primf, fracclearprod, fracclearresid, fracharvprod, fracharvresid, fracharvsecresid, grass, harvprod, harvprodloss, primf, secdf, smharv, syharv, cbiomass, clitt, fnep, freq_age_secondary, ftransfergross, ftransfernet, gtop, age_history_secdf, area_history_secdf, biomass_age_primary, biomass_age_secondary, freq_age_primary, latitude, longitude, pharv
alloc_soil_parameter_type calls elev, bch_vec, clay_vec, hyds_vec, org_vec, sand_vec, sfc_vec, slope, slope_std, ssat_vec, sucs_vec, swilt_vec, watr, drain_dens, elev_std, gwbch_vec, gwdz, gwhyds_vec, gwrhosoil_vec, gwssat_vec, gwsucs_vec, gwwatr, gwz, rhosoil_vec, silt_vec
alloc_soil_snow_type calls gwwb, qrecharge, satfrac, evapfbl, rt_qh_sublayer, rtevap_sat, rtevap_unsat, wetfac, dhkdw, dsmpdw, fland, fracice, gwdhkdw, gwdsmpdw, gwhk, gwsmp, gwwbeq, gwzq, hk, icefrac, ifland, otgg, otss, otss_0, owetfac, qasrf, qfsrf, qhlev, qhz, qssrf, qstss, rh_srf, sinfil, smp, t_snwlr, tevap, tggav, tilefrac, totenbal, totenbal2, totwblake, tprecip, trnoff, wb_lake, wbeq, wbfice, wbliq, wbtot, wbtot1, wbtot2, wmice, wmliq, wmtot, wtd, zq
alloc_veg_parameter_type calls a1gs, d0gs, froot, alpha, cfrd, conkc0, conko0, convex, deciduous, ekc, eko, extkn, gswmin, refl, taul, vlaimax, wai
avgsoil calls btran, moist, moistavg, sfc, swilt, tsoilavg
beamfraction calls spitter
canopyreflectance calls canopyreflectance_beam, canopyreflectance_dif
canopytransmitance calls canopytransmitance_beam, canopytransmitance_dif
casa_allocation calls 1166, cplant, crmplant, fraccalloc, glai, glaimin, iveg, kplant, sla, btran, fracnpptop, glaimax, moistavg, sfc, swilt, tsoilavg, casa_wolf
casa_cnpbal calls 100, clabile, cplant, crgplant, crmplant, crsoil, fraccalloc, iveg2, kplant, lat, lon, nsoilmin, psoillab, psoilocc, psoilsorb, cbalance, cgpp, clabilelast, cnpp, cplantlast, dclabiledt, dcplantdt, nmindep, nminfix, nminleach, nminloss, nminuptake, nsoilminlast, nupland, pdep, plabuptake, pleach, ploss, psoillablast, psoilocclast, psoilsorblast, pupland, pwea
casa_cnpcycle calls clabile, clitter, cplant, csoil, cwoodprod, glai, glaimin, iveg, iveg2, lat, lon, nlitter, nplant, nsoil, nsoilmin, nwoodprod, plitter, pplant, psoil, psoillab, psoilocc, pwoodprod, sla, dclabiledt, dclitterdt, dcplantdt, dcsoildt, dnlitterdt, dnplantdt, dnsoildt, dnsoilmindt, dplitterdt, dpplantdt, dpsoildt, dpsoillabdt, dpsoiloccdt, glaimax, kmlabp, psorbmax, casa_poolzero
casa_coeffplant calls cplant, glai, glaimin, iveg, kplant, nplant, fracligninplant, fromptol, ftransnptol, plantrate
casa_coeffsoil calls isorder, iveg, iveg2, clay, fracligninplant, fromltoco2, fromltos, fromstoco2, fromstos, ksoil, litterrate, silt, soilrate, xkplab, xkpocc, xkpsorb
casa_delplant calls clabloss, cplant, crgplant, crmplant, fraccalloc, iveg, iveg2, kplant, nplant, pplant, cgpp, cnpp, dcplantdt, dnplantdt, dpplantdt, fluxctolitter, fluxntolitter, fluxptolitter, fracclabile, fracnalloc, fracpalloc, fromptol, ftransnptol, ftranspptol, lnonwood, nminuptake, plabuptake
casa_delsoil calls 20, clitter, crsoil, csoil, iveg, iveg2, nlitter, nsoil, nsoilmin, plitter, psoil, psoillab, psoilocc, psoilsorb, rationcsoilnew, cnpp, costnpup, dpsoillabdt, fluxctoco2, fluxctolitter, fluxctosoil, fluxntolitter, fluxntosoil, fluxptolitter, fluxptosoil, fnminleach, fnminloss, fpleach, fromltoco2, fromltos, fromstoco2, fromstos, klitter, kmlabp, kpocc, kpsorb, ksoil, nlittermin, nmindep, nminfix, nminleach, nminloss, nsimm, nsmin, nsnet, nupland, pdep, pleach, plittermin, prodptase, psimm, psmin, psnet, psorbmax, pupland, pwea, ratiopcsoil, tsoilavg
casa_ndummy calls clitter, cplant, csoil, rationclitter, rationcplant, rationcsoil
casa_nuptake calls 100, iveg, iveg2, nsoilmin, kminn, nminuptake, casa_nrequire
casa_pdummy calls clitter, cplant, csoil, isorder, ratiopclitter, ratiopcplant, ratiopcsoil
casa_puptake calls iveg, psoillab, kuplabp, plabuptake, casa_prequire
casa_rplant calls clabile, clabloss, cplant, crgplant, crmplant, frac_sapwood, iveg, nplant, vcmax_np, rationcplantmax, sla, cgpp, cnpp, kclabrate, ratiopcplantmax, rmplant, tairk, tsoilavg, qtemp_max_last_year
casa_rplant1 calls clabile, clabloss, cplant, crgplant, crmplant, iveg, nplant, cgpp, cnpp, kclabrate, rationpplantmin, rmplant, tairk, tsoilavg
casa_xkn calls clitter, csoil, iveg, iveg2, nlitter, nsoil, nsoilmin, rationcsoilnew, fromltos, fromstos, klitter, ksoil, maxcwd, maxfinelitter, rationcsoilmax, rationcsoilmin
casa_xnp calls 20, cplant, iveg, iveg2, nplant, nsoilmin, pplant, psoillab, cgpp, cnpp, fracclabile, xnpmax, casa_nrequire, casa_prequire
casa_xrateplant calls iveg, iveg2, phase, btran, tairk, tkshed, xkleafcoldexp, xkleafcoldmax, xkleafdryexp, xkleafdrymax
casa_xratesoil calls iveg, iveg2, moistavg, q10soil, ssat, tsoilavg, xkoptlitter, xkoptsoil
common_initrad_scalings calls calc_rhoch, common_initrad_coeffs
comp_friction_vel calls psim
define_output_parameter_r1 calls nf90_def_var, nf90_put_att, nc_abort, grid
define_output_parameter_r2 calls nf90_def_var, nf90_put_att, nc_abort, grid
define_output_variable_r1 calls nf90_def_var, nf90_put_att, nc_abort, grid
define_output_variable_r2 calls nf90_def_var, nf90_put_att, nc_abort, grid
dryleaf calls cansto, iveg, qcan, tk, vcmax, wb, zse, a1gs, cmolar, d0gs, dleaf, ejmax, evapfbl, frac4, froot, fvlai, gswx, ssat_vec, swilt, swilt_vec, vlaiw, alpha, ca, cfrd, conkc0, conko0, convex, dsatdk, dva, ekc, eko, fevc, fwet, g0, gradis, ej3x, ej4x, fwsoil_calc_lai_ktaul, fwsoil_calc_non_linear, fwsoil_calc_std, getrex_1d, photosynthesis, xejmxt3, xrdt, xvcmxt3, xvcmxt4, psyc, qtemp_max_last_year, rex, rlam, rniso, scalex, tvair, wbliq, zr
effectiveextinctcoeffs calls effectiveextinctcoeff
effectivesurfacereflectance calls effectivereflectance
execute_luc_event calls frac_forest, primf, freq_age_secondary, ptog, ptos, stog, n_event
extinctioncoeff calls extinctioncoeff_beam, extinctioncoeff_dif
extrarestart calls nf90_get_var, nf90_inq_varid, nc_abort, readpar, redistr_i, redistr_r, redistr_r2, redistr_r2d, redistr_rd
getdiagnostics calls pop_grid, get_allometry, interpolate_biomass_1d, interpolate_biomass_2d, smooth_flux
getpatchfrequencies calls pop_grid
getuniqueagefrequencies calls pop_grid, cumexponential, realexponential
hydraulic_redistribution calls wb, wbice, zse, froot, sfc, ssat, swilt
increment_age calls smharv, syharv, freq_age_secondary
init_veg_from_vegin calls iveg, vcmax, a1gs, canst1, clitt, d0gs, dleaf, ejmax, frac4, froot, hc, rp20, rpcoef, rs20, shelrb, tmaxvj, tminvj, vbeta, xalbnir, xfang, alpha, cfrd, conkc0, conko0, convex, ekc, eko, extkn, g0, g1, gswmin, refl1, refl2, rootbeta, taul1, taul2, vegcf, wai, zr
initpop2d_poisson calls pop_grid, cumexponential, exponential
layer_recruitment_single_patch calls pop_grid, get_allometry
leap_day calls is_leapyear
luc_expt_set_tiles calls 1166, grass, ivegp, mtemp_min20, prim_only, primaryf, secdf
patch_disturb calls pop_grid, layer_recruitment_single_patch
patch_partial_disturb calls pop_grid
patch_partial_disturb2 calls pop_grid
patchannualdynamics calls pop_grid, get_allometry, layer_recruitment
penman_monteith calls qsatfjh
phenology calls doyphase, phase
popluc_set_params calls biome, fracharvresid, fracharvsecresid, ivegp
psim calls alog
psis calls alog
radiation calls albsoilsn, fsd, qcan, fvlai, cexpkbm, cexpkdm, extkbm, extkdm, fbeam, gradis, reffbm, reffdf, refl, scalex, taul
read_casa_restart_nc calls nf90_close, nf90_get_att, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_open, handle_err
read_gridinfo calls nf90_close, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_open, nc_abort
read_luc_restart_nc calls nf90_close, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_open, handle_err, 1000
read_soilcolor calls nf90_close, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_open, nc_abort
remove_trans calls wb, zse, evapfbl, froot
snow_accum calls gammzz, isflag, isoilm, osnowd, precip_sn, sdepth, smass, snowd, ssdn, tgg, tggsn, cls, evapsn, fes_cor, fess, precis
snow_melting calls gammzz, isflag, sdepth, smass, snowd, ssdn, tgg, tggsn, dtmlt
snowcheck calls isflag, smass, snowd, ssdn, ssdnn, tgg, tggsn, t_snwlr
snowdensity calls smass, ssdn, tgg, tggsn, sconds
snowl_adjust calls isflag, sdepth, smass, snowd, ssdn, tggsn
soilfreeze calls gammzz, tgg, wb, wbice, zse
spatialsoil calls nf90_close, nf90_get_var, nf90_inq_varid, nf90_open, nc_abort
stempv calls gammzz, sdepth, ssdn, tgg, tggsn, zse, old_soil_conductivity, total_soil_conductivity, trimb, sconds, wbfice, wblf
surf_wetness_fact calls iveg, snowd, tk, wb, wbice, wetfac
surfbv calls gammzz, sdepth, smass, ssdn, tgg, wb, zse, sfc, smoisturev
wetleaf calls cansto, tk, vlaiw, dsatdk, dva, fevw, fwet, psyc, rlam, tvair
within_canopy calls fes, fev, fhs, pmb, qv, satfrac, tk, tss, hruff, rt1, rtevap_sat, rtevap_unsat, vlaiw, wetfac, z0soilsn, cls, epsi, fhv, meth, qsatfjh2, qstss, qvair, rho, rlam, tvair
write_output_parameter_r1 calls nf90_put_var, nc_abort, grid
write_output_parameter_r1d calls nf90_put_var, nc_abort
write_output_parameter_r2 calls nf90_put_var, nc_abort, grid
write_output_parameter_r2d calls nf90_put_var, nc_abort
write_output_variable_r1 calls nf90_put_var, nc_abort, grid, range_abort
write_output_variable_r2 calls nf90_put_var, nc_abort, grid, range_abort
casa_nrequire calls cplant, fraccalloc, iveg, iveg2, kplant, nplant, nsoilmin, rationcplantmax, rationcplantmin, ftransnptol
casa_poolzero calls clitter, cplant, csoil, nlitter, nplant, nsoil
casa_prequire calls cplant, fraccalloc, iveg, iveg2, kplant, pplant, ratiopcplantmin, ftranspptol, ratiopcplantmax
casa_wolf calls cplant, iveg, iveg2, cnpp, fracnpptop
fwsoil_calc_lai_ktaul calls wb, froot, ssat, swilt
fwsoil_calc_non_linear calls sfc
get_allometry calls allometry, getheight, williams_allometry
interpolate_biomass_1d calls pop_grid, realexponential
interpolate_biomass_2d calls pop_grid, realexponential, area_triangle
layer_recruitment calls pop_grid, get_allometry
old_soil_conductivity calls isoilm, ssat, wbfice, wblf, cnsd
range_abort calls doy, hod, year
readpar_i calls nf90_get_var, nf90_inq_varid, nf90_inquire_variable, nc_abort
readpar_r calls nf90_get_var, nf90_inq_varid, nf90_inquire_variable, nc_abort
readpar_r2 calls nf90_get_var, nf90_inq_varid, nf90_inquire_variable, nc_abort
readpar_r2d calls nf90_get_var, nf90_inq_varid, nf90_inquire_variable, nc_abort
readpar_rd calls nf90_get_var, nf90_inq_varid, nf90_inquire_variable, nc_abort
redistr_r calls float
redistr_r2 calls float
redistr_r2d calls float
redistr_rd calls float
smoisturev calls wb, wbice, zse, sfc, ssat, trimb, wbfice, wblf, zshh
smooth_flux calls pop_grid, regress
total_soil_conductivity calls isflag, isoilm, snowd, tgg, wb, wbice, sand_vec, ssat_vec, watr, wbliq, cnsd_vec