adjust_k_Collatz – POP
adjust_k_Collatz Subroutine
46 statements
Source File
public subroutine adjust_k_Collatz(veg, p)
Arguments
Type Intent Optional Attributes Name
type(veg_parameter_type), intent(inout) :: veg
integer, intent(in) :: p
Calls
Called by
Contents
Call graph
adjust_k_collatz calls c4kci, cfrd, frac4, gm, light_inhibition, vcmax
casa_feedback calls adjust_k_collatz