ADJUST_POP_FOR_FIRE – POP
ADJUST_POP_FOR_FIRE Subroutine
36 statements
Source File
public subroutine ADJUST_POP_FOR_FIRE(pop, disturbance_interval, burned_area, FLI)
Arguments
Type Intent Optional Attributes Name
type(POP_TYPE), intent(inout) :: pop
integer(kind=i4b), intent(in) :: disturbance_interval(:,:)
real(kind=dp), intent(in) :: burned_area(:)
real(kind=dp), intent(in) :: FLI(:)
Calls
Contents
Call graph
adjust_pop_for_fire calls pop_grid, interpolate_firemortality, topkill_collins
interpolate_firemortality calls pop_grid, realexponential