adjust_JV_gm – POP
adjust_JV_gm Subroutine
91 statements
Source File
public subroutine adjust_JV_gm(veg, p)
1) Calculate An-Ci curve 2) Exclude negative parts of the An-Ci curve Avoid unrealistic Vcmax and Jmax values
Arguments
Type Intent Optional Attributes Name
type(veg_parameter_type), intent(inout) :: veg
integer, intent(in) :: p
Calls
Called by
Contents
Call graph
adjust_jv_gm calls cfrd, ejmax, frac4, gm, light_inhibition, lmdif1, point2constants, photosyn25, vcmax
casa_feedback calls adjust_jv_gm