alloc_phenvariable – POP
alloc_phenvariable Subroutine
9 statements
Source File
public subroutine alloc_phenvariable(phen, arraysize)
Uses
casadimension
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
type(phen_variable), intent(inout) :: phen
integer, intent(in) :: arraysize
Calls
Contents
Call graph
alloc_phenvariable calls aphen, doyphase, doyphasespin_1, doyphasespin_2, doyphasespin_3, doyphasespin_4, phase, phasespin, tkshed