alloc_casaflux – POP
alloc_casaflux Subroutine
7 statements
Source File
private subroutine alloc_casaflux(casaflux, arraysize)
Uses
casadimension
Arguments
Type Intent Optional Attributes Name
type(casa_flux), intent(inout) :: casaflux
integer, intent(in) :: arraysize
Calls
Called by
Contents
Call graph
alloc_casaflux calls cgpp, charvest, clabloss, cnep, cnpp, cplant_turnover, cplant_turnover_crowding, cplant_turnover_disturbance, cplant_turnover_resource_limitation, crgplant, crmplant, crp, crsoil, ctransferluc, fcrop, fharvest, fluxctoclear, fluxctoco2, fluxctoco2_litter_fire, fluxctoco2_plant_fire, fluxctohwp, fluxctolitter, fluxctosoil, fluxfromltoco2, fluxfromltoco2_fire, fluxfromltos, fluxfromptoco2, fluxfromptoco2_fire, fluxfromptoharvest, fluxfromptol, fluxfromstoco2, fluxfromstos, fluxntoatm_fire, fluxntoclear, fluxntohwp, fluxntolitter, fluxntosoil, fluxptoclear, fluxptohwp, fluxptolitter, fluxptosoil, fnminleach, fnminloss, fpleach, frac_sapwood, fraccalloc, fracclabile, fracnalloc, fracpalloc, fromltoco2, fromltos, fromptol, fromptol_fire, fromstoco2, fromstos, klitter, klitter_fire, klitter_tot, kmlabp, kplab, kplant, kplant_fire, kplant_tot, kpocc, kpsorb, ksoil, nharvest, nlittermin, nmindep, nminfix, nminleach, nminloss, nminuptake, nsimm, nsmin, nsnet, nupland, pdep, pharvest, plabuptake, pleach, plittermin, ploss, psimm, psmin, psnet, psorbmax, pupland, pwea, sapwood_area, stemnpp
alloc_casa_var calls alloc_casaflux
alloc_sum_casa calls alloc_casaflux