alloc_POPLUC – POP
alloc_POPLUC Subroutine
71 statements
Source File
public subroutine alloc_POPLUC(POPLUC, arraysize)
Arguments
Type Intent Optional Attributes Name
type(POPLUC_TYPE), intent(inout) :: POPLUC
integer, intent(in) :: arraysize
Calls
Called by
Contents
Call graph
alloc_popluc calls age_history_secdf, agprod, agprodloss, area_history_secdf, biomass_age_primary, biomass_age_secondary, cbiomass, clearprod, clearprodloss, clitt, crelclear, crop, csoil, ctos, dcsharvclear, fag, fclearance, fharvest, fluxpclearresidtolitter, fluxpharvresidtolitter, fluxsclearresidtolitter, fluxsharvresidtolitter, fnep, frac_forest, frac_primf, fracclearprod, fracclearresid, fracharvprod, fracharvresid, fracharvsecresid, freq_age_primary, freq_age_secondary, ftransfergross, ftransfernet, grass, gtop, gtos, harvprod, harvprodloss, kclear, kexpand1, kexpand2, knatdist, ksecharv, latitude, longitude, past, pharv, primf, ptoc, ptog, ptoq, ptos, qtos, secdf, smharv, stoc, stog, stoq, syharv
popluc_init calls alloc_popluc