alloc_sum_casa – POP
alloc_sum_casa Subroutine
8 statements
Source File
public subroutine alloc_sum_casa(sum_casapool, sum_casaflux, arraysize)
Arguments
Type Intent Optional Attributes Name
type(casa_pool), intent(inout) :: sum_casapool
type(casa_flux), intent(inout) :: sum_casaflux
integer, intent(in) :: arraysize
Calls
Contents
Call graph
alloc_sum_casa calls alloc_casaflux, alloc_casapool
alloc_casaflux calls cgpp, charvest, clabloss, cnep, cnpp, cplant_turnover, cplant_turnover_crowding, cplant_turnover_disturbance, cplant_turnover_resource_limitation, crgplant, crmplant, crp, crsoil, ctransferluc, fcrop, fharvest, fluxctoclear, fluxctoco2, fluxctoco2_litter_fire, fluxctoco2_plant_fire, fluxctohwp, fluxctolitter, fluxctosoil, fluxfromltoco2, fluxfromltoco2_fire, fluxfromltos, fluxfromptoco2, fluxfromptoco2_fire, fluxfromptoharvest, fluxfromptol, fluxfromstoco2, fluxfromstos, fluxntoatm_fire, fluxntoclear, fluxntohwp, fluxntolitter, fluxntosoil, fluxptoclear, fluxptohwp, fluxptolitter, fluxptosoil, fnminleach, fnminloss, fpleach, frac_sapwood, fraccalloc, fracclabile, fracnalloc, fracpalloc, fromltoco2, fromltos, fromptol, fromptol_fire, fromstoco2, fromstos, klitter, klitter_fire, klitter_tot, kmlabp, kplab, kplant, kplant_fire, kplant_tot, kpocc, kpsorb, ksoil, nharvest, nlittermin, nmindep, nminfix, nminleach, nminloss, nminuptake, nsimm, nsmin, nsnet, nupland, pdep, pharvest, plabuptake, pleach, plittermin, ploss, psimm, psmin, psnet, psorbmax, pupland, pwea, sapwood_area, stemnpp
alloc_casapool calls clabile, clitter, cplant, csoil, ctot, ctot_0, dclabiledt, dclitterdt, dcplantdt, dcsoildt, dnlitterdt, dnplantdt, dnsoildt, dnsoilmindt, dplitterdt, dpplantdt, dpsoildt, dpsoillabdt, dpsoiloccdt, dpsoilsorbdt, nlitter, nplant, nsoil, nsoilmin, plitter, pplant, psoil, psoillab, psoilocc, psoilsorb, rationclitter, rationcplant, rationcsoil, rationcsoilmax, rationcsoilmin, rationcsoilnew, rationplitter, rationpplant, rationpsoil, ratiopclitter, ratiopcplant, ratiopcsoil