alloc_casamet – POP
alloc_casamet Subroutine
8 statements
Source File
private subroutine alloc_casamet(casamet, arraysize)
Uses
casadimension
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
type(casa_met), intent(inout) :: casamet
integer, intent(in) :: arraysize
Calls
Called by
Contents
Call graph
alloc_casamet calls aprecip_av20_spin, areacell, btran, can12spin, can13spin, cgppspin, crmplantspin_1, crmplantspin_2, crmplantspin_3, d_macarthur_spin, dprecip_spin, drhum_spin, dslr_spin, dtemp_max_spin, dtemp_min_spin, du10_max_spin, ffdi_spin, frecspin, glai, ijgcm, isorder, iveg2, kbdi_spin, last_precip_spin, lat, lnonwood, lon, moist, moistavg, moistspin_1, moistspin_2, moistspin_3, moistspin_4, moistspin_5, moistspin_6, mtempspin, precip, tairk, tairkspin, tsoil, tsoilavg, tsoilspin_1, tsoilspin_2, tsoilspin_3, tsoilspin_4, tsoilspin_5, tsoilspin_6
alloc_casa_var calls alloc_casamet