alloc_casabiome – POP
alloc_casabiome Subroutine
7 statements
Source File
private subroutine alloc_casabiome(casabiome)
Uses
cable_def_types_mod
casadimension
vh_js !!
Arguments
Type Intent Optional Attributes Name
type(casa_biome), intent(inout) :: casabiome
Calls
Called by
Contents
Call graph
alloc_casabiome calls costnpup, damm_alpha, damm_ea, damm_enzpool, damm_kmcp, damm_kmo2, disturbance_interval, fraclabile, fraclignin, fracligninplant, fracnpptop, ftransnptol, ftranspptol, glaimax, glaimin, ivt2, kclabrate, kminn, kroot, krootlen, kuplabp, kuptake, la_to_sa, litterrate, maxcwd, maxfinelitter, nintercept, nslope, plantrate, prodptase, q10soil, ratiofrootleaf, rationcplantmax, rationcplantmin, rationpplantmax, rationpplantmin, ratiopcplantmax, ratiopcplantmin, rmplant, rootdepth, sla, soilrate, vcmax_scalar, xkleafcoldexp, xkleafcoldmax, xkleafdryexp, xkleafdrymax, xkoptlitter, xkoptsoil, xkplab, xkpocc, xkpsorb, xnpmax
alloc_casa_var calls alloc_casabiome