alloc_casapool – POP
alloc_casapool Subroutine
7 statements
Source File
private subroutine alloc_casapool(casapool, arraysize)
Uses
casadimension
Arguments
Type Intent Optional Attributes Name
type(casa_pool), intent(inout) :: casapool
integer, intent(in) :: arraysize
Calls
Called by
Contents
Call graph
alloc_casapool calls clabile, clitter, cplant, csoil, ctot, ctot_0, dclabiledt, dclitterdt, dcplantdt, dcsoildt, dnlitterdt, dnplantdt, dnsoildt, dnsoilmindt, dplitterdt, dpplantdt, dpsoildt, dpsoillabdt, dpsoiloccdt, dpsoilsorbdt, nlitter, nplant, nsoil, nsoilmin, plitter, pplant, psoil, psoillab, psoilocc, psoilsorb, rationclitter, rationcplant, rationcsoil, rationcsoilmax, rationcsoilmin, rationcsoilnew, rationplitter, rationpplant, rationpsoil, ratiopclitter, ratiopcplant, ratiopcsoil
alloc_casa_var calls alloc_casapool
alloc_sum_casa calls alloc_casapool