analyticpool – POP
analyticpool Subroutine
115 statements
Source File
public subroutine analyticpool(veg, soil, casabiome, casapool, casaflux, casamet, casabal, avgcleaf2met, avgcleaf2str, avgcroot2met, avgcroot2str, avgcwood2cwd, avgnleaf2met, avgnleaf2str, avgnroot2met, avgnroot2str, avgnwood2cwd, avgpleaf2met, avgpleaf2str, avgproot2met, avgproot2str, avgpwood2cwd, avgcnpp, avgxkNlimiting, avgxklitter, avgxksoil, avgratioNCsoilmic, avgratioNCsoilslow, avgratioNCsoilpass, avgnsoilmin, avgpsoillab, avgpsoilsorb, avgpsoilocc, avg_c13leaf2met, avg_c13leaf2str, avg_c13root2met, avg_c13root2str, avg_c13wood2cwd, c13o2pools)
Uses
cable_common_module
cable_c13o2_def
casavariable
casaparm
cable_carbon_module
casadimension
cable_def_types_mod
set the following two backflow to set (see Bolker 199x)
Arguments
Type Intent Optional Attributes Name
type(veg_parameter_type), intent(in) :: veg
type(soil_parameter_type), intent(in) :: soil
type(casa_biome), intent(in) :: casabiome
type(casa_pool), intent(inout) :: casapool
type(casa_flux), intent(inout) :: casaflux
type(casa_met), intent(in) :: casamet
type(casa_balance), intent(inout) :: casabal
real(kind=r_2), intent(in), dimension(mp) :: avgcleaf2met
real(kind=r_2), intent(in), dimension(mp) :: avgcleaf2str
real(kind=r_2), intent(in), dimension(mp) :: avgcroot2met
real(kind=r_2), intent(in), dimension(mp) :: avgcroot2str
real(kind=r_2), intent(in), dimension(mp) :: avgcwood2cwd
real(kind=r_2), intent(in), dimension(mp) :: avgnleaf2met
real(kind=r_2), intent(in), dimension(mp) :: avgnleaf2str
real(kind=r_2), intent(in), dimension(mp) :: avgnroot2met
real(kind=r_2), intent(in), dimension(mp) :: avgnroot2str
real(kind=r_2), intent(in), dimension(mp) :: avgnwood2cwd
real(kind=r_2), intent(in), dimension(mp) :: avgpleaf2met
real(kind=r_2), intent(in), dimension(mp) :: avgpleaf2str
real(kind=r_2), intent(in), dimension(mp) :: avgproot2met
real(kind=r_2), intent(in), dimension(mp) :: avgproot2str
real(kind=r_2), intent(in), dimension(mp) :: avgpwood2cwd
real(kind=r_2), intent(in), dimension(mp) :: avgcnpp
real(kind=r_2), intent(in), dimension(mp) :: avgxkNlimiting
real(kind=r_2), intent(in), dimension(mp) :: avgxklitter
real(kind=r_2), intent(in), dimension(mp) :: avgxksoil
real(kind=r_2), intent(in), dimension(mp) :: avgratioNCsoilmic
real(kind=r_2), intent(in), dimension(mp) :: avgratioNCsoilslow
real(kind=r_2), intent(in), dimension(mp) :: avgratioNCsoilpass
real(kind=r_2), intent(in), dimension(mp) :: avgnsoilmin
real(kind=r_2), intent(in), dimension(mp) :: avgpsoillab
real(kind=r_2), intent(in), dimension(mp) :: avgpsoilsorb
real(kind=r_2), intent(in), dimension(mp) :: avgpsoilocc
real(kind=r_2), intent(in), dimension(mp) :: avg_c13leaf2met
real(kind=r_2), intent(in), dimension(mp) :: avg_c13leaf2str
real(kind=r_2), intent(in), dimension(mp) :: avg_c13root2met
real(kind=r_2), intent(in), dimension(mp) :: avg_c13root2str
real(kind=r_2), intent(in), dimension(mp) :: avg_c13wood2cwd
type(c13o2_pool), intent(inout) :: c13o2pools
Calls
Called by
Contents
Call graph
analyticpool calls clay, clitter, csoil, fracligninplant, fromltos, fromstos, isorder, iveg, iveg2, klitter, kmlabp, ksoil, litterrate, nlitter, nsoil, psoillab, psorbmax, rationclitter, rationcsoil, rationpsoil, ratiopclitter, ratiopcsoil, silt, soilrate
spincasacnp calls analyticpool