bgcdriver – POP
bgcdriver Subroutine
124 statements
Source File
public subroutine bgcdriver(ktau, kstart, dels, met, ssnow, canopy, veg, soil, climate, casabiome, casapool, casaflux, casamet, casabal, phen, POP, ktauday, idoy, LOY, dump_read, LALLOC, c13o2flux, c13o2pools)
Uses
cable_def_types_mod
cable_common_module
POP_Types
casavariable
cable_c13o2
TypeDef
cable_phenology_module
phenvariable
casa_inout
casadimension
casaparm
cable_c13o2_def
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ktau
integer, intent(in) :: kstart
real, intent(in) :: dels
type(met_type), intent(inout) :: met
type(soil_snow_type), intent(inout) :: ssnow
type(canopy_type), intent(inout) :: canopy
type(veg_parameter_type), intent(inout) :: veg
type(soil_parameter_type), intent(inout) :: soil
type(climate_type), intent(in) :: climate
type(casa_biome), intent(inout) :: casabiome
type(casa_pool), intent(inout) :: casapool
type(casa_flux), intent(inout) :: casaflux
type(casa_met), intent(inout) :: casamet
type(casa_balance), intent(inout) :: casabal
type(phen_variable), intent(inout) :: phen
type(POP_TYPE), intent(inout) :: POP
integer, intent(in) :: ktauday
integer, intent(in) :: idoy
integer, intent(in) :: LOY
logical, intent(in) :: dump_read
integer, intent(in) :: LALLOC
type(c13o2_flux), intent(inout) :: c13o2flux
type(c13o2_pool), intent(inout) :: c13o2pools
Calls
Contents
Call graph
bgcdriver calls c13o2_save_casapool, c13o2_update_pools, cplant, crmplant, fraccalloc, biogeochem, cable_phenology_clim
biogeochem calls cplant_turnover, iwood, klitter, klitter_fire, kplant, kplant_fire, pop_grid, avgsoil, casa_allocation, casa_cnpbal, casa_cnpcycle, casa_cnpflux, casa_coeffplant, casa_coeffsoil, casa_delplant, casa_delsoil, casa_ndummy, casa_nuptake, casa_pdummy, casa_puptake, casa_rplant, casa_xkn, casa_xnp, casa_xrateplant, casa_xratesoil, phenology
cable_phenology_clim calls aphen, chilldays, doyphase, eq, gdd5, ge, gmd, iveg, patch, phase
avgsoil calls btran, moist, moistavg, tsoilavg
casa_allocation calls cplant, crmplant, fraccalloc, iveg, btran, fracnpptop, glai, glaimax, glaimin, kplant_tot, la_to_sa, moistavg, casa_wolf, sfc, sla, swilt, tsoilavg
casa_cnpbal calls cplant, klitter, klitter_fire, kplant, kplant_fire, clabile, clabilelast, clitterlast, cnpp, cplantlast, crsoil, fharvest, fluxctoco2_plant_fire, fluxctolitter, fluxfromptoco2, fromptol_fire, klitter_tot, kplant_tot, nmindep, nminfix, nminleach, nminloss, nminuptake, nsoilmin, nsoilminlast, nupland, pdep, plabuptake, pleach, ploss, psoillab, psoillablast, psoilocc, psoilocclast, psoilsorb, psoilsorblast, pupland, pwea
casa_cnpcycle calls cplant, iveg, clabile, clitter, csoil, dclabiledt, dclitterdt, dcplantdt, dcsoildt, dnlitterdt, dnplantdt, dnsoildt, dnsoilmindt, dplitterdt, dpplantdt, dpsoildt, dpsoillabdt, dpsoiloccdt, glai, glaimax, glaimin, iveg2, kmlabp, lat, lon, nlitter, nplant, nsoil, nsoilmin, plitter, pplant, casa_poolzero, psoil, psoillab, psoilocc, psorbmax, rationcplantmax, sla
casa_cnpflux calls crmplant, fcrmleafyear, fcrmrootyear, fcrmwoodyear
casa_coeffplant calls cplant, iveg, kplant, kplant_fire, fracligninplant, fromptol, ftransnptol, glai, glaimin, nplant, plantrate
casa_coeffsoil calls iveg, klitter, klitter_fire, clay, fracligninplant, fromltoco2, fromltos, fromstoco2, fromstos, isorder, iveg2, ksoil, litterrate, silt, soilrate, xkplab, xkpocc, xkpsorb
casa_delplant calls cplant, crmplant, fraccalloc, iveg, kplant, kplant_fire, cgpp, charvest, clabloss, cnpp, crgplant, dcplantdt, dnplantdt, dpplantdt, fharvest, fluxctoco2_plant_fire, fluxctolitter, fluxfromptoco2, fluxfromptoharvest, fluxntolitter, fluxptolitter, fracclabile, fracnalloc, fracpalloc, fromptol, fromptol_fire, ftransnptol, ftranspptol, iveg2, kplant_tot, lnonwood, nharvest, nminuptake, nplant, pharvest, plabuptake, pplant
casa_delsoil calls iveg, klitter, klitter_fire, clitter, cnpp, costnpup, crsoil, csoil, dpsoillabdt, fluxctoco2, fluxctoco2_litter_fire, fluxctolitter, fluxctosoil, fluxfromltoco2, fluxfromltos, fluxfromstoco2, fluxfromstos, fluxntolitter, fluxntosoil, fluxptolitter, fluxptosoil, fnminleach, fnminloss, fpleach, fromltoco2, fromltos, fromstoco2, fromstos, iveg2, klitter_tot, kmlabp, kpocc, kpsorb, ksoil, nlitter, nlittermin, nmindep, nminfix, nminleach, nminloss, nsimm, nsmin, nsnet, nsoil, nsoilmin, nupland, pdep, pleach, plitter, plittermin, prodptase, psimm, psmin, psnet, psoil, psoillab, psoilocc, psoilsorb, psorbmax, pupland, pwea, rationcsoilnew, rationpsoil, tsoilavg
casa_ndummy calls cplant, rationcplant
casa_nuptake calls iveg, iveg2, kminn, nminuptake, nsoilmin, casa_nrequire
casa_pdummy calls nplant, rationpplant
casa_puptake calls iveg, kuplabp, plabuptake, casa_prequire, psoillab
casa_rplant calls cplant, crmplant, iveg, cgpp, clabile, crgplant, frac_sapwood, frec, kclabrate, nplant, vcmax_np, qtemp_max_last_year, rationcplantmax, ratiopcplantmax, rmplant, sla, tairk, tsoilavg, vcmax, vcmax_scalar
casa_xkn calls iveg, klitter, clitter, csoil, fromltos, fromstos, iveg2, ksoil, maxcwd, maxfinelitter, nlitter, nsoil, nsoilmin, rationcsoilmax, rationcsoilmin, rationcsoilnew
casa_xnp calls cplant, iveg, cgpp, cnpp, fharvest, fracclabile, iveg2, nplant, nsoilmin, pplant, casa_nrequire, casa_prequire, psoillab, xnpmax
casa_xrateplant calls ge, iveg, phase, btran, iveg2, le, lnonwood, tairk, tkshed, xkleafcoldexp, xkleafcoldmax, xkleafdryexp, xkleafdrymax
casa_xratesoil calls iveg, damm_alpha, damm_ea, damm_enzpool, damm_kmcp, damm_kmo2, iveg2, moistavg, q10soil, ssat, tsoilavg, xkoptlitter, xkoptsoil
phenology calls doyphase, phase
casa_nrequire calls cplant, fraccalloc, iveg, kplant, ftransnptol, iveg2, nplant, nsoilmin, rationcplantmax, rationcplantmin
casa_poolzero calls cplant, clitter, csoil, nlitter, nplant, nsoil
casa_prequire calls cplant, fraccalloc, iveg, kplant, ftranspptol, iveg2, nplant, pplant, rationpplantmax, rationpplantmin
casa_wolf calls cplant, iveg, cnpp, fracnpptop, iveg2