biogeochem – POP
biogeochem Subroutine
104 statements
Source File
public subroutine biogeochem(idoy, LALLOC, veg, soil, casabiome, casapool, casaflux, casamet, casabal, phen, POP, climate, xnplimit, xkNlimiting, xklitter, xksoil, xkleaf, xkleafcold, xkleafdry, cleaf2met, cleaf2str, croot2met, croot2str, cwood2cwd, nleaf2met, nleaf2str, nroot2met, nroot2str, nwood2cwd, pleaf2met, pleaf2str, proot2met, proot2str, pwood2cwd)
Uses
POP_Types
casadimension
casa_cnp_module
cable_def_types_mod
vh_js !!
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: idoy
integer, intent(in) :: LALLOC
type(veg_parameter_type), intent(inout) :: veg
type(soil_parameter_type), intent(inout) :: soil
type(casa_biome), intent(inout) :: casabiome
type(casa_pool), intent(inout) :: casapool
type(casa_flux), intent(inout) :: casaflux
type(casa_met), intent(inout) :: casamet
type(casa_balance), intent(inout) :: casabal
type(phen_variable), intent(inout) :: phen
type(POP_TYPE), intent(in) :: POP
type(climate_TYPE), intent(in) :: climate
real(kind=r_2), intent(out), dimension(mp) :: xnplimit
real(kind=r_2), intent(out), dimension(mp) :: xkNlimiting
real(kind=r_2), intent(out), dimension(mp) :: xklitter
real(kind=r_2), intent(out), dimension(mp) :: xksoil
real(kind=r_2), intent(out), dimension(mp) :: xkleaf
real(kind=r_2), intent(out), dimension(mp) :: xkleafcold
real(kind=r_2), intent(out), dimension(mp) :: xkleafdry
real(kind=r_2), intent(out), dimension(mp) :: cleaf2met
real(kind=r_2), intent(out), dimension(mp) :: cleaf2str
real(kind=r_2), intent(out), dimension(mp) :: croot2met
real(kind=r_2), intent(out), dimension(mp) :: croot2str
real(kind=r_2), intent(out), dimension(mp) :: cwood2cwd
real(kind=r_2), intent(out), dimension(mp) :: nleaf2met
real(kind=r_2), intent(out), dimension(mp) :: nleaf2str
real(kind=r_2), intent(out), dimension(mp) :: nroot2met
real(kind=r_2), intent(out), dimension(mp) :: nroot2str
real(kind=r_2), intent(out), dimension(mp) :: nwood2cwd
real(kind=r_2), intent(out), dimension(mp) :: pleaf2met
real(kind=r_2), intent(out), dimension(mp) :: pleaf2str
real(kind=r_2), intent(out), dimension(mp) :: proot2met
real(kind=r_2), intent(out), dimension(mp) :: proot2str
real(kind=r_2), intent(out), dimension(mp) :: pwood2cwd
Calls
Called by
Contents
Call graph
biogeochem calls cplant_turnover, iwood, klitter, klitter_fire, kplant, kplant_fire, pop_grid, avgsoil, casa_allocation, casa_cnpbal, casa_cnpcycle, casa_cnpflux, casa_coeffplant, casa_coeffsoil, casa_delplant, casa_delsoil, casa_ndummy, casa_nuptake, casa_pdummy, casa_puptake, casa_rplant, casa_xkn, casa_xnp, casa_xrateplant, casa_xratesoil, phenology
avgsoil calls btran, moist, moistavg, tsoilavg
casa_allocation calls btran, cplant, crmplant, fraccalloc, fracnpptop, glai, glaimax, glaimin, iveg, kplant_tot, la_to_sa, moistavg, casa_wolf, sfc, sla, swilt, tsoilavg
casa_cnpbal calls klitter, klitter_fire, kplant, kplant_fire, clabile, clabilelast, clitterlast, cnpp, cplant, cplantlast, crsoil, fharvest, fluxctoco2_plant_fire, fluxctolitter, fluxfromptoco2, fromptol_fire, klitter_tot, kplant_tot, nmindep, nminfix, nminleach, nminloss, nminuptake, nsoilmin, nsoilminlast, nupland, pdep, plabuptake, pleach, ploss, psoillab, psoillablast, psoilocc, psoilocclast, psoilsorb, psoilsorblast, pupland, pwea
casa_cnpcycle calls clabile, clitter, cplant, csoil, dclabiledt, dclitterdt, dcplantdt, dcsoildt, dnlitterdt, dnplantdt, dnsoildt, dnsoilmindt, dplitterdt, dpplantdt, dpsoildt, dpsoillabdt, dpsoiloccdt, glai, glaimax, glaimin, iveg, iveg2, kmlabp, lat, lon, nlitter, nplant, nsoil, nsoilmin, plitter, pplant, casa_poolzero, psoil, psoillab, psoilocc, psorbmax, rationcplantmax, sla
casa_cnpflux calls crmplant, fcrmleafyear, fcrmrootyear, fcrmwoodyear
casa_coeffplant calls kplant, kplant_fire, cplant, fracligninplant, fromptol, ftransnptol, glai, glaimin, iveg, nplant, plantrate
casa_coeffsoil calls klitter, klitter_fire, clay, fracligninplant, fromltoco2, fromltos, fromstoco2, fromstos, isorder, iveg, iveg2, ksoil, litterrate, silt, soilrate, xkplab, xkpocc, xkpsorb
casa_delplant calls kplant, kplant_fire, cgpp, charvest, clabloss, cnpp, cplant, crgplant, crmplant, dcplantdt, dnplantdt, dpplantdt, fharvest, fluxctoco2_plant_fire, fluxctolitter, fluxfromptoco2, fluxfromptoharvest, fluxntolitter, fluxptolitter, fraccalloc, fracclabile, fracnalloc, fracpalloc, fromptol, fromptol_fire, ftransnptol, ftranspptol, iveg, iveg2, kplant_tot, lnonwood, nharvest, nminuptake, nplant, pharvest, plabuptake, pplant
casa_delsoil calls klitter, klitter_fire, clitter, cnpp, costnpup, crsoil, csoil, dpsoillabdt, fluxctoco2, fluxctoco2_litter_fire, fluxctolitter, fluxctosoil, fluxfromltoco2, fluxfromltos, fluxfromstoco2, fluxfromstos, fluxntolitter, fluxntosoil, fluxptolitter, fluxptosoil, fnminleach, fnminloss, fpleach, fromltoco2, fromltos, fromstoco2, fromstos, iveg, iveg2, klitter_tot, kmlabp, kpocc, kpsorb, ksoil, nlitter, nlittermin, nmindep, nminfix, nminleach, nminloss, nsimm, nsmin, nsnet, nsoil, nsoilmin, nupland, pdep, pleach, plitter, plittermin, prodptase, psimm, psmin, psnet, psoil, psoillab, psoilocc, psoilsorb, psorbmax, pupland, pwea, rationcsoilnew, rationpsoil, tsoilavg
casa_ndummy calls cplant, rationcplant
casa_nuptake calls iveg, iveg2, kminn, nminuptake, nsoilmin, casa_nrequire
casa_pdummy calls nplant, rationpplant
casa_puptake calls iveg, kuplabp, plabuptake, casa_prequire, psoillab
casa_rplant calls cgpp, clabile, cplant, crgplant, crmplant, frac_sapwood, frec, iveg, kclabrate, nplant, vcmax_np, qtemp_max_last_year, rationcplantmax, ratiopcplantmax, rmplant, sla, tairk, tsoilavg, vcmax, vcmax_scalar
casa_xkn calls klitter, clitter, csoil, fromltos, fromstos, iveg, iveg2, ksoil, maxcwd, maxfinelitter, nlitter, nsoil, nsoilmin, rationcsoilmax, rationcsoilmin, rationcsoilnew
casa_xnp calls cgpp, cnpp, cplant, fharvest, fracclabile, iveg, iveg2, nplant, nsoilmin, pplant, casa_nrequire, casa_prequire, psoillab, xnpmax
casa_xrateplant calls btran, ge, iveg, iveg2, le, lnonwood, phase, tairk, tkshed, xkleafcoldexp, xkleafcoldmax, xkleafdryexp, xkleafdrymax
casa_xratesoil calls damm_alpha, damm_ea, damm_enzpool, damm_kmcp, damm_kmo2, iveg, iveg2, moistavg, q10soil, ssat, tsoilavg, xkoptlitter, xkoptsoil
phenology calls doyphase, phase
casa_nrequire calls kplant, cplant, fraccalloc, ftransnptol, iveg, iveg2, nplant, nsoilmin, rationcplantmax, rationcplantmin
casa_poolzero calls clitter, cplant, csoil, nlitter, nplant, nsoil
casa_prequire calls kplant, cplant, fraccalloc, ftranspptol, iveg, iveg2, nplant, pplant, rationpplantmax, rationpplantmin
casa_wolf calls cnpp, cplant, fracnpptop, iveg, iveg2
bgcdriver calls biogeochem
casaonly_luc calls biogeochem
spincasacnp calls biogeochem