casa_feedback – POP
casa_feedback Subroutine
139 statements
Source File
public subroutine casa_feedback(ktau, veg, casabiome, casapool, casamet, climate, ktauday)
Uses
casaparm
cable_data_module
casavariable
cable_def_types_mod
cable_common_module
casadimension
cable_adjust_JV_gm_module
cable_optimise_JV_module
casa_cnp_module
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ktau
type(veg_parameter_type), intent(inout) :: veg
type(casa_biome), intent(inout) :: casabiome
type(casa_pool), intent(in) :: casapool
type(casa_met), intent(in) :: casamet
type(climate_type), intent(in) :: climate
integer, intent(in) :: ktauday
Calls
Contents
Call graph
casa_feedback calls cplant, ejmaxcc, glai, glaimin, gmmax, iveg, iveg2, mtemp_max20, nintercept, nplant, nslope, point2constants, pplant, adjust_jv_gm, adjust_k_collatz, find_vcmax_jmax_lut, optimise_jv, vcmax_np, rationcplantmax, rationcplantmin, rationpplantmax, rationpplantmin, sla, vcmax, vcmax_scalar, vcmaxcc
adjust_jv_gm calls point2constants, vcmax, cfrd, ejmax, frac4, gm, light_inhibition, lmdif1, photosyn25
adjust_k_collatz calls vcmax, c4kci, cfrd, frac4, gm, light_inhibition
find_vcmax_jmax_lut calls ejmaxcc, vcmax, vcmaxcc, cfrd, ejmax, frac4, gm, light_inhibition
optimise_jv calls mtemp_max20, point2constants, vcmax, vcmaxcc, a1gs, apar_leaf_shade, apar_leaf_sun, cfrd, cs_shade, cs_sun, d0gs, dleaf_shade, dleaf_sun, ejmax, frac4, mtemp, diff_ac_aj, golden, rtbis, total_photosynthesis_cost, scalex_shade, scalex_sun, tleaf_shade, tleaf_sun, vcmax_shade, vcmax_sun
diff_ac_aj calls point2constants, ej3x, fabc, fabcd, fam_c3, fan_c3, fpq, light_inhibition, xejmxt3, xejmxt3_acclim, xgmest, xrdt, xvcmxt3, xvcmxt3_acclim
rtbis calls eq, ge, le
total_photosynthesis_cost calls point2constants, ej3x, fabc, fabcd, fam_c3, fan_c3, fpq, light_inhibition, xejmxt3, xejmxt3_acclim, xgmest, xrdt, xvcmxt3, xvcmxt3_acclim