casa_delplant – POP
casa_delplant Subroutine
181 statements
Source File
public subroutine casa_delplant(veg, casabiome, casapool, casaflux, casamet, cleaf2met, cleaf2str, croot2met, croot2str, cwood2cwd, nleaf2met, nleaf2str, nroot2met, nroot2str, nwood2cwd, pleaf2met, pleaf2str, proot2met, proot2str, pwood2cwd)
vh_js !!
vh_js !! end of adjustments to avoid negative stocks Ticket#108
Arguments
Type Intent Optional Attributes Name
type(veg_parameter_type), intent(inout) :: veg
type(casa_biome), intent(inout) :: casabiome
type(casa_pool), intent(inout) :: casapool
type(casa_flux), intent(inout) :: casaflux
type(casa_met), intent(inout) :: casamet
real(kind=r_2), intent(out), dimension(mp) :: cleaf2met
real(kind=r_2), intent(out), dimension(mp) :: cleaf2str
real(kind=r_2), intent(out), dimension(mp) :: croot2met
real(kind=r_2), intent(out), dimension(mp) :: croot2str
real(kind=r_2), intent(out), dimension(mp) :: cwood2cwd
real(kind=r_2), intent(out), dimension(mp) :: nleaf2met
real(kind=r_2), intent(out), dimension(mp) :: nleaf2str
real(kind=r_2), intent(out), dimension(mp) :: nroot2met
real(kind=r_2), intent(out), dimension(mp) :: nroot2str
real(kind=r_2), intent(out), dimension(mp) :: nwood2cwd
real(kind=r_2), intent(out), dimension(mp) :: pleaf2met
real(kind=r_2), intent(out), dimension(mp) :: pleaf2str
real(kind=r_2), intent(out), dimension(mp) :: proot2met
real(kind=r_2), intent(out), dimension(mp) :: proot2str
real(kind=r_2), intent(out), dimension(mp) :: pwood2cwd
Calls
Called by
Contents
Call graph
casa_delplant calls cgpp, charvest, clabloss, cnpp, cplant, crgplant, crmplant, dcplantdt, dnplantdt, dpplantdt, fharvest, fluxctoco2_plant_fire, fluxctolitter, fluxfromptoco2, fluxfromptoharvest, fluxntolitter, fluxptolitter, fraccalloc, fracclabile, fracnalloc, fracpalloc, fromptol, fromptol_fire, ftransnptol, ftranspptol, iveg, iveg2, kplant, kplant_fire, kplant_tot, lnonwood, nharvest, nminuptake, nplant, pharvest, plabuptake, pplant
biogeochem calls casa_delplant
bgcdriver calls biogeochem
casaonly_luc calls biogeochem
spincasacnp calls biogeochem