casa_xratesoil – POP
casa_xratesoil Subroutine
110 statements
Source File
public subroutine casa_xratesoil(xklitter, xksoil, veg, soil, casamet, casabiome)
Arguments
Type Intent Optional Attributes Name
real(kind=r_2), intent(out), DIMENSION(mp) :: xklitter
real(kind=r_2), intent(out), DIMENSION(mp) :: xksoil
type(veg_parameter_type), intent(inout) :: veg
type(soil_parameter_type), intent(inout) :: soil
type(casa_met), intent(inout) :: casamet
type(casa_biome), intent(inout) :: casabiome
Calls
Called by
Contents
Call graph
casa_xratesoil calls damm_alpha, damm_ea, damm_enzpool, damm_kmcp, damm_kmo2, iveg, iveg2, moistavg, q10soil, ssat, tsoilavg, xkoptlitter, xkoptsoil
biogeochem calls casa_xratesoil
bgcdriver calls biogeochem
casaonly_luc calls biogeochem
spincasacnp calls biogeochem