casa_init – POP
casa_init Subroutine
44 statements
Source File
public subroutine casa_init(casabiome, casamet, casaflux, casapool, casabal, phen)
Uses
cable_def_types_mod
cable_common_module
casavariable
phenvariable
cable_io_vars_module
casadimension
casaparm
for first time reading file *_1220.csv (BP may2010)
SUBROUTINE casa_init(mst,casapool,casabal) end addition (BP may2010)
Arguments
Type Intent Optional Attributes Name
type(casa_biome), intent(inout) :: casabiome
type(casa_met), intent(inout) :: casamet
type(casa_flux), intent(inout) :: casaflux
type(casa_pool), intent(inout) :: casapool
type(casa_balance), intent(inout) :: casabal
type(phen_variable), intent(inout) :: phen
Calls
Contents
Call graph
casa_init calls doyphase, patch, read_casa_restart_nc, zero_casa_dump
read_casa_restart_nc calls read_netcdf_casa_var, read_netcdf_phen_var
read_netcdf_casa_var calls read_netcdf_casabal, read_netcdf_casabiome, read_netcdf_casaflux, read_netcdf_casamet, read_netcdf_casapool
read_netcdf_phen_var calls nc_err, nf90_close, nf90_get_var, nf90_inq_varid, nf90_open
read_netcdf_casabal calls nc_err, nf90_close, nf90_get_var, nf90_inq_varid, nf90_open
read_netcdf_casabiome calls nc_err, nf90_close, nf90_get_var, nf90_inq_varid, nf90_open
read_netcdf_casaflux calls nc_err, nf90_close, nf90_get_var, nf90_inq_varid, nf90_open
read_netcdf_casamet calls nc_err, nf90_close, nf90_get_var, nf90_inq_varid, nf90_open
read_netcdf_casapool calls nc_err, nf90_close, nf90_get_var, nf90_inq_varid, nf90_open