casa_Nrequire – POP
casa_Nrequire Subroutine
56 statements
Source File
public subroutine casa_Nrequire(xnCnpp, Nreqmin, Nreqmax, NtransPtoP, veg, casabiome, casapool, casaflux, casamet)
Arguments
Type Intent Optional Attributes Name
real(kind=r_2), intent(in), DIMENSION(mp) :: xnCnpp
real(kind=r_2), intent(inout), DIMENSION(mp,mplant) :: Nreqmin
real(kind=r_2), intent(inout), DIMENSION(mp,mplant) :: Nreqmax
real(kind=r_2), intent(inout), DIMENSION(mp,mplant) :: NtransPtoP
type(veg_parameter_type), intent(inout) :: veg
type(casa_biome), intent(inout) :: casabiome
type(casa_pool), intent(inout) :: casapool
type(casa_flux), intent(inout) :: casaflux
type(casa_met), intent(inout) :: casamet
Calls
Called by
Contents
Call graph
casa_nrequire calls cplant, fraccalloc, ftransnptol, iveg, iveg2, kplant, nplant, nsoilmin, rationcplantmax, rationcplantmin
casa_nuptake calls casa_nrequire
casa_xnp calls casa_nrequire
biogeochem calls casa_nuptake, casa_xnp
bgcdriver calls biogeochem
casaonly_luc calls biogeochem
spincasacnp calls biogeochem