casa_xrateplant – POP
casa_xrateplant Subroutine
40 statements
Source File
public subroutine casa_xrateplant(xkleafcold, xkleafdry, xkleaf, veg, casabiome, casamet, phen)
Uses
mo_utils
Arguments
Type Intent Optional Attributes Name
real(kind=r_2), intent(out), DIMENSION(mp) :: xkleafcold
real(kind=r_2), intent(out), DIMENSION(mp) :: xkleafdry
real(kind=r_2), intent(out), DIMENSION(mp) :: xkleaf
type(veg_parameter_type), intent(inout) :: veg
type(casa_biome), intent(inout) :: casabiome
type(casa_met), intent(inout) :: casamet
type(phen_variable), intent(inout) :: phen
Calls
Called by
Contents
Call graph
casa_xrateplant calls btran, ge, iveg, iveg2, le, lnonwood, phase, tairk, tkshed, xkleafcoldexp, xkleafcoldmax, xkleafdryexp, xkleafdrymax
biogeochem calls casa_xrateplant
bgcdriver calls biogeochem
casaonly_luc calls biogeochem
spincasacnp calls biogeochem