create_pop_gridcell_type – POP
create_pop_gridcell_type Subroutine
275 statements
Source File
public subroutine create_pop_gridcell_type(gcell_t, comm)
Uses
mpi
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: gcell_t
integer, intent(in) :: comm
Calls
Contents
Call graph
create_pop_gridcell_type calls mpi_abort, mpi_get_address, mpi_type_commit, mpi_type_create_resized, mpi_type_create_struct, create_patch
create_patch calls mpi_abort, mpi_get_address, mpi_type_commit, mpi_type_create_resized, mpi_type_create_struct, create_layer
create_layer calls mpi_abort, mpi_get_address, mpi_type_commit, mpi_type_create_resized, mpi_type_create_struct, create_cohort
create_cohort calls mpi_abort, mpi_get_address, mpi_type_commit, mpi_type_create_resized, mpi_type_create_struct