diff_Ac_Aj – POP
diff_Ac_Aj Function
117 statements
Source File
public function diff_Ac_Aj(bjv)
Uses
cable_canopy_module
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: bjv
Return Value real
Calls
Called by
Contents
Call graph
diff_ac_aj calls ej3x, point2constants, fabc, fabcd, fam_c3, fan_c3, fpq, light_inhibition, xejmxt3, xejmxt3_acclim, xgmest, xrdt, xvcmxt3, xvcmxt3_acclim
optimise_jv calls diff_ac_aj
casa_feedback calls optimise_jv