find_Vcmax_Jmax_LUT – POP
find_Vcmax_Jmax_LUT Subroutine
38 statements
Source File
public subroutine find_Vcmax_Jmax_LUT(veg, p, LUT_VcmaxJmax, LUT_gm, LUT_vcmax, LUT_Rd)
Arguments
Type Intent Optional Attributes Name
type(veg_parameter_type), intent(inout) :: veg
integer, intent(in) :: p
real(kind=dp), intent(in), dimension(:,:,:,:) :: LUT_VcmaxJmax
real(kind=dp), intent(in), dimension(:) :: LUT_gm
real(kind=dp), intent(in), dimension(:) :: LUT_vcmax
real(kind=dp), intent(in), dimension(:) :: LUT_Rd
Calls
Called by
Contents
Call graph
find_vcmax_jmax_lut calls cfrd, ejmax, ejmaxcc, frac4, gm, light_inhibition, vcmax, vcmaxcc
casa_feedback calls find_vcmax_jmax_lut