fpq – POP
fpq Subroutine
8 statements
Source File
public subroutine fpq(a, b, c, d, p, q)
Uses
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
real(kind=r_2), intent(in) :: a
real(kind=r_2), intent(in) :: b
real(kind=r_2), intent(in) :: c
real(kind=r_2), intent(in) :: d
real(kind=r_2), intent(out) :: p
real(kind=r_2), intent(out) :: q
Called by
Contents
Call graph
diff_ac_aj calls fpq
total_an_ac_aj calls fpq
total_photosynthesis calls fpq
total_photosynthesis_cost calls fpq
optimise_jv calls diff_ac_aj, total_photosynthesis_cost
casa_feedback calls optimise_jv