GetUniqueAgeFrequencies – POP
GetUniqueAgeFrequencies Subroutine
108 statements
Source File
public subroutine GetUniqueAgeFrequencies(POP, disturbance_interval, idisturb)
Arguments
Type Intent Optional Attributes Name
type(POP_TYPE), intent(inout) :: POP
integer(kind=i4b), intent(in) :: disturbance_interval(:,:)
integer(kind=i4b), intent(in) :: idisturb
Calls
Called by
Contents
Call graph
getuniqueagefrequencies calls pop_grid, cumexponential, realexponential
popstep calls getuniqueagefrequencies
popdriver calls popstep
casaonly_luc calls popdriver
spincasacnp calls popdriver