INCREMENT_AGE – POP
INCREMENT_AGE Subroutine
79 statements
Source File
public subroutine INCREMENT_AGE(POPLUC, g)
Arguments
Type Intent Optional Attributes Name
type(POPLUC_TYPE), intent(inout) :: POPLUC
integer(kind=i4b), intent(in) :: g
Calls
Called by
Contents
Call graph
increment_age calls biomass_age_secondary, freq_age_secondary, smharv, syharv
poplucstep calls increment_age
casaonly_luc calls poplucstep