INTERPOLATE_BIOMASS_2D – POP
INTERPOLATE_BIOMASS_2D Subroutine
330 statements
Source File
public subroutine INTERPOLATE_BIOMASS_2D(POP, disturbance_interval, it, g)
Uses
mo_utils
Arguments
Type Intent Optional Attributes Name
type(POP_TYPE), intent(inout) :: POP
integer(kind=i4b), intent(in) :: disturbance_interval(:,:)
integer(kind=i4b), intent(in) :: it
integer(kind=i4b), intent(in) :: g
Calls
Called by
Contents
Call graph
interpolate_biomass_2d calls eq, pop_grid, area_triangle, realexponential
getdiagnostics calls interpolate_biomass_2d
popstep calls getdiagnostics
popdriver calls popstep
casaonly_luc calls popdriver
spincasacnp calls popdriver