layer_recruitment – POP
layer_recruitment Subroutine
37 statements
Source File
public subroutine layer_recruitment(POP, precip)
Arguments
Type Intent Optional Attributes Name
type(POP_TYPE), intent(inout) :: POP
real(kind=dp), intent(in), optional :: precip(:)
Calls
Called by
Contents
Call graph
layer_recruitment calls pop_grid, get_allometry
get_allometry calls allometry, getheight, williams_allometry
patchannualdynamics calls layer_recruitment
popstep calls patchannualdynamics
popdriver calls popstep
casaonly_luc calls popdriver
spincasacnp calls popdriver