light_inhibition – POP
light_inhibition Function
10 statements
Source File
public function light_inhibition(APAR) result(xrd)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: APAR
Return Value real
Called by
Contents
Call graph
diff_ac_aj calls light_inhibition
total_an_ac_aj calls light_inhibition
total_photosynthesis calls light_inhibition
total_photosynthesis_cost calls light_inhibition
optimise_jv calls diff_ac_aj, total_photosynthesis_cost
casa_feedback calls optimise_jv