optimise_JV – POP
optimise_JV Subroutine
135 statements
Source File
public subroutine optimise_JV(veg, climate, ktauday, bjv, relcostJ)
Arguments
Type Intent Optional Attributes Name
type(veg_parameter_type), intent(inout) :: veg
type(climate_type), intent(in) :: climate
integer, intent(in) :: ktauday
real, intent(in), DIMENSION(mp) :: bjv
real, intent(in), DIMENSION(mp) :: relcostJ
Calls
Called by
Contents
Call graph
optimise_jv calls a1gs, apar_leaf_shade, apar_leaf_sun, cfrd, cs_shade, cs_sun, d0gs, dleaf_shade, dleaf_sun, ejmax, frac4, mtemp, mtemp_max20, point2constants, diff_ac_aj, golden, rtbis, total_photosynthesis_cost, scalex_shade, scalex_sun, tleaf_shade, tleaf_sun, vcmax, vcmax_shade, vcmax_sun, vcmaxcc
diff_ac_aj calls point2constants, ej3x, fabc, fabcd, fam_c3, fan_c3, fpq, light_inhibition, xejmxt3, xejmxt3_acclim, xgmest, xrdt, xvcmxt3, xvcmxt3_acclim
rtbis calls eq, ge, le
total_photosynthesis_cost calls point2constants, ej3x, fabc, fabcd, fam_c3, fan_c3, fpq, light_inhibition, xejmxt3, xejmxt3_acclim, xgmest, xrdt, xvcmxt3, xvcmxt3_acclim
casa_feedback calls optimise_jv