PatchAnnualDynamics – POP
PatchAnnualDynamics Subroutine
249 statements
Source File
public subroutine PatchAnnualDynamics(pop, StemNPP, NPPtoGPP, it, StemNPP_av, precip)
assumes crown radius (m) = 0.1492 * dbh (cm) (from G. Cook, pers. comm.)
Arguments
Type Intent Optional Attributes Name
type(POP_TYPE), intent(inout) :: pop
real(kind=dp), intent(in) :: StemNPP(:,:)
real(kind=dp), intent(in) :: NPPtoGPP(:)
integer(kind=i4b), intent(in) :: it(:)
real(kind=dp), intent(in), optional :: StemNPP_av(:)
real(kind=dp), intent(in), optional :: precip(:)
Calls
Called by
Contents
Call graph
patchannualdynamics calls pop_grid, get_allometry, layer_recruitment
get_allometry calls allometry, getheight, williams_allometry
layer_recruitment calls pop_grid, get_allometry
popstep calls patchannualdynamics
popdriver calls popstep
casaonly_luc calls popdriver
spincasacnp calls popdriver