POP_init – POP
POP_init Subroutine
27 statements
Source File
public subroutine POP_init(POP, disturbance_interval, np, Iwood, precip)
Uses
TypeDef
POP_Types
Arguments
Type Intent Optional Attributes Name
type(POP_TYPE), intent(inout) :: POP
integer(kind=i4b), intent(in) :: disturbance_interval(:,:)
integer(kind=i4b), intent(in) :: np
integer(kind=i4b), intent(in) :: Iwood(:)
real(kind=dp), intent(in), optional :: precip(:)
Calls
Contents
Call graph
pop_init calls alloc_pop, initpop2d_poisson, layer_recruitment_single_patch, zeropop
alloc_pop calls it_pop, iwood, pop_grid
initpop2d_poisson calls pop_grid, cumexponential, exponential
layer_recruitment_single_patch calls pop_grid, get_allometry
get_allometry calls allometry, getheight, williams_allometry