POPLUC_Init – POP
POPLUC_Init Subroutine
67 statements
Source File
public subroutine POPLUC_Init(POPLUC, LUC_EXPT, casapool, casaflux, casabiome, veg, POP, np)
Uses
cable_def_types_mod
casaparm
Arguments
Type Intent Optional Attributes Name
type(POPLUC_TYPE), intent(inout) :: POPLUC
type(LUC_EXPT_TYPE), intent(in) :: LUC_EXPT
type(casa_pool), intent(inout) :: casapool
type(casa_flux), intent(inout) :: casaflux
type(casa_biome), intent(in) :: casabiome
type(veg_parameter_type), intent(in) :: veg
type(POP_TYPE), intent(inout) :: POP
integer(kind=i4b), intent(in) :: np
Calls
Contents
Call graph
popluc_init calls cplant, iwood, landpt, patch, prim_only, alloc_popluc, pop_init_single, popluc_set_params, read_luc_restart_nc, zero_popluc, rationcplantmin, ratiopcplantmin
alloc_popluc calls age_history_secdf, agprod, agprodloss, area_history_secdf, biomass_age_primary, biomass_age_secondary, cbiomass, clearprod, clearprodloss, clitt, crelclear, crop, csoil, ctos, dcsharvclear, fag, fclearance, fharvest, fluxpclearresidtolitter, fluxpharvresidtolitter, fluxsclearresidtolitter, fluxsharvresidtolitter, fnep, frac_forest, frac_primf, fracclearprod, fracclearresid, fracharvprod, fracharvresid, fracharvsecresid, freq_age_primary, freq_age_secondary, ftransfergross, ftransfernet, grass, gtop, gtos, harvprod, harvprodloss, kclear, kexpand1, kexpand2, knatdist, ksecharv, latitude, longitude, past, pharv, primf, ptoc, ptog, ptoq, ptos, qtos, secdf, smharv, stoc, stog, stoq, syharv
pop_init_single calls initpop2d_poisson, layer_recruitment_single_patch, zeropop
popluc_set_params calls biome, fracharvresid, fracharvsecresid, ivegp
read_luc_restart_nc calls handle_err, nf90_close, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_open
initpop2d_poisson calls pop_grid, cumexponential, exponential
layer_recruitment_single_patch calls pop_grid, get_allometry
get_allometry calls allometry, getheight, williams_allometry