read_gm_LUT – POP
read_gm_LUT Subroutine
60 statements
Source File
public subroutine read_gm_LUT(gm_LUT_file, LUT_VcmaxJmax, LUT_gm, LUT_vcmax, LUT_Rd)
Uses
netcdf
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: gm_LUT_file
real(kind=dp), intent(out), dimension(:,:,:,:), allocatable :: LUT_VcmaxJmax
real(kind=dp), intent(out), dimension(:), allocatable :: LUT_gm
real(kind=dp), intent(out), dimension(:), allocatable :: LUT_vcmax
real(kind=dp), intent(out), dimension(:), allocatable :: LUT_Rd
Calls
Contents
Call graph
read_gm_lut calls nc_abort, nf90_close, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_open