read_netcdf_casapool – POP
read_netcdf_casapool Subroutine
100 statements
Source File
private subroutine read_netcdf_casapool(filename, casapool)
Uses
netcdf
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
type(casa_pool), intent(inout) :: casapool
Calls
Called by
Contents
Call graph
read_netcdf_casapool calls nc_err, nf90_close, nf90_get_var, nf90_inq_varid, nf90_open
read_netcdf_casa_var calls read_netcdf_casapool
read_casa_restart_nc calls read_netcdf_casa_var
casa_init calls read_casa_restart_nc