REALExponential – POP
REALExponential Function
10 statements
Source File
public function REALExponential(lambda, x)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: lambda
real(kind=dp), intent(in) :: x
Return Value real(kind=dp)
Called by
Contents
Call graph
getuniqueagefrequencies calls realexponential
interpolate_biomass_1d calls realexponential
interpolate_biomass_2d calls realexponential
interpolate_firemortality calls realexponential
adjust_pop_for_fire calls interpolate_firemortality
getdiagnostics calls interpolate_biomass_1d, interpolate_biomass_2d
popstep calls getuniqueagefrequencies, getdiagnostics
popdriver calls popstep
casaonly_luc calls popdriver
spincasacnp calls popdriver