SMOOTH_FLUX – POP
SMOOTH_FLUX Subroutine
39 statements
Source File
public subroutine SMOOTH_FLUX(POP, g, t)
Arguments
Type Intent Optional Attributes Name
type(POP_TYPE), intent(inout) :: POP
integer(kind=i4b), intent(in) :: g
integer(kind=i4b), intent(in) :: t
Calls
Called by
Contents
Call graph
smooth_flux calls pop_grid, regress
getdiagnostics calls smooth_flux
popstep calls getdiagnostics
popdriver calls popstep
casaonly_luc calls popdriver
spincasacnp calls popdriver