spincasacnp – POP
spincasacnp Subroutine
371 statements
Source File
public subroutine spincasacnp(dels, kstart, kend, mloop, veg, soil, casabiome, casapool, casaflux, casamet, casabal, phen, pop, climate, lalloc, c13o2flux, c13o2pools, BLAZE, SIMFIRE)
Uses
casadimension
TypeDef
cable_c13o2_def
POP_Constants
casa_cable
casaparm
POP_Types
blaze_drv
BLAZE_MOD
cable_c13o2
cable_def_types_mod
casavariable
cable_carbon_module
cable_common_module
casa_inout
mo_isotope
SIMFIRE_MOD
phenvariable
CLN character(len=99), intent(in) :: fcnpspin vh_js !! CLN OPEN(91, file=fcnpspin) CLN read(91,*) myearspin CLN CLOSE(91)
CLN OPEN(91,file=fcnpspin) CLN read(91,*) CLN read(91,901) ncfile
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: dels
integer, intent(in) :: kstart
integer, intent(in) :: kend
integer, intent(in) :: mloop
type(veg_parameter_type), intent(inout) :: veg
type(soil_parameter_type), intent(inout) :: soil
type(casa_biome), intent(inout) :: casabiome
type(casa_pool), intent(inout) :: casapool
type(casa_flux), intent(inout) :: casaflux
type(casa_met), intent(inout) :: casamet
type(casa_balance), intent(inout) :: casabal
type(phen_variable), intent(inout) :: phen
type(POP_TYPE), intent(inout) :: pop
type(climate_type), intent(inout) :: climate
integer, intent(in) :: lalloc
type(c13o2_flux), intent(inout) :: c13o2flux
type(c13o2_pool), intent(inout) :: c13o2pools
type(TYPE_BLAZE), intent(inout) :: BLAZE
type(TYPE_SIMFIRE), intent(inout) :: SIMFIRE
Calls
Contents
Call graph
spincasacnp calls aprecip_av20_spin, blaze_accounting, blaze_driver, c13o2_close_output, c13o2_create_output, c13o2_sanity_pools, c13o2_save_casapool, c13o2_update_pools, c13o2_write_output, can12spin, can13spin, cgppspin, cplant, crmplantspin_1, crmplantspin_2, crmplantspin_3, d_macarthur_spin, doyphasespin_1, doyphasespin_2, doyphasespin_3, doyphasespin_4, dprecip_spin, drhum_spin, dslr_spin, dtemp_max_spin, du10_max_spin, ffdi_spin, fraccalloc, frecspin, isoratio, kbdi_spin, last_precip_spin, moistspin_1, moistspin_2, moistspin_3, moistspin_4, moistspin_5, moistspin_6, mtempspin, phasespin, analyticpool, biogeochem, casa_fluxout, popdriver, read_casa_dump, write_casa_output_nc, rationcsoilnew, tairkspin, tsoilspin_1, tsoilspin_2, tsoilspin_3, tsoilspin_4, tsoilspin_5, tsoilspin_6, write_blaze_output_nc
analyticpool calls clay, clitter, csoil, fracligninplant, fromltos, fromstos, isorder, iveg, iveg2, klitter, kmlabp, ksoil, litterrate, nlitter, nsoil, psoillab, psorbmax, rationclitter, rationcsoil, rationpsoil, ratiopclitter, ratiopcsoil, silt, soilrate
biogeochem calls cplant_turnover, iwood, klitter, klitter_fire, kplant, kplant_fire, pop_grid, avgsoil, casa_allocation, casa_cnpbal, casa_cnpcycle, casa_cnpflux, casa_coeffplant, casa_coeffsoil, casa_delplant, casa_delsoil, casa_ndummy, casa_nuptake, casa_pdummy, casa_puptake, casa_rplant, casa_xkn, casa_xnp, casa_xrateplant, casa_xratesoil, phenology
casa_fluxout calls areacell, fcgppyear, fcneeyear, fcnppyear, fcrgrowyear, fcrmleafyear, fcrmrootyear, fcrmwoodyear, fcrsyear, fndepyear, fnfixyear, fnleachyear, fnlossyear, fnsnetyear, fnupyear, fpdustyear, fpleachyear, fplossyear, fpsnetyear, fpupyear, fpweayear, isoilm, isorder, iveg, lat, lon
popdriver calls disturbance_intensity, disturbance_interval, popstep
read_casa_dump calls get_var_nc, nf90_close, nf90_open, stderr_nc
write_casa_output_nc calls handle_err, nf90_close, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_put_att, nf90_put_var, patch
avgsoil calls btran, moist, moistavg, tsoilavg
casa_allocation calls cplant, fraccalloc, iveg, btran, crmplant, fracnpptop, glai, glaimax, glaimin, kplant_tot, la_to_sa, moistavg, casa_wolf, sfc, sla, swilt, tsoilavg
casa_cnpbal calls cplant, klitter, klitter_fire, kplant, kplant_fire, psoillab, clabile, clabilelast, clitterlast, cnpp, cplantlast, crsoil, fharvest, fluxctoco2_plant_fire, fluxctolitter, fluxfromptoco2, fromptol_fire, klitter_tot, kplant_tot, nmindep, nminfix, nminleach, nminloss, nminuptake, nsoilmin, nsoilminlast, nupland, pdep, plabuptake, pleach, ploss, psoillablast, psoilocc, psoilocclast, psoilsorb, psoilsorblast, pupland, pwea
casa_cnpcycle calls cplant, clitter, csoil, iveg, iveg2, kmlabp, lat, lon, nlitter, nsoil, psoillab, psorbmax, clabile, dclabiledt, dclitterdt, dcplantdt, dcsoildt, dnlitterdt, dnplantdt, dnsoildt, dnsoilmindt, dplitterdt, dpplantdt, dpsoildt, dpsoillabdt, dpsoiloccdt, glai, glaimax, glaimin, nplant, nsoilmin, plitter, pplant, casa_poolzero, psoil, psoilocc, rationcplantmax, sla
casa_cnpflux calls fcrmleafyear, fcrmrootyear, fcrmwoodyear, crmplant
casa_coeffplant calls cplant, fracligninplant, iveg, kplant, kplant_fire, fromptol, ftransnptol, glai, glaimin, nplant, plantrate
casa_coeffsoil calls clay, fracligninplant, fromltos, fromstos, isorder, iveg, iveg2, klitter, klitter_fire, ksoil, litterrate, silt, soilrate, fromltoco2, fromstoco2, xkplab, xkpocc, xkpsorb
casa_delplant calls cplant, fraccalloc, iveg, iveg2, kplant, kplant_fire, cgpp, charvest, clabloss, cnpp, crgplant, crmplant, dcplantdt, dnplantdt, dpplantdt, fharvest, fluxctoco2_plant_fire, fluxctolitter, fluxfromptoco2, fluxfromptoharvest, fluxntolitter, fluxptolitter, fracclabile, fracnalloc, fracpalloc, fromptol, fromptol_fire, ftransnptol, ftranspptol, kplant_tot, lnonwood, nharvest, nminuptake, nplant, pharvest, plabuptake, pplant
casa_delsoil calls rationcsoilnew, clitter, csoil, fromltos, fromstos, iveg, iveg2, klitter, klitter_fire, kmlabp, ksoil, nlitter, nsoil, psoillab, psorbmax, rationpsoil, cnpp, costnpup, crsoil, dpsoillabdt, fluxctoco2, fluxctoco2_litter_fire, fluxctolitter, fluxctosoil, fluxfromltoco2, fluxfromltos, fluxfromstoco2, fluxfromstos, fluxntolitter, fluxntosoil, fluxptolitter, fluxptosoil, fnminleach, fnminloss, fpleach, fromltoco2, fromstoco2, klitter_tot, kpocc, kpsorb, nlittermin, nmindep, nminfix, nminleach, nminloss, nsimm, nsmin, nsnet, nsoilmin, nupland, pdep, pleach, plitter, plittermin, prodptase, psimm, psmin, psnet, psoil, psoilocc, psoilsorb, pupland, pwea, tsoilavg
casa_ndummy calls cplant, rationcplant
casa_nuptake calls iveg, iveg2, kminn, nminuptake, nsoilmin, casa_nrequire
casa_pdummy calls nplant, rationpplant
casa_puptake calls iveg, psoillab, kuplabp, plabuptake, casa_prequire
casa_rplant calls cplant, iveg, cgpp, clabile, crgplant, crmplant, frac_sapwood, frec, kclabrate, nplant, vcmax_np, qtemp_max_last_year, rationcplantmax, ratiopcplantmax, rmplant, sla, tairk, tsoilavg, vcmax, vcmax_scalar
casa_xkn calls rationcsoilnew, clitter, csoil, fromltos, fromstos, iveg, iveg2, klitter, ksoil, nlitter, nsoil, maxcwd, maxfinelitter, nsoilmin, rationcsoilmax, rationcsoilmin
casa_xnp calls cplant, iveg, iveg2, psoillab, cgpp, cnpp, fharvest, fracclabile, nplant, nsoilmin, pplant, casa_nrequire, casa_prequire, xnpmax
casa_xrateplant calls iveg, iveg2, btran, ge, le, lnonwood, phase, tairk, tkshed, xkleafcoldexp, xkleafcoldmax, xkleafdryexp, xkleafdrymax
casa_xratesoil calls iveg, iveg2, damm_alpha, damm_ea, damm_enzpool, damm_kmcp, damm_kmo2, moistavg, q10soil, ssat, tsoilavg, xkoptlitter, xkoptsoil
phenology calls doyphase, phase
popstep calls pop_grid, getdiagnostics, getpatchfrequencies, getuniqueagefrequencies, patch_disturb, patch_partial_disturb, patch_partial_disturb2, patchannualdynamics
casa_nrequire calls cplant, fraccalloc, iveg, iveg2, kplant, ftransnptol, nplant, nsoilmin, rationcplantmax, rationcplantmin
casa_poolzero calls cplant, clitter, csoil, nlitter, nsoil, nplant
casa_prequire calls cplant, fraccalloc, iveg, iveg2, kplant, ftranspptol, nplant, pplant, rationpplantmax, rationpplantmin
casa_wolf calls cplant, iveg, iveg2, cnpp, fracnpptop
getdiagnostics calls pop_grid, get_allometry, interpolate_biomass_1d, interpolate_biomass_2d, smooth_flux
getpatchfrequencies calls pop_grid
getuniqueagefrequencies calls pop_grid, cumexponential, realexponential
patch_disturb calls pop_grid, layer_recruitment_single_patch
patch_partial_disturb calls pop_grid
patch_partial_disturb2 calls pop_grid
patchannualdynamics calls pop_grid, get_allometry, layer_recruitment
get_allometry calls allometry, getheight, williams_allometry
interpolate_biomass_1d calls pop_grid, realexponential
interpolate_biomass_2d calls pop_grid, realexponential, eq, area_triangle
layer_recruitment calls pop_grid, get_allometry
layer_recruitment_single_patch calls pop_grid, get_allometry
smooth_flux calls pop_grid, regress