total_photosynthesis_cost – POP
total_photosynthesis_cost Function
113 statements
Source File
public function total_photosynthesis_cost(bjv)
Uses
cable_canopy_module
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: bjv
Return Value real
Calls
Called by
Contents
Call graph
total_photosynthesis_cost calls ej3x, point2constants, fabc, fabcd, fam_c3, fan_c3, fpq, light_inhibition, xejmxt3, xejmxt3_acclim, xgmest, xrdt, xvcmxt3, xvcmxt3_acclim
optimise_jv calls total_photosynthesis_cost
casa_feedback calls optimise_jv