total_photosynthesis – POP
total_photosynthesis Function
107 statements
Source File
public function total_photosynthesis(bjv)
Uses
cable_def_types_mod
cable_canopy_module
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: bjv
Return Value real
Calls
Contents
Call graph
total_photosynthesis calls ej3x, point2constants, fabc, fabcd, fam_c3, fan_c3, fpq, light_inhibition, xejmxt3, xejmxt3_acclim, xgmest, xrdt, xvcmxt3, xvcmxt3_acclim