Williams_Allometry – POP
Williams_Allometry Subroutine
13 statements
Source File
public subroutine Williams_Allometry(agbiomass, density, height, dbh, basal)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: agbiomass
real(kind=dp), intent(in) :: density
real(kind=dp), intent(out) :: height
real(kind=dp), intent(out) :: dbh
real(kind=dp), intent(out) :: basal
Called by
Contents
Call graph
get_allometry calls williams_allometry
getdiagnostics calls get_allometry
layer_recruitment calls get_allometry
layer_recruitment_single_patch calls get_allometry
patchannualdynamics calls get_allometry, layer_recruitment
patch_disturb calls layer_recruitment_single_patch
pop_init calls layer_recruitment_single_patch
pop_init_single calls layer_recruitment_single_patch
popstep calls getdiagnostics, patchannualdynamics, patch_disturb
casaonly_luc calls pop_init_single, popdriver
popdriver calls popstep
popluc_init calls pop_init_single
spincasacnp calls popdriver