write_casa_restart_nc – POP
write_casa_restart_nc Subroutine
36 statements
Source File
public subroutine write_casa_restart_nc(casabiome, casamet, casapool, casaflux, casabal, phen)
Uses
phenvariable
casavariable
cable_common_module
Arguments
Type Intent Optional Attributes Name
type(casa_biome), intent(in) :: casabiome
type(casa_met), intent(in) :: casamet
type(casa_pool), intent(in) :: casapool
type(casa_flux), intent(in) :: casaflux
type(casa_balance), intent(in) :: casabal
type(phen_variable), intent(in) :: phen
Calls
Contents
Call graph
write_casa_restart_nc calls write_netcdf_casa_var, write_netcdf_phen_var
write_netcdf_casa_var calls write_netcdf_casabal, write_netcdf_casabiome, write_netcdf_casaflux, write_netcdf_casamet, write_netcdf_casapool
write_netcdf_phen_var calls nc_err, nf90_close, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_put_var
write_netcdf_casabal calls nc_err, nf90_close, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_put_var
write_netcdf_casabiome calls nc_err, nf90_close, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_put_var
write_netcdf_casaflux calls nc_err, nf90_close, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_put_var
write_netcdf_casamet calls nc_err, nf90_close, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_put_var
write_netcdf_casapool calls nc_err, nf90_close, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_put_var