write_netcdf_casabiome – POP
write_netcdf_casabiome Subroutine
126 statements
Source File
private subroutine write_netcdf_casabiome(filename, casabiome)
Uses
netcdf
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
type(casa_biome), intent(in) :: casabiome
Calls
Called by
Contents
Call graph
write_netcdf_casabiome calls nc_err, nf90_close, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_put_var
write_netcdf_casa_var calls write_netcdf_casabiome
write_casa_restart_nc calls write_netcdf_casa_var