write_netcdf_phen_var – POP
write_netcdf_phen_var Subroutine
40 statements
Source File
public subroutine write_netcdf_phen_var(filename, phen)
Uses
netcdf
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
type(phen_variable), intent(in) :: phen
Calls
Called by
Contents
Call graph
write_netcdf_phen_var calls nc_err, nf90_close, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_put_var
write_casa_restart_nc calls write_netcdf_phen_var