alloc_casa_var – POP
alloc_casa_var Interface
3 statements
Source File
public interface alloc_casa_var
Calls
Contents
Module Procedures
alloc_casabiome alloc_casapool alloc_casaflux alloc_casamet alloc_casabal
Module Procedures
private subroutine alloc_casabiome(casabiome)
vh_js !!
Arguments
Type Intent Optional Attributes Name
type(casa_biome), intent(inout) :: casabiome
private subroutine alloc_casapool(casapool, arraysize)
Arguments
Type Intent Optional Attributes Name
type(casa_pool), intent(inout) :: casapool
integer, intent(in) :: arraysize
private subroutine alloc_casaflux(casaflux, arraysize)
Arguments
Type Intent Optional Attributes Name
type(casa_flux), intent(inout) :: casaflux
integer, intent(in) :: arraysize
private subroutine alloc_casamet(casamet, arraysize)
Arguments
Type Intent Optional Attributes Name
type(casa_met), intent(inout) :: casamet
integer, intent(in) :: arraysize
private subroutine alloc_casabal(casabal, arraysize)
Arguments
Type Intent Optional Attributes Name
type(casa_balance), intent(inout) :: casabal
integer, intent(in) :: arraysize
Call graph
alloc_casa_var calls alloc_casabal, alloc_casabiome, alloc_casaflux, alloc_casamet, alloc_casapool
alloc_casabal calls cbalance, clabilelast, cleafmean, clitterlast, cplantlast, crootmean, csoillast, dcdtyear, fcgppyear, fcneeyear, fcnppyear, fcrgrowyear, fcrmleafyear, fcrmrootyear, fcrmwoodyear, fcrpyear, fcrsyear, fndepyear, fnfixyear, fnleachyear, fnlossyear, fnsnetyear, fnupyear, fpdustyear, fpleachyear, fplossyear, fpsnetyear, fpupyear, fpweayear, glaimon, glaimonx, laimax, nbalance, nlitterlast, nplantlast, nsoillast, nsoilminlast, pbalance, plitterlast, pplantlast, psoillablast, psoillast, psoilocclast, psoilsorblast, sumcbal, sumnbal, sumpbal
alloc_casabiome calls costnpup, damm_alpha, damm_ea, damm_enzpool, damm_kmcp, damm_kmo2, disturbance_interval, fraclabile, fraclignin, fracligninplant, fracnpptop, ftransnptol, ftranspptol, glaimax, glaimin, ivt2, kclabrate, kminn, kroot, krootlen, kuplabp, kuptake, la_to_sa, litterrate, maxcwd, maxfinelitter, nintercept, nslope, plantrate, prodptase, q10soil, ratiofrootleaf, rationcplantmax, rationcplantmin, rationpplantmax, rationpplantmin, ratiopcplantmax, ratiopcplantmin, rmplant, rootdepth, sla, soilrate, vcmax_scalar, xkleafcoldexp, xkleafcoldmax, xkleafdryexp, xkleafdrymax, xkoptlitter, xkoptsoil, xkplab, xkpocc, xkpsorb, xnpmax
alloc_casaflux calls cgpp, charvest, clabloss, cnep, cnpp, cplant_turnover, cplant_turnover_crowding, cplant_turnover_disturbance, cplant_turnover_resource_limitation, crgplant, crmplant, crp, crsoil, ctransferluc, fcrop, fharvest, fluxctoclear, fluxctoco2, fluxctoco2_litter_fire, fluxctoco2_plant_fire, fluxctohwp, fluxctolitter, fluxctosoil, fluxfromltoco2, fluxfromltoco2_fire, fluxfromltos, fluxfromptoco2, fluxfromptoco2_fire, fluxfromptoharvest, fluxfromptol, fluxfromstoco2, fluxfromstos, fluxntoatm_fire, fluxntoclear, fluxntohwp, fluxntolitter, fluxntosoil, fluxptoclear, fluxptohwp, fluxptolitter, fluxptosoil, fnminleach, fnminloss, fpleach, frac_sapwood, fraccalloc, fracclabile, fracnalloc, fracpalloc, fromltoco2, fromltos, fromptol, fromptol_fire, fromstoco2, fromstos, klitter, klitter_fire, klitter_tot, kmlabp, kplab, kplant, kplant_fire, kplant_tot, kpocc, kpsorb, ksoil, nharvest, nlittermin, nmindep, nminfix, nminleach, nminloss, nminuptake, nsimm, nsmin, nsnet, nupland, pdep, pharvest, plabuptake, pleach, plittermin, ploss, psimm, psmin, psnet, psorbmax, pupland, pwea, sapwood_area, stemnpp
alloc_casamet calls aprecip_av20_spin, areacell, btran, can12spin, can13spin, cgppspin, crmplantspin_1, crmplantspin_2, crmplantspin_3, d_macarthur_spin, dprecip_spin, drhum_spin, dslr_spin, dtemp_max_spin, dtemp_min_spin, du10_max_spin, ffdi_spin, frecspin, glai, ijgcm, isorder, iveg2, kbdi_spin, last_precip_spin, lat, lnonwood, lon, moist, moistavg, moistspin_1, moistspin_2, moistspin_3, moistspin_4, moistspin_5, moistspin_6, mtempspin, precip, tairk, tairkspin, tsoil, tsoilavg, tsoilspin_1, tsoilspin_2, tsoilspin_3, tsoilspin_4, tsoilspin_5, tsoilspin_6
alloc_casapool calls clabile, clitter, cplant, csoil, ctot, ctot_0, dclabiledt, dclitterdt, dcplantdt, dcsoildt, dnlitterdt, dnplantdt, dnsoildt, dnsoilmindt, dplitterdt, dpplantdt, dpsoildt, dpsoillabdt, dpsoiloccdt, dpsoilsorbdt, nlitter, nplant, nsoil, nsoilmin, plitter, pplant, psoil, psoillab, psoilocc, psoilsorb, rationclitter, rationcplant, rationcsoil, rationcsoilmax, rationcsoilmin, rationcsoilnew, rationplitter, rationpplant, rationpsoil, ratiopclitter, ratiopcplant, ratiopcsoil