alloc_casavariable – CABLE
alloc_casavariable Subroutine
28 statements
Source File
public subroutine alloc_casavariable(casabiome, casapool, casaflux, casamet, casabal, arraysize)
Uses
casaparm
Arguments
Type Intent Optional Attributes Name
type(casa_biome), intent(inout) :: casabiome
type(casa_pool), intent(inout) :: casapool
type(casa_flux), intent(inout) :: casaflux
type(casa_met), intent(inout) :: casamet
type(casa_balance), intent(inout) :: casabal
integer, intent(in) :: arraysize
Calls
Called by
Contents
Call graph
alloc_casavariable calls areacell, btran, cbalance, cgpp, cgppspin, clabile, clabilelast, clabloss, cleafmean, clitter, clitterlast, cnep, cnpp, costnpup, cplant, cplant_turnover, cplant_turnover_crowding, cplant_turnover_disturbance, cplant_turnover_resource_limitation, cplantlast, crgplant, crmplant, crmplantspin_1, crmplantspin_2, crmplantspin_3, crootmean, crp, crsoil, csoil, csoillast, ctot, ctot_0, ctransferluc, cwoodprod, dcdtyear, dclabiledt, dclitterdt, dcplantdt, dcsoildt, dnlitterdt, dnplantdt, dnsoildt, dnsoilmindt, dplitterdt, dpplantdt, dpsoildt, dpsoillabdt, dpsoiloccdt, dpsoilsorbdt, fcgppyear, fcneeyear, fcnppyear, fcrgrowyear, fcrmleafyear, fcrmrootyear, fcrmwoodyear, fcrpyear, fcrsyear, fluxctoclear, fluxctoco2, fluxctohwp, fluxctolitter, fluxctosoil, fluxntoclear, fluxntohwp, fluxntolitter, fluxntosoil, fluxptoclear, fluxptohwp, fluxptolitter, fluxptosoil, fndepyear, fnfixyear, fnleachyear, fnlossyear, fnminleach, fnminloss, fnsnetyear, fnupyear, fpdustyear, fpleach, fpleachyear, fplossyear, fpsnetyear, fpupyear, fpweayear, frac_sapwood, fraccalloc, fracclabile, fraclabile, fraclignin, fracligninplant, fracnalloc, fracnpptop, fracpalloc, fromltoco2, fromltos, fromptol, fromstoco2, fromstos, ftransnptol, ftranspptol, glai, glaimax, glaimin, glaimon, glaimonx, ijgcm, isorder, iveg2, ivt2, kclabrate, klitter, kminn, kmlabp, kplab, kplant, kpocc, kpsorb, kroot, krootlen, ksoil, kuplabp, kuptake, laimax, lat, litterrate, lnonwood, lon, maxcwd, maxfinelitter, meangpp, meanrleaf, moist, moistavg, moistspin_1, moistspin_2, moistspin_3, moistspin_4, moistspin_5, moistspin_6, mtempspin, nbalance, nintercept, nlitter, nlitterlast, nlittermin, nmindep, nminfix, nminleach, nminloss, nminuptake, nplant, nplantlast, nsimm, nslope, nsmin, nsnet, nsoil, nsoillast, nsoilmin, nsoilminlast, nupland, nwoodprod, pbalance, pdep, plabuptake, plantrate, pleach, plitter, plitterlast, plittermin, ploss, pplant, pplantlast, precip, prodptase, psimm, psmin, psnet, psoil, psoillab, psoillablast, psoillast, psoilocc, psoilocclast, psoilsorb, psoilsorblast, psorbmax, pupland, pwea, pwoodprod, q10soil, ratiofrootleaf, rationclitter, rationcplant, rationcplantmax, rationcplantmin, rationcsoil, rationcsoilmax, rationcsoilmin, rationcsoilnew, rationplitter, rationpplant, rationpplantmax, rationpplantmin, rationpsoil, ratiopclitter, ratiopcplant, ratiopcplantmax, ratiopcplantmin, ratiopcsoil, rmplant, rootdepth, sapwood_area, sla, soilrate, stemnpp, sumcbal, sumnbal, sumpbal, tairk, tairkspin, tsoil, tsoilavg, tsoilspin_1, tsoilspin_2, tsoilspin_3, tsoilspin_4, tsoilspin_5, tsoilspin_6, xkleafcoldexp, xkleafcoldmax, xkleafdryexp, xkleafdrymax, xkoptlitter, xkoptsoil, xkplab, xkpocc, xkpsorb, xnpmax
load_parameters calls alloc_casavariable
worker_casa_params calls alloc_casavariable
mpidrv_master calls load_parameters
mpidrv_worker calls worker_casa_params
cable_offline_driver calls load_parameters
mpi_driver calls mpidrv_master, mpidrv_worker