alloc_sum_flux_type – CABLE
alloc_sum_flux_type Subroutine
16 statements
Source File
public subroutine alloc_sum_flux_type(var, mp)
Arguments
Type Intent Optional Attributes Name
type(sum_flux_type), intent(inout) :: var
integer, intent(in) :: mp
Called by
Contents
Call graph
alloc_cbm_var calls alloc_sum_flux_type
allocate_cable_vars calls alloc_cbm_var
climate_init calls alloc_cbm_var
mpidrv_master calls alloc_cbm_var, load_parameters, master_climate_types
load_parameters calls allocate_cable_vars
master_climate_types calls climate_init
worker_cable_params calls allocate_cable_vars
worker_climate_types calls climate_init
cable_offline_driver calls climate_init, load_parameters
mpi_driver calls mpidrv_master, mpidrv_worker
mpidrv_worker calls worker_cable_params, worker_climate_types