alloc_soil_parameter_type – CABLE
alloc_soil_parameter_type Subroutine
66 statements
Source File
public subroutine alloc_soil_parameter_type(var, mp)
Arguments
Type Intent Optional Attributes Name
type(soil_parameter_type), intent(inout) :: var
integer, intent(in) :: mp
Calls
Called by
Contents
Call graph
alloc_soil_parameter_type calls bch_vec, clay_vec, drain_dens, elev, elev_std, gwbch_vec, gwdz, gwhyds_vec, gwrhosoil_vec, gwssat_vec, gwsucs_vec, gwwatr, gwz, hyds_vec, org_vec, rhosoil_vec, sand_vec, sfc_vec, silt_vec, slope, slope_std, ssat_vec, sucs_vec, swilt_vec, watr
alloc_cbm_var calls alloc_soil_parameter_type
allocate_cable_vars calls alloc_cbm_var
climate_init calls alloc_cbm_var
mpidrv_master calls alloc_cbm_var, load_parameters, master_climate_types
load_parameters calls allocate_cable_vars
master_climate_types calls climate_init
worker_cable_params calls allocate_cable_vars
worker_climate_types calls climate_init
cable_offline_driver calls climate_init, load_parameters
mpi_driver calls mpidrv_master, mpidrv_worker
mpidrv_worker calls worker_cable_params, worker_climate_types