alloc_veg_parameter_type – CABLE
alloc_veg_parameter_type Subroutine
53 statements
Source File
public subroutine alloc_veg_parameter_type(var, mp)
Arguments
Type Intent Optional Attributes Name
type(veg_parameter_type), intent(inout) :: var
integer, intent(in) :: mp
Calls
Called by
Contents
Call graph
alloc_veg_parameter_type calls a1gs, alpha, cfrd, conkc0, conko0, convex, d0gs, deciduous, ekc, eko, extkn, froot, gswmin, refl, taul, vlaimax, wai
alloc_cbm_var calls alloc_veg_parameter_type
allocate_cable_vars calls alloc_cbm_var
climate_init calls alloc_cbm_var
mpidrv_master calls alloc_cbm_var, load_parameters, master_climate_types
load_parameters calls allocate_cable_vars
master_climate_types calls climate_init
worker_cable_params calls allocate_cable_vars
worker_climate_types calls climate_init
cable_offline_driver calls climate_init, load_parameters
mpi_driver calls mpidrv_master, mpidrv_worker
mpidrv_worker calls worker_cable_params, worker_climate_types