allocate_cable_vars – CABLE
allocate_cable_vars Subroutine
26 statements
Source File
public subroutine allocate_cable_vars(air, bgc, canopy, met, bal, rad, rough, soil, ssnow, sum_flux, veg, arraysize)
Arguments
Type Intent Optional Attributes Name
type(air_type), intent(inout) :: air
type(bgc_pool_type), intent(inout) :: bgc
type(canopy_type), intent(inout) :: canopy
type(met_type), intent(inout) :: met
type(balances_type), intent(inout) :: bal
type(radiation_type), intent(inout) :: rad
type(roughness_type), intent(inout) :: rough
type(soil_parameter_type), intent(inout) :: soil
type(soil_snow_type), intent(inout) :: ssnow
type(sum_flux_type), intent(inout) :: sum_flux
type(veg_parameter_type), intent(inout) :: veg
integer, intent(in) :: arraysize
Calls
Called by
Contents
Call graph
allocate_cable_vars calls alloc_cbm_var
alloc_cbm_var calls alloc_air_type, alloc_balances_type, alloc_bgc_pool_type, alloc_canopy_type, alloc_climate_type, alloc_met_type, alloc_radiation_type, alloc_roughness_type, alloc_soil_parameter_type, alloc_soil_snow_type, alloc_sum_flux_type, alloc_veg_parameter_type
alloc_canopy_type calls sublayer_dz
alloc_soil_parameter_type calls bch_vec, clay_vec, drain_dens, elev, elev_std, gwbch_vec, gwdz, gwhyds_vec, gwrhosoil_vec, gwssat_vec, gwsucs_vec, gwwatr, gwz, hyds_vec, org_vec, rhosoil_vec, sand_vec, sfc_vec, silt_vec, slope, slope_std, ssat_vec, sucs_vec, swilt_vec, watr
alloc_soil_snow_type calls dhkdw, dsmpdw, evapfbl, fland, fracice, gwdhkdw, gwdsmpdw, gwhk, gwsmp, gwwb, gwwbeq, gwzq, hk, icefrac, ifland, otgg, otss, otss_0, owetfac, qasrf, qfsrf, qhlev, qhz, qrecharge, qssrf, qstss, rh_srf, rt_qh_sublayer, rtevap_sat, rtevap_unsat, satfrac, sinfil, smp, t_snwlr, tevap, tggav, tilefrac, totenbal, totenbal2, totwblake, tprecip, trnoff, wb_lake, wbeq, wbfice, wbliq, wbtot, wbtot1, wbtot2, wetfac, wmice, wmliq, wmtot, wtd, zq
alloc_veg_parameter_type calls a1gs, alpha, cfrd, conkc0, conko0, convex, d0gs, deciduous, ekc, eko, extkn, froot, gswmin, refl, taul, vlaimax, wai
load_parameters calls allocate_cable_vars
worker_cable_params calls allocate_cable_vars
mpidrv_master calls load_parameters
mpidrv_worker calls worker_cable_params
cable_offline_driver calls load_parameters
mpi_driver calls mpidrv_master, mpidrv_worker