alloc_soil_snow_type – CABLE
alloc_soil_snow_type Subroutine
127 statements
Source File
public subroutine alloc_soil_snow_type(var, mp)
Arguments
Type Intent Optional Attributes Name
type(soil_snow_type), intent(inout) :: var
integer, intent(in) :: mp
Calls
Called by
Contents
Call graph
alloc_soil_snow_type calls dhkdw, dsmpdw, evapfbl, fland, fracice, gwdhkdw, gwdsmpdw, gwhk, gwsmp, gwwb, gwwbeq, gwzq, hk, icefrac, ifland, otgg, otss, otss_0, owetfac, qasrf, qfsrf, qhlev, qhz, qrecharge, qssrf, qstss, rh_srf, rt_qh_sublayer, rtevap_sat, rtevap_unsat, satfrac, sinfil, smp, t_snwlr, tevap, tggav, tilefrac, totenbal, totenbal2, totwblake, tprecip, trnoff, wb_lake, wbeq, wbfice, wbliq, wbtot, wbtot1, wbtot2, wetfac, wmice, wmliq, wmtot, wtd, zq
alloc_cbm_var calls alloc_soil_snow_type
allocate_cable_vars calls alloc_cbm_var
climate_init calls alloc_cbm_var
mpidrv_master calls alloc_cbm_var, load_parameters, master_climate_types
load_parameters calls allocate_cable_vars
master_climate_types calls climate_init
worker_cable_params calls allocate_cable_vars
worker_climate_types calls climate_init
cable_offline_driver calls climate_init, load_parameters
mpi_driver calls mpidrv_master, mpidrv_worker
mpidrv_worker calls worker_cable_params, worker_climate_types