alloc_sum_casavariable – CABLE
alloc_sum_casavariable Subroutine
12 statements
Source File
public subroutine alloc_sum_casavariable(sum_casapool, sum_casaflux, arraysize)
Uses
casaparm
Arguments
Type Intent Optional Attributes Name
type(casa_pool), intent(inout) :: sum_casapool
type(casa_flux), intent(inout) :: sum_casaflux
integer, intent(in) :: arraysize
Calls
Called by
Contents
Call graph
alloc_sum_casavariable calls cgpp, clabile, clabloss, clitter, cnep, cnpp, cplant, cplant_turnover, cplant_turnover_crowding, cplant_turnover_disturbance, cplant_turnover_resource_limitation, crgplant, crmplant, crp, crsoil, csoil, dclabiledt, dclitterdt, dcplantdt, dcsoildt, dnlitterdt, dnplantdt, dnsoildt, dnsoilmindt, dplitterdt, dpplantdt, dpsoildt, dpsoillabdt, dpsoiloccdt, dpsoilsorbdt, fluxctoco2, fluxctolitter, fluxctosoil, fluxntolitter, fluxntosoil, fluxptolitter, fluxptosoil, fnminleach, fnminloss, fpleach, frac_sapwood, fraccalloc, fracclabile, fracnalloc, fracpalloc, fromltoco2, fromltos, fromptol, fromstoco2, fromstos, klitter, kmlabp, kplab, kplant, kpocc, kpsorb, ksoil, nlitter, nlittermin, nmindep, nminfix, nminleach, nminloss, nminuptake, nplant, nsimm, nsmin, nsnet, nsoil, nsoilmin, nupland, pdep, plabuptake, pleach, plitter, plittermin, ploss, pplant, psimm, psmin, psnet, psoil, psoillab, psoilocc, psoilsorb, psorbmax, pupland, pwea, rationclitter, rationcplant, rationcsoil, rationcsoilmax, rationcsoilmin, rationcsoilnew, rationplitter, rationpplant, rationpsoil, ratiopclitter, ratiopcplant, ratiopcsoil, sapwood_area, stemnpp
load_parameters calls alloc_sum_casavariable
mpidrv_master calls load_parameters
cable_offline_driver calls load_parameters
mpi_driver calls mpidrv_master