alloc_POP – CABLE
alloc_POP Subroutine
9 statements
Source File
public subroutine alloc_POP(POP, arraysize)
Uses
TypeDef
POP_Types
Arguments
Type Intent Optional Attributes Name
type(POP_TYPE), intent(inout) :: POP
integer, intent(in) :: arraysize
Calls
Called by
Contents
Call graph
alloc_pop calls it_pop, iwood, pop_grid
pop_init calls alloc_pop
load_parameters calls pop_init
worker_pop_types calls pop_init
mpidrv_master calls load_parameters
mpidrv_worker calls worker_pop_types
cable_offline_driver calls load_parameters
mpi_driver calls mpidrv_master, mpidrv_worker