aquifer_recharge – CABLE
aquifer_recharge Subroutine
18 statements
Source File
private subroutine aquifer_recharge(dt, ssnow, soil, veg, zaq, zmm, dzmm)
Uses
cable_common_module
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: dt
type(soil_snow_type), intent(inout) :: ssnow
type(soil_parameter_type), intent(inout) :: soil
type(veg_parameter_type), intent(inout) :: veg
real(kind=r_2), intent(in), DIMENSION(:) :: zaq
real(kind=r_2), intent(in), DIMENSION(:) :: zmm
real(kind=r_2), intent(in), DIMENSION(:) :: dzmm
Calls
Called by
Contents
Call graph
aquifer_recharge calls gwhk, hk, isoilm, iveg, smp, wtd, zq, zse_vec
sli_hydrology calls aquifer_recharge
smoistgw calls aquifer_recharge
soil_snow_gw calls smoistgw