Area_Triangle – CABLE
Area_Triangle Function
5 statements
Source File
public function Area_Triangle(x1, y1, x2, y2, x3, y3)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x1
real(kind=dp), intent(in) :: y1
real(kind=dp), intent(in) :: x2
real(kind=dp), intent(in) :: y2
real(kind=dp), intent(in) :: x3
real(kind=dp), intent(in) :: y3
Return Value real(kind=dp)
Called by
Contents
Call graph
interpolate_biomass_2d calls area_triangle
getdiagnostics calls interpolate_biomass_2d
popstep calls getdiagnostics
popdriver calls popstep
casaonly_luc calls popdriver
mpidrv_worker calls popdriver, worker_casaonly_luc, worker_spincasacnp
spincasacnp calls popdriver
worker_casaonly_luc calls popdriver
worker_spincasacnp calls popdriver
cable_offline_driver calls popdriver, casaonly_luc, spincasacnp
mpi_driver calls mpidrv_worker