avgsoil – CABLE
avgsoil Subroutine
18 statements
Source File
public subroutine avgsoil(veg, soil, casamet)
Arguments
Type Intent Optional Attributes Name
type(veg_parameter_type), intent(inout) :: veg
type(soil_parameter_type), intent(inout) :: soil
type(casa_met), intent(inout) :: casamet
Calls
Called by
Contents
Call graph
avgsoil calls btran, moist, moistavg, sfc, swilt, tsoilavg
biogeochem calls avgsoil
bgcdriver calls biogeochem
casaonly_luc calls biogeochem
spincasacnp calls biogeochem
worker_casaonly_luc calls biogeochem
worker_spincasacnp calls biogeochem
mpidrv_worker calls bgcdriver, worker_casaonly_luc, worker_spincasacnp
cable_offline_driver calls bgcdriver, casaonly_luc, spincasacnp
mpi_driver calls mpidrv_worker