biome1_pft – CABLE
biome1_pft Subroutine
154 statements
Source File
public subroutine biome1_pft(climate, np)
Arguments
Type Intent Optional Attributes Name
type(climate_type), intent(inout) :: climate
integer, intent(in) :: np
Calls
Called by
Contents
Call graph
biome1_pft calls agdd0, agdd5, biome, iveg, mtemp_max20, mtemp_min20
cable_climate calls biome1_pft
mpidrv_worker calls cable_climate
cable_offline_driver calls cable_climate
mpi_driver calls mpidrv_worker