cable_climate – CABLE
cable_climate Subroutine
145 statements
Source File
public subroutine cable_climate(ktau, kstart, kend, ktauday, idoy, LOY, met, climate, canopy, air, rad, dels, np)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ktau
integer, intent(in) :: kstart
integer, intent(in) :: kend
integer, intent(in) :: ktauday
integer, intent(in) :: idoy
integer, intent(in) :: LOY
type(met_type), intent(in) :: met
type(climate_type), intent(inout) :: climate
type(canopy_type), intent(in) :: canopy
type(air_type), intent(in) :: air
type(radiation_type), intent(in) :: rad
real, intent(in) :: dels
integer, intent(in) :: np
Calls
Called by
Contents
Call graph
cable_climate calls alpha_pt_20, dmoist_31, dtemp_31, dtemp_91, float, mtemp_max_20, mtemp_min_20, biome1_pft, epsif
biome1_pft calls agdd0, agdd5, biome, iveg, mtemp_max20, mtemp_min20
mpidrv_worker calls cable_climate
cable_offline_driver calls cable_climate
mpi_driver calls mpidrv_worker