cable_phenology_clim – CABLE
cable_phenology_clim Subroutine
63 statements
Source File
public subroutine cable_phenology_clim(veg, climate, phen)
Uses
casadimension
casaparm
phenvariable
casavariable
Arguments
Type Intent Optional Attributes Name
type(veg_parameter_type), intent(in) :: veg
type(climate_type), intent(in) :: climate
type(phen_variable), intent(inout) :: phen
Calls
Called by
Contents
Call graph
cable_phenology_clim calls aphen, chilldays, dmoist, doyphase, gdd5, iveg, phase
bgcdriver calls cable_phenology_clim
mpidrv_worker calls bgcdriver
cable_offline_driver calls bgcdriver
mpi_driver calls mpidrv_worker