cable_Lprintf2 – CABLE
cable_Lprintf2 Subroutine
43 statements
Source File
public subroutine cable_Lprintf2(iDiag, basename, dimx, dimy, timestep, node, dir, var1)
Uses
cable_common_module
Arguments
Type Intent Optional Attributes Name
integer :: iDiag
character(len=*) :: basename
integer :: dimx
integer :: dimy
integer :: timestep
integer :: node
character(len=*) :: dir
logical, dimension(dimx,dimy) :: var1
Calls
Called by
Contents
Call graph
cable_lprintf2 calls check_timestep, open_file_per_node
open_file_per_node calls open_idiag
cable_fprintf calls cable_lprintf2