calc_srf_wet_fraction – CABLE
calc_srf_wet_fraction Subroutine
57 statements
Source File
public subroutine calc_srf_wet_fraction(ssnow, soil, met, veg)
Arguments
Type Intent Optional Attributes Name
type(soil_snow_type), intent(inout) :: ssnow
type(soil_parameter_type), intent(in) :: soil
type(met_type), intent(in) :: met
type(veg_parameter_type), intent(in) :: veg
Calls
Contents
Call graph
calc_srf_wet_fraction calls iveg, saturated_fraction, satfrac, sfc_vec, snowd, ssat_vec, swilt_vec, tk, wb, wbice, wetfac, zse_vec
saturated_fraction calls iveg, ssat_vec, wb, wbice, zse_vec, my_erf, slope_std, watr, zse