calc_soil_hydraulic_props – CABLE
calc_soil_hydraulic_props Subroutine
95 statements
Source File
private subroutine calc_soil_hydraulic_props(ssnow, soil, veg)
Uses
cable_common_module
Arguments
Type Intent Optional Attributes Name
type(soil_snow_type), intent(inout) :: ssnow
type(soil_parameter_type), intent(inout) :: soil
type(veg_parameter_type), intent(inout) :: veg
Calls
Called by
Contents
Call graph
calc_soil_hydraulic_props calls bch_vec, drain_dens, fracice, gwbch_vec, gwhk, gwhyds_vec, gwsmp, gwssat_vec, gwsucs_vec, gwwatr, gwwb, hyds_vec, icefrac, isoilm, smp, ssat_vec, sucs_vec, watr, wb, wbice, wbliq, wtd
sli_hydrology calls calc_soil_hydraulic_props
smoistgw calls calc_soil_hydraulic_props
soil_snow_gw calls smoistgw