calc_equilibrium_water_content – CABLE
calc_equilibrium_water_content Subroutine
86 statements
Source File
private subroutine calc_equilibrium_water_content(ssnow, soil)
Arguments
Type Intent Optional Attributes Name
type(soil_snow_type), intent(inout) :: ssnow
type(soil_parameter_type), intent(inout) :: soil
Calls
Called by
Contents
Call graph
calc_equilibrium_water_content calls bch_vec, gwbch_vec, gwdz, gwssat_vec, gwsucs_vec, gwwatr, gwwbeq, gwzq, ssat_vec, sucs_vec, watr, wbeq, wbice, wtd, zse
smoistgw calls calc_equilibrium_water_content
soil_snow_gw calls smoistgw