CALCULATE_WEIGHTS – CABLE
CALCULATE_WEIGHTS Subroutine
20 statements
Source File
public subroutine CALCULATE_WEIGHTS(POPLUC, g)
Arguments
Type Intent Optional Attributes Name
type(POPLUC_TYPE), intent(inout) :: POPLUC
integer(kind=i4b), intent(in) :: g
Calls
Contents
Call graph
calculate_weights calls age_history_secdf, area_history_secdf, freq_age_primary, n_event, realexponential