casa_readphen – CABLE
casa_readphen Subroutine
42 statements
Source File
public subroutine casa_readphen(veg, casamet, phen)
Uses
cable_def_types_mod
casadimension
phenvariable
casavariable
casaparm
Arguments
Type Intent Optional Attributes Name
type(veg_parameter_type), intent(in) :: veg
type(casa_met), intent(in) :: casamet
type(phen_variable), intent(inout) :: phen
Calls
Called by
Contents
Call graph
casa_readphen calls doyphase, iveg, lat
load_parameters calls casa_readphen
mpidrv_master calls load_parameters
cable_offline_driver calls load_parameters
mpi_driver calls mpidrv_master