casa_pdummy – CABLE
casa_pdummy Subroutine
27 statements
Source File
public subroutine casa_pdummy(casamet, casabal, casaflux, casapool)
Arguments
Type Intent Optional Attributes Name
type(casa_met), intent(in) :: casamet
type(casa_balance), intent(inout) :: casabal
type(casa_flux), intent(in) :: casaflux
type(casa_pool), intent(inout) :: casapool
Calls
Called by
Contents
Call graph
casa_pdummy calls clitter, cplant, csoil, isorder, ratiopclitter, ratiopcplant, ratiopcsoil
biogeochem calls casa_pdummy
bgcdriver calls biogeochem
casaonly_luc calls biogeochem
spincasacnp calls biogeochem
worker_casaonly_luc calls biogeochem
worker_spincasacnp calls biogeochem
mpidrv_worker calls bgcdriver, worker_casaonly_luc, worker_spincasacnp
cable_offline_driver calls bgcdriver, casaonly_luc, spincasacnp
mpi_driver calls mpidrv_worker