casa_xkN – CABLE
casa_xkN Subroutine
56 statements
Source File
public subroutine casa_xkN(xkNlimiting, casapool, casaflux, casamet, casabiome, veg)
Arguments
Type Intent Optional Attributes Name
real(kind=r_2), intent(inout), DIMENSION(mp) :: xkNlimiting
type(casa_pool), intent(inout) :: casapool
type(casa_flux), intent(inout) :: casaflux
type(casa_met), intent(inout) :: casamet
type(casa_biome), intent(inout) :: casabiome
type(veg_parameter_type), intent(in) :: veg
Calls
Called by
Contents
Call graph
casa_xkn calls clitter, csoil, fromltos, fromstos, iveg, iveg2, klitter, ksoil, maxcwd, maxfinelitter, nlitter, nsoil, nsoilmin, rationcsoilmax, rationcsoilmin, rationcsoilnew
biogeochem calls casa_xkn
bgcdriver calls biogeochem
casaonly_luc calls biogeochem
spincasacnp calls biogeochem
worker_casaonly_luc calls biogeochem
worker_spincasacnp calls biogeochem
mpidrv_worker calls bgcdriver, worker_casaonly_luc, worker_spincasacnp
cable_offline_driver calls bgcdriver, casaonly_luc, spincasacnp
mpi_driver calls mpidrv_worker