casa_coeffplant – CABLE
casa_coeffplant Subroutine
30 statements
Source File
public subroutine casa_coeffplant(xkleafcold, xkleafdry, xkleaf, veg, casabiome, casapool, casaflux, casamet, phen)
Arguments
Type Intent Optional Attributes Name
real(kind=r_2), intent(in), DIMENSION(mp) :: xkleafcold
real(kind=r_2), intent(in), DIMENSION(mp) :: xkleafdry
real(kind=r_2), intent(in), DIMENSION(mp) :: xkleaf
type(veg_parameter_type), intent(inout) :: veg
type(casa_biome), intent(inout) :: casabiome
type(casa_pool), intent(inout) :: casapool
type(casa_flux), intent(inout) :: casaflux
type(casa_met), intent(inout) :: casamet
type(phen_variable), intent(in) :: phen
Calls
Called by
Contents
Call graph
casa_coeffplant calls cplant, fracligninplant, fromptol, ftransnptol, glai, glaimin, iveg, kplant, nplant, plantrate
biogeochem calls casa_coeffplant
bgcdriver calls biogeochem
casaonly_luc calls biogeochem
spincasacnp calls biogeochem
worker_casaonly_luc calls biogeochem
worker_spincasacnp calls biogeochem
mpidrv_worker calls bgcdriver, worker_casaonly_luc, worker_spincasacnp
cable_offline_driver calls bgcdriver, casaonly_luc, spincasacnp
mpi_driver calls mpidrv_worker