casa_poolout – CABLE
casa_poolout Subroutine
91 statements
Source File
public subroutine casa_poolout(ktau, veg, soil, casabiome, casapool, casaflux, casamet, casabal, phen)
Uses
cable_common_module
phenvariable
cable_def_types_mod
casaparm
casadimension
casavariable
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ktau
type(veg_parameter_type), intent(inout) :: veg
type(soil_parameter_type), intent(inout) :: soil
type(casa_biome), intent(inout) :: casabiome
type(casa_pool), intent(inout) :: casapool
type(casa_flux), intent(inout) :: casaflux
type(casa_met), intent(inout) :: casamet
type(casa_balance), intent(inout) :: casabal
type(phen_variable), intent(inout) :: phen
Calls
Called by
Contents
Call graph
casa_poolout calls 100, 2, 5, aphen, areacell, doyphase, frac_sapwood, glai, isoilm, isorder, iveg, iveg2, kmlabp, lat, lon, phase, psorbmax, rationclitter, rationcplant, rationcsoil, rationplitter, rationpplant, rationpsoil, sapwood_area, sla, sumcbal, sumnbal, sumpbal
master_spincasacnp calls casa_poolout
mpidrv_master calls master_spincasacnp
mpi_driver calls mpidrv_master