casa_coeffsoil – CABLE
casa_coeffsoil Subroutine
58 statements
Source File
public subroutine casa_coeffsoil(xklitter, xksoil, veg, soil, casabiome, casaflux, casamet)
Arguments
Type Intent Optional Attributes Name
real(kind=r_2), intent(in), DIMENSION(mp) :: xklitter
real(kind=r_2), intent(in), DIMENSION(mp) :: xksoil
type(veg_parameter_type), intent(inout) :: veg
type(soil_parameter_type), intent(inout) :: soil
type(casa_biome), intent(inout) :: casabiome
type(casa_flux), intent(inout) :: casaflux
type(casa_met), intent(inout) :: casamet
Calls
Called by
Contents
Call graph
casa_coeffsoil calls clay, fracligninplant, fromltoco2, fromltos, fromstoco2, fromstos, isorder, iveg, iveg2, ksoil, litterrate, silt, soilrate, xkplab, xkpocc, xkpsorb
biogeochem calls casa_coeffsoil
bgcdriver calls biogeochem
casaonly_luc calls biogeochem
spincasacnp calls biogeochem
worker_casaonly_luc calls biogeochem
worker_spincasacnp calls biogeochem
mpidrv_worker calls bgcdriver, worker_casaonly_luc, worker_spincasacnp
cable_offline_driver calls bgcdriver, casaonly_luc, spincasacnp
mpi_driver calls mpidrv_worker