casa_cnpcycle – CABLE
casa_cnpcycle Subroutine
123 statements
Source File
public subroutine casa_cnpcycle(veg, casabiome, casapool, casaflux, casamet, casabal, LALLOC)
Arguments
Type Intent Optional Attributes Name
type(veg_parameter_type), intent(inout) :: veg
type(casa_biome), intent(inout) :: casabiome
type(casa_pool), intent(inout) :: casapool
type(casa_flux), intent(inout) :: casaflux
type(casa_met), intent(inout) :: casamet
type(casa_balance), intent(inout) :: casabal
integer, intent(in) :: LALLOC
Calls
Called by
Contents
Call graph
casa_cnpcycle calls clabile, clitter, cplant, csoil, cwoodprod, dclabiledt, dclitterdt, dcplantdt, dcsoildt, dnlitterdt, dnplantdt, dnsoildt, dnsoilmindt, dplitterdt, dpplantdt, dpsoildt, dpsoillabdt, dpsoiloccdt, glai, glaimax, glaimin, iveg, iveg2, kmlabp, lat, lon, nlitter, nplant, nsoil, nsoilmin, nwoodprod, plitter, pplant, casa_poolzero, psoil, psoillab, psoilocc, psorbmax, pwoodprod, sla
casa_poolzero calls clitter, cplant, csoil, nlitter, nplant, nsoil
biogeochem calls casa_cnpcycle
bgcdriver calls biogeochem
casaonly_luc calls biogeochem
spincasacnp calls biogeochem
worker_casaonly_luc calls biogeochem
worker_spincasacnp calls biogeochem
mpidrv_worker calls bgcdriver, worker_casaonly_luc, worker_spincasacnp
cable_offline_driver calls bgcdriver, casaonly_luc, spincasacnp
mpi_driver calls mpidrv_worker