casa_feedback – CABLE
casa_feedback Subroutine
54 statements
Source File
public subroutine casa_feedback(ktau, veg, casabiome, casapool, casamet)
Uses
casadimension
casaparm
cable_common_module
casa_cnp_module
casavariable
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ktau
type(veg_parameter_type), intent(inout) :: veg
type(casa_biome), intent(inout) :: casabiome
type(casa_pool), intent(in) :: casapool
type(casa_met), intent(in) :: casamet
Calls
Contents
Call graph
casa_feedback calls cplant, glai, glaimin, iveg, iveg2, nintercept, nplant, nslope, pplant, vcmax_np, rationcplantmax, rationcplantmin, sla, vcmax