casa_cnpbal – CABLE
casa_cnpbal Subroutine
63 statements
Source File
public subroutine casa_cnpbal(veg, casamet, casapool, casaflux, casabal)
Arguments
Type Intent Optional Attributes Name
type(veg_parameter_type), intent(in) :: veg
type(casa_met), intent(in) :: casamet
type(casa_pool), intent(inout) :: casapool
type(casa_flux), intent(inout) :: casaflux
type(casa_balance), intent(inout) :: casabal
Calls
Called by
Contents
Call graph
casa_cnpbal calls 100, cbalance, cgpp, clabile, clabilelast, cnpp, cplant, cplantlast, crgplant, crmplant, crsoil, dclabiledt, dcplantdt, fraccalloc, iveg2, kplant, lat, lon, nmindep, nminfix, nminleach, nminloss, nminuptake, nsoilmin, nsoilminlast, nupland, pdep, plabuptake, pleach, ploss, psoillab, psoillablast, psoilocc, psoilocclast, psoilsorb, psoilsorblast, pupland, pwea
biogeochem calls casa_cnpbal
bgcdriver calls biogeochem
casaonly_luc calls biogeochem
spincasacnp calls biogeochem
worker_casaonly_luc calls biogeochem
worker_spincasacnp calls biogeochem
mpidrv_worker calls bgcdriver, worker_casaonly_luc, worker_spincasacnp
cable_offline_driver calls bgcdriver, casaonly_luc, spincasacnp
mpi_driver calls mpidrv_worker