casa_poolzero – CABLE
casa_poolzero Subroutine
29 statements
Source File
public subroutine casa_poolzero(n, ipool, casapool)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
integer, intent(in) :: ipool
type(casa_pool), intent(inout) :: casapool
Calls
Called by
Contents
Call graph
casa_poolzero calls clitter, cplant, csoil, nlitter, nplant, nsoil
casa_cnpcycle calls casa_poolzero
biogeochem calls casa_cnpcycle
bgcdriver calls biogeochem
casaonly_luc calls biogeochem
spincasacnp calls biogeochem
worker_casaonly_luc calls biogeochem
worker_spincasacnp calls biogeochem
mpidrv_worker calls bgcdriver, worker_casaonly_luc, worker_spincasacnp
cable_offline_driver calls bgcdriver, casaonly_luc, spincasacnp
mpi_driver calls mpidrv_worker