casa_puptake – CABLE
casa_puptake Subroutine
34 statements
Source File
public subroutine casa_puptake(veg, xkNlimiting, casabiome, casapool, casaflux, casamet)
Arguments
Type Intent Optional Attributes Name
type(veg_parameter_type), intent(inout) :: veg
real(kind=r_2), intent(in), DIMENSION(mp) :: xkNlimiting
type(casa_biome), intent(inout) :: casabiome
type(casa_pool), intent(inout) :: casapool
type(casa_flux), intent(inout) :: casaflux
type(casa_met), intent(inout) :: casamet
Calls
Called by
Contents
Call graph
casa_puptake calls iveg, kuplabp, plabuptake, casa_prequire, psoillab
casa_prequire calls iveg, cplant, fraccalloc, ftranspptol, iveg2, kplant, pplant, ratiopcplantmax, ratiopcplantmin
biogeochem calls casa_puptake
bgcdriver calls biogeochem
casaonly_luc calls biogeochem
spincasacnp calls biogeochem
worker_casaonly_luc calls biogeochem
worker_spincasacnp calls biogeochem
mpidrv_worker calls bgcdriver, worker_casaonly_luc, worker_spincasacnp
cable_offline_driver calls bgcdriver, casaonly_luc, spincasacnp
mpi_driver calls mpidrv_worker