casa_fluxout – CABLE
casa_fluxout Subroutine
57 statements
Source File
public subroutine casa_fluxout(myear, veg, soil, casabal, casamet)
Uses
cable_def_types_mod
casadimension
phenvariable
casavariable
casaparm
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: myear
type(veg_parameter_type), intent(inout) :: veg
type(soil_parameter_type), intent(inout) :: soil
type(casa_balance), intent(inout) :: casabal
type(casa_met), intent(inout) :: casamet
Calls
Called by
Contents
Call graph
casa_fluxout calls 100, 5, areacell, fcgppyear, fcneeyear, fcnppyear, fcrgrowyear, fcrmleafyear, fcrmrootyear, fcrmwoodyear, fcrsyear, float, fndepyear, fnfixyear, fnleachyear, fnlossyear, fnsnetyear, fnupyear, fpdustyear, fpleachyear, fplossyear, fpsnetyear, fpupyear, fpweayear, isoilm, isorder, iveg, lat, lon
mpidrv_master calls casa_fluxout
spincasacnp calls casa_fluxout
cable_offline_driver calls casa_fluxout, spincasacnp
mpi_driver calls mpidrv_master