casa_xnp – CABLE
casa_xnp Subroutine
85 statements
Source File
public subroutine casa_xnp(xnplimit, xNPuptake, veg, casabiome, casapool, casaflux, casamet)
Arguments
Type Intent Optional Attributes Name
real(kind=r_2), intent(out), DIMENSION(mp) :: xnplimit
real(kind=r_2), intent(out), DIMENSION(mp) :: xNPuptake
type(veg_parameter_type), intent(inout) :: veg
type(casa_biome), intent(inout) :: casabiome
type(casa_pool), intent(inout) :: casapool
type(casa_flux), intent(inout) :: casaflux
type(casa_met), intent(inout) :: casamet
Calls
Called by
Contents
Call graph
casa_xnp calls 20, cgpp, cnpp, cplant, fracclabile, iveg, iveg2, nplant, nsoilmin, pplant, casa_nrequire, casa_prequire, psoillab, xnpmax
casa_nrequire calls cplant, iveg, iveg2, nplant, nsoilmin, fraccalloc, ftransnptol, kplant, rationcplantmax, rationcplantmin
casa_prequire calls cplant, iveg, iveg2, pplant, fraccalloc, ftranspptol, kplant, ratiopcplantmax, ratiopcplantmin
biogeochem calls casa_xnp
bgcdriver calls biogeochem
casaonly_luc calls biogeochem
spincasacnp calls biogeochem
worker_casaonly_luc calls biogeochem
worker_spincasacnp calls biogeochem
mpidrv_worker calls bgcdriver, worker_casaonly_luc, worker_spincasacnp
cable_offline_driver calls bgcdriver, casaonly_luc, spincasacnp
mpi_driver calls mpidrv_worker