casa_readbiome – CABLE
casa_readbiome Subroutine
251 statements
Source File
public subroutine casa_readbiome(veg, soil, casabiome, casapool, casaflux, casamet, phen)
Uses
casadimension
casaparm
cable_common_module
casavariable
cable_def_types_mod
phenvariable
vh_js !! vh_js !! vh_js
Arguments
Type Intent Optional Attributes Name
type(veg_parameter_type), intent(inout) :: veg
type(soil_parameter_type), intent(inout) :: soil
type(casa_biome), intent(inout) :: casabiome
type(casa_pool), intent(inout) :: casapool
type(casa_flux), intent(inout) :: casaflux
type(casa_met), intent(inout) :: casamet
type(phen_variable), intent(inout) :: phen
Calls
Called by
Contents
Call graph
casa_readbiome calls clitter, cplant, csoil, fracligninplant, fracnpptop, ftransnptol, ftranspptol, glaimax, glaimin, isorder, iveg, iveg2, ivt2, kminn, kmlabp, kroot, krootlen, kuplabp, kuptake, nlitter, psoillab, psorbmax, rationclitter, rationcplant, rationcplantmax, rationcplantmin, rationcsoil, rationcsoilmax, rationpplantmin, ratiopclitter, ratiopcplant, ratiopcplantmin, ratiopcsoil, rmplant, rootdepth, sla, tkshed, xkleafcoldexp, xkleafdryexp, zse
load_parameters calls casa_readbiome
mpidrv_master calls load_parameters
cable_offline_driver calls load_parameters
mpi_driver calls mpidrv_master