casa_rplant – CABLE
casa_rplant Subroutine
107 statements
Source File
public subroutine casa_rplant(veg, casabiome, casapool, casaflux, casamet, climate)
Uses
casa_cnp_module
Arguments
Type Intent Optional Attributes Name
type(veg_parameter_type), intent(inout) :: veg
type(casa_biome), intent(inout) :: casabiome
type(casa_pool), intent(inout) :: casapool
type(casa_flux), intent(inout) :: casaflux
type(casa_met), intent(inout) :: casamet
type(climate_type), intent(in) :: climate
Calls
Called by
Contents
Call graph
casa_rplant calls cgpp, clabile, clabloss, cnpp, cplant, crgplant, crmplant, frac_sapwood, iveg, kclabrate, nplant, vcmax_np, qtemp_max_last_year, rationcplantmax, ratiopcplantmax, rmplant, sla, tairk, tsoilavg
biogeochem calls casa_rplant
bgcdriver calls biogeochem
casaonly_luc calls biogeochem
spincasacnp calls biogeochem
worker_casaonly_luc calls biogeochem
worker_spincasacnp calls biogeochem
mpidrv_worker calls bgcdriver, worker_casaonly_luc, worker_spincasacnp
cable_offline_driver calls bgcdriver, casaonly_luc, spincasacnp
mpi_driver calls mpidrv_worker