casa_Prequire – CABLE
casa_Prequire Subroutine
46 statements
Source File
public subroutine casa_Prequire(xpCnpp, Preqmin, Preqmax, PtransPtoP, veg, casabiome, casapool, casaflux, casamet)
Arguments
Type Intent Optional Attributes Name
real(kind=r_2), intent(in), DIMENSION(mp) :: xpCnpp
real(kind=r_2), intent(inout), DIMENSION(mp,mplant) :: Preqmin
real(kind=r_2), intent(inout), DIMENSION(mp,mplant) :: Preqmax
real(kind=r_2), intent(inout), DIMENSION(mp,mplant) :: PtransPtoP
type(veg_parameter_type), intent(inout) :: veg
type(casa_biome), intent(inout) :: casabiome
type(casa_pool), intent(inout) :: casapool
type(casa_flux), intent(inout) :: casaflux
type(casa_met), intent(inout) :: casamet
Calls
Called by
Contents
Call graph
casa_prequire calls cplant, fraccalloc, ftranspptol, iveg, iveg2, kplant, pplant, ratiopcplantmax, ratiopcplantmin
casa_puptake calls casa_prequire
casa_xnp calls casa_prequire
biogeochem calls casa_puptake, casa_xnp
bgcdriver calls biogeochem
casaonly_luc calls biogeochem
spincasacnp calls biogeochem
worker_casaonly_luc calls biogeochem
worker_spincasacnp calls biogeochem
mpidrv_worker calls bgcdriver, worker_casaonly_luc, worker_spincasacnp
cable_offline_driver calls bgcdriver, casaonly_luc, spincasacnp
mpi_driver calls mpidrv_worker