casa_cnpflux – CABLE
casa_cnpflux Subroutine
71 statements
Source File
public subroutine casa_cnpflux(casaflux, casapool, casabal, zeroflux)
Uses
cable_def_types_mod
casaparm
casadimension
casavariable
Arguments
Type Intent Optional Attributes Name
type(casa_flux), intent(inout) :: casaflux
type(casa_pool), intent(inout) :: casapool
type(casa_balance), intent(inout) :: casabal
logical :: zeroflux
Calls
Called by
Contents
Call graph
casa_cnpflux calls crgplant, crmplant, fcrmleafyear, fcrmrootyear, fcrmwoodyear
biogeochem calls casa_cnpflux
cable_offline_driver calls casa_cnpflux, bgcdriver, casaonly_luc, spincasacnp
bgcdriver calls biogeochem
casaonly_luc calls biogeochem
spincasacnp calls biogeochem
worker_casaonly_luc calls biogeochem
worker_spincasacnp calls biogeochem
mpidrv_worker calls bgcdriver, worker_casaonly_luc, worker_spincasacnp
mpi_driver calls mpidrv_worker