CASAONLY_LUC – CABLE
CASAONLY_LUC Subroutine
187 statements
Source File
subroutine CASAONLY_LUC(dels, kstart, kend, veg, soil, casabiome, casapool, casaflux, casamet, casabal, phen, POP, climate, LALLOC, LUC_EXPT, POPLUC, sum_casapool, sum_casaflux)
Uses
casaparm
CABLE_LUC_EXPT
casa_offline_inout_module
casavariable
POP_Types
cable_IO_vars_module
casadimension
cable_def_types_mod
TypeDef
POPModule
casa_ncdf_module
POPLUC_Module
biogeochem_mod
cable_common_module
phenvariable
POPLUC_Types
casa_cable
cable_carbon_module
casa_inout_module
CLN CHARACTER(LEN=99), INTENT(IN) :: fcnpspin vh_js !! CLN901 format(A99) $ WHERE (pop%pop_grid(:)%cmass_sum_old.gt.0.1 .and. pop%pop_grid(:)%cmass_sum.gt.0.1) $ casapool%Cplant(Iw,2) = casapool%Cplant(Iw,2)(1.0- min(POP%pop_grid(:)%cat_mortality/(POP%pop_grid(:)%cmass_sum_old),0.99)) $ casapool%Nplant(Iw,2) = casapool%Nplant(Iw,2)(1.0- min(POP%pop_grid(:)%cat_mortality/(POP%pop_grid(:)%cmass_sum_old),0.99)) $ ENDWHERE
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: dels
integer, intent(in) :: kstart
integer, intent(in) :: kend
type(veg_parameter_type), intent(inout) :: veg
type(soil_parameter_type), intent(inout) :: soil
type(casa_biome), intent(inout) :: casabiome
type(casa_pool), intent(inout) :: casapool
type(casa_flux), intent(inout) :: casaflux
type(casa_met), intent(inout) :: casamet
type(casa_balance), intent(inout) :: casabal
type(phen_variable), intent(inout) :: phen
type(POP_TYPE), intent(inout) :: POP
type(climate_type), intent(inout) :: climate
integer, intent(in) :: LALLOC
type(LUC_EXPT_TYPE), intent(inout) :: LUC_EXPT
type(POPLUC_TYPE), intent(inout) :: POPLUC
type(casa_pool), intent(inout) :: sum_casapool
type(casa_flux), intent(inout) :: sum_casaflux
Calls
Called by
Contents
Call graph
casaonly_luc calls cgppspin, cplant, crmplantspin_1, crmplantspin_2, crmplantspin_3, doyphasespin_1, doyphasespin_2, doyphasespin_3, doyphasespin_4, frac_forest, fraccalloc, ilu, input, iveg, iwood, moistspin_1, moistspin_2, moistspin_3, moistspin_4, moistspin_5, moistspin_6, mtempspin, phasespin, prim_only, primf, biogeochem, is_casa_time, pop_init_single, pop_io, pop_luc_casa_transfer, popdriver, popluc_set_patchfrac, popluc_weights_transfer, poplucstep, read_casa_dump, read_luh2, update_sum_casa, write_casa_output_nc, write_luc_output_grid_nc, write_luc_restart_nc, zero_sum_casa, rationcplantmin, ratiopcplantmin, tairkspin, tsoilspin_1, tsoilspin_2, tsoilspin_3, tsoilspin_4, tsoilspin_5, tsoilspin_6
biogeochem calls cplant_turnover, disturbance_interval, klitter, pop_grid, avgsoil, casa_allocation, casa_cnpbal, casa_cnpcycle, casa_cnpflux, casa_coeffplant, casa_coeffsoil, casa_delplant, casa_delsoil, casa_ndummy, casa_nuptake, casa_pdummy, casa_puptake, casa_rplant, casa_rplant1, casa_xkn, casa_xnp, casa_xrateplant, casa_xratesoil, phenology
is_casa_time calls is_leapyear
pop_init_single calls initpop2d_poisson, layer_recruitment_single_patch, zeropop
pop_io calls lat, lon, nf90_close, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_open, nf90_put_att, nf90_put_var, nf90_redef, pop_grid, handle_err
pop_luc_casa_transfer calls cplant, iwood, prim_only, 1166, clabile, clearprod, clearprodloss, clitter, csoil, ctransferluc, fclearance, fcneeyear, fharvest, fracclearprod, fracclearresid, fracharvprod, fracharvresid, fracharvsecresid, grass, harvprod, harvprodloss, nlitter, nplant, nsoil, nsoilmin, plitter, pop_grid, pplant, psoil, smharv, syharv
popdriver calls disturbance_intensity, disturbance_interval, popstep
popluc_set_patchfrac calls prim_only, primf, grass
popluc_weights_transfer calls iwood, prim_only, freq_age_secondary
poplucstep calls primf, freq_age_secondary, gtop, gtos, execute_luc_event, increment_age, ptog, ptos, stog
read_casa_dump calls nf90_close, nf90_open, get_var_ncr2, get_var_ncr3, stderr_nc
read_luh2 calls input, f_id, nf90_get_var, handle_err, transfile, v_id
write_casa_output_nc calls fcrgrowyear, fcrmleafyear, fcrmrootyear, fcrmwoodyear, nf90_close, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_inq_dimid, nf90_inq_varid, nf90_open, nf90_put_att, nf90_put_var, nf90_redef, handle_err
write_luc_output_grid_nc calls cbiomass, clearprod, clearprodloss, clitt, csoil, fclearance, fharvest, fnep, ftransfergross, ftransfernet, harvprod, harvprodloss, nf90_close, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_put_att, nf90_put_var, nf90_redef, handle_err
write_luc_restart_nc calls nf90_close, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_put_att, nf90_put_var, nf90_redef, handle_err
avgsoil calls btran, moist, moistavg, sfc, swilt, tsoilavg
casa_allocation calls cplant, fraccalloc, iveg, 1166, btran, crmplant, fracnpptop, glai, glaimax, glaimin, kplant, moistavg, casa_wolf, sfc, sla, swilt, tsoilavg
casa_cnpbal calls cplant, fraccalloc, clabile, lat, lon, nsoilmin, 100, cbalance, cgpp, clabilelast, cnpp, cplantlast, crgplant, crmplant, crsoil, dclabiledt, dcplantdt, iveg2, kplant, nmindep, nminfix, nminleach, nminloss, nminuptake, nsoilminlast, nupland, pdep, plabuptake, pleach, ploss, psoillab, psoillablast, psoilocc, psoilocclast, psoilsorb, psoilsorblast, pupland, pwea
casa_cnpcycle calls cplant, iveg, clabile, clitter, csoil, lat, lon, nlitter, nplant, nsoil, nsoilmin, plitter, pplant, psoil, cwoodprod, dclabiledt, dclitterdt, dcplantdt, dcsoildt, dnlitterdt, dnplantdt, dnsoildt, dnsoilmindt, dplitterdt, dpplantdt, dpsoildt, dpsoillabdt, dpsoiloccdt, glai, glaimax, glaimin, iveg2, kmlabp, nwoodprod, casa_poolzero, psoillab, psoilocc, psorbmax, pwoodprod, sla
casa_cnpflux calls fcrmleafyear, fcrmrootyear, fcrmwoodyear, crgplant, crmplant
casa_coeffplant calls cplant, iveg, nplant, fracligninplant, fromptol, ftransnptol, glai, glaimin, kplant, plantrate
casa_coeffsoil calls iveg, clay, fracligninplant, fromltoco2, fromltos, fromstoco2, fromstos, isorder, iveg2, ksoil, litterrate, silt, soilrate, xkplab, xkpocc, xkpsorb
casa_delplant calls cplant, fraccalloc, iveg, nplant, pplant, cgpp, clabloss, cnpp, crgplant, crmplant, dcplantdt, dnplantdt, dpplantdt, fluxctolitter, fluxntolitter, fluxptolitter, fracclabile, fracnalloc, fracpalloc, fromptol, ftransnptol, ftranspptol, iveg2, kplant, lnonwood, nminuptake, plabuptake
casa_delsoil calls iveg, clitter, csoil, klitter, nlitter, nsoil, nsoilmin, plitter, psoil, 20, cnpp, costnpup, crsoil, dpsoillabdt, fluxctoco2, fluxctolitter, fluxctosoil, fluxntolitter, fluxntosoil, fluxptolitter, fluxptosoil, fnminleach, fnminloss, fpleach, fromltoco2, fromltos, fromstoco2, fromstos, iveg2, kmlabp, kpocc, kpsorb, ksoil, nlittermin, nmindep, nminfix, nminleach, nminloss, nsimm, nsmin, nsnet, nupland, pdep, pleach, plittermin, prodptase, psimm, psmin, psnet, psoillab, psoilocc, psoilsorb, psorbmax, pupland, pwea, rationcsoilnew, ratiopcsoil, tsoilavg
casa_ndummy calls cplant, clitter, csoil, rationclitter, rationcplant, rationcsoil
casa_nuptake calls iveg, nsoilmin, 100, iveg2, kminn, nminuptake, casa_nrequire
casa_pdummy calls cplant, clitter, csoil, isorder, ratiopclitter, ratiopcplant, ratiopcsoil
casa_puptake calls iveg, kuplabp, plabuptake, casa_prequire, psoillab
casa_rplant calls cplant, iveg, clabile, nplant, cgpp, clabloss, cnpp, crgplant, crmplant, frac_sapwood, kclabrate, vcmax_np, qtemp_max_last_year, rationcplantmax, ratiopcplantmax, rmplant, sla, tairk, tsoilavg
casa_rplant1 calls cplant, iveg, clabile, nplant, cgpp, clabloss, cnpp, crgplant, crmplant, kclabrate, rationpplantmin, rmplant, tairk, tsoilavg
casa_xkn calls iveg, clitter, csoil, klitter, nlitter, nsoil, nsoilmin, fromltos, fromstos, iveg2, ksoil, maxcwd, maxfinelitter, rationcsoilmax, rationcsoilmin, rationcsoilnew
casa_xnp calls cplant, iveg, nplant, nsoilmin, pplant, 20, cgpp, cnpp, fracclabile, iveg2, casa_nrequire, casa_prequire, psoillab, xnpmax
casa_xrateplant calls iveg, btran, iveg2, phase, tairk, tkshed, xkleafcoldexp, xkleafcoldmax, xkleafdryexp, xkleafdrymax
casa_xratesoil calls iveg, iveg2, moistavg, q10soil, ssat, tsoilavg, xkoptlitter, xkoptsoil
execute_luc_event calls frac_forest, primf, freq_age_secondary, ptog, ptos, stog, n_event
get_var_ncr2 calls nf90_get_var, nf90_inq_varid, stderr_nc
get_var_ncr3 calls nf90_get_var, nf90_inq_varid, stderr_nc
handle_err calls nf90_strerror
increment_age calls freq_age_secondary, smharv, syharv
initpop2d_poisson calls pop_grid, cumexponential, exponential
layer_recruitment_single_patch calls pop_grid, get_allometry
phenology calls doyphase, phase
popstep calls pop_grid, getdiagnostics, getpatchfrequencies, getuniqueagefrequencies, patch_disturb, patch_partial_disturb, patch_partial_disturb2, patchannualdynamics
stderr_nc calls nf90_strerror
casa_nrequire calls cplant, fraccalloc, iveg, rationcplantmin, nplant, nsoilmin, ftransnptol, iveg2, kplant, rationcplantmax
casa_poolzero calls cplant, clitter, csoil, nlitter, nplant, nsoil
casa_prequire calls cplant, fraccalloc, iveg, ratiopcplantmin, pplant, ftranspptol, iveg2, kplant, ratiopcplantmax
casa_wolf calls cplant, iveg, cnpp, fracnpptop, iveg2
get_allometry calls allometry, getheight, williams_allometry
getdiagnostics calls pop_grid, get_allometry, interpolate_biomass_1d, interpolate_biomass_2d, smooth_flux
getpatchfrequencies calls pop_grid
getuniqueagefrequencies calls pop_grid, cumexponential, realexponential
patch_disturb calls pop_grid, layer_recruitment_single_patch
patch_partial_disturb calls pop_grid
patch_partial_disturb2 calls pop_grid
patchannualdynamics calls pop_grid, get_allometry, layer_recruitment
interpolate_biomass_1d calls pop_grid, realexponential
interpolate_biomass_2d calls pop_grid, realexponential, area_triangle
layer_recruitment calls pop_grid, get_allometry
smooth_flux calls pop_grid, regress
cable_offline_driver calls casaonly_luc