casa_nuptake – CABLE
casa_nuptake Subroutine
37 statements
Source File
public subroutine casa_nuptake(veg, xkNlimiting, casabiome, casapool, casaflux, casamet)
Arguments
Type Intent Optional Attributes Name
type(veg_parameter_type), intent(inout) :: veg
real(kind=r_2), intent(in), DIMENSION(mp) :: xkNlimiting
type(casa_biome), intent(inout) :: casabiome
type(casa_pool), intent(inout) :: casapool
type(casa_flux), intent(inout) :: casaflux
type(casa_met), intent(inout) :: casamet
Calls
Called by
Contents
Call graph
casa_nuptake calls 100, iveg, iveg2, kminn, nminuptake, nsoilmin, casa_nrequire
casa_nrequire calls iveg, iveg2, nsoilmin, cplant, fraccalloc, ftransnptol, kplant, nplant, rationcplantmax, rationcplantmin
biogeochem calls casa_nuptake
bgcdriver calls biogeochem
casaonly_luc calls biogeochem
spincasacnp calls biogeochem
worker_casaonly_luc calls biogeochem
worker_spincasacnp calls biogeochem
mpidrv_worker calls bgcdriver, worker_casaonly_luc, worker_spincasacnp
cable_offline_driver calls bgcdriver, casaonly_luc, spincasacnp
mpi_driver calls mpidrv_worker