casa_allocation – CABLE
casa_allocation Subroutine
162 statements
Source File
public subroutine casa_allocation(veg, soil, casabiome, casaflux, casapool, casamet, phen, LALLOC)
Computes the fraction of net photosynthate allocated to leaf, wood and froot using an allocation scheme modified from Pierre Friedlingstein.
Implementation by Qian Zhang and Ying Ping Wang in 2005
Arguments
Type Intent Optional Attributes Name
type(veg_parameter_type), intent(inout) :: veg
type(soil_parameter_type), intent(inout) :: soil
type(casa_biome), intent(inout) :: casabiome
type(casa_flux), intent(inout) :: casaflux
type(casa_pool), intent(inout) :: casapool
type(casa_met), intent(inout) :: casamet
type(phen_variable), intent(inout) :: phen
integer, intent(in) :: LALLOC
Calls
Called by
Contents
Call graph
casa_allocation calls 1166, btran, cplant, crmplant, fraccalloc, fracnpptop, glai, glaimax, glaimin, iveg, kplant, moistavg, casa_wolf, sfc, sla, swilt, tsoilavg
casa_wolf calls cplant, fracnpptop, iveg, cnpp, iveg2
biogeochem calls casa_allocation
bgcdriver calls biogeochem
casaonly_luc calls biogeochem
spincasacnp calls biogeochem
worker_casaonly_luc calls biogeochem
worker_spincasacnp calls biogeochem
mpidrv_worker calls bgcdriver, worker_casaonly_luc, worker_spincasacnp
cable_offline_driver calls bgcdriver, casaonly_luc, spincasacnp
mpi_driver calls mpidrv_worker