cbm – CABLE
cbm Subroutine
76 statements
Source File
public subroutine cbm(ktau, dels, air, bgc, canopy, met, bal, rad, rough, soil, ssnow, sum_flux, veg, climate, xk, c1, rhoch)
Uses
cable_def_types_mod
cable_air_module
cable_canopy_module
cbl_albedo_mod
sli_main_mod
cable_math_constants_mod
cbl_masks_mod
casadimension
snow_aging_mod
cable_other_constants_mod
cable_roughness_module
cable_gw_hydro_module
cable_common_module
cable_carbon_module
cbl_init_radiation_module
cable_phys_constants_mod
cbl_soil_snow_main_module
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ktau
real, intent(in) :: dels
type(air_type), intent(inout) :: air
type(bgc_pool_type), intent(inout) :: bgc
type(canopy_type), intent(inout) :: canopy
type(met_type), intent(inout) :: met
type(balances_type), intent(inout) :: bal
type(radiation_type), intent(inout) :: rad
type(roughness_type), intent(inout) :: rough
type(soil_parameter_type), intent(inout) :: soil
type(soil_snow_type), intent(inout) :: ssnow
type(sum_flux_type), intent(inout) :: sum_flux
type(veg_parameter_type), intent(inout) :: veg
type(climate_type), intent(in) :: climate
real :: xk(mp,nrb)
real :: c1(mp,nrb)
real :: rhoch(mp,nrb)
Calls
Called by
Contents
Call graph
cbm calls fsd, albedo, carbon_pl, define_air, define_canopy, fsunlit_mask, fsunlit_veg_mask, fveg_mask, init_radiation, plantcarb, ruff_resist, snow_aging, soil_snow, soilcarb, tgg, tggsn
albedo calls canopyreflectance, canopytransmitance, effectivesurfacereflectance, fbeamradalbedo, surface_albedosn
carbon_pl calls cplant, csoil
define_canopy calls define_air, ruff_resist, tgg, tggsn, cmolar, coexp, disp, dleaf, evapfbl, extkb, fes, fev, fevw_pot, fvlai, gswx, hruff, lwabv, potev, comp_friction_vel, dryleaf, humidity_deficit_method, latent_heat_flux, penman_monteith, psim, psis, qsatfjh, radiation, surf_wetness_fact, update_zetar, wetleaf, within_canopy, qv, rghlai, rt0us, rt1, rt1usa, rt1usb, rt_qh_sublayer, rtevap_sat, rtevap_unsat, rtsoil, satfrac, shelrb, tk, transd, tss, tvrad, us, usuh, visc, vlaiw, wb, wbice, wetfac, wetfac_cs, z0soilsn, zetar, zetash, zref_tq, zruffs, zse
init_radiation calls beamfraction, common_initrad_scalings, effectiveextinctcoeffs, extinctioncoeff
plantcarb calls cplant, ratecp, tk
ruff_resist calls coexp, disp, hruff, hgtabovesnow, lai_eff, rghlai, rt1usb, term2, term3, term5, usuh, vlaiw, z0m, z0soilsn, za_tq, za_uv, zref_tq, zref_uv, zruffs
soil_snow calls tgg, tggsn, css, dtmlt, gammzz, hydraulic_redistribution, remove_trans, snow_accum, snow_melting, snowcheck, snowdensity, snowl_adjust, soilfreeze, stempv, surfbv, rhosoil, wb, wbice, zse
soilcarb calls tgg, froot, wb
beamfraction calls spitter
canopyreflectance calls canopyreflectance_beam, canopyreflectance_dif
canopytransmitance calls canopytransmitance_beam, canopytransmitance_dif
common_initrad_scalings calls calc_rhoch, common_initrad_coeffs
comp_friction_vel calls psim
dryleaf calls cmolar, dleaf, evapfbl, froot, fvlai, gswx, tk, vlaiw, wb, zse, a1gs, alpha, ca, cansto, cfrd, conkc0, conko0, convex, d0gs, dsatdk, dva, ejmax, ekc, eko, fevc, frac4, fwet, g0, gradis, iveg, ej3x, ej4x, fwsoil_calc_lai_ktaul, fwsoil_calc_non_linear, fwsoil_calc_std, getrex_1d, photosynthesis, xejmxt3, xrdt, xvcmxt3, xvcmxt4, psyc, qcan, qtemp_max_last_year, rex, rlam, rniso, scalex, ssat_vec, swilt, swilt_vec, tvair, vcmax, wbliq, zr
effectiveextinctcoeffs calls effectiveextinctcoeff
effectivesurfacereflectance calls effectivereflectance
extinctioncoeff calls extinctioncoeff_beam, extinctioncoeff_dif
hydraulic_redistribution calls froot, wb, wbice, zse, sfc, ssat, swilt
penman_monteith calls qsatfjh
psim calls alog
psis calls alog
radiation calls fsd, fvlai, albsoilsn, cexpkbm, cexpkdm, extkbm, extkdm, fbeam, gradis, qcan, reffbm, reffdf, refl, scalex, taul
remove_trans calls evapfbl, froot, wb, zse
snow_accum calls tgg, tggsn, gammzz, cls, evapsn, fes_cor, fess, isflag, isoilm, osnowd, precip_sn, precis, sdepth, smass, snowd, ssdn
snow_melting calls tgg, tggsn, dtmlt, gammzz, isflag, sdepth, smass, snowd, ssdn
snowcheck calls tgg, tggsn, isflag, smass, snowd, ssdn, ssdnn, t_snwlr
snowdensity calls tgg, tggsn, sconds, smass, ssdn
snowl_adjust calls tggsn, isflag, sdepth, smass, snowd, ssdn
soilfreeze calls tgg, gammzz, wb, wbice, zse
stempv calls tgg, tggsn, gammzz, zse, old_soil_conductivity, total_soil_conductivity, trimb, sconds, sdepth, ssdn, wbfice, wblf
surf_wetness_fact calls tk, wb, wbice, wetfac, iveg, snowd
surfbv calls tgg, gammzz, wb, zse, smoisturev, sdepth, sfc, smass, ssdn
wetleaf calls tk, vlaiw, cansto, dsatdk, dva, fevw, fwet, psyc, rlam, tvair
within_canopy calls fes, fev, hruff, qv, rt1, rtevap_sat, rtevap_unsat, satfrac, tk, tss, vlaiw, wetfac, z0soilsn, cls, epsi, fhs, fhv, meth, pmb, qsatfjh2, qstss, qvair, rho, rlam, tvair
fwsoil_calc_lai_ktaul calls froot, wb, ssat, swilt
fwsoil_calc_non_linear calls sfc
old_soil_conductivity calls isoilm, ssat, wbfice, wblf, cnsd
smoisturev calls wb, wbice, zse, trimb, sfc, ssat, wbfice, wblf, zshh
total_soil_conductivity calls tgg, wb, wbice, isflag, isoilm, snowd, ssat_vec, wbliq, cnsd_vec, sand_vec, watr
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker