close_output_file – CABLE
close_output_file Subroutine
28 statements
Source File
public subroutine close_output_file(bal, air, bgc, canopy, met, rad, rough, soil, ssnow, sum_flux, veg)
Arguments
Type Intent Optional Attributes Name
type(balances_type), intent(inout) :: bal
type(air_type), intent(inout) :: air
type(bgc_pool_type), intent(inout) :: bgc
type(canopy_type), intent(inout) :: canopy
type(met_type), intent(inout) :: met
type(radiation_type), intent(inout) :: rad
type(roughness_type), intent(inout) :: rough
type(soil_parameter_type), intent(inout) :: soil
type(soil_snow_type), intent(inout) :: ssnow
type(sum_flux_type), intent(inout) :: sum_flux
type(veg_parameter_type), intent(inout) :: veg
Calls
Called by
Contents
Call graph
close_output_file calls ebal_tot, nf90_close, nc_abort, wbal_tot
nc_abort calls nf90_strerror
mpidrv_master calls close_output_file
cable_offline_driver calls close_output_file
mpi_driver calls mpidrv_master