create_restart – CABLE
create_restart Subroutine
205 statements
Source File
public subroutine create_restart(logn, dels, ktau, soil, veg, ssnow, canopy, rough, rad, bgc, bal, met)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: logn
real, intent(in) :: dels
integer, intent(in) :: ktau
type(soil_parameter_type), intent(in) :: soil
type(veg_parameter_type), intent(in) :: veg
type(soil_snow_type), intent(in) :: ssnow
type(canopy_type), intent(in) :: canopy
type(roughness_type), intent(in) :: rough
type(radiation_type), intent(in) :: rad
type(bgc_pool_type), intent(in) :: bgc
type(balances_type), intent(in) :: bal
type(met_type), intent(in) :: met
Calls
Called by
Contents
Call graph
create_restart calls define_ovar, write_ovar, nf90_close, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_put_att, nf90_put_var, nf90_redef, nc_abort
define_ovar calls define_output_parameter_r1, define_output_parameter_r2, define_output_variable_r1, define_output_variable_r2
write_ovar calls write_output_parameter_r1, write_output_parameter_r1d, write_output_parameter_r2, write_output_parameter_r2d, write_output_variable_r1, write_output_variable_r2
nc_abort calls nf90_strerror
define_output_parameter_r1 calls nf90_def_var, nf90_put_att, nc_abort, grid
define_output_parameter_r2 calls nf90_def_var, nf90_put_att, nc_abort, grid
define_output_variable_r1 calls nf90_def_var, nf90_put_att, nc_abort, grid
define_output_variable_r2 calls nf90_def_var, nf90_put_att, nc_abort, grid
write_output_parameter_r1 calls nf90_put_var, nc_abort, grid
write_output_parameter_r1d calls nf90_put_var, nc_abort
write_output_parameter_r2 calls nf90_put_var, nc_abort, grid
write_output_parameter_r2d calls nf90_put_var, nc_abort
write_output_variable_r1 calls nf90_put_var, nc_abort, grid, range_abort
write_output_variable_r2 calls nf90_put_var, nc_abort, grid, range_abort
range_abort calls doy, hod, year
mpidrv_master calls create_restart
cable_offline_driver calls create_restart
mpi_driver calls mpidrv_master