create_patch – CABLE
create_patch Subroutine
175 statements
Source File
public subroutine create_patch(patch_t, comm)
Uses
mpi
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: patch_t
integer, intent(in) :: comm
Calls
Called by
Contents
Call graph
create_patch calls mpi_abort, mpi_get_address, mpi_type_commit, mpi_type_create_resized, mpi_type_create_struct, create_layer
create_layer calls mpi_abort, mpi_get_address, mpi_type_commit, mpi_type_create_resized, mpi_type_create_struct, create_cohort
create_cohort calls mpi_abort, mpi_get_address, mpi_type_commit, mpi_type_create_resized, mpi_type_create_struct
create_pop_gridcell_type calls create_patch
master_pop_types calls create_pop_gridcell_type
worker_pop_types calls create_pop_gridcell_type
mpidrv_master calls master_pop_types
mpidrv_worker calls worker_pop_types
mpi_driver calls mpidrv_master, mpidrv_worker