create_cohort – CABLE
create_cohort Subroutine
139 statements
Source File
public subroutine create_cohort(cohort_t, comm)
Uses
mpi
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: cohort_t
integer, intent(in) :: comm
Calls
Called by
Contents
Call graph
create_cohort calls mpi_abort, mpi_get_address, mpi_type_commit, mpi_type_create_resized, mpi_type_create_struct
create_layer calls create_cohort
create_patch calls create_layer
create_pop_gridcell_type calls create_patch
master_pop_types calls create_pop_gridcell_type
worker_pop_types calls create_pop_gridcell_type
mpidrv_master calls master_pop_types
mpidrv_worker calls worker_pop_types
mpi_driver calls mpidrv_master, mpidrv_worker