create_landuse_cable_restart – CABLE
create_landuse_cable_restart Subroutine
204 statements
Source File
subroutine create_landuse_cable_restart(logn, dels, ktau, soil, mpx, lucmp, cstart, cend, nap)
Uses
cable_abort_module
cable_write_module
cable_IO_vars_module
cable_checks_module
cable_def_types_mod
netcdf
landuse_variable
cable_common_module
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: logn
real, intent(in) :: dels
integer, intent(in) :: ktau
type(soil_parameter_type) :: soil
integer, intent(in) :: mpx
type(landuse_mp) :: lucmp
integer, intent(in), DIMENSION(mland) :: cstart
integer, intent(in), DIMENSION(mland) :: cend
integer, intent(in), DIMENSION(mland) :: nap
Calls
Called by
Contents
Call graph
create_landuse_cable_restart calls define_ovar, write_ovar, nf90_close, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_put_att, nf90_put_var, nf90_redef, nc_abort
define_ovar calls define_output_parameter_r1, define_output_parameter_r2, define_output_variable_r1, define_output_variable_r2
write_ovar calls write_output_parameter_r1, write_output_parameter_r1d, write_output_parameter_r2, write_output_parameter_r2d, write_output_variable_r1, write_output_variable_r2
nc_abort calls nf90_strerror
define_output_parameter_r1 calls nf90_def_var, nf90_put_att, nc_abort, grid
define_output_parameter_r2 calls nf90_def_var, nf90_put_att, nc_abort, grid
define_output_variable_r1 calls nf90_def_var, nf90_put_att, nc_abort, grid
define_output_variable_r2 calls nf90_def_var, nf90_put_att, nc_abort, grid
write_output_parameter_r1 calls nf90_put_var, nc_abort, grid
write_output_parameter_r1d calls nf90_put_var, nc_abort
write_output_parameter_r2 calls nf90_put_var, nc_abort, grid
write_output_parameter_r2d calls nf90_put_var, nc_abort
write_output_variable_r1 calls nf90_put_var, nc_abort, grid, range_abort
write_output_variable_r2 calls nf90_put_var, nc_abort, grid, range_abort
range_abort calls doy, hod, year
mpidrv_master calls create_landuse_cable_restart
cable_offline_driver calls create_landuse_cable_restart
mpi_driver calls mpidrv_master