CRU_GET_SUBDIURNAL_MET – CABLE
CRU_GET_SUBDIURNAL_MET Subroutine
92 statements
Source File
public subroutine CRU_GET_SUBDIURNAL_MET(CRU, MET, CurYear, ktau, kend, LastYearOfMet)
Uses
cable_checks_module
casa_ncdf_module
cable_def_types_mod
cable_IO_vars_module
CABLE_WEATHERGENERATOR
Arguments
Type Intent Optional Attributes Name
type(CRU_TYPE) :: CRU
type(met_type) :: MET
integer, intent(in) :: CurYear
integer, intent(in) :: ktau
integer, intent(in) :: kend
logical, intent(in) :: LastYearOfMet
Calls
Called by
Contents
Call graph
cru_get_subdiurnal_met calls avg_lwdn, coszen, doy, f_id, hod, metfile, ndepvals, nf90_close, phild, phisd, precip, cru_get_daily_met, doysod2ymdhms, get_cru_co2, get_cru_ndep, handle_err, open_cru_met, wgen_daily_constants, wgen_init, wgen_subdiurnal_met, temp, wind
cru_get_daily_met calls f_id, metfile, nf90_close, handle_err, met, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_open, cru_get_filename, v_id, var_name
doysod2ymdhms calls is_leapyear
get_cru_co2 calls co2vals, get_unit
get_cru_ndep calls handle_err, nf90_get_var, nf90_inq_varid, nf90_open
handle_err calls nf90_strerror
open_cru_met calls f_id, metfile, handle_err, nf90_inq_varid, nf90_open, cru_get_filename, v_id, var_name
wgen_init calls coszen, phild, phisd, precip, temp, wind, daylength, latdeg, latrad, pmb, pmbday, precipday, snow, snowday, solarmjday, solarnorm, tempmaxday, tempmaxdayprev, tempminday, tempmindaynext, tempnightrate, tempnightrateprev, temprangeaft, temprangeday, tempsunset, tempsunsetprev, timemaxtemp, timesunrise, timesunset, timesunsetprev, vappmb, winddark, windday, windlite
mpidrv_master calls cru_get_subdiurnal_met
cable_offline_driver calls cru_get_subdiurnal_met
mpi_driver calls mpidrv_master