CRU_INIT – CABLE
CRU_INIT Subroutine
231 statements
Source File
public subroutine CRU_INIT(CRU)
Uses
cable_IO_vars_module
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
type(CRU_TYPE) :: CRU
Calls
Called by
Contents
Call graph
cru_init calls avg_lwdn, met, ndepvals, nf90_close, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_open, get_unit, handle_err
handle_err calls nf90_strerror
mpidrv_master calls cru_init
cable_offline_driver calls cru_init
mpi_driver calls mpidrv_master