CRU_GET_DAILY_MET – CABLE
CRU_GET_DAILY_MET Subroutine
258 statements
Source File
public subroutine CRU_GET_DAILY_MET(CRU, LastDayOfYear, LastYearOfMet)
Arguments
Type Intent Optional Attributes Name
type(CRU_TYPE) :: CRU
logical, intent(in) :: LastDayOfYear
logical, intent(in) :: LastYearOfMet
Calls
Called by
Contents
Call graph
cru_get_daily_met calls f_id, met, metfile, nf90_close, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_open, cru_get_filename, handle_err, v_id, var_name
handle_err calls nf90_strerror
cru_get_subdiurnal_met calls cru_get_daily_met
mpidrv_master calls cru_get_subdiurnal_met
cable_offline_driver calls cru_get_subdiurnal_met
mpi_driver calls mpidrv_master