decomp_types – CABLE
decomp_types Subroutine
43 statements
Source File
public subroutine decomp_types(landpt_t, patch_t)
Uses
mpi
cable_IO_vars_module
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: landpt_t
integer, intent(out) :: patch_t
Calls
Called by
Contents
Call graph
decomp_types calls mpi_get_address, mpi_type_commit, mpi_type_create_resized, mpi_type_create_struct
master_cable_params calls decomp_types
worker_cable_params calls decomp_types
mpidrv_master calls master_cable_params
mpidrv_worker calls worker_cable_params
mpi_driver calls mpidrv_master, mpidrv_worker