define_canopy – CABLE
define_canopy Subroutine
423 statements
Source File
public subroutine define_canopy(bal, rad, rough, air, met, dels, ssnow, soil, veg, canopy, climate, sunlit_veg_mask, reducedLAIdue2snow)
Uses
cbl_qsat_module
cbl_dryLeaf_module
cable_photo_constants_mod
cable_math_constants_mod
cable_wetleaf_module
cable_within_canopy_module
cable_phys_constants_mod
cable_roughness_module
cable_other_constants_mod
cbl_SurfaceWetness_module
cbl_zetar_module
cable_def_types_mod
cable_air_module
cable_latent_heat_module
cbl_radiation_module
cbl_friction_vel_module
cable_common_module
cbl_pot_evap_snow_module
Arguments
Type Intent Optional Attributes Name
type(balances_type), intent(inout) :: bal
type(radiation_type), intent(inout) :: rad
type(roughness_type), intent(inout) :: rough
type(air_type), intent(inout) :: air
type(met_type), intent(inout) :: met
real, intent(in) :: dels
type(soil_snow_type), intent(inout) :: ssnow
type(soil_parameter_type), intent(inout) :: soil
type(veg_parameter_type), intent(inout) :: veg
type(canopy_type), intent(inout) :: canopy
type(climate_type), intent(in) :: climate
logical :: sunlit_veg_mask(mp)
real :: reducedLAIdue2snow(mp)
Calls
Called by
Contents
Call graph
define_canopy calls cmolar, coexp, disp, dleaf, evapfbl, extkb, fes, fev, fevw_pot, fvlai, gswx, hruff, lwabv, potev, comp_friction_vel, define_air, dryleaf, humidity_deficit_method, latent_heat_flux, penman_monteith, psim, psis, qsatfjh, radiation, ruff_resist, surf_wetness_fact, update_zetar, wetleaf, within_canopy, qv, rghlai, rt0us, rt1, rt1usa, rt1usb, rt_qh_sublayer, rtevap_sat, rtevap_unsat, rtsoil, satfrac, shelrb, tgg, tggsn, tk, transd, tss, tvrad, us, usuh, visc, vlaiw, wb, wbice, wetfac, wetfac_cs, z0soilsn, zetar, zetash, zref_tq, zruffs, zse
comp_friction_vel calls psim
dryleaf calls cmolar, dleaf, evapfbl, fvlai, gswx, tk, vlaiw, wb, zse, a1gs, alpha, ca, cansto, cfrd, conkc0, conko0, convex, d0gs, dsatdk, dva, ejmax, ekc, eko, fevc, frac4, froot, fwet, g0, gradis, iveg, ej3x, ej4x, fwsoil_calc_lai_ktaul, fwsoil_calc_non_linear, fwsoil_calc_std, getrex_1d, photosynthesis, xejmxt3, xrdt, xvcmxt3, xvcmxt4, psyc, qcan, qtemp_max_last_year, rex, rlam, rniso, scalex, ssat_vec, swilt, swilt_vec, tvair, vcmax, wbliq, zr
penman_monteith calls qsatfjh
psim calls alog
psis calls alog
radiation calls fvlai, albsoilsn, cexpkbm, cexpkdm, extkbm, extkdm, fbeam, fsd, gradis, qcan, reffbm, reffdf, refl, scalex, taul
ruff_resist calls coexp, disp, hruff, rghlai, rt1usb, usuh, vlaiw, z0soilsn, zref_tq, zruffs, hgtabovesnow, lai_eff, term2, term3, term5, z0m, za_tq, za_uv, zref_uv
surf_wetness_fact calls tk, wb, wbice, wetfac, iveg, snowd
wetleaf calls tk, vlaiw, cansto, dsatdk, dva, fevw, fwet, psyc, rlam, tvair
within_canopy calls fes, fev, hruff, qv, rt1, rtevap_sat, rtevap_unsat, satfrac, tk, tss, vlaiw, wetfac, z0soilsn, cls, epsi, fhs, fhv, meth, pmb, qsatfjh2, qstss, qvair, rho, rlam, tvair
fwsoil_calc_lai_ktaul calls wb, froot, swilt, ssat
fwsoil_calc_non_linear calls sfc
cbm calls define_canopy
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker