define_output_parameter_r1 – CABLE
define_output_parameter_r1 Subroutine
78 statements
Source File
private subroutine define_output_parameter_r1(ncid, parID, pname, punits, longname, writepatch, dimswitch, xID, yID, zID, landID, patchID, restart)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncid
integer, intent(out) :: parID
character(len=*), intent(in) :: pname
character(len=*), intent(in) :: punits
character(len=*), intent(in) :: longname
logical, intent(in) :: writepatch
character(len=*), intent(in) :: dimswitch
integer, intent(in) :: xID
integer, intent(in) :: yID
integer, intent(in) :: zID
integer, intent(in) :: landID
integer, intent(in) :: patchID
logical, intent(in), optional :: restart
Calls
Called by
Contents
Call graph
define_output_parameter_r1 calls grid, nf90_def_var, nf90_put_att, nc_abort
nc_abort calls nf90_strerror
define_ovar calls define_output_parameter_r1
create_landuse_cable_restart calls define_ovar
create_restart calls define_ovar
open_output_file calls define_ovar
mpidrv_master calls create_landuse_cable_restart, create_restart, open_output_file
cable_offline_driver calls create_landuse_cable_restart, create_restart, open_output_file
mpi_driver calls mpidrv_master