derived_parameters – CABLE
derived_parameters Subroutine
126 statements
Source File
public subroutine derived_parameters(soil, sum_flux, bal, ssnow, veg, rough)
Arguments
Type Intent Optional Attributes Name
type(soil_parameter_type), intent(inout) :: soil
type(sum_flux_type), intent(inout) :: sum_flux
type(balances_type), intent(inout) :: bal
type(soil_snow_type), intent(inout) :: ssnow
type(veg_parameter_type), intent(in) :: veg
type(roughness_type), intent(inout) :: rough
Calls
Called by
Contents
Call graph
derived_parameters calls bch_vec, clay_vec, hyds_vec, iveg, org_vec, sand_vec, sfc, sfc_vec, slope, slope_std, ssat_vec, sucs_vec, swilt, swilt_vec, watr, wb, wbice, zse
load_parameters calls derived_parameters
mpidrv_master calls load_parameters
cable_offline_driver calls load_parameters
mpi_driver calls mpidrv_master