DOYSOD2YMDHMS – CABLE
DOYSOD2YMDHMS Subroutine
28 statements
Source File
public subroutine DOYSOD2YMDHMS(YYYY, DOY, SOD, MM, DD, HOUR, MINUTE, SECOND)
Uses
cable_common_module
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: YYYY
integer, intent(in) :: DOY
integer, intent(in) :: SOD
integer, intent(out) :: MM
integer, intent(out) :: DD
integer, intent(out), optional :: HOUR
integer, intent(out), optional :: MINUTE
integer, intent(out), optional :: SECOND
Calls
Called by
Contents
Call graph
doysod2ymdhms calls is_leapyear
cru_get_subdiurnal_met calls doysod2ymdhms
open_met_file calls doysod2ymdhms
plume_mip_get_met calls doysod2ymdhms
mpidrv_master calls cru_get_subdiurnal_met, open_met_file, plume_mip_get_met
cable_offline_driver calls cru_get_subdiurnal_met, open_met_file, plume_mip_get_met
mpi_driver calls mpidrv_master