dryLeaf – CABLE
dryLeaf Subroutine
282 statements
Source File
public subroutine dryLeaf(dels, rad, rough, air, met, veg, canopy, soil, ssnow, dsx, fwsoil, tlfx, tlfy, ecy, hcy, rny, gbhu, gbhf, csx, cansat, ghwet, iter, climate)
Uses
cbl_fwsoil_module
cable_photo_constants_mod
cable_common_module
cable_def_types_mod
cable_phys_constants_mod
cable_other_constants_mod
cbl_photosynthesis_module
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: dels
type(radiation_type), intent(inout) :: rad
type(roughness_type), intent(inout) :: rough
type(air_type), intent(inout) :: air
type(met_type), intent(inout) :: met
type(veg_parameter_type), intent(inout) :: veg
type(canopy_type), intent(inout) :: canopy
type(soil_parameter_type), intent(inout) :: soil
type(soil_snow_type), intent(inout) :: ssnow
real, intent(inout), DIMENSION(:) :: dsx
real, intent(inout), DIMENSION(:) :: fwsoil
real, intent(inout), DIMENSION(:) :: tlfx
real, intent(inout), DIMENSION(:) :: tlfy
real(kind=R_2), intent(inout), DIMENSION(:) :: ecy
real(kind=R_2), intent(inout), DIMENSION(:) :: hcy
real(kind=R_2), intent(inout), DIMENSION(:) :: rny
real(kind=R_2), intent(inout), DIMENSION(:,:) :: gbhu
real(kind=R_2), intent(inout), DIMENSION(:,:) :: gbhf
real(kind=R_2), intent(inout), DIMENSION(:,:) :: csx
real, intent(in), DIMENSION(:) :: cansat
real(kind=r_2), intent(out), DIMENSION(:) :: ghwet
integer, intent(in) :: iter
type(climate_type), intent(in) :: climate
Calls
Called by
Contents
Call graph
dryleaf calls a1gs, alpha, ca, cansto, cfrd, cmolar, conkc0, conko0, convex, d0gs, dleaf, dsatdk, dva, ejmax, ekc, eko, evapfbl, fevc, frac4, froot, fvlai, fwet, g0, gradis, gswx, iveg, ej3x, ej4x, fwsoil_calc_lai_ktaul, fwsoil_calc_non_linear, fwsoil_calc_std, getrex_1d, photosynthesis, xejmxt3, xrdt, xvcmxt3, xvcmxt4, psyc, qcan, qtemp_max_last_year, rex, rlam, rniso, scalex, ssat_vec, swilt, swilt_vec, tk, tvair, vcmax, vlaiw, wb, wbliq, zr, zse
fwsoil_calc_lai_ktaul calls froot, swilt, wb, ssat
fwsoil_calc_non_linear calls sfc
define_canopy calls dryleaf
cbm calls define_canopy
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker