energy_balance – CABLE
energy_balance Subroutine
19 statements
Source File
public subroutine energy_balance(dels, ktau, met, rad, canopy, bal, ssnow, SBOLTZ, EMLEAF, EMSOIL)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: dels
integer, intent(in) :: ktau
type(met_type), intent(in) :: met
type(radiation_type), intent(in) :: rad
type(canopy_type), intent(in) :: canopy
type(balances_type), intent(inout) :: bal
type(soil_snow_type), intent(in) :: ssnow
real, intent(in) :: SBOLTZ
real, intent(in) :: EMLEAF
real, intent(in) :: EMSOIL
Calls
Called by
Contents
Call graph
energy_balance calls albedo, fsd, qcan
write_output calls energy_balance
mpidrv_master calls write_output
cable_offline_driver calls write_output
mpi_driver calls mpidrv_master