execute_luc_event – CABLE
execute_luc_event Subroutine
64 statements
Source File
public subroutine execute_luc_event(from_state, to_state, frac_change_grid, g, POPLUC)
Arguments
Type Intent Optional Attributes Name
character(len=5), intent(in) :: from_state
character(len=5), intent(in) :: to_state
real(kind=dp), intent(inout) :: frac_change_grid
integer(kind=i4b), intent(in) :: g
type(POPLUC_TYPE), intent(inout) :: POPLUC
Calls
Called by
Contents
Call graph
execute_luc_event calls frac_forest, freq_age_secondary, n_event, primf, ptog, ptos, stog
poplucstep calls execute_luc_event
casaonly_luc calls poplucstep
lucdriver calls poplucstep
master_casaonly_luc calls poplucstep
mpidrv_master calls lucdriver, master_casaonly_luc
cable_offline_driver calls casaonly_luc, lucdriver
mpi_driver calls mpidrv_master