extraRestart – CABLE
extraRestart Subroutine
105 statements
Source File
private subroutine extraRestart(INpatch, ssnow, canopy, rough, bgc, bal, veg, soil, rad, EMSOIL)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: INpatch
type(soil_snow_type), intent(inout) :: ssnow
type(canopy_type), intent(inout) :: canopy
type(roughness_type), intent(inout) :: rough
type(bgc_pool_type), intent(inout) :: bgc
type(balances_type), intent(inout) :: bal
type(veg_parameter_type), intent(inout) :: veg
type(soil_parameter_type), intent(inout) :: soil
type(radiation_type), intent(inout) :: rad
real, intent(in) :: EMSOIL
Calls
Called by
Contents
Call graph
extrarestart calls readpar, nf90_get_var, nf90_inq_varid, nc_abort, redistr_i, redistr_r, redistr_r2, redistr_r2d, redistr_rd
readpar calls readpar_i, readpar_r, readpar_r2, readpar_r2d, readpar_rd
nc_abort calls nf90_strerror
redistr_r calls float
redistr_r2 calls float
redistr_r2d calls float
redistr_rd calls float
readpar_i calls nf90_get_var, nf90_inq_varid, nc_abort, nf90_inquire_variable
readpar_r calls nf90_get_var, nf90_inq_varid, nc_abort, nf90_inquire_variable
readpar_r2 calls nf90_get_var, nf90_inq_varid, nc_abort, nf90_inquire_variable
readpar_r2d calls nf90_get_var, nf90_inq_varid, nc_abort, nf90_inquire_variable
readpar_rd calls nf90_get_var, nf90_inq_varid, nc_abort, nf90_inquire_variable
get_restart_data calls extrarestart
load_parameters calls get_restart_data
mpidrv_master calls load_parameters
cable_offline_driver calls load_parameters
mpi_driver calls mpidrv_master