find_extents – CABLE
find_extents Subroutine
23 statements
Source File
public subroutine find_extents()
Uses
cable_def_types_mod
mpi
Arguments
None
Calls
Called by
Contents
None
Call graph
find_extents calls mpi_get_address
mpidrv_master calls find_extents
mpidrv_worker calls find_extents, worker_outtype
worker_outtype calls find_extents
mpi_driver calls mpidrv_master, mpidrv_worker