fwsoil_calc_Lai_Ktaul – CABLE
fwsoil_calc_Lai_Ktaul Subroutine
19 statements
Source File
public subroutine fwsoil_calc_Lai_Ktaul(fwsoil, soil, ssnow, veg)
Uses
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
real, intent(out), DIMENSION(:) :: fwsoil
type(soil_parameter_type), intent(inout) :: soil
type(soil_snow_type), intent(inout) :: ssnow
type(veg_parameter_type), intent(inout) :: veg
Calls
Called by
Contents
Call graph
fwsoil_calc_lai_ktaul calls froot, ssat, swilt, wb
dryleaf calls fwsoil_calc_lai_ktaul
define_canopy calls dryleaf
cbm calls define_canopy
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker