get_default_params – CABLE
get_default_params Subroutine
33 statements
Source File
public subroutine get_default_params(logn, vegparmnew, LUC_EXPT)
Uses
cable_common_module
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: logn
logical, intent(in) :: vegparmnew
type(LUC_EXPT_TYPE), intent(inout) :: LUC_EXPT
Calls
Called by
Contents
Call graph
get_default_params calls cable_pft_params, cable_soil_params, countpatch, get_land_index, luc_expt_set_tiles, read_gridinfo, read_soilcolor, spatialsoil
luc_expt_set_tiles calls 1166, grass, ivegp, mtemp_min20, prim_only, primaryf, secdf
read_gridinfo calls nf90_close, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_open, nc_abort
read_soilcolor calls nf90_close, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_open, nc_abort
spatialsoil calls nf90_close, nf90_get_var, nf90_inq_varid, nf90_open, nc_abort
nc_abort calls nf90_strerror
load_parameters calls get_default_params
mpidrv_master calls load_parameters
cable_offline_driver calls load_parameters
mpi_driver calls mpidrv_master