get_default_lai – CABLE
get_default_lai Subroutine
68 statements
Source File
public subroutine get_default_lai()
Arguments
None
Calls
Contents
None
Call graph
get_default_lai calls nf90_close, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_open, nc_abort
nc_abort calls nf90_strerror