get_met_data – CABLE
get_met_data Subroutine
588 statements
Source File
public subroutine get_met_data(spinup, spinConv, met, soil, rad, veg, kend, dels, TFRZ, ktau, kstart)
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: spinup
logical, intent(in) :: spinConv
type(met_type), intent(inout) :: met
type(soil_parameter_type), intent(in) :: soil
type(radiation_type), intent(in) :: rad
type(veg_parameter_type), intent(inout) :: veg
integer, intent(in) :: kend
real, intent(in) :: dels
real, intent(in) :: TFRZ
integer, intent(in) :: ktau
integer, intent(in) :: kstart
Calls
Called by
Contents
Call graph
get_met_data calls doy, fsd, hod, lwdown, moy, nf90_get_var, nf90_inquire_variable, pmb, precip, precip_sn, is_leapyear, nc_abort, rh_sh, sinbet, psurf, qair, qv, rainf, swdown, tair, tk, ua, wind, year
nc_abort calls nf90_strerror
rh_sh calls svp
mpidrv_master calls get_met_data
cable_offline_driver calls get_met_data
mpi_driver calls mpidrv_master