get_parameters_met – CABLE
get_parameters_met Subroutine
55 statements
Source File
private subroutine get_parameters_met(soil, veg, bgc, rough, completeSet)
Searches for CABLE parameters in the met forcing file, and if it finds any, uses these values to overwrite the values that have already been loaded from the default parameter loading and/or the restart file.
WARNING: The ability to set vegetation and soil type from the met file has been commented out here, so site based simulations can only have the default vegetation type - this is clearly problematic. To fix this issue, the parameter loading needs to be reordered a little, so that if the default veg or soil type is set here, the parameter values themselves are actually written as a result of this.
WARNING: The list of parameters searched for here is not complete for all CABLE applications. Not too urgent to fix if people don't often add parameters to the met file, but more important for detailed site-based process studies.
Arguments
Type Intent Optional Attributes Name
type(soil_parameter_type), intent(inout) :: soil
type(veg_parameter_type), intent(inout) :: veg
type(bgc_pool_type), intent(inout) :: bgc
type(roughness_type), intent(inout) :: rough
logical, intent(out) :: completeSet
Calls
Called by
Contents
Call graph
get_parameters_met calls readpar, nf90_inq_varid
readpar calls readpar_i, readpar_r, readpar_r2, readpar_r2d, readpar_rd
readpar_i calls nf90_inq_varid, nf90_get_var, nf90_inquire_variable, nc_abort
readpar_r calls nf90_inq_varid, nf90_get_var, nf90_inquire_variable, nc_abort
readpar_r2 calls nf90_inq_varid, nf90_get_var, nf90_inquire_variable, nc_abort
readpar_r2d calls nf90_inq_varid, nf90_get_var, nf90_inquire_variable, nc_abort
readpar_rd calls nf90_inq_varid, nf90_get_var, nf90_inquire_variable, nc_abort
nc_abort calls nf90_strerror
load_parameters calls get_parameters_met
mpidrv_master calls load_parameters
cable_offline_driver calls load_parameters
mpi_driver calls mpidrv_master