GetDiagnostics – CABLE
GetDiagnostics Subroutine
273 statements
Source File
public subroutine GetDiagnostics(POP, LAI, Cleaf, Croot, disturbance_interval, it, precip)
Arguments
Type Intent Optional Attributes Name
type(POP_TYPE), intent(inout) :: POP
real(kind=dp), intent(in) :: LAI(:)
real(kind=dp), intent(in) :: Cleaf(:)
real(kind=dp), intent(in) :: Croot(:)
integer(kind=i4b), intent(in) :: disturbance_interval(:,:)
integer(kind=i4b), intent(in) :: it(:)
real(kind=dp), intent(in), optional :: precip(:)
Calls
Called by
Contents
Call graph
getdiagnostics calls pop_grid, get_allometry, interpolate_biomass_1d, interpolate_biomass_2d, smooth_flux
get_allometry calls allometry, getheight, williams_allometry
interpolate_biomass_1d calls pop_grid, realexponential
interpolate_biomass_2d calls pop_grid, area_triangle, realexponential
smooth_flux calls pop_grid, regress
popstep calls getdiagnostics
popdriver calls popstep
casaonly_luc calls popdriver
mpidrv_worker calls popdriver, worker_casaonly_luc, worker_spincasacnp
spincasacnp calls popdriver
worker_casaonly_luc calls popdriver
worker_spincasacnp calls popdriver
cable_offline_driver calls popdriver, casaonly_luc, spincasacnp
mpi_driver calls mpidrv_worker