getheatfluxes_2d – CABLE
getheatfluxes_2d Subroutine
112 statements
Source File
private subroutine getheatfluxes_2d(dx, dxL, i_qh, i_qhya, i_qhyb, i_qhTa, i_qhTb, var, vlit, T, TL, litter, i_q, i_qya, i_qyb, i_qTa, i_qTb, i_qadv, i_qadvya, i_qadvyb, i_qadvTa, i_qadvTb, advection)
Arguments
Type Intent Optional Attributes Name
real(kind=r_2), intent(in), DIMENSION(:,:) :: dx
real(kind=r_2), intent(in), DIMENSION(:) :: dxL
real(kind=r_2), intent(inout), DIMENSION(:,:) :: i_qh
real(kind=r_2), intent(inout), DIMENSION(:,:) :: i_qhya
real(kind=r_2), intent(inout), DIMENSION(:,:) :: i_qhyb
real(kind=r_2), intent(inout), DIMENSION(:,:) :: i_qhTa
real(kind=r_2), intent(inout), DIMENSION(:,:) :: i_qhTb
type(vars), intent(in), DIMENSION(:,:) :: var
type(vars), intent(in), DIMENSION(:) :: vlit
real(kind=r_2), intent(in), DIMENSION(:,:) :: T
real(kind=r_2), intent(in), DIMENSION(:) :: TL
logical, intent(in) :: litter
real(kind=r_2), intent(inout), DIMENSION(:,:) :: i_q
real(kind=r_2), intent(inout), DIMENSION(:,:) :: i_qya
real(kind=r_2), intent(inout), DIMENSION(:,:) :: i_qyb
real(kind=r_2), intent(inout), DIMENSION(:,:) :: i_qTa
real(kind=r_2), intent(inout), DIMENSION(:,:) :: i_qTb
real(kind=r_2), intent(inout), DIMENSION(:,:) :: i_qadv
real(kind=r_2), intent(inout), DIMENSION(:,:) :: i_qadvya
real(kind=r_2), intent(inout), DIMENSION(:,:) :: i_qadvyb
real(kind=r_2), intent(inout), DIMENSION(:,:) :: i_qadvTa
real(kind=r_2), intent(inout), DIMENSION(:,:) :: i_qadvTb
integer(kind=i_d), intent(in) :: advection
Called by
Contents
Call graph
getheatfluxes calls getheatfluxes_2d
get_fluxes_and_derivs calls getheatfluxes
iflux_loop calls get_fluxes_and_derivs
timestep_loop calls iflux_loop
solve calls timestep_loop
sli_main calls solve