GetHeight – CABLE
GetHeight Function
34 statements
Source File
public function GetHeight(precip, biomass, density)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: precip
real(kind=dp), intent(in) :: biomass
real(kind=dp), intent(in) :: density
Return Value real(kind=dp)
Called by
Contents
Call graph
get_allometry calls getheight
getdiagnostics calls get_allometry
layer_recruitment calls get_allometry
layer_recruitment_single_patch calls get_allometry
patchannualdynamics calls get_allometry, layer_recruitment
patch_disturb calls layer_recruitment_single_patch
pop_init calls layer_recruitment_single_patch
pop_init_single calls layer_recruitment_single_patch
popstep calls getdiagnostics, patchannualdynamics, patch_disturb
casaonly_luc calls pop_init_single, popdriver
load_parameters calls pop_init, popluc_init
lucdriver calls pop_init_single
master_casaonly_luc calls pop_init_single
popdriver calls popstep
popluc_init calls pop_init_single
worker_pop_types calls pop_init
mpidrv_master calls load_parameters, lucdriver, master_casaonly_luc
mpidrv_worker calls popdriver, worker_pop_types, worker_casaonly_luc, worker_spincasacnp
spincasacnp calls popdriver
worker_casaonly_luc calls popdriver
worker_spincasacnp calls popdriver
cable_offline_driver calls casaonly_luc, load_parameters, lucdriver, popdriver, spincasacnp
mpi_driver calls mpidrv_master, mpidrv_worker