GWsoilfreeze – CABLE
GWsoilfreeze Subroutine
85 statements
Source File
private subroutine GWsoilfreeze(dels, soil, ssnow, tgg_old)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: dels
type(soil_parameter_type), intent(inout) :: soil
type(soil_snow_type), intent(inout) :: ssnow
real, intent(inout), DIMENSION(mp,ms) :: tgg_old
Calls
Called by
Contents
Call graph
gwsoilfreeze calls css_vec, gammzz, heat_cap_lower_limit, isflag, isoilm, rhosoil_vec, snowd, ssat_vec, tgg, wb, wbice, wbliq, zse_vec
soil_snow_gw calls gwsoilfreeze