GWstempv – CABLE
GWstempv Subroutine
113 statements
Source File
public subroutine GWstempv(dels, canopy, ssnow, soil)
Uses
total_soil_conductivity_mod
trimb_mod
cable_common_module
old_soil_conductivity_mod
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: dels
type(canopy_type), intent(inout) :: canopy
type(soil_snow_type), intent(inout) :: ssnow
type(soil_parameter_type), intent(inout) :: soil
Calls
Called by
Contents
Call graph
gwstempv calls css_vec, gammzz, old_soil_conductivity, total_soil_conductivity, trimb, rhosoil_vec, sconds, sdepth, ssat_vec, ssdn, tgg, tggsn, wbfice, wblf, zse, zse_vec
old_soil_conductivity calls wbfice, wblf, cnsd, isoilm, ssat
total_soil_conductivity calls ssat_vec, tgg, cnsd_vec, isflag, isoilm, sand_vec, snowd, watr, wb, wbice, wbliq
snow_processes_soil_thermal calls gwstempv
soil_snow_gw calls snow_processes_soil_thermal