HANDLE_ERR – CABLE
HANDLE_ERR Subroutine
11 statements
Source File
public subroutine HANDLE_ERR(status, msg)
Uses
netcdf
Arguments
Type Intent Optional Attributes Name
integer :: status
character(len=*), intent(in), optional :: msg
Calls
Called by
Contents
Call graph
handle_err calls nf90_strerror
cru_get_daily_met calls handle_err
cru_get_subdiurnal_met calls handle_err, cru_get_daily_met, get_cru_ndep, open_cru_met
cru_init calls handle_err
get_cru_ndep calls handle_err
load_parameters calls handle_err, pop_io, casa_init, popluc_init
luc_expt_init calls handle_err, read_climatefile
open_cru_met calls handle_err
open_met_file calls handle_err
open_plume_met calls handle_err
plume_get_daily_met calls handle_err
plume_mip_get_met calls handle_err, open_plume_met, plume_get_daily_met
plume_mip_init calls handle_err
pop_io calls handle_err
read_casa_restart_nc calls handle_err
read_climate_restart_nc calls handle_err
read_climatefile calls handle_err
read_luc_restart_nc calls handle_err
read_luh2 calls handle_err
write_casa_output_nc calls handle_err
write_casa_restart_nc calls handle_err
write_climate_restart_nc calls handle_err
write_landuse_casa_restart_nc calls handle_err
write_luc_output_grid_nc calls handle_err
write_luc_output_nc calls handle_err
write_luc_restart_nc calls handle_err
casa_init calls read_casa_restart_nc
casaonly_luc calls pop_io, read_luh2, write_casa_output_nc, write_luc_output_grid_nc, write_luc_restart_nc
climate_init calls read_climate_restart_nc
lucdriver calls read_luh2
master_casaonly_luc calls pop_io, read_luh2, write_casa_restart_nc, write_luc_output_grid_nc, write_luc_output_nc, write_luc_restart_nc
master_climate_types calls read_climate_restart_nc, climate_init
master_spincasacnp calls pop_io, write_casa_restart_nc
mpidrv_master calls cru_get_subdiurnal_met, cru_init, load_parameters, luc_expt_init, open_met_file, plume_mip_get_met, plume_mip_init, pop_io, write_casa_output_nc, write_casa_restart_nc, write_climate_restart_nc, write_landuse_casa_restart_nc, write_luc_output_grid_nc, write_luc_output_nc, write_luc_restart_nc, lucdriver, master_casaonly_luc, master_climate_types, master_spincasacnp
popluc_init calls read_luc_restart_nc
cable_offline_driver calls cru_get_subdiurnal_met, cru_init, load_parameters, luc_expt_init, open_met_file, plume_mip_get_met, plume_mip_init, pop_io, read_climate_restart_nc, write_casa_output_nc, write_casa_restart_nc, write_climate_restart_nc, write_landuse_casa_restart_nc, write_luc_output_nc, write_luc_restart_nc, casaonly_luc, climate_init, lucdriver
worker_climate_types calls climate_init
mpi_driver calls mpidrv_master, mpidrv_worker
mpidrv_worker calls worker_climate_types