hydraulic_redistribution – CABLE
hydraulic_redistribution Subroutine
104 statements
Source File
public subroutine hydraulic_redistribution(dels, soil, ssnow, canopy, veg, met)
Uses
cable_common_module
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: dels
type(soil_parameter_type), intent(in) :: soil
type(soil_snow_type), intent(inout) :: ssnow
type(canopy_type), intent(in) :: canopy
type(veg_parameter_type), intent(in) :: veg
type(met_type), intent(inout) :: met
Calls
Called by
Contents
Call graph
hydraulic_redistribution calls froot, sfc, ssat, swilt, wb, wbice, zse
soil_snow calls hydraulic_redistribution
cbm calls soil_snow
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker