hyofh – CABLE
hyofh Subroutine
16 statements
Source File
public pure elemental subroutine hyofh(h, lam, eta, Ke, he, K, Kh, phi)
Arguments
Type Intent Optional Attributes Name
real(kind=r_2), intent(in) :: h
real(kind=r_2), intent(in) :: lam
real(kind=r_2), intent(in) :: eta
real(kind=r_2), intent(in) :: Ke
real(kind=r_2), intent(in) :: he
real(kind=r_2), intent(out) :: K
real(kind=r_2), intent(out) :: Kh
real(kind=r_2), intent(out) :: phi
Called by
Contents
Call graph
getfluxes_vp_1d calls hyofh, flux
getfluxes_vp_2d calls hyofh, flux
seb calls hyofh
seb_fr calls hyofh
solve calls hyofh, timestep_loop
weight calls hyofh
getfluxes_vp calls getfluxes_vp_1d, getfluxes_vp_2d
flux calls weight
get_fluxes_and_derivs calls seb, getfluxes_vp, flux
sli_main calls seb, solve
iflux_loop calls get_fluxes_and_derivs
timestep_loop calls iflux_loop