igamma – CABLE
igamma Function
13 statements
Source File
public pure elemental function igamma(a, x)
Uses
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
real(kind=r_2), intent(in) :: a
real(kind=r_2), intent(in) :: x
Return Value real(kind=r_2)
Calls
Called by
Contents
Call graph
igamma calls gammln, gcf, gser
gcf calls gammln
gser calls gammln
hyofs calls igamma
iflux_loop calls hyofs
sli_main calls hyofs, solve
solve calls hyofs, timestep_loop
timestep_loop calls iflux_loop