InitPOP2D_Poisson – CABLE
InitPOP2D_Poisson Subroutine
86 statements
Source File
public subroutine InitPOP2D_Poisson(POP, mean_disturbance_interval, m)
Arguments
Type Intent Optional Attributes Name
type(POP_TYPE), intent(inout) :: POP
integer(kind=i4b), intent(in) :: mean_disturbance_interval(:,:)
integer(kind=i4b), intent(in), optional :: m
Calls
Called by
Contents
Call graph
initpop2d_poisson calls pop_grid, cumexponential, exponential
pop_init calls initpop2d_poisson
pop_init_single calls initpop2d_poisson
casaonly_luc calls pop_init_single
load_parameters calls pop_init, popluc_init
lucdriver calls pop_init_single
master_casaonly_luc calls pop_init_single
popluc_init calls pop_init_single
worker_pop_types calls pop_init
mpidrv_master calls load_parameters, lucdriver, master_casaonly_luc
mpidrv_worker calls worker_pop_types
cable_offline_driver calls casaonly_luc, load_parameters, lucdriver
mpi_driver calls mpidrv_master, mpidrv_worker