init_veg_from_vegin – CABLE
init_veg_from_vegin Subroutine
59 statements
Source File
private subroutine init_veg_from_vegin(ifmp, fmp, veg, soil_zse)
Uses
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
integer :: ifmp
integer :: fmp
type(veg_parameter_type) :: veg
real, DIMENSION(ms) :: soil_zse
Calls
Called by
Contents
Call graph
init_veg_from_vegin calls a1gs, alpha, canst1, cfrd, clitt, conkc0, conko0, convex, d0gs, dleaf, ejmax, ekc, eko, extkn, frac4, froot, g0, g1, gswmin, hc, iveg, refl1, refl2, rootbeta, rp20, rpcoef, rs20, shelrb, taul1, taul2, tmaxvj, tminvj, vbeta, vcmax, vegcf, wai, xalbnir, xfang, zr
write_default_params calls init_veg_from_vegin
load_parameters calls write_default_params
mpidrv_master calls load_parameters
cable_offline_driver calls load_parameters
mpi_driver calls mpidrv_master