IS_CASA_TIME – CABLE
IS_CASA_TIME Function
48 statements
Source File
public function IS_CASA_TIME(iotype, yyyy, ktau, kstart, koffset, kend, ktauday, logn)
Uses
cable_common_module
cable_IO_vars_module
Arguments
Type Intent Optional Attributes Name
character(len=1), intent(in) :: iotype*5
integer, intent(in) :: yyyy
integer, intent(in) :: ktau
integer, intent(in) :: kstart
integer, intent(in) :: koffset
integer, intent(in) :: kend
integer, intent(in) :: ktauday
integer, intent(in) :: logn
Return Value logical
Calls
Called by
Contents
Call graph
is_casa_time calls is_leapyear
casaonly_luc calls is_casa_time
mpidrv_master calls is_casa_time
mpidrv_worker calls is_casa_time
cable_offline_driver calls is_casa_time, casaonly_luc
mpi_driver calls mpidrv_master, mpidrv_worker