IS_LEAPYEAR – CABLE
IS_LEAPYEAR Function
7 statements
Source File
public elemental function IS_LEAPYEAR(YYYY)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: YYYY
Return Value logical
Called by
Contents
Call graph
doysod2ymdhms calls is_leapyear
get_met_data calls is_leapyear
leap_day calls is_leapyear
mpidrv_master calls is_leapyear, get_met_data, open_met_file, write_output, cru_get_subdiurnal_met, plume_mip_get_met
mpidrv_worker calls is_leapyear
open_met_file calls is_leapyear, doysod2ymdhms, ymdhms2doysod
write_output calls is_leapyear
ymdhms2doysod calls is_leapyear
cable_offline_driver calls is_leapyear, get_met_data, open_met_file, write_output, cru_get_subdiurnal_met, plume_mip_get_met
cru_get_subdiurnal_met calls doysod2ymdhms
open_plume_met calls leap_day
plume_mip_get_met calls doysod2ymdhms, open_plume_met
mpi_driver calls mpidrv_master, mpidrv_worker