iterative_wtd – CABLE
iterative_wtd Subroutine
93 statements
Source File
private subroutine iterative_wtd(ssnow, soil, veg, include_aquifer)
Arguments
Type Intent Optional Attributes Name
type(soil_snow_type), intent(inout) :: ssnow
type(soil_parameter_type), intent(inout) :: soil
type(veg_parameter_type), intent(inout) :: veg
logical, intent(in) :: include_aquifer
Calls
Called by
Contents
Call graph
iterative_wtd calls bch_vec, gwdz, gwssat_vec, gwwb, isoilm, iveg, ssat_vec, sucs_vec, wbice, wbliq, wtd, zse
sli_hydrology calls iterative_wtd
soil_snow_gw calls iterative_wtd