landuse_transitx – CABLE
landuse_transitx Subroutine
307 statements
Source File
subroutine landuse_transitx(luc, casabiome)
Uses
landuse_constant
casaparm
casadimension
casavariable
cable_def_types_mod
landuse_variable
Arguments
Type Intent Optional Attributes Name
type(landuse_mland) :: luc
type(casa_biome) :: casabiome
Calls
Called by
Contents
Call graph
landuse_transitx calls albedo_x, albsoil_x, albsoilsn_x, aphen_x, atransit, cansto_x, clabile_x, clitter_x, cplant_x, cplant_y, cplantx_x, csoil_x, csoilx_x, cwoodprod_x, dgdtg_x, doyphase3_x, doyphase3_y, fes_x, fev_x, fharvw, fhs_x, frac_sapwood_x, fracligninplant, ftransnptol, ga_x, gammzz_x, ghflux_x, gwwb_x, isoil_x, isoil_y, nlitter_x, nplant_x, nplant_y, nsoil_x, nsoilmin_x, nwoodprod_x, osnowd0_x, osnowd_x, patchfrac_x, patchfrac_y, phase_x, phase_y, phen_x, plitter_x, pplant_x, landuse_redistribution, psoil_x, psoillab_x, psoilocc_x, psoilsorb_x, pwoodprod_x, rationcplantmax, rationpplantmin, rnof1_x, rnof2_x, rtsoil_x, runoff_x, sapwood_area_x, sdepth_x, sghflux_x, sla_x, sla_y, smass_x, smass_y, snage_x, snowd_x, soilorder_x, soilorder_y, ssdn_x, ssdnn_x, tgg_x, tggsn_x, trad_x, tss_x, wb_x, wbice_x, wbtot0_x, xluh2cable
landuse_driver calls landuse_transitx
mpidrv_master calls landuse_driver
cable_offline_driver calls landuse_driver
mpi_driver calls mpidrv_master