landuse_allocate_mp – CABLE
landuse_allocate_mp Subroutine
92 statements
Source File
public subroutine landuse_allocate_mp(mpx, ms, msn, nrb, mplant, mlitter, msoil, mwood, ncp, ncs, lucmp)
Arguments
Type Intent Optional Attributes Name
integer :: mpx
integer :: ms
integer :: msn
integer :: nrb
integer :: mplant
integer :: mlitter
integer :: msoil
integer :: mwood
integer :: ncp
integer :: ncs
type(landuse_mp), intent(inout) :: lucmp
Calls
Called by
Contents
Call graph
landuse_allocate_mp calls albedo, albsoil, albsoilsn, aphen, areacell, cansto, clabile, clitter, cplant, cplantx, csoil, csoilx, cwoodprod, dgdtg, doyphase3, fes, fev, fhs, frac_sapwood, ga, gammzz, ghflux, gwwb, isflag, isoil, iveg, lai, lat, lon, nlitter, nplant, nsoil, nsoilmin, nwoodprod, osnowd, osnowd0, patchfrac, phase, phen, plitter, pplant, psoil, psoillab, psoilocc, psoilsorb, pwoodprod, rnof1, rnof2, rtsoil, runoff, sapwood_area, sdepth, sghflux, sla, smass, snage, snowd, soilorder, ssdn, ssdnn, sumcbal, sumnbal, sumpbal, tgg, tggsn, trad, tss, wb, wbice, wbtot0
landuse_driver calls landuse_allocate_mp
mpidrv_master calls landuse_driver
cable_offline_driver calls landuse_driver
mpi_driver calls mpidrv_master