landuse_land2mpx – CABLE
landuse_land2mpx Subroutine
93 statements
Source File
subroutine landuse_land2mpx(luc, lucmp, mpx)
Uses
landuse_constant
cable_def_types_mod
landuse_variable
Arguments
Type Intent Optional Attributes Name
type(landuse_mland) :: luc
type(landuse_mp) :: lucmp
integer :: mpx
Calls
Called by
Contents
Call graph
landuse_land2mpx calls albedo_y, albsoil_y, albsoilsn_y, aphen_y, cansto_y, clabile_y, clitter_y, cplant_y, cplantx_y, csoil_y, csoilx_y, cwoodprod_y, dgdtg_y, doyphase3_y, fes_y, fev_y, fhs_y, frac_sapwood_y, ga_y, gammzz_y, ghflux_y, gwwb_y, isflag_y, isoil_y, lai_y, nlitter_y, nplant_y, nsoil_y, nsoilmin_y, nwoodprod_y, osnowd0_y, osnowd_y, patchfrac_x, patchfrac_y, phase_y, phen_y, plitter_y, pplant_y, psoil_y, psoillab_y, psoilocc_y, psoilsorb_y, pwoodprod_y, rnof1_y, rnof2_y, rtsoil_y, runoff_y, sapwood_area_y, sdepth_y, sghflux_y, sla_y, smass_y, snage_y, snowd_y, soilorder_y, ssdn_y, ssdnn_y, tgg_y, tggsn_y, trad_y, tss_y, wb_y, wbice_y, wbtot0_y
landuse_driver calls landuse_land2mpx
mpidrv_master calls landuse_driver
cable_offline_driver calls landuse_driver
mpi_driver calls mpidrv_master