landuse_allocate_mland – CABLE
landuse_allocate_mland Subroutine
146 statements
Source File
public subroutine landuse_allocate_mland(mland, luc)
Uses
landuse_constant
Arguments
Type Intent Optional Attributes Name
integer :: mland
type(landuse_mland), intent(inout) :: luc
Calls
Called by
Contents
Call graph
landuse_allocate_mland calls albedo_x, albedo_y, albsoil_x, albsoil_y, albsoilsn_x, albsoilsn_y, aphen_x, aphen_y, atransit, cansto_x, cansto_y, clabile_x, clabile_y, clitter_x, clitter_y, cplant_x, cplant_y, cplantx_x, cplantx_y, csoil_x, csoil_y, csoilx_x, csoilx_y, cwoodprod_x, cwoodprod_y, dgdtg_x, dgdtg_y, doyphase3_x, doyphase3_y, fes_x, fes_y, fev_x, fev_y, fharvw, fhs_x, fhs_y, frac_sapwood_x, frac_sapwood_y, ga_x, ga_y, gammzz_x, gammzz_y, ghflux_x, ghflux_y, gwwb_x, gwwb_y, isflag_x, isflag_y, isoil_x, isoil_y, iveg_x, iveg_y, lai_x, lai_y, nlitter_x, nlitter_y, nplant_x, nplant_y, nsoil_x, nsoil_y, nsoilmin_x, nsoilmin_y, nwoodprod_x, nwoodprod_y, osnowd0_x, osnowd0_y, osnowd_x, osnowd_y, patchfrac_x, patchfrac_y, pftfrac, phase_x, phase_y, phen_x, phen_y, plitter_x, plitter_y, pplant_x, pplant_y, psoil_x, psoil_y, psoillab_x, psoillab_y, psoilocc_x, psoilocc_y, psoilsorb_x, psoilsorb_y, pwoodprod_x, pwoodprod_y, rnof1_x, rnof1_y, rnof2_x, rnof2_y, rtsoil_x, rtsoil_y, runoff_x, runoff_y, sapwood_area_x, sapwood_area_y, sdepth_x, sdepth_y, sghflux_x, sghflux_y, sla_x, sla_y, smass_x, smass_y, snage_x, snage_y, snowd_x, snowd_y, soilorder_x, soilorder_y, ssdn_x, ssdn_y, ssdnn_x, ssdnn_y, tgg_x, tgg_y, tggsn_x, tggsn_y, trad_x, trad_y, tss_x, tss_y, wb_x, wb_y, wbice_x, wbice_y, wbtot0_x, wbtot0_y, xluh2cable
landuse_driver calls landuse_allocate_mland
mpidrv_master calls landuse_driver
cable_offline_driver calls landuse_driver
mpi_driver calls mpidrv_master