landuse_checks – CABLE
landuse_checks Subroutine
72 statements
Source File
subroutine landuse_checks(mlon, mlat, landmask, luc)
Uses
landuse_constant
cable_def_types_mod
landuse_variable
Arguments
Type Intent Optional Attributes Name
integer :: mlon
integer :: mlat
integer, dimension(mlon,mlat) :: landmask
type(landuse_mland) :: luc
Calls
Called by
Contents
Call graph
landuse_checks calls 20, clabile_y, clitter_y, cplant_y, csoil_y, cwoodprod_y, nlitter_y, nplant_y, nsoil_y, nsoilmin_y, nwoodprod_y, patchfrac_y, plitter_y, pplant_y, psoil_y, psoillab_y, psoilocc_y, psoilsorb_y, pwoodprod_y
landuse_driver calls landuse_checks
mpidrv_master calls landuse_driver
cable_offline_driver calls landuse_driver
mpi_driver calls mpidrv_master