landuse_driver – CABLE
landuse_driver Subroutine
188 statements
Source File
subroutine landuse_driver(mlon, mlat, landmask, arealand, ssnow, soil, veg, bal, canopy, phen, casapool, casabal, casamet, casabiome, casaflux, bgc, rad, cstart, cend, nap, lucmp)
Uses
phenvariable
casadimension
casavariable
cable_def_types_mod
landuse_variable
cable_IO_vars_module
Arguments
Type Intent Optional Attributes Name
integer :: mlon
integer :: mlat
integer, dimension(mlon,mlat) :: landmask
real(kind=r_2), dimension(mland) :: arealand
type(soil_snow_type) :: ssnow
type(soil_parameter_type) :: soil
type(veg_parameter_type) :: veg
type(balances_type) :: bal
type(canopy_type) :: canopy
type(phen_variable) :: phen
type(casa_pool) :: casapool
type(casa_balance) :: casabal
type(casa_met) :: casamet
type(casa_biome) :: casabiome
type(casa_flux) :: casaflux
type(bgc_pool_type) :: bgc
type(radiation_type) :: rad
integer, dimension(mland) :: cstart
integer, dimension(mland) :: cend
integer, dimension(mland) :: nap
type(landuse_mp) :: lucmp
Calls
Called by
Contents
Call graph
landuse_driver calls albedo, albsoil, albsoilsn, aphen, cansto, clabile, clitter, cplant, csoil, cwoodprod, dgdtg, doyphase, fes, fev, fhs, frac_sapwood, ga, gammzz, ghflux, gwwb, isflag, isoilm, isorder, iveg, nlitter, nplant, nsoil, nsoilmin, nwoodprod, osnowd, osnowd0, patchfrac_y, phase, plitter, pplant, landuse_allocate_mland, landuse_allocate_mp, landuse_checks, landuse_deallocate_mland, landuse_deallocate_mp, landuse_land2mpx, landuse_mp2land, landuse_transitx, landuse_update_mland, psoil, psoillab, psoilocc, psoilsorb, pwoodprod, rnof1, rnof2, runoff, sapwood_area, sdepth, sghflux, sla, smass, snage, snowd, ssdn, ssdnn, sumcbal, sumnbal, sumpbal, tgg, tggsn, trad, tss, vlai, wb, wbice, wbtot0
landuse_allocate_mland calls patchfrac_y, albedo_x, albedo_y, albsoil_x, albsoil_y, albsoilsn_x, albsoilsn_y, aphen_x, aphen_y, atransit, cansto_x, cansto_y, clabile_x, clabile_y, clitter_x, clitter_y, cplant_x, cplant_y, cplantx_x, cplantx_y, csoil_x, csoil_y, csoilx_x, csoilx_y, cwoodprod_x, cwoodprod_y, dgdtg_x, dgdtg_y, doyphase3_x, doyphase3_y, fes_x, fes_y, fev_x, fev_y, fharvw, fhs_x, fhs_y, frac_sapwood_x, frac_sapwood_y, ga_x, ga_y, gammzz_x, gammzz_y, ghflux_x, ghflux_y, gwwb_x, gwwb_y, isflag_x, isflag_y, isoil_x, isoil_y, iveg_x, iveg_y, lai_x, lai_y, nlitter_x, nlitter_y, nplant_x, nplant_y, nsoil_x, nsoil_y, nsoilmin_x, nsoilmin_y, nwoodprod_x, nwoodprod_y, osnowd0_x, osnowd0_y, osnowd_x, osnowd_y, patchfrac_x, pftfrac, phase_x, phase_y, phen_x, phen_y, plitter_x, plitter_y, pplant_x, pplant_y, psoil_x, psoil_y, psoillab_x, psoillab_y, psoilocc_x, psoilocc_y, psoilsorb_x, psoilsorb_y, pwoodprod_x, pwoodprod_y, rnof1_x, rnof1_y, rnof2_x, rnof2_y, rtsoil_x, rtsoil_y, runoff_x, runoff_y, sapwood_area_x, sapwood_area_y, sdepth_x, sdepth_y, sghflux_x, sghflux_y, sla_x, sla_y, smass_x, smass_y, snage_x, snage_y, snowd_x, snowd_y, soilorder_x, soilorder_y, ssdn_x, ssdn_y, ssdnn_x, ssdnn_y, tgg_x, tgg_y, tggsn_x, tggsn_y, trad_x, trad_y, tss_x, tss_y, wb_x, wb_y, wbice_x, wbice_y, wbtot0_x, wbtot0_y, xluh2cable
landuse_allocate_mp calls albedo, albsoil, albsoilsn, aphen, cansto, clabile, clitter, cplant, csoil, cwoodprod, dgdtg, fes, fev, fhs, frac_sapwood, ga, gammzz, ghflux, gwwb, isflag, iveg, nlitter, nplant, nsoil, nsoilmin, nwoodprod, osnowd, osnowd0, phase, plitter, pplant, psoil, psoillab, psoilocc, psoilsorb, pwoodprod, rnof1, rnof2, runoff, sapwood_area, sdepth, sghflux, sla, smass, snage, snowd, ssdn, ssdnn, sumcbal, sumnbal, sumpbal, tgg, tggsn, trad, tss, wb, wbice, wbtot0, areacell, cplantx, csoilx, doyphase3, isoil, lai, lat, lon, patchfrac, phen, rtsoil, soilorder
landuse_checks calls patchfrac_y, 20, clabile_y, clitter_y, cplant_y, csoil_y, cwoodprod_y, nlitter_y, nplant_y, nsoil_y, nsoilmin_y, nwoodprod_y, plitter_y, pplant_y, psoil_y, psoillab_y, psoilocc_y, psoilsorb_y, pwoodprod_y
landuse_land2mpx calls patchfrac_y, albedo_y, albsoil_y, albsoilsn_y, aphen_y, cansto_y, clabile_y, clitter_y, cplant_y, cplantx_y, csoil_y, csoilx_y, cwoodprod_y, dgdtg_y, doyphase3_y, fes_y, fev_y, fhs_y, frac_sapwood_y, ga_y, gammzz_y, ghflux_y, gwwb_y, isflag_y, isoil_y, lai_y, nlitter_y, nplant_y, nsoil_y, nsoilmin_y, nwoodprod_y, osnowd0_y, osnowd_y, patchfrac_x, phase_y, phen_y, plitter_y, pplant_y, psoil_y, psoillab_y, psoilocc_y, psoilsorb_y, pwoodprod_y, rnof1_y, rnof2_y, rtsoil_y, runoff_y, sapwood_area_y, sdepth_y, sghflux_y, sla_y, smass_y, snage_y, snowd_y, soilorder_y, ssdn_y, ssdnn_y, tgg_y, tggsn_y, trad_y, tss_y, wb_y, wbice_y, wbtot0_y
landuse_mp2land calls albedo, albsoil, albsoilsn, aphen, cansto, clabile, clitter, cplant, csoil, cwoodprod, dgdtg, fes, fev, fhs, frac_sapwood, ga, gammzz, ghflux, gwwb, isflag, iveg, nlitter, nplant, nsoil, nsoilmin, nwoodprod, osnowd, osnowd0, phase, plitter, pplant, psoil, psoillab, psoilocc, psoilsorb, pwoodprod, rnof1, rnof2, runoff, sapwood_area, sdepth, sghflux, sla, smass, snage, snowd, ssdn, ssdnn, tgg, tggsn, trad, tss, wb, wbice, wbtot0, cplantx, csoilx, doyphase3, isoil, lai, patchfrac, phen, rtsoil, soilorder
landuse_transitx calls patchfrac_y, albedo_x, albsoil_x, albsoilsn_x, aphen_x, atransit, cansto_x, clabile_x, clitter_x, cplant_x, cplant_y, cplantx_x, csoil_x, csoilx_x, cwoodprod_x, dgdtg_x, doyphase3_x, doyphase3_y, fes_x, fev_x, fharvw, fhs_x, frac_sapwood_x, fracligninplant, ftransnptol, ga_x, gammzz_x, ghflux_x, gwwb_x, isoil_x, isoil_y, nlitter_x, nplant_x, nplant_y, nsoil_x, nsoilmin_x, nwoodprod_x, osnowd0_x, osnowd_x, patchfrac_x, phase_x, phase_y, phen_x, plitter_x, pplant_x, landuse_redistribution, psoil_x, psoillab_x, psoilocc_x, psoilsorb_x, pwoodprod_x, rationcplantmax, rationpplantmin, rnof1_x, rnof2_x, rtsoil_x, runoff_x, sapwood_area_x, sdepth_x, sghflux_x, sla_x, sla_y, smass_x, smass_y, snage_x, snowd_x, soilorder_x, soilorder_y, ssdn_x, ssdnn_x, tgg_x, tggsn_x, trad_x, tss_x, wb_x, wbice_x, wbtot0_x, xluh2cable
mpidrv_master calls landuse_driver
cable_offline_driver calls landuse_driver
mpi_driver calls mpidrv_master