landuse_mp2land – CABLE
landuse_mp2land Subroutine
167 statements
Source File
subroutine landuse_mp2land(luc, lucmp, mp, cstart, cend)
Uses
casadimension
cable_def_types_mod
landuse_variable
Arguments
Type Intent Optional Attributes Name
type(landuse_mland) :: luc
type(landuse_mp) :: lucmp
integer :: mp
integer, dimension(mland) :: cstart
integer, dimension(mland) :: cend
Calls
Called by
Contents
Call graph
landuse_mp2land calls albedo, albsoil, albsoilsn, aphen, cansto, clabile, clitter, cplant, cplantx, csoil, csoilx, cwoodprod, dgdtg, doyphase3, fes, fev, fhs, frac_sapwood, ga, gammzz, ghflux, gwwb, isflag, isoil, iveg, lai, nlitter, nplant, nsoil, nsoilmin, nwoodprod, osnowd, osnowd0, patchfrac, phase, phen, plitter, pplant, psoil, psoillab, psoilocc, psoilsorb, pwoodprod, rnof1, rnof2, rtsoil, runoff, sapwood_area, sdepth, sghflux, sla, smass, snage, snowd, soilorder, ssdn, ssdnn, tgg, tggsn, trad, tss, wb, wbice, wbtot0
landuse_driver calls landuse_mp2land
mpidrv_master calls landuse_driver
cable_offline_driver calls landuse_driver
mpi_driver calls mpidrv_master