layer_recruitment_single_patch – CABLE
layer_recruitment_single_patch Subroutine
38 statements
Source File
public subroutine layer_recruitment_single_patch(POP, index, grid_index, precip)
Arguments
Type Intent Optional Attributes Name
type(POP_TYPE), intent(inout) :: POP
integer(kind=i4b), intent(in) :: index
integer(kind=i4b), intent(in) :: grid_index
real(kind=dp), intent(in), optional :: precip(:)
Calls
Called by
Contents
Call graph
layer_recruitment_single_patch calls pop_grid, get_allometry
get_allometry calls allometry, getheight, williams_allometry
patch_disturb calls layer_recruitment_single_patch
pop_init calls layer_recruitment_single_patch
pop_init_single calls layer_recruitment_single_patch
casaonly_luc calls pop_init_single, popdriver
load_parameters calls pop_init, popluc_init
lucdriver calls pop_init_single
master_casaonly_luc calls pop_init_single
popluc_init calls pop_init_single
popstep calls patch_disturb
worker_pop_types calls pop_init
mpidrv_master calls load_parameters, lucdriver, master_casaonly_luc
mpidrv_worker calls worker_pop_types, popdriver, worker_casaonly_luc, worker_spincasacnp
popdriver calls popstep
cable_offline_driver calls casaonly_luc, load_parameters, lucdriver, popdriver, spincasacnp
spincasacnp calls popdriver
worker_casaonly_luc calls popdriver
worker_spincasacnp calls popdriver
mpi_driver calls mpidrv_master, mpidrv_worker