litter_props – CABLE
litter_props Subroutine
46 statements
Source File
public pure elemental subroutine litter_props(S, Tsoil, vlit, plit, h0)
Arguments
Type Intent Optional Attributes Name
real(kind=r_2), intent(in) :: S
real(kind=r_2), intent(in) :: Tsoil
type(vars), intent(inout) :: vlit
type(params), intent(in) :: plit
real(kind=r_2), intent(in) :: h0
Calls
Called by
Contents
Call graph
litter_props calls slope_esat
iflux_loop calls litter_props
solve calls litter_props, timestep_loop
timestep_loop calls litter_props, iflux_loop
sli_main calls solve