load_parameters – CABLE
load_parameters Subroutine
123 statements
Source File
public subroutine load_parameters(met, air, ssnow, veg, climate, bgc, soil, canopy, rough, rad, sum_flux, bal, logn, vegparmnew, casabiome, casapool, casaflux, sum_casapool, sum_casaflux, casamet, casabal, phen, POP, spinup, EMSOIL, TFRZ, LUC_EXPT, POPLUC)
Uses
POPModule
CABLE_LUC_EXPT
POPLUC_Module
Defines the priority order of sources of parameter values for CABLE, determines the total number of patches over all grid cells, and writes parameter values to CABLE's parameter arrays.
WARNING: this needs reordering and tweaking to (a) remove the possibility of inconsistencies between the number of patches in the default parameter grid and a restart file, and (b) allow vegetation and soil type to be forced from the met file (this is more complicated than simply uncommenting the iveg and isoil reads from the met file - it requires the actual parameter values to be written after that read).
Order of processes:
Load parameter values for each grid cell from default vegetation and soil types based on latitude and longitude. This includes determining the number of patches in each grid cell, and so the total number of patches.
Allocate CABLE (and CASA's [+phenology], if used) variables now that the dimension of arrays is known - i.e. now that we know how many grid cells and patches there are.
WARNING: I think this allocation should happen after ALL parameter and restart information has been loaded. As it stands, I think there is the potential for the restart file to contain variables of a different dimension to what is declared here.
Assign the loaded parameter values to CABLE's parameter variables
[IF CASA is being used] Assign the CASA parameters from CABLE parameters
WARNING: again this should happen after the restart file and met file information has been used to define CABLE parameters, otherwise they could be out of sync.
[IF CASA is being used] Initialise CASA state variables
Check that the total number of patches in the restart file matches the total number of patches from the default grid (abort if not).
WARNING: if a restart file exists, it should define the total number of patches, not the default grid.
Load initialisations and parameter values from restart file, and overwrite default values with these.
Overwrite parameter values with any found in the met forcing file. This could be just a subset of parameters.
Construct derived parameters and zero initialisations for the groundwater routine, regardless of where parameters and other initialisations have loaded from
Check for basic inconsistencies in parameter values
Write per-site parameter values to log file if requested
Arguments
Type Intent Optional Attributes Name
type(met_type), intent(inout) :: met
type(air_type), intent(inout) :: air
type(soil_snow_type), intent(out) :: ssnow
type(veg_parameter_type), intent(out) :: veg
type(climate_type), intent(inout) :: climate
type(bgc_pool_type), intent(out) :: bgc
type(soil_parameter_type), intent(out) :: soil
type(canopy_type), intent(out) :: canopy
type(roughness_type), intent(out) :: rough
type(radiation_type), intent(out) :: rad
type(sum_flux_type), intent(out) :: sum_flux
type(balances_type), intent(out) :: bal
integer, intent(in) :: logn
logical, intent(in) :: vegparmnew
type(casa_biome), intent(out) :: casabiome
type(casa_pool), intent(out) :: casapool
type(casa_flux), intent(out) :: casaflux
type(casa_pool), intent(out) :: sum_casapool
type(casa_flux), intent(out) :: sum_casaflux
type(casa_met), intent(out) :: casamet
type(casa_balance), intent(out) :: casabal
type(phen_variable), intent(out) :: phen
type(POP_TYPE), intent(inout) :: POP
logical, intent(in) :: spinup
real, intent(in) :: EMSOIL
real, intent(in) :: TFRZ
type(LUC_EXPT_TYPE), intent(inout) :: LUC_EXPT
type(POPLUC_TYPE), intent(inout) :: POPLUC
Calls
Called by
Contents
Call graph
load_parameters calls disturbance_interval, iveg, iveg2, nf90_inq_dimid, nf90_inquire_dimension, nf90_open, alloc_casavariable, alloc_phenvariable, alloc_sum_casavariable, allocate_cable_vars, casa_init, casa_readbiome, casa_readphen, check_parameter_values, derived_parameters, get_default_params, get_parameters_met, get_restart_data, handle_err, nc_abort, pop_init, pop_io, popluc_init, report_parameters, write_cnp_params, write_default_params
alloc_casavariable calls iveg2, areacell, btran, cbalance, cgpp, cgppspin, clabile, clabilelast, clabloss, cleafmean, clitter, clitterlast, cnep, cnpp, costnpup, cplant, cplant_turnover, cplant_turnover_crowding, cplant_turnover_disturbance, cplant_turnover_resource_limitation, cplantlast, crgplant, crmplant, crmplantspin_1, crmplantspin_2, crmplantspin_3, crootmean, crp, crsoil, csoil, csoillast, ctot, ctot_0, ctransferluc, cwoodprod, dcdtyear, dclabiledt, dclitterdt, dcplantdt, dcsoildt, dnlitterdt, dnplantdt, dnsoildt, dnsoilmindt, dplitterdt, dpplantdt, dpsoildt, dpsoillabdt, dpsoiloccdt, dpsoilsorbdt, fcgppyear, fcneeyear, fcnppyear, fcrgrowyear, fcrmleafyear, fcrmrootyear, fcrmwoodyear, fcrpyear, fcrsyear, fluxctoclear, fluxctoco2, fluxctohwp, fluxctolitter, fluxctosoil, fluxntoclear, fluxntohwp, fluxntolitter, fluxntosoil, fluxptoclear, fluxptohwp, fluxptolitter, fluxptosoil, fndepyear, fnfixyear, fnleachyear, fnlossyear, fnminleach, fnminloss, fnsnetyear, fnupyear, fpdustyear, fpleach, fpleachyear, fplossyear, fpsnetyear, fpupyear, fpweayear, frac_sapwood, fraccalloc, fracclabile, fraclabile, fraclignin, fracligninplant, fracnalloc, fracnpptop, fracpalloc, fromltoco2, fromltos, fromptol, fromstoco2, fromstos, ftransnptol, ftranspptol, glai, glaimax, glaimin, glaimon, glaimonx, ijgcm, isorder, ivt2, kclabrate, klitter, kminn, kmlabp, kplab, kplant, kpocc, kpsorb, kroot, krootlen, ksoil, kuplabp, kuptake, laimax, lat, litterrate, lnonwood, lon, maxcwd, maxfinelitter, meangpp, meanrleaf, moist, moistavg, moistspin_1, moistspin_2, moistspin_3, moistspin_4, moistspin_5, moistspin_6, mtempspin, nbalance, nintercept, nlitter, nlitterlast, nlittermin, nmindep, nminfix, nminleach, nminloss, nminuptake, nplant, nplantlast, nsimm, nslope, nsmin, nsnet, nsoil, nsoillast, nsoilmin, nsoilminlast, nupland, nwoodprod, pbalance, pdep, plabuptake, plantrate, pleach, plitter, plitterlast, plittermin, ploss, pplant, pplantlast, precip, prodptase, psimm, psmin, psnet, psoil, psoillab, psoillablast, psoillast, psoilocc, psoilocclast, psoilsorb, psoilsorblast, psorbmax, pupland, pwea, pwoodprod, q10soil, ratiofrootleaf, rationclitter, rationcplant, rationcplantmax, rationcplantmin, rationcsoil, rationcsoilmax, rationcsoilmin, rationcsoilnew, rationplitter, rationpplant, rationpplantmax, rationpplantmin, rationpsoil, ratiopclitter, ratiopcplant, ratiopcplantmax, ratiopcplantmin, ratiopcsoil, rmplant, rootdepth, sapwood_area, sla, soilrate, stemnpp, sumcbal, sumnbal, sumpbal, tairk, tairkspin, tsoil, tsoilavg, tsoilspin_1, tsoilspin_2, tsoilspin_3, tsoilspin_4, tsoilspin_5, tsoilspin_6, xkleafcoldexp, xkleafcoldmax, xkleafdryexp, xkleafdrymax, xkoptlitter, xkoptsoil, xkplab, xkpocc, xkpsorb, xnpmax
alloc_phenvariable calls aphen, doyphase, doyphasespin_1, doyphasespin_2, doyphasespin_3, doyphasespin_4, phase, phasespin, tkshed
alloc_sum_casavariable calls cgpp, clabile, clabloss, clitter, cnep, cnpp, cplant, cplant_turnover, cplant_turnover_crowding, cplant_turnover_disturbance, cplant_turnover_resource_limitation, crgplant, crmplant, crp, crsoil, csoil, dclabiledt, dclitterdt, dcplantdt, dcsoildt, dnlitterdt, dnplantdt, dnsoildt, dnsoilmindt, dplitterdt, dpplantdt, dpsoildt, dpsoillabdt, dpsoiloccdt, dpsoilsorbdt, fluxctoco2, fluxctolitter, fluxctosoil, fluxntolitter, fluxntosoil, fluxptolitter, fluxptosoil, fnminleach, fnminloss, fpleach, frac_sapwood, fraccalloc, fracclabile, fracnalloc, fracpalloc, fromltoco2, fromltos, fromptol, fromstoco2, fromstos, klitter, kmlabp, kplab, kplant, kpocc, kpsorb, ksoil, nlitter, nlittermin, nmindep, nminfix, nminleach, nminloss, nminuptake, nplant, nsimm, nsmin, nsnet, nsoil, nsoilmin, nupland, pdep, plabuptake, pleach, plitter, plittermin, ploss, pplant, psimm, psmin, psnet, psoil, psoillab, psoilocc, psoilsorb, psorbmax, pupland, pwea, rationclitter, rationcplant, rationcsoil, rationcsoilmax, rationcsoilmin, rationcsoilnew, rationplitter, rationpplant, rationpsoil, ratiopclitter, ratiopcplant, ratiopcsoil, sapwood_area, stemnpp
allocate_cable_vars calls alloc_cbm_var
casa_init calls 100, 2, 5, read_casa_restart_nc, rationcplant, rationcsoil, rationpsoil
casa_readbiome calls iveg, iveg2, clitter, cplant, csoil, fracligninplant, fracnpptop, ftransnptol, ftranspptol, glaimax, glaimin, isorder, ivt2, kminn, kmlabp, kroot, krootlen, kuplabp, kuptake, nlitter, psoillab, psorbmax, rationclitter, rationcplant, rationcplantmax, rationcplantmin, rationcsoil, rationcsoilmax, rationpplantmin, ratiopclitter, ratiopcplant, ratiopcplantmin, ratiopcsoil, rmplant, rootdepth, sla, tkshed, xkleafcoldexp, xkleafdryexp, zse
casa_readphen calls iveg, doyphase, lat
check_parameter_values calls iveg, clay, froot, isoilm, sand, sfc, silt, ssat, swilt
derived_parameters calls iveg, bch_vec, clay_vec, hyds_vec, org_vec, sand_vec, sfc, sfc_vec, slope, slope_std, ssat_vec, sucs_vec, swilt, swilt_vec, watr, wb, wbice, zse
get_default_params calls cable_pft_params, cable_soil_params, countpatch, get_land_index, luc_expt_set_tiles, read_gridinfo, read_soilcolor, spatialsoil
get_parameters_met calls readpar, nf90_inq_varid
get_restart_data calls nf90_inq_dimid, nf90_inquire_dimension, nc_abort, readpar, nf90_close, nf90_get_var, nf90_inq_varid, extrarestart
handle_err calls nf90_strerror
nc_abort calls nf90_strerror
pop_init calls alloc_pop, initpop2d_poisson, layer_recruitment_single_patch, zeropop
pop_io calls nf90_inq_dimid, nf90_inquire_dimension, nf90_open, handle_err, lat, lon, nf90_close, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_get_var, nf90_inq_varid, nf90_put_att, nf90_put_var, nf90_redef, pop_grid
popluc_init calls cplant, iwood, prim_only, alloc_popluc, pop_init_single, popluc_set_params, read_luc_restart_nc, zeropopluc, rationcplantmin, ratiopcplantmin
report_parameters calls iveg, iveg2, a1gs, albsoil, albsoilsn, areacell, bch, canst1, cansto, clabile, clay, clitter, cplant, csoil, css, d0gs, dleaf, ejmax, frac4, froot, glai, hc, hyds, isflag, isoilm, isorder, nlitter, nmindep, nminfix, nplant, nsoil, nsoilmin, osnowd, pdep, phase, plitter, pplant, cable_pft_params, cable_soil_params, psoil, psoillab, psoilocc, psoilsorb, pwea, ratecp, ratecs, rhosoil, rnof1, rnof2, rp20, rpcoef, rs20, rtsoil, runoff, sand, sfc, shelrb, silt, smass, snage, snowd, ssat, ssdn, ssdnn, sucs, swilt, tgg, tggsn, tmaxvj, tminvj, vbeta, vcmax, wb, wbice, xalbnir, xfang, za_tq, za_uv
write_cnp_params calls iveg, nmindep, pdep
write_default_params calls iveg, bch, clay, cplant1, cplant2, cplant3, csoil1, csoil2, css, hyds, isoilm, init_veg_from_vegin, ratecp1, ratecp2, ratecp3, ratecs1, ratecs2, rhosoil, sand, sfc, silt, snowd, ssat, sucs, swilt, tgg, vcmax, watr, wb
alloc_cbm_var calls alloc_air_type, alloc_balances_type, alloc_bgc_pool_type, alloc_canopy_type, alloc_climate_type, alloc_met_type, alloc_radiation_type, alloc_roughness_type, alloc_soil_parameter_type, alloc_soil_snow_type, alloc_sum_flux_type, alloc_veg_parameter_type
readpar calls readpar_i, readpar_r, readpar_r2, readpar_r2d, readpar_rd
alloc_pop calls iwood, pop_grid, it_pop
alloc_popluc calls csoil, age_history_secdf, area_history_secdf, biomass_age_primary, biomass_age_secondary, cbiomass, clearprod, clearprodloss, clitt, fclearance, fharvest, fnep, frac_forest, frac_primf, fracclearprod, fracclearresid, fracharvprod, fracharvresid, fracharvsecresid, freq_age_primary, freq_age_secondary, ftransfergross, ftransfernet, grass, gtop, harvprod, harvprodloss, latitude, longitude, pharv, primf, secdf, smharv, syharv
extrarestart calls nc_abort, readpar, nf90_get_var, nf90_inq_varid, redistr_i, redistr_r, redistr_r2, redistr_r2d, redistr_rd
init_veg_from_vegin calls iveg, a1gs, canst1, d0gs, dleaf, ejmax, frac4, froot, hc, rp20, rpcoef, rs20, shelrb, tmaxvj, tminvj, vbeta, vcmax, xalbnir, xfang, alpha, cfrd, clitt, conkc0, conko0, convex, ekc, eko, extkn, g0, g1, gswmin, refl1, refl2, rootbeta, taul1, taul2, vegcf, wai, zr
initpop2d_poisson calls pop_grid, cumexponential, exponential
layer_recruitment_single_patch calls pop_grid, get_allometry
luc_expt_set_tiles calls prim_only, 1166, grass, ivegp, mtemp_min20, primaryf, secdf
pop_init_single calls initpop2d_poisson, layer_recruitment_single_patch, zeropop
popluc_set_params calls biome, fracharvresid, fracharvsecresid, ivegp
read_casa_restart_nc calls nf90_inq_dimid, nf90_inquire_dimension, nf90_open, handle_err, nf90_close, nf90_get_var, nf90_inq_varid, nf90_get_att
read_gridinfo calls nf90_inq_dimid, nf90_inquire_dimension, nf90_open, nc_abort, nf90_close, nf90_get_var, nf90_inq_varid
read_luc_restart_nc calls nf90_inq_dimid, nf90_inquire_dimension, nf90_open, handle_err, nf90_close, nf90_get_var, nf90_inq_varid, 1000
read_soilcolor calls nf90_inq_dimid, nf90_inquire_dimension, nf90_open, nc_abort, nf90_close, nf90_get_var, nf90_inq_varid
spatialsoil calls nf90_open, nc_abort, nf90_close, nf90_get_var, nf90_inq_varid
alloc_canopy_type calls sublayer_dz
alloc_soil_parameter_type calls bch_vec, clay_vec, hyds_vec, org_vec, sand_vec, sfc_vec, slope, slope_std, ssat_vec, sucs_vec, swilt_vec, watr, drain_dens, elev, elev_std, gwbch_vec, gwdz, gwhyds_vec, gwrhosoil_vec, gwssat_vec, gwsucs_vec, gwwatr, gwz, rhosoil_vec, silt_vec
alloc_soil_snow_type calls dhkdw, dsmpdw, evapfbl, fland, fracice, gwdhkdw, gwdsmpdw, gwhk, gwsmp, gwwb, gwwbeq, gwzq, hk, icefrac, ifland, otgg, otss, otss_0, owetfac, qasrf, qfsrf, qhlev, qhz, qrecharge, qssrf, qstss, rh_srf, rt_qh_sublayer, rtevap_sat, rtevap_unsat, satfrac, sinfil, smp, t_snwlr, tevap, tggav, tilefrac, totenbal, totenbal2, totwblake, tprecip, trnoff, wb_lake, wbeq, wbfice, wbliq, wbtot, wbtot1, wbtot2, wetfac, wmice, wmliq, wmtot, wtd, zq
alloc_veg_parameter_type calls a1gs, d0gs, froot, alpha, cfrd, conkc0, conko0, convex, ekc, eko, extkn, gswmin, wai, deciduous, refl, taul, vlaimax
get_allometry calls allometry, getheight, williams_allometry
readpar_i calls nc_abort, nf90_get_var, nf90_inq_varid, nf90_inquire_variable
readpar_r calls nc_abort, nf90_get_var, nf90_inq_varid, nf90_inquire_variable
readpar_r2 calls nc_abort, nf90_get_var, nf90_inq_varid, nf90_inquire_variable
readpar_r2d calls nc_abort, nf90_get_var, nf90_inq_varid, nf90_inquire_variable
readpar_rd calls nc_abort, nf90_get_var, nf90_inq_varid, nf90_inquire_variable
redistr_r calls float
redistr_r2 calls float
redistr_r2d calls float
redistr_rd calls float
mpidrv_master calls load_parameters
cable_offline_driver calls load_parameters
mpi_driver calls mpidrv_master