LUC_EXPT_INIT – CABLE
LUC_EXPT_INIT Subroutine
177 statements
Source File
public subroutine LUC_EXPT_INIT(LUC_EXPT)
Arguments
Type Intent Optional Attributes Name
type(LUC_EXPT_TYPE), intent(inout) :: LUC_EXPT
Calls
Called by
Contents
Call graph
luc_expt_init calls biome, f_id, grass, input, ivegp, mtemp_min20, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_open, prim_only, primaryf, get_unit, handle_err, read_climatefile, secdf, transfile, v_id, var_name
handle_err calls nf90_strerror
read_climatefile calls nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_open, handle_err, nf90_close
mpidrv_master calls luc_expt_init
cable_offline_driver calls luc_expt_init
mpi_driver calls mpidrv_master