LUCdriver – CABLE
LUCdriver Subroutine
64 statements
Source File
subroutine LUCdriver(casabiome, casapool, casaflux, POP, LUC_EXPT, POPLUC, veg)
Uses
TypeDef
POPLUC_Module
POP_Types
cable_carbon_module
casa_ncdf_module
POPModule
casaparm
CABLE_LUC_EXPT
POPLUC_Types
cable_common_module
cable_def_types_mod
casadimension
casavariable
cable_IO_vars_module
Arguments
Type Intent Optional Attributes Name
type(casa_biome), intent(inout) :: casabiome
type(casa_pool), intent(inout) :: casapool
type(casa_flux), intent(inout) :: casaflux
type(POP_TYPE), intent(inout) :: POP
type(LUC_EXPT_TYPE), intent(inout) :: LUC_EXPT
type(POPLUC_TYPE), intent(inout) :: POPLUC
type(veg_parameter_type), intent(in) :: veg
Calls
Called by
Contents
Call graph
lucdriver calls cplant, frac_forest, frac_primf, input, iveg, iwood, prim_only, pop_init_single, popluc_weights_transfer, poplucstep, read_luh2, rationcplantmin, ratiopcplantmin
pop_init_single calls initpop2d_poisson, layer_recruitment_single_patch, zeropop
popluc_weights_transfer calls iwood, prim_only, freq_age_secondary
poplucstep calls freq_age_secondary, gtop, gtos, primf, execute_luc_event, increment_age, ptog, ptos, stog
read_luh2 calls input, f_id, nf90_get_var, handle_err, transfile, v_id
execute_luc_event calls frac_forest, freq_age_secondary, primf, ptog, ptos, stog, n_event
handle_err calls nf90_strerror
increment_age calls freq_age_secondary, smharv, syharv
initpop2d_poisson calls pop_grid, cumexponential, exponential
layer_recruitment_single_patch calls pop_grid, get_allometry
get_allometry calls allometry, getheight, williams_allometry
cable_offline_driver calls lucdriver