master_casa_params – CABLE
master_casa_params Subroutine
782 statements
Source File
private subroutine master_casa_params(comm, casabiome, casapool, casaflux, casamet, casabal, phen)
Uses
cable_def_types_mod
mpi
phenvariable
casavariable
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
type(casa_biome), intent(inout) :: casabiome
type(casa_pool), intent(inout) :: casapool
type(casa_flux), intent(inout) :: casaflux
type(casa_met), intent(inout) :: casamet
type(casa_balance), intent(inout) :: casabal
type(phen_variable), intent(inout) :: phen
Calls
Called by
Contents
Call graph
master_casa_params calls aphen, areacell, btran, cbalance, cgpp, clabile, clabilelast, clabloss, clitter, clitterlast, cnep, cnpp, cplant, cplantlast, crgplant, crmplant, crp, crsoil, csoil, csoillast, cwoodprod, dclabiledt, dclitterdt, dcplantdt, dcsoildt, dnlitterdt, dnplantdt, dnsoildt, dnsoilmindt, doyphase, doyphasespin_1, doyphasespin_2, doyphasespin_3, doyphasespin_4, dplitterdt, dpplantdt, dpsoildt, dpsoillabdt, dpsoiloccdt, dpsoilsorbdt, fcgppyear, fcneeyear, fcnppyear, fcrgrowyear, fcrmleafyear, fcrmrootyear, fcrmwoodyear, fcrpyear, fcrsyear, fluxctoco2, fluxctolitter, fluxctosoil, fluxntolitter, fluxntosoil, fluxptolitter, fluxptosoil, fndepyear, fnfixyear, fnleachyear, fnlossyear, fnminleach, fnminloss, fnsnetyear, fnupyear, fpdustyear, fpleach, fpleachyear, fplossyear, fpsnetyear, fpupyear, fpweayear, frac_sapwood, fraccalloc, fracclabile, fracnalloc, fracpalloc, fromltoco2, fromltos, fromptol, fromstoco2, fromstos, glai, glaimon, glaimonx, ijgcm, isorder, iveg2, klitter, kmlabp, kplab, kplant, kpocc, kpsorb, ksoil, lat, lnonwood, lon, moist, moistavg, mpi_abort, mpi_barrier, mpi_get_address, mpi_reduce, mpi_type_commit, mpi_type_create_hvector, mpi_type_create_struct, mpi_type_free, mpi_type_get_extent, mpi_type_size, nbalance, nlitter, nlitterlast, nlittermin, nmindep, nminfix, nminleach, nminloss, nminuptake, nplant, nplantlast, nsimm, nsmin, nsnet, nsoil, nsoillast, nsoilmin, nsoilminlast, nupland, nwoodprod, pbalance, pdep, phase, phasespin, plabuptake, pleach, plitter, plitterlast, plittermin, ploss, pplant, pplantlast, precip, master_send_input, psimm, psmin, psnet, psoil, psoillab, psoillablast, psoillast, psoilocc, psoilocclast, psoilsorb, psoilsorblast, psorbmax, pupland, pwea, pwoodprod, rationclitter, rationcplant, rationcsoil, rationcsoilmax, rationcsoilmin, rationcsoilnew, rationplitter, rationpplant, rationpsoil, ratiopclitter, ratiopcplant, ratiopcsoil, sapwood_area, sumcbal, sumnbal, sumpbal, tairk, tsoil, tsoilavg
master_send_input calls mpi_isend, mpi_waitall
mpidrv_master calls master_casa_params
mpi_driver calls mpidrv_master