master_receive_pop – CABLE
master_receive_pop Subroutine
17 statements
Source File
private subroutine master_receive_pop(pop, comm)
Uses
pop_mpi
POP_Types
cable_common_module
mpi
Arguments
Type Intent Optional Attributes Name
type(POP_TYPE), intent(inout) :: pop
integer, intent(in) :: comm
Calls
Called by
Contents
Call graph
master_receive_pop calls mpi_recv, pop_grid
master_casaonly_luc calls master_receive_pop
master_spincasacnp calls master_receive_pop
mpidrv_master calls master_receive_pop, master_casaonly_luc, master_spincasacnp
mpi_driver calls mpidrv_master