master_intypes – CABLE
master_intypes Subroutine
109 statements
Source File
private subroutine master_intypes(comm, met, veg)
Uses
cable_def_types_mod
mpi
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
type(met_type), intent(in) :: met
type(veg_parameter_type), intent(in) :: veg
Calls
Called by
Contents
Call graph
master_intypes calls ca, coszen, doy, fld, fsd, hod, moy, mpi_abort, mpi_get_address, mpi_reduce, mpi_type_commit, mpi_type_create_hvector, mpi_type_create_struct, mpi_type_get_extent, mpi_type_size, ndep, pmb, precip, precip_sn, qv, tk, ua, vlai, year
mpidrv_master calls master_intypes
mpi_driver calls mpidrv_master