master_casa_types – CABLE
master_casa_types Subroutine
423 statements
Source File
private subroutine master_casa_types(comm, casapool, casaflux, casamet, casabal, phen)
Uses
cable_def_types_mod
casavariable
phenvariable
casadimension
mpi
Arguments
Type Intent Optional Attributes Name
integer :: comm
type(casa_pool), intent(inout) :: casapool
type(casa_flux), intent(inout) :: casaflux
type(casa_met), intent(inout) :: casamet
type(casa_balance), intent(inout) :: casabal
type(phen_variable), intent(inout) :: phen
Calls
Called by
Contents
Call graph
master_casa_types calls aphen, cgpp, clabile, clabloss, clitter, cnep, cnpp, cplant, cplant_turnover, cplant_turnover_crowding, cplant_turnover_disturbance, cplant_turnover_resource_limitation, crgplant, crmplant, crp, crsoil, csoil, ctot, ctot_0, cwoodprod, doyphase, doyphasespin_1, doyphasespin_2, doyphasespin_3, doyphasespin_4, fcgppyear, fcneeyear, fcnppyear, fcrgrowyear, fcrmleafyear, fcrmrootyear, fcrmwoodyear, fcrpyear, fcrsyear, fluxctolitter, fluxctosoil, fluxntolitter, fluxntosoil, fluxptolitter, fluxptosoil, fndepyear, fnfixyear, fnleachyear, fnlossyear, fnsnetyear, fnupyear, fpdustyear, fpleachyear, fplossyear, fpsnetyear, fpupyear, fpweayear, frac_sapwood, fraccalloc, fracclabile, fracnalloc, fracpalloc, fromltoco2, fromltos, fromptol, fromstoco2, fromstos, glai, klitter, kplant, ksoil, mpi_abort, mpi_get_address, mpi_reduce, mpi_type_commit, mpi_type_create_hvector, mpi_type_create_struct, mpi_type_free, mpi_type_get_extent, mpi_type_size, nlitter, nlittermin, nmindep, nminfix, nminleach, nminloss, nminuptake, nplant, nsimm, nsmin, nsnet, nsoil, nsoilmin, nupland, nwoodprod, phase, phasespin, plabuptake, plitter, pplant, psoil, psoillab, psoilocc, psoilsorb, psorbmax, pwoodprod, rationclitter, rationcplant, rationcsoil, ratiopclitter, ratiopcplant, ratiopcsoil, sapwood_area, sumcbal, sumnbal, sumpbal
mpidrv_master calls master_casa_types
mpi_driver calls mpidrv_master