master_climate_types – CABLE
master_climate_types Subroutine
187 statements
Source File
private subroutine master_climate_types(comm, climate, ktauday)
Uses
cable_def_types_mod
mpi
cable_common_module
cable_climate_mod
Arguments
Type Intent Optional Attributes Name
integer :: comm
type(climate_type) :: climate
integer :: ktauday
Calls
Called by
Contents
Call graph
master_climate_types calls aevap, agdd0, agdd5, alpha_pt, alpha_pt_20, atemp_mean, biome, chilldays, dmoist, dmoist_31, dtemp, dtemp_31, dtemp_91, evap_pt, gdd0, gdd5, mmoist, mpi_abort, mpi_get_address, mpi_isend, mpi_reduce, mpi_type_commit, mpi_type_create_hvector, mpi_type_create_struct, mpi_type_get_extent, mpi_type_size, mpi_waitall, mtemp, mtemp_max, mtemp_max20, mtemp_max_20, mtemp_min, mtemp_min20, mtemp_min_20, climate_init, read_climate_restart_nc, qtemp, qtemp_max, qtemp_max_last_year
climate_init calls read_climate_restart_nc, alloc_cbm_var
read_climate_restart_nc calls nf90_close, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_open, handle_err
alloc_cbm_var calls alloc_air_type, alloc_balances_type, alloc_bgc_pool_type, alloc_canopy_type, alloc_climate_type, alloc_met_type, alloc_radiation_type, alloc_roughness_type, alloc_soil_parameter_type, alloc_soil_snow_type, alloc_sum_flux_type, alloc_veg_parameter_type
handle_err calls nf90_strerror
alloc_canopy_type calls sublayer_dz
alloc_soil_parameter_type calls bch_vec, clay_vec, drain_dens, elev, elev_std, gwbch_vec, gwdz, gwhyds_vec, gwrhosoil_vec, gwssat_vec, gwsucs_vec, gwwatr, gwz, hyds_vec, org_vec, rhosoil_vec, sand_vec, sfc_vec, silt_vec, slope, slope_std, ssat_vec, sucs_vec, swilt_vec, watr
alloc_soil_snow_type calls dhkdw, dsmpdw, evapfbl, fland, fracice, gwdhkdw, gwdsmpdw, gwhk, gwsmp, gwwb, gwwbeq, gwzq, hk, icefrac, ifland, otgg, otss, otss_0, owetfac, qasrf, qfsrf, qhlev, qhz, qrecharge, qssrf, qstss, rh_srf, rt_qh_sublayer, rtevap_sat, rtevap_unsat, satfrac, sinfil, smp, t_snwlr, tevap, tggav, tilefrac, totenbal, totenbal2, totwblake, tprecip, trnoff, wb_lake, wbeq, wbfice, wbliq, wbtot, wbtot1, wbtot2, wetfac, wmice, wmliq, wmtot, wtd, zq
alloc_veg_parameter_type calls a1gs, alpha, cfrd, conkc0, conko0, convex, d0gs, deciduous, ekc, eko, extkn, froot, gswmin, refl, taul, vlaimax, wai
mpidrv_master calls master_climate_types
mpi_driver calls mpidrv_master