master_spincasacnp – CABLE
master_spincasacnp Subroutine
136 statements
Source File
private subroutine master_spincasacnp(dels, kstart, kend, mloop, veg, soil, casabiome, casapool, casaflux, casamet, casabal, phen, POP, climate, LALLOC, icomm, ocomm)
Uses
cable_carbon_module
phenvariable
cable_def_types_mod
TypeDef
casa_offline_inout_module
casaparm
casadimension
casavariable
cable_common_module
POP_Types
POPModule
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: dels
integer, intent(in) :: kstart
integer, intent(in) :: kend
integer, intent(in) :: mloop
type(veg_parameter_type), intent(inout) :: veg
type(soil_parameter_type), intent(inout) :: soil
type(casa_biome), intent(inout) :: casabiome
type(casa_pool), intent(inout) :: casapool
type(casa_flux), intent(inout) :: casaflux
type(casa_met), intent(inout) :: casamet
type(casa_balance), intent(inout) :: casabal
type(phen_variable), intent(inout) :: phen
type(POP_TYPE), intent(inout) :: POP
type(climate_type), intent(inout) :: climate
integer, intent(in) :: LALLOC
integer, intent(in) :: icomm
integer, intent(in) :: ocomm
Calls
Called by
Contents
Call graph
master_spincasacnp calls cgppspin, crmplantspin_1, crmplantspin_2, crmplantspin_3, doyphasespin_1, doyphasespin_2, doyphasespin_3, doyphasespin_4, moistspin_1, moistspin_2, moistspin_3, moistspin_4, moistspin_5, moistspin_6, mtempspin, phasespin, casa_poolout, master_receive, master_receive_pop, master_send_input, pop_io, read_casa_dump, write_casa_restart_nc, tairkspin, tsoilspin_1, tsoilspin_2, tsoilspin_3, tsoilspin_4, tsoilspin_5, tsoilspin_6
casa_poolout calls 100, 2, 5, aphen, areacell, doyphase, frac_sapwood, glai, isoilm, isorder, iveg, iveg2, kmlabp, lat, lon, phase, psorbmax, rationclitter, rationcplant, rationcsoil, rationplitter, rationpplant, rationpsoil, sapwood_area, sla, sumcbal, sumnbal, sumpbal
master_receive calls mpi_irecv, mpi_waitall
master_receive_pop calls mpi_recv, pop_grid
master_send_input calls mpi_isend, mpi_waitall
pop_io calls lat, lon, nf90_close, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_open, nf90_put_att, nf90_put_var, nf90_redef, pop_grid, handle_err
read_casa_dump calls nf90_close, nf90_open, get_var_ncr2, get_var_ncr3, stderr_nc
write_casa_restart_nc calls doyphase, nf90_close, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_put_att, nf90_put_var, nf90_redef, handle_err
get_var_ncr2 calls nf90_get_var, nf90_inq_varid, stderr_nc
get_var_ncr3 calls nf90_get_var, nf90_inq_varid, stderr_nc
handle_err calls nf90_strerror
stderr_nc calls nf90_strerror
mpidrv_master calls master_spincasacnp
mpi_driver calls mpidrv_master