master_CASAONLY_LUC – CABLE
master_CASAONLY_LUC Subroutine
172 statements
Source File
private subroutine master_CASAONLY_LUC(dels, kstart, kend, veg, soil, casabiome, casapool, casaflux, casamet, casabal, phen, POP, climate, LALLOC, LUC_EXPT, POPLUC, icomm, ocomm)
Uses
TypeDef
POPLUC_Module
POP_Types
cable_carbon_module
casa_ncdf_module
phenvariable
casaparm
POPModule
CABLE_LUC_EXPT
POPLUC_Types
casa_offline_inout_module
cable_common_module
cable_def_types_mod
casadimension
casavariable
cable_IO_vars_module
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: dels
integer, intent(in) :: kstart
integer, intent(in) :: kend
type(veg_parameter_type), intent(inout) :: veg
type(soil_parameter_type), intent(inout) :: soil
type(casa_biome), intent(inout) :: casabiome
type(casa_pool), intent(inout) :: casapool
type(casa_flux), intent(inout) :: casaflux
type(casa_met), intent(inout) :: casamet
type(casa_balance), intent(inout) :: casabal
type(phen_variable), intent(inout) :: phen
type(POP_TYPE), intent(inout) :: POP
type(climate_type), intent(inout) :: climate
integer, intent(in) :: LALLOC
type(LUC_EXPT_TYPE), intent(inout) :: LUC_EXPT
type(POPLUC_TYPE), intent(inout) :: POPLUC
integer, intent(in) :: icomm
integer, intent(in) :: ocomm
Calls
Called by
Contents
Call graph
master_casaonly_luc calls cgppspin, cplant, crmplantspin_1, crmplantspin_2, crmplantspin_3, doyphasespin_1, doyphasespin_2, doyphasespin_3, doyphasespin_4, frac_forest, grid, ilu, input, iwood, moistspin_1, moistspin_2, moistspin_3, moistspin_4, moistspin_5, moistspin_6, mpi_send, mtempspin, phasespin, pop_grid, prim_only, primf, master_receive, master_receive_pop, master_send_input, pop_init_single, pop_io, pop_luc_casa_transfer, popluc_set_patchfrac, popluc_weights_transfer, poplucstep, read_casa_dump, read_luh2, write_casa_restart_nc, write_luc_output_grid_nc, write_luc_output_nc, write_luc_restart_nc, rationcplantmin, ratiopcplantmin, tairkspin, tsoilspin_1, tsoilspin_2, tsoilspin_3, tsoilspin_4, tsoilspin_5, tsoilspin_6
master_receive calls mpi_irecv, mpi_waitall
master_receive_pop calls pop_grid, mpi_recv
master_send_input calls mpi_isend, mpi_waitall
pop_init_single calls initpop2d_poisson, layer_recruitment_single_patch, zeropop
pop_io calls pop_grid, lat, lon, nf90_close, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_open, nf90_put_att, nf90_put_var, nf90_redef, handle_err
pop_luc_casa_transfer calls cplant, iwood, pop_grid, prim_only, 1166, clabile, clearprod, clearprodloss, clitter, csoil, ctransferluc, fclearance, fcneeyear, fharvest, fracclearprod, fracclearresid, fracharvprod, fracharvresid, fracharvsecresid, grass, harvprod, harvprodloss, nlitter, nplant, nsoil, nsoilmin, plitter, pplant, psoil, smharv, syharv
popluc_set_patchfrac calls prim_only, primf, grass
popluc_weights_transfer calls iwood, prim_only, freq_age_secondary
poplucstep calls primf, freq_age_secondary, gtop, gtos, execute_luc_event, increment_age, ptog, ptos, stog
read_casa_dump calls nf90_close, nf90_open, get_var_ncr2, get_var_ncr3, stderr_nc
read_luh2 calls input, f_id, nf90_get_var, handle_err, transfile, v_id
write_casa_restart_nc calls doyphase, nf90_close, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_put_att, nf90_put_var, nf90_redef, handle_err
write_luc_output_grid_nc calls cbiomass, clearprod, clearprodloss, clitt, csoil, fclearance, fharvest, fnep, ftransfergross, ftransfernet, harvprod, harvprodloss, nf90_close, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_put_att, nf90_put_var, nf90_redef, handle_err
write_luc_output_nc calls nf90_close, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_put_att, nf90_put_var, nf90_redef, handle_err
write_luc_restart_nc calls nf90_close, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_put_att, nf90_put_var, nf90_redef, handle_err
execute_luc_event calls frac_forest, primf, freq_age_secondary, ptog, ptos, stog, n_event
get_var_ncr2 calls nf90_get_var, nf90_inq_varid, stderr_nc
get_var_ncr3 calls nf90_get_var, nf90_inq_varid, stderr_nc
handle_err calls nf90_strerror
increment_age calls freq_age_secondary, smharv, syharv
initpop2d_poisson calls pop_grid, cumexponential, exponential
layer_recruitment_single_patch calls pop_grid, get_allometry
stderr_nc calls nf90_strerror
get_allometry calls allometry, getheight, williams_allometry
mpidrv_master calls master_casaonly_luc
mpi_driver calls mpidrv_master