master_pop_types – CABLE
master_pop_types Subroutine
48 statements
Source File
private subroutine master_pop_types(comm, casamet, pop)
Uses
cable_common_module
mpi
POP_Types
pop_mpi
casavariable
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
type(casa_met), intent(in) :: casamet
type(POP_TYPE), intent(inout) :: pop
Calls
Called by
Contents
Call graph
master_pop_types calls mpi_send, pop_grid, create_pop_gridcell_type
create_pop_gridcell_type calls mpi_abort, mpi_get_address, mpi_type_commit, mpi_type_create_resized, mpi_type_create_struct, create_patch
create_patch calls mpi_abort, mpi_get_address, mpi_type_commit, mpi_type_create_resized, mpi_type_create_struct, create_layer
create_layer calls mpi_abort, mpi_get_address, mpi_type_commit, mpi_type_create_resized, mpi_type_create_struct, create_cohort
create_cohort calls mpi_abort, mpi_get_address, mpi_type_commit, mpi_type_create_resized, mpi_type_create_struct
mpidrv_master calls master_pop_types
mpi_driver calls mpidrv_master