master_cable_params – CABLE
master_cable_params Subroutine
1139 statements
Source File
private subroutine master_cable_params(comm, met, air, ssnow, veg, bgc, soil, canopy, rough, rad, sum_flux, bal)
Uses
cable_def_types_mod
mpi
cable_common_module
cable_IO_vars_module
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
type(met_type), intent(inout) :: met
type(air_type), intent(inout) :: air
type(soil_snow_type), intent(inout) :: ssnow
type(veg_parameter_type), intent(inout) :: veg
type(bgc_pool_type), intent(inout) :: bgc
type(soil_parameter_type), intent(inout) :: soil
type(canopy_type), intent(inout) :: canopy
type(roughness_type), intent(inout) :: rough
type(radiation_type), intent(inout) :: rad
type(sum_flux_type), intent(inout) :: sum_flux
type(balances_type), intent(inout) :: bal
Calls
Called by
Contents
Call graph
master_cable_params calls a1gs, albedo, albedo_t, albsoil, albsoilsn, alpha, bch, bch_vec, c3, ca, canst1, cansto, cansto0, cdtq, cduv, cexpkbm, cexpkdm, cfrd, clay, clitt, cls, cmolar, cnsd, coexp, conkc0, conko0, convex, coszen, cplant, csoil, css, d0gs, da, ddq_dtg, deciduous, deltss, delwc, delwc_tot, dewmm, dfe_ddq, dfe_dtg, dfh_dtg, dfn_dtg, dgdtg, disp, disturbance_intensity, disturbance_interval, dleaf, doy, drybal, dsatdk, dsumpn, dsumrd, dsumrp, dsumrs, dtmlt, dva, ebal, ebal_cncheck, ebal_tot, ebal_tot_cncheck, ebal_tottr, ebaltr, ejmax, ekc, eko, epot, epsi, evap_tot, evapc_tot, evapfbl, evaps_tot, evapsn, extkb, extkbm, extkd, extkd2, extkdm, extkn, fbeam, fe, fes, fes_cor, fesp, fess, fev, fevc, fevw, fevw_pot, fh, fhs, fhs_cor, fhv, fhvw, fland, fld, flws, fnee, fnpp, fns, fns_cor, fnv, fpn, frac4, frday, froot, frp, frpr, frpw, frs, fsatmax, fsd, fvlai, fwet, fwsoil, fwtop, fwtop1, fwtop2, fwtop3, g0, g1, ga, ga_cor, gammzz, ghflux, gradis, gswmin, gswx, gswx_t, gwbch_vec, gwdz, gwhyds_vec, gwssat_vec, gwsucs_vec, gwwatr, gwwb, gwz, h0, hc, hod, hruff, hruff_grmx, hsbh, hyds, hyds_vec, i2bp3, iantrct, ibp2, ifland, isflag, isoilm, lwabv, meth, moy, mpi_abort, mpi_get_address, mpi_reduce, mpi_send, mpi_type_commit, mpi_type_create_hvector, mpi_type_create_struct, mpi_type_free, mpi_type_get_extent, mpi_type_size, nsnow, oldcansto, osnowd, osnowd0, otss, otss_0, owb1, owbtot, owetfac, pmb, potev, precip, precip_sn, precip_tot, precis, decomp_types, master_send_input, psyc, pudsmx, pudsto, pwb_min, qasrf, qasrf_tot, qcan, qfsrf, qfsrf_tot, qsat, qscrn, qssabs, qssrf, qssrf_tot, qstss, qv, qvair, reffbm, reffdf, refl, rghlai, rho, rhocbm, rhocdf, rhosoil, rlam, rnet, rniso, rnof1, rnof1_tot, rnof2, rnof2_tot, rnoff_tot, rp20, rpcoef, rs20, rt0us, rt1, rt1usa, rt1usb, rtsoil, runoff, s, sand, scalex, sconds, sdepth, segg, sfc, sfc_vec, sghflux, shelrb, silt, sinfil, slope, slope_std, smass, smelt, snage, snowd, snowdc_tot, snowliq, soilcol, spill, ssat, ssat_vec, ssdn, ssdnn, sucs, sucs_vec, sumpn, sumrd, sumrp, sumrpr, sumrpw, sumrs, sumxrp, sumxrs, swilt, swilt_vec, t_snwlr, taul, term2, term3, term5, term6, tevap, tgg, tggav, tggsn, thetai, through, tilefrac, tk, tmaxvj, tminvj, totenbal, totenbal2, tprecip, trad, transb, transd, trnoff, tscrn, tsoil, tss, tss_p, tsurface, tv, tvair, tvrad, ua, us, uscrn, usuh, vbeta, vcmax, vegcf, visc, vlaimax, vlaiw, volm, wai, watr, wb, wb_lake, wbal, wbal_tot, wbal_tot1, wbfice, wbice, wblf, wbtot, wbtot0, wbtot1, wcint, wetbal, wetfac, wetfac_cs, xalbnir, xfang, year, z0m, z0soil, z0soilsn, za_tq, za_uv, zeta, zetar, zr, zref_tq, zref_uv, zruffs
decomp_types calls mpi_get_address, mpi_type_commit, mpi_type_create_struct, mpi_type_create_resized
master_send_input calls mpi_isend, mpi_waitall
mpidrv_master calls master_cable_params
mpi_driver calls mpidrv_master