master_casa_dump_types – CABLE
master_casa_dump_types Subroutine
91 statements
Source File
private subroutine master_casa_dump_types(comm, casamet, casaflux, phen, climate)
Uses
casavariable
cable_def_types_mod
mpi
phenvariable
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
type(casa_met), intent(inout) :: casamet
type(casa_flux), intent(inout) :: casaflux
type(phen_variable), intent(inout) :: phen
type(climate_type) :: climate
Calls
Called by
Contents
Call graph
master_casa_dump_types calls cgpp, crmplant, doyphase, moist, mpi_abort, mpi_get_address, mpi_reduce, mpi_type_commit, mpi_type_create_hvector, mpi_type_create_struct, mpi_type_get_extent, mpi_type_size, nmindep, phase, tairk, tsoil
mpidrv_master calls master_casa_dump_types
mpi_driver calls mpidrv_master