master_restart_types – CABLE
master_restart_types Subroutine
112 statements
Source File
private subroutine master_restart_types(comm, canopy, air)
Uses
cable_def_types_mod
casadimension
casavariable
mpi
Arguments
Type Intent Optional Attributes Name
integer :: comm
type(canopy_type), intent(in) :: canopy
type(air_type), intent(in) :: air
Calls
Called by
Contents
Call graph
master_restart_types calls cduv, cmolar, dewmm, dgdtg, dsatdk, epsi, evapfbl, fnv, frpr, frpw, mpi_abort, mpi_get_address, mpi_reduce, mpi_type_commit, mpi_type_create_hvector, mpi_type_create_struct, mpi_type_free, mpi_type_get_extent, mpi_type_size, psyc, qsat, rho, visc, volm
mpidrv_master calls master_restart_types
mpi_driver calls mpidrv_master