mpidrv_worker – CABLE
mpidrv_worker Subroutine
270 statements
Source File
public subroutine mpidrv_worker(comm)
Uses
cable_def_types_mod
mpi
cable_climate_mod
CABLE_PLUME_MIP
casa_ncdf_module
cable_input_module
casadimension
POP_Constants
phenvariable
POP_Types
POPModule
cable_namelist_util
cable_common_module
casavariable
cbl_soil_snow_init_special_module
cable_output_module
cable_cbm_module
cable_IO_vars_module
Arguments
Type Intent Optional Attributes Name
integer :: comm
Calls
Called by
Contents
Call graph
mpidrv_worker calls fsd, glai, mpi_bcast, mpi_comm_dup, mpi_comm_rank, mpi_recv, mpi_send, pop_grid, bgcdriver, cable_climate, casa_feedback, cbm, find_extents, is_casa_time, is_leapyear, popdriver, spec_init_soil_snow, sumcflux, worker_cable_params, worker_casa_dump_types, worker_casa_luc_types, worker_casa_params, worker_casa_type, worker_casaonly_luc, worker_climate_types, worker_decomp, worker_end, worker_intype, worker_outtype, worker_pop_types, worker_restart_type, worker_send_pop, worker_spincasacnp, tgg, vlai
bgcdriver calls cplant, float, fraccalloc, biogeochem, cable_phenology_clim
cable_climate calls alpha_pt_20, dmoist_31, dtemp_31, dtemp_91, float, mtemp_max_20, mtemp_min_20, biome1_pft, epsif
casa_feedback calls glai, cplant, glaimin, iveg, iveg2, nintercept, nplant, nslope, pplant, vcmax_np, rationcplantmax, rationcplantmin, sla, vcmax
cbm calls fsd, tgg, albedo, carbon_pl, define_air, define_canopy, fsunlit_mask, fsunlit_veg_mask, fveg_mask, init_radiation, plantcarb, ruff_resist, snow_aging, soil_snow, soilcarb, tggsn
find_extents calls mpi_get_address
is_casa_time calls is_leapyear
popdriver calls disturbance_intensity, disturbance_interval, popstep
spec_init_soil_snow calls tgg, wb, wbice, zse
sumcflux calls clabloss, crgplant, crsoil
worker_cable_params calls mpi_comm_rank, mpi_recv, mpi_abort, mpi_get_address, mpi_get_count, mpi_reduce, mpi_type_commit, mpi_type_create_struct, mpi_type_free, mpi_type_get_extent, mpi_type_size, mpi_unpack, allocate_cable_vars, decomp_types
worker_casa_dump_types calls mpi_comm_rank, mpi_abort, mpi_get_address, mpi_reduce, mpi_type_commit, mpi_type_create_struct, mpi_type_get_extent, mpi_type_size
worker_casa_luc_types calls mpi_comm_rank, clabile, clitter, cplant, csoil, fcneeyear, mpi_abort, mpi_get_address, mpi_reduce, mpi_type_commit, mpi_type_create_struct, mpi_type_get_extent, mpi_type_size, nlitter, nplant, nsoil, nsoilmin, plitter, pplant, psoil
worker_casa_params calls mpi_comm_rank, mpi_recv, aphen, doyphasespin_1, doyphasespin_2, doyphasespin_3, doyphasespin_4, mpi_abort, mpi_barrier, mpi_get_address, mpi_get_count, mpi_reduce, mpi_type_commit, mpi_type_create_struct, mpi_type_free, mpi_type_get_extent, mpi_type_size, mpi_unpack, phasespin, alloc_casavariable, alloc_phenvariable
worker_casa_type calls glai, aphen, cgpp, clabile, clabloss, clitter, cnep, cnpp, cplant, cplant_turnover, cplant_turnover_crowding, cplant_turnover_disturbance, cplant_turnover_resource_limitation, crgplant, crp, crsoil, csoil, ctot, ctot_0, cwoodprod, doyphase, doyphasespin_1, doyphasespin_2, doyphasespin_3, doyphasespin_4, fcgppyear, fcneeyear, fcnppyear, fcrgrowyear, fcrmleafyear, fcrmrootyear, fcrmwoodyear, fcrpyear, fcrsyear, fndepyear, fnfixyear, fnleachyear, fnlossyear, fnsnetyear, fnupyear, fpdustyear, fpleachyear, fplossyear, fpsnetyear, fpupyear, fpweayear, frac_sapwood, fracclabile, mpi_abort, mpi_get_address, mpi_reduce, mpi_type_commit, mpi_type_create_struct, mpi_type_get_extent, mpi_type_size, nlitter, nlittermin, nmindep, nminfix, nminleach, nminloss, nminuptake, nplant, nsimm, nsmin, nsnet, nsoil, nsoilmin, nupland, nwoodprod, phase, phasespin, plabuptake, plitter, pplant, psoil, psoillab, psoilocc, psoilsorb, psorbmax, pwoodprod, rationclitter, rationcplant, rationcsoil, ratiopclitter, ratiopcplant, ratiopcsoil, sapwood_area, sumcbal, sumnbal, sumpbal
worker_casaonly_luc calls mpi_comm_rank, mpi_recv, mpi_send, pop_grid, popdriver, worker_send_pop, cplant, fraccalloc, biogeochem
worker_climate_types calls mpi_recv, aevap, agdd0, agdd5, alpha_pt, alpha_pt_20, atemp_mean, biome, chilldays, dmoist, dmoist_31, dtemp, dtemp_31, dtemp_91, evap_pt, gdd0, gdd5, iveg, mmoist, mpi_abort, mpi_get_address, mpi_get_count, mpi_reduce, mpi_type_commit, mpi_type_create_struct, mpi_type_get_extent, mpi_type_size, mpi_unpack, mtemp, mtemp_max, mtemp_max20, mtemp_max_20, mtemp_min, mtemp_min20, mtemp_min_20, climate_init, qtemp, qtemp_max, qtemp_max_last_year
worker_decomp calls mpi_recv
worker_end calls mpi_type_free
worker_intype calls mpi_comm_rank, mpi_abort, mpi_get_address, mpi_reduce, mpi_type_commit, mpi_type_create_struct, mpi_type_get_extent, mpi_type_size
worker_outtype calls fsd, mpi_comm_rank, find_extents, tgg, vlai, albedo, albsoil, albsoilsn, bch, c3, ca, canst1, cansto, cdtq, cduv, cexpkbm, cexpkdm, clay, cls, cmolar, cnsd, coszen, css, da, ddq_dtg, deciduous, delwc, delwcol, dewmm, dfe_ddq, dfe_dtg, dfh_dtg, dfn_dtg, dgdtg, dleaf, drybal, dsatdk, dtmlt, dva, ejmax, epot, epsi, evap, evapfbl, evapsn, extkb, extkbm, extkd, extkd2, extkdm, extkn, fbeam, fe, fes, fes_cor, fesp, fess, fev, fevc, fevw, fevw_pot, fh, fhs, fhs_cor, fhv, fhvw, fld, flws, fnee, fnpp, fns, fns_cor, fnv, fpn, frac4, frday, froot, frp, frpr, frpw, frs, fvlai, fwet, fwsoil, fwtop, fwtop1, fwtop2, fwtop3, ga, ga_cor, gammzz, ghflux, gradis, gswx, gswx_t, gwwb, h0, hc, hsbh, hyds, i2bp3, ibp2, isflag, isoilm, iveg, lwabv, meth, mpi_abort, mpi_get_address, mpi_reduce, mpi_type_commit, mpi_type_create_struct, mpi_type_get_extent, mpi_type_size, nsnow, nsteps, osnowd, osnowd0, otss, otss_0, owetfac, pmb, potev, precip, precip_sn, precis, psyc, pudsmx, pudsto, pwb_min, qcan, qrecharge, qsat, qscrn, qssabs, qstss, qv, qvair, reffbm, reffdf, refl, rghlai, rho, rhocbm, rhocdf, rhosoil, rlam, rnet, rniso, rnof1, rnof2, rp20, rpcoef, rs20, rtsoil, runoff, s, sand, satfrac, scalex, sconds, sdepth, segg, sfc, sghflux, shelrb, silt, sinfil, smass, smelt, snage, snowd, snowliq, spill, ssat, ssdn, ssdnn, sucs, swilt, t_snwlr, taul, tggav, tggsn, thetai, through, tk, tmaxvj, tminvj, trad, transb, transd, tscrn, tsoil, tss, tsurface, tv, tvair, tvrad, ua, us, uscrn, vbeta, vcmax, vegcf, visc, vlaiw, volm, wai, wb, wb_lake, wbfice, wbice, wblf, wbtot, wbtot0, wcint, wetbal, wetfac, wetfac_cs, wtd, xalbnir, xfang, zetar
worker_pop_types calls mpi_comm_rank, mpi_recv, pop_grid, create_pop_gridcell_type, pop_init
worker_restart_type calls mpi_comm_rank, cduv, cmolar, dewmm, dgdtg, dsatdk, epsi, evapfbl, fnv, frpr, frpw, mpi_abort, mpi_get_address, mpi_reduce, mpi_type_commit, mpi_type_create_struct, mpi_type_get_extent, mpi_type_size, psyc, qsat, rho, visc, volm
worker_send_pop calls mpi_send, pop_grid
worker_spincasacnp calls mpi_recv, mpi_send, popdriver, worker_send_pop, cplant, fraccalloc, kplant, analyticpool, biogeochem, rationcsoilnew
albedo calls canopyreflectance, canopytransmitance, effectivesurfacereflectance, fbeamradalbedo, surface_albedosn
alloc_casavariable calls glai, cgpp, clabile, clabloss, clitter, cnep, cnpp, cplant, cplant_turnover, cplant_turnover_crowding, cplant_turnover_disturbance, cplant_turnover_resource_limitation, crgplant, crp, crsoil, csoil, ctot, ctot_0, cwoodprod, fcgppyear, fcneeyear, fcnppyear, fcrgrowyear, fcrmleafyear, fcrmrootyear, fcrmwoodyear, fcrpyear, fcrsyear, fndepyear, fnfixyear, fnleachyear, fnlossyear, fnsnetyear, fnupyear, fpdustyear, fpleachyear, fplossyear, fpsnetyear, fpupyear, fpweayear, frac_sapwood, fraccalloc, fracclabile, glaimin, iveg2, kplant, nintercept, nlitter, nlittermin, nmindep, nminfix, nminleach, nminloss, nminuptake, nplant, nsimm, nslope, nsmin, nsnet, nsoil, nsoilmin, nupland, nwoodprod, plabuptake, plitter, pplant, precip, psoil, psoillab, psoilocc, psoilsorb, psorbmax, pwoodprod, rationclitter, rationcplant, rationcplantmax, rationcplantmin, rationcsoil, rationcsoilnew, ratiopclitter, ratiopcplant, ratiopcsoil, sapwood_area, sla, sumcbal, sumnbal, sumpbal, tsoil, areacell, btran, cbalance, cgppspin, clabilelast, cleafmean, clitterlast, costnpup, cplantlast, crmplant, crmplantspin_1, crmplantspin_2, crmplantspin_3, crootmean, csoillast, ctransferluc, dcdtyear, dclabiledt, dclitterdt, dcplantdt, dcsoildt, dnlitterdt, dnplantdt, dnsoildt, dnsoilmindt, dplitterdt, dpplantdt, dpsoildt, dpsoillabdt, dpsoiloccdt, dpsoilsorbdt, fluxctoclear, fluxctoco2, fluxctohwp, fluxctolitter, fluxctosoil, fluxntoclear, fluxntohwp, fluxntolitter, fluxntosoil, fluxptoclear, fluxptohwp, fluxptolitter, fluxptosoil, fnminleach, fnminloss, fpleach, fraclabile, fraclignin, fracligninplant, fracnalloc, fracnpptop, fracpalloc, fromltoco2, fromltos, fromptol, fromstoco2, fromstos, ftransnptol, ftranspptol, glaimax, glaimon, glaimonx, ijgcm, isorder, ivt2, kclabrate, klitter, kminn, kmlabp, kplab, kpocc, kpsorb, kroot, krootlen, ksoil, kuplabp, kuptake, laimax, lat, litterrate, lnonwood, lon, maxcwd, maxfinelitter, meangpp, meanrleaf, moist, moistavg, moistspin_1, moistspin_2, moistspin_3, moistspin_4, moistspin_5, moistspin_6, mtempspin, nbalance, nlitterlast, nplantlast, nsoillast, nsoilminlast, pbalance, pdep, plantrate, pleach, plitterlast, plittermin, ploss, pplantlast, prodptase, psimm, psmin, psnet, psoillablast, psoillast, psoilocclast, psoilsorblast, pupland, pwea, q10soil, ratiofrootleaf, rationcsoilmax, rationcsoilmin, rationplitter, rationpplant, rationpplantmax, rationpplantmin, rationpsoil, ratiopcplantmax, ratiopcplantmin, rmplant, rootdepth, soilrate, stemnpp, tairk, tairkspin, tsoilavg, tsoilspin_1, tsoilspin_2, tsoilspin_3, tsoilspin_4, tsoilspin_5, tsoilspin_6, xkleafcoldexp, xkleafcoldmax, xkleafdryexp, xkleafdrymax, xkoptlitter, xkoptsoil, xkplab, xkpocc, xkpsorb, xnpmax
alloc_phenvariable calls aphen, doyphase, doyphasespin_1, doyphasespin_2, doyphasespin_3, doyphasespin_4, phase, phasespin, tkshed
allocate_cable_vars calls alloc_cbm_var
analyticpool calls clay, clitter, csoil, iveg, iveg2, nlitter, nsoil, psoillab, psorbmax, rationclitter, rationcsoil, silt, fracligninplant, fromltos, fromstos, isorder, klitter, kmlabp, ksoil, litterrate, rationplitter, rationpsoil, soilrate
biogeochem calls pop_grid, cplant_turnover, disturbance_interval, klitter, avgsoil, casa_allocation, casa_cnpbal, casa_cnpcycle, casa_cnpflux, casa_coeffplant, casa_coeffsoil, casa_delplant, casa_delsoil, casa_ndummy, casa_nuptake, casa_pdummy, casa_puptake, casa_rplant, casa_rplant1, casa_xkn, casa_xnp, casa_xrateplant, casa_xratesoil, phenology
biome1_pft calls agdd0, agdd5, biome, iveg, mtemp_max20, mtemp_min20
cable_phenology_clim calls aphen, chilldays, dmoist, doyphase, gdd5, iveg, phase
carbon_pl calls cplant, csoil
climate_init calls alloc_cbm_var, read_climate_restart_nc
create_pop_gridcell_type calls mpi_abort, mpi_get_address, mpi_type_commit, mpi_type_create_struct, mpi_type_create_resized, create_patch
decomp_types calls mpi_get_address, mpi_type_commit, mpi_type_create_struct, mpi_type_create_resized
define_canopy calls tgg, cmolar, dleaf, evapfbl, extkb, fes, fev, fevw_pot, fvlai, gswx, lwabv, potev, define_air, ruff_resist, qv, rghlai, rtsoil, satfrac, shelrb, tggsn, tk, transd, tss, tvrad, us, visc, vlaiw, wb, wbice, wetfac, wetfac_cs, zetar, zse, coexp, disp, hruff, comp_friction_vel, dryleaf, humidity_deficit_method, latent_heat_flux, penman_monteith, psim, psis, qsatfjh, radiation, surf_wetness_fact, update_zetar, wetleaf, within_canopy, rt0us, rt1, rt1usa, rt1usb, rt_qh_sublayer, rtevap_sat, rtevap_unsat, usuh, z0soilsn, zetash, zref_tq, zruffs
init_radiation calls beamfraction, common_initrad_scalings, effectiveextinctcoeffs, extinctioncoeff
plantcarb calls cplant, tk, ratecp
pop_init calls alloc_pop, initpop2d_poisson, layer_recruitment_single_patch, zeropop
popstep calls pop_grid, getdiagnostics, getpatchfrequencies, getuniqueagefrequencies, patch_disturb, patch_partial_disturb, patch_partial_disturb2, patchannualdynamics
ruff_resist calls rghlai, vlaiw, coexp, disp, hruff, hgtabovesnow, lai_eff, rt1usb, term2, term3, term5, usuh, z0m, z0soilsn, za_tq, za_uv, zref_tq, zref_uv, zruffs
soil_snow calls tgg, css, dtmlt, gammzz, rhosoil, tggsn, wb, wbice, zse, hydraulic_redistribution, remove_trans, snow_accum, snow_melting, snowcheck, snowdensity, snowl_adjust, soilfreeze, stempv, surfbv
soilcarb calls tgg, froot, wb
alloc_cbm_var calls alloc_air_type, alloc_balances_type, alloc_bgc_pool_type, alloc_canopy_type, alloc_climate_type, alloc_met_type, alloc_radiation_type, alloc_roughness_type, alloc_soil_parameter_type, alloc_soil_snow_type, alloc_sum_flux_type, alloc_veg_parameter_type
alloc_pop calls pop_grid, it_pop, iwood
avgsoil calls sfc, swilt, btran, moist, moistavg, tsoilavg
beamfraction calls spitter
canopyreflectance calls canopyreflectance_beam, canopyreflectance_dif
canopytransmitance calls canopytransmitance_beam, canopytransmitance_dif
casa_allocation calls glai, cplant, fraccalloc, glaimin, iveg, kplant, sfc, sla, swilt, btran, crmplant, fracnpptop, glaimax, moistavg, tsoilavg, 1166, casa_wolf
casa_cnpbal calls cgpp, clabile, cnpp, cplant, crgplant, crsoil, fraccalloc, iveg2, kplant, nmindep, nminfix, nminleach, nminloss, nminuptake, nsoilmin, nupland, plabuptake, psoillab, psoilocc, psoilsorb, cbalance, clabilelast, cplantlast, crmplant, dclabiledt, dcplantdt, lat, lon, nsoilminlast, pdep, pleach, ploss, psoillablast, psoilocclast, psoilsorblast, pupland, pwea, 100
casa_cnpcycle calls glai, clabile, clitter, cplant, csoil, cwoodprod, glaimin, iveg, iveg2, nlitter, nplant, nsoil, nsoilmin, nwoodprod, plitter, pplant, psoil, psoillab, psoilocc, psorbmax, pwoodprod, sla, dclabiledt, dclitterdt, dcplantdt, dcsoildt, dnlitterdt, dnplantdt, dnsoildt, dnsoilmindt, dplitterdt, dpplantdt, dpsoildt, dpsoillabdt, dpsoiloccdt, glaimax, kmlabp, lat, lon, casa_poolzero
casa_cnpflux calls crgplant, fcrmleafyear, fcrmrootyear, fcrmwoodyear, crmplant
casa_coeffplant calls glai, cplant, glaimin, iveg, kplant, nplant, fracligninplant, fromptol, ftransnptol, plantrate
casa_coeffsoil calls clay, iveg, iveg2, silt, fracligninplant, fromltoco2, fromltos, fromstoco2, fromstos, isorder, ksoil, litterrate, soilrate, xkplab, xkpocc, xkpsorb
casa_delplant calls cgpp, clabloss, cnpp, cplant, crgplant, fraccalloc, fracclabile, iveg, iveg2, kplant, nminuptake, nplant, plabuptake, pplant, crmplant, dcplantdt, dnplantdt, dpplantdt, fluxctolitter, fluxntolitter, fluxptolitter, fracnalloc, fracpalloc, fromptol, ftransnptol, ftranspptol, lnonwood
casa_delsoil calls clitter, cnpp, crsoil, csoil, iveg, iveg2, nlitter, nlittermin, nmindep, nminfix, nminleach, nminloss, nsimm, nsmin, nsnet, nsoil, nsoilmin, nupland, plitter, psoil, psoillab, psoilocc, psoilsorb, psorbmax, rationcsoilnew, ratiopcsoil, costnpup, dpsoillabdt, fluxctoco2, fluxctolitter, fluxctosoil, fluxntolitter, fluxntosoil, fluxptolitter, fluxptosoil, fnminleach, fnminloss, fpleach, fromltoco2, fromltos, fromstoco2, fromstos, klitter, kmlabp, kpocc, kpsorb, ksoil, pdep, pleach, plittermin, prodptase, psimm, psmin, psnet, pupland, pwea, tsoilavg, 20
casa_ndummy calls clitter, cplant, csoil, rationclitter, rationcplant, rationcsoil
casa_nuptake calls iveg, iveg2, nminuptake, nsoilmin, kminn, 100, casa_nrequire
casa_pdummy calls clitter, cplant, csoil, ratiopclitter, ratiopcplant, ratiopcsoil, isorder
casa_puptake calls iveg, plabuptake, psoillab, kuplabp, casa_prequire
casa_rplant calls cgpp, clabile, clabloss, cnpp, cplant, crgplant, frac_sapwood, iveg, nplant, vcmax_np, qtemp_max_last_year, rationcplantmax, sla, crmplant, kclabrate, ratiopcplantmax, rmplant, tairk, tsoilavg
casa_rplant1 calls cgpp, clabile, clabloss, cnpp, cplant, crgplant, iveg, nplant, crmplant, kclabrate, rationpplantmin, rmplant, tairk, tsoilavg
casa_xkn calls clitter, csoil, iveg, iveg2, nlitter, nsoil, nsoilmin, rationcsoilnew, fromltos, fromstos, klitter, ksoil, maxcwd, maxfinelitter, rationcsoilmax, rationcsoilmin
casa_xnp calls cgpp, cnpp, cplant, fracclabile, iveg, iveg2, nplant, nsoilmin, pplant, psoillab, xnpmax, 20, casa_nrequire, casa_prequire
casa_xrateplant calls iveg, iveg2, phase, btran, tairk, tkshed, xkleafcoldexp, xkleafcoldmax, xkleafdryexp, xkleafdrymax
casa_xratesoil calls iveg, iveg2, ssat, moistavg, q10soil, tsoilavg, xkoptlitter, xkoptsoil
common_initrad_scalings calls calc_rhoch, common_initrad_coeffs
comp_friction_vel calls psim
create_patch calls mpi_abort, mpi_get_address, mpi_type_commit, mpi_type_create_struct, mpi_type_create_resized, create_layer
dryleaf calls ca, cansto, cmolar, dleaf, dsatdk, dva, ejmax, evapfbl, fevc, frac4, froot, fvlai, fwet, gradis, gswx, iveg, psyc, qcan, qtemp_max_last_year, rlam, rniso, scalex, swilt, tk, tvair, vcmax, vlaiw, wb, zse, a1gs, alpha, cfrd, conkc0, conko0, convex, d0gs, ekc, eko, g0, ej3x, ej4x, fwsoil_calc_lai_ktaul, fwsoil_calc_non_linear, fwsoil_calc_std, getrex_1d, photosynthesis, xejmxt3, xrdt, xvcmxt3, xvcmxt4, rex, ssat_vec, swilt_vec, wbliq, zr
effectiveextinctcoeffs calls effectiveextinctcoeff
effectivesurfacereflectance calls effectivereflectance
extinctioncoeff calls extinctioncoeff_beam, extinctioncoeff_dif
getdiagnostics calls pop_grid, get_allometry, interpolate_biomass_1d, interpolate_biomass_2d, smooth_flux
getpatchfrequencies calls pop_grid
getuniqueagefrequencies calls pop_grid, cumexponential, realexponential
hydraulic_redistribution calls froot, sfc, ssat, swilt, wb, wbice, zse
initpop2d_poisson calls pop_grid, cumexponential, exponential
layer_recruitment_single_patch calls pop_grid, get_allometry
patch_disturb calls pop_grid, layer_recruitment_single_patch
patch_partial_disturb calls pop_grid
patch_partial_disturb2 calls pop_grid
patchannualdynamics calls pop_grid, get_allometry, layer_recruitment
penman_monteith calls qsatfjh
phenology calls doyphase, phase
psim calls alog
psis calls alog
radiation calls fsd, albsoilsn, cexpkbm, cexpkdm, extkbm, extkdm, fbeam, fvlai, gradis, qcan, reffbm, reffdf, refl, scalex, taul
read_climate_restart_nc calls nf90_close, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_open, handle_err
remove_trans calls evapfbl, froot, wb, zse
snow_accum calls tgg, cls, evapsn, fes_cor, fess, gammzz, isflag, isoilm, osnowd, precip_sn, precis, sdepth, smass, snowd, ssdn, tggsn
snow_melting calls tgg, dtmlt, gammzz, isflag, sdepth, smass, snowd, ssdn, tggsn
snowcheck calls tgg, isflag, smass, snowd, ssdn, ssdnn, t_snwlr, tggsn
snowdensity calls tgg, sconds, smass, ssdn, tggsn
snowl_adjust calls isflag, sdepth, smass, snowd, ssdn, tggsn
soilfreeze calls tgg, gammzz, wb, wbice, zse
stempv calls tgg, gammzz, sconds, sdepth, ssdn, tggsn, wbfice, wblf, zse, old_soil_conductivity, total_soil_conductivity, trimb
surf_wetness_fact calls iveg, snowd, tk, wb, wbice, wetfac
surfbv calls tgg, gammzz, sdepth, sfc, smass, ssdn, wb, zse, smoisturev
wetleaf calls cansto, dsatdk, dva, fevw, fwet, psyc, rlam, tk, tvair, vlaiw
within_canopy calls cls, epsi, fes, fev, fhs, fhv, meth, pmb, qstss, qv, qvair, rho, rlam, satfrac, tk, tss, tvair, vlaiw, wetfac, hruff, rt1, rtevap_sat, rtevap_unsat, z0soilsn, qsatfjh2
alloc_canopy_type calls sublayer_dz
alloc_soil_parameter_type calls ssat_vec, swilt_vec, bch_vec, clay_vec, drain_dens, elev, elev_std, gwbch_vec, gwdz, gwhyds_vec, gwrhosoil_vec, gwssat_vec, gwsucs_vec, gwwatr, gwz, hyds_vec, org_vec, rhosoil_vec, sand_vec, sfc_vec, silt_vec, slope, slope_std, sucs_vec, watr
alloc_soil_snow_type calls evapfbl, gwwb, otss, otss_0, owetfac, qrecharge, qstss, satfrac, sinfil, t_snwlr, tggav, wb_lake, wbfice, wbtot, wetfac, wtd, rt_qh_sublayer, rtevap_sat, rtevap_unsat, wbliq, dhkdw, dsmpdw, fland, fracice, gwdhkdw, gwdsmpdw, gwhk, gwsmp, gwwbeq, gwzq, hk, icefrac, ifland, otgg, qasrf, qfsrf, qhlev, qhz, qssrf, rh_srf, smp, tevap, tilefrac, totenbal, totenbal2, totwblake, tprecip, trnoff, wbeq, wbtot1, wbtot2, wmice, wmliq, wmtot, zq
alloc_veg_parameter_type calls deciduous, extkn, froot, refl, taul, wai, a1gs, alpha, cfrd, conkc0, conko0, convex, d0gs, ekc, eko, gswmin, vlaimax
casa_nrequire calls cplant, fraccalloc, iveg, iveg2, kplant, nplant, nsoilmin, rationcplantmax, rationcplantmin, ftransnptol
casa_poolzero calls clitter, cplant, csoil, nlitter, nplant, nsoil
casa_prequire calls cplant, fraccalloc, iveg, iveg2, kplant, pplant, ftranspptol, ratiopcplantmax, ratiopcplantmin
casa_wolf calls cnpp, cplant, iveg, iveg2, fracnpptop
create_layer calls mpi_abort, mpi_get_address, mpi_type_commit, mpi_type_create_struct, mpi_type_create_resized, create_cohort
fwsoil_calc_lai_ktaul calls froot, ssat, swilt, wb
fwsoil_calc_non_linear calls sfc
get_allometry calls allometry, getheight, williams_allometry
handle_err calls nf90_strerror
interpolate_biomass_1d calls pop_grid, realexponential
interpolate_biomass_2d calls pop_grid, realexponential, area_triangle
layer_recruitment calls pop_grid, get_allometry
old_soil_conductivity calls cnsd, isoilm, ssat, wbfice, wblf
smoisturev calls sfc, ssat, wb, wbfice, wbice, wblf, zse, trimb, zshh
smooth_flux calls pop_grid, regress
total_soil_conductivity calls tgg, isflag, isoilm, snowd, wb, wbice, ssat_vec, wbliq, cnsd_vec, sand_vec, watr
create_cohort calls mpi_abort, mpi_get_address, mpi_type_commit, mpi_type_create_struct, mpi_type_create_resized
mpi_driver calls mpidrv_worker