mpidrv_master – CABLE
mpidrv_master Subroutine
635 statements
Source File
public subroutine mpidrv_master(comm)
Uses
phenvariable
cable_write_module
cable_phys_constants_mod
cable_cbm_module
casavariable
casa_ncdf_module
POP_Constants
casa_offline_inout_module
cable_output_module
casa_cable
cable_namelist_util
cable_IO_vars_module
cable_climate_mod
bgcdriver_mod
CABLE_LUC_EXPT
POPLUC_Module
landuse_constant
CABLE_CRU
cable_common_module
casa_inout_module
POPLUC_Types
CABLE_PLUME_MIP
cable_def_types_mod
cable_input_module
POP_Types
mpi
casadimension
landuse_variable
Arguments
Type Intent Optional Attributes Name
integer :: comm
Calls
Called by
Contents
Call graph
mpidrv_master calls fe, fld, fsd, fvlai, fwsoil, ga, grid, gwwb, alloc_cbm_var, mpi_abort, mpi_bcast, mpi_comm_dup, mpi_send, mpi_waitall, patchfrac, pmb, pop_grid, potev, precip, precip_sn, casa_fluxout, close_met_file, close_output_file, create_landuse_cable_restart, create_new_gridinfo, create_restart, cru_get_subdiurnal_met, cru_init, find_extents, get_met_data, is_casa_time, is_leapyear, landuse_data, landuse_deallocate_mp, landuse_driver, load_parameters, luc_expt_init, lucdriver, master_cable_params, master_casa_dump_types, master_casa_luc_types, master_casa_params, master_casa_types, master_casaonly_luc, master_climate_types, master_decomp, master_end, master_intypes, master_outtypes, master_pop_types, master_receive, master_receive_pop, master_restart_types, master_send_input, master_spincasacnp, nullify_write, open_met_file, open_output_file, plume_mip_get_met, plume_mip_init, pop_io, pop_luc_casa_transfer, popluc_set_patchfrac, preparefiles, write_casa_dump, write_casa_output_nc, write_casa_restart_nc, write_climate_restart_nc, write_landuse_casa_restart_nc, write_luc_output_grid_nc, write_luc_output_nc, write_luc_restart_nc, write_output, qv, tgg, tk, ua, vlaiw, wb, year
alloc_cbm_var calls alloc_air_type, alloc_balances_type, alloc_bgc_pool_type, alloc_canopy_type, alloc_climate_type, alloc_met_type, alloc_radiation_type, alloc_roughness_type, alloc_soil_parameter_type, alloc_soil_snow_type, alloc_sum_flux_type, alloc_veg_parameter_type
casa_fluxout calls 100, 5, areacell, fcgppyear, fcneeyear, fcnppyear, fcrgrowyear, fcrmleafyear, fcrmrootyear, fcrmwoodyear, fcrsyear, float, fndepyear, fnfixyear, fnleachyear, fnlossyear, fnsnetyear, fnupyear, fpdustyear, fpleachyear, fplossyear, fpsnetyear, fpupyear, fpweayear, isoilm, isorder, iveg, lat, lon
close_met_file calls nf90_close, nc_abort
close_output_file calls ebal_tot, nf90_close, nc_abort, wbal_tot
create_landuse_cable_restart calls define_ovar, write_ovar, nf90_close, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_put_att, nf90_put_var, nf90_redef, nc_abort
create_new_gridinfo calls nf90_close, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_get_var, nf90_inq_varid, nf90_open, nf90_put_att, nf90_put_var, nc_abort, rangechk2, rangechk3, sort
create_restart calls define_ovar, write_ovar, nf90_close, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_put_att, nf90_put_var, nf90_redef, nc_abort
cru_get_subdiurnal_met calls precip, avg_lwdn, coszen, doy, f_id, hod, metfile, ndepvals, nf90_close, phild, phisd, cru_get_daily_met, doysod2ymdhms, get_cru_co2, get_cru_ndep, handle_err, open_cru_met, wgen_daily_constants, wgen_init, wgen_subdiurnal_met, temp, wind
cru_init calls avg_lwdn, met, ndepvals, nf90_close, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_open, get_unit, handle_err
find_extents calls mpi_get_address
get_met_data calls fsd, pmb, precip, precip_sn, is_leapyear, qv, tk, ua, year, doy, hod, lwdown, moy, nf90_get_var, nf90_inquire_variable, nc_abort, rh_sh, sinbet, psurf, qair, rainf, swdown, tair, wind
is_casa_time calls is_leapyear
landuse_data calls nf90_close, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_open, landuse_getdata, landuse_getxluh2, nc_abort
landuse_driver calls ga, gwwb, landuse_deallocate_mp, tgg, wb, albedo, albsoil, albsoilsn, aphen, cansto, clabile, clitter, cplant, csoil, cwoodprod, dgdtg, doyphase, fes, fev, fhs, frac_sapwood, gammzz, ghflux, isflag, isoilm, isorder, iveg, nlitter, nplant, nsoil, nsoilmin, nwoodprod, osnowd, osnowd0, patchfrac_y, phase, plitter, pplant, landuse_allocate_mland, landuse_allocate_mp, landuse_checks, landuse_deallocate_mland, landuse_land2mpx, landuse_mp2land, landuse_transitx, landuse_update_mland, psoil, psoillab, psoilocc, psoilsorb, pwoodprod, rnof1, rnof2, runoff, sapwood_area, sdepth, sghflux, sla, smass, snage, snowd, ssdn, ssdnn, sumcbal, sumnbal, sumpbal, tggsn, trad, tss, vlai, wbice, wbtot0
load_parameters calls pop_io, disturbance_interval, iveg, iveg2, nf90_inq_dimid, nf90_inquire_dimension, nf90_open, alloc_casavariable, alloc_phenvariable, alloc_sum_casavariable, allocate_cable_vars, casa_init, casa_readbiome, casa_readphen, check_parameter_values, derived_parameters, get_default_params, get_parameters_met, get_restart_data, handle_err, nc_abort, pop_init, popluc_init, report_parameters, write_cnp_params, write_default_params
luc_expt_init calls biome, f_id, grass, input, ivegp, mtemp_min20, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_open, prim_only, primaryf, get_unit, handle_err, read_climatefile, secdf, transfile, v_id, var_name
lucdriver calls cplant, frac_forest, frac_primf, input, iwood, prim_only, pop_init_single, popluc_weights_transfer, poplucstep, read_luh2, rationcplantmin, ratiopcplantmin
master_cable_params calls fe, fld, fsd, fvlai, fwsoil, ga, gwwb, mpi_abort, mpi_send, pmb, potev, precip, precip_sn, master_send_input, qv, tgg, tk, ua, vlaiw, wb, year, a1gs, albedo, albedo_t, albsoil, albsoilsn, alpha, bch, bch_vec, c3, ca, canst1, cansto, cansto0, cdtq, cduv, cexpkbm, cexpkdm, cfrd, clay, clitt, cls, cmolar, cnsd, coexp, conkc0, conko0, convex, coszen, cplant, csoil, css, d0gs, da, ddq_dtg, deciduous, deltss, delwc, delwc_tot, dewmm, dfe_ddq, dfe_dtg, dfh_dtg, dfn_dtg, dgdtg, disp, disturbance_intensity, disturbance_interval, dleaf, doy, drybal, dsatdk, dsumpn, dsumrd, dsumrp, dsumrs, dtmlt, dva, ebal, ebal_cncheck, ebal_tot, ebal_tot_cncheck, ebal_tottr, ebaltr, ejmax, ekc, eko, epot, epsi, evap_tot, evapc_tot, evapfbl, evaps_tot, evapsn, extkb, extkbm, extkd, extkd2, extkdm, extkn, fbeam, fes, fes_cor, fesp, fess, fev, fevc, fevw, fevw_pot, fh, fhs, fhs_cor, fhv, fhvw, fland, flws, fnee, fnpp, fns, fns_cor, fnv, fpn, frac4, frday, froot, frp, frpr, frpw, frs, fsatmax, fwet, fwtop, fwtop1, fwtop2, fwtop3, g0, g1, ga_cor, gammzz, ghflux, gradis, gswmin, gswx, gswx_t, gwbch_vec, gwdz, gwhyds_vec, gwssat_vec, gwsucs_vec, gwwatr, gwz, h0, hc, hod, hruff, hruff_grmx, hsbh, hyds, hyds_vec, i2bp3, iantrct, ibp2, ifland, isflag, isoilm, lwabv, meth, moy, mpi_get_address, mpi_reduce, mpi_type_commit, mpi_type_create_hvector, mpi_type_create_struct, mpi_type_free, mpi_type_get_extent, mpi_type_size, nsnow, oldcansto, osnowd, osnowd0, otss, otss_0, owb1, owbtot, owetfac, precip_tot, precis, decomp_types, psyc, pudsmx, pudsto, pwb_min, qasrf, qasrf_tot, qcan, qfsrf, qfsrf_tot, qsat, qscrn, qssabs, qssrf, qssrf_tot, qstss, qvair, reffbm, reffdf, refl, rghlai, rho, rhocbm, rhocdf, rhosoil, rlam, rnet, rniso, rnof1, rnof1_tot, rnof2, rnof2_tot, rnoff_tot, rp20, rpcoef, rs20, rt0us, rt1, rt1usa, rt1usb, rtsoil, runoff, s, sand, scalex, sconds, sdepth, segg, sfc, sfc_vec, sghflux, shelrb, silt, sinfil, slope, slope_std, smass, smelt, snage, snowd, snowdc_tot, snowliq, soilcol, spill, ssat, ssat_vec, ssdn, ssdnn, sucs, sucs_vec, sumpn, sumrd, sumrp, sumrpr, sumrpw, sumrs, sumxrp, sumxrs, swilt, swilt_vec, t_snwlr, taul, term2, term3, term5, term6, tevap, tggav, tggsn, thetai, through, tilefrac, tmaxvj, tminvj, totenbal, totenbal2, tprecip, trad, transb, transd, trnoff, tscrn, tsoil, tss, tss_p, tsurface, tv, tvair, tvrad, us, uscrn, usuh, vbeta, vcmax, vegcf, visc, vlaimax, volm, wai, watr, wb_lake, wbal, wbal_tot, wbal_tot1, wbfice, wbice, wblf, wbtot, wbtot0, wbtot1, wcint, wetbal, wetfac, wetfac_cs, xalbnir, xfang, z0m, z0soil, z0soilsn, za_tq, za_uv, zeta, zetar, zr, zref_tq, zref_uv, zruffs
master_casa_dump_types calls mpi_abort, cgpp, crmplant, doyphase, moist, mpi_get_address, mpi_reduce, mpi_type_commit, mpi_type_create_hvector, mpi_type_create_struct, mpi_type_get_extent, mpi_type_size, nmindep, phase, tairk, tsoil
master_casa_luc_types calls mpi_abort, clabile, clitter, cplant, csoil, fcneeyear, mpi_get_address, mpi_reduce, mpi_type_commit, mpi_type_create_hvector, mpi_type_create_struct, mpi_type_get_extent, mpi_type_size, nlitter, nplant, nsoil, nsoilmin, plitter, pplant, psoil
master_casa_params calls mpi_abort, precip, master_send_input, aphen, areacell, btran, cbalance, cgpp, clabile, clabilelast, clabloss, clitter, clitterlast, cnep, cnpp, cplant, cplantlast, crgplant, crmplant, crp, crsoil, csoil, csoillast, cwoodprod, dclabiledt, dclitterdt, dcplantdt, dcsoildt, dnlitterdt, dnplantdt, dnsoildt, dnsoilmindt, doyphase, doyphasespin_1, doyphasespin_2, doyphasespin_3, doyphasespin_4, dplitterdt, dpplantdt, dpsoildt, dpsoillabdt, dpsoiloccdt, dpsoilsorbdt, fcgppyear, fcneeyear, fcnppyear, fcrgrowyear, fcrmleafyear, fcrmrootyear, fcrmwoodyear, fcrpyear, fcrsyear, fluxctoco2, fluxctolitter, fluxctosoil, fluxntolitter, fluxntosoil, fluxptolitter, fluxptosoil, fndepyear, fnfixyear, fnleachyear, fnlossyear, fnminleach, fnminloss, fnsnetyear, fnupyear, fpdustyear, fpleach, fpleachyear, fplossyear, fpsnetyear, fpupyear, fpweayear, frac_sapwood, fraccalloc, fracclabile, fracnalloc, fracpalloc, fromltoco2, fromltos, fromptol, fromstoco2, fromstos, glai, glaimon, glaimonx, ijgcm, isorder, iveg2, klitter, kmlabp, kplab, kplant, kpocc, kpsorb, ksoil, lat, lnonwood, lon, moist, moistavg, mpi_barrier, mpi_get_address, mpi_reduce, mpi_type_commit, mpi_type_create_hvector, mpi_type_create_struct, mpi_type_free, mpi_type_get_extent, mpi_type_size, nbalance, nlitter, nlitterlast, nlittermin, nmindep, nminfix, nminleach, nminloss, nminuptake, nplant, nplantlast, nsimm, nsmin, nsnet, nsoil, nsoillast, nsoilmin, nsoilminlast, nupland, nwoodprod, pbalance, pdep, phase, phasespin, plabuptake, pleach, plitter, plitterlast, plittermin, ploss, pplant, pplantlast, psimm, psmin, psnet, psoil, psoillab, psoillablast, psoillast, psoilocc, psoilocclast, psoilsorb, psoilsorblast, psorbmax, pupland, pwea, pwoodprod, rationclitter, rationcplant, rationcsoil, rationcsoilmax, rationcsoilmin, rationcsoilnew, rationplitter, rationpplant, rationpsoil, ratiopclitter, ratiopcplant, ratiopcsoil, sapwood_area, sumcbal, sumnbal, sumpbal, tairk, tsoil, tsoilavg
master_casa_types calls mpi_abort, aphen, cgpp, clabile, clabloss, clitter, cnep, cnpp, cplant, cplant_turnover, cplant_turnover_crowding, cplant_turnover_disturbance, cplant_turnover_resource_limitation, crgplant, crmplant, crp, crsoil, csoil, ctot, ctot_0, cwoodprod, doyphase, doyphasespin_1, doyphasespin_2, doyphasespin_3, doyphasespin_4, fcgppyear, fcneeyear, fcnppyear, fcrgrowyear, fcrmleafyear, fcrmrootyear, fcrmwoodyear, fcrpyear, fcrsyear, fluxctolitter, fluxctosoil, fluxntolitter, fluxntosoil, fluxptolitter, fluxptosoil, fndepyear, fnfixyear, fnleachyear, fnlossyear, fnsnetyear, fnupyear, fpdustyear, fpleachyear, fplossyear, fpsnetyear, fpupyear, fpweayear, frac_sapwood, fraccalloc, fracclabile, fracnalloc, fracpalloc, fromltoco2, fromltos, fromptol, fromstoco2, fromstos, glai, klitter, kplant, ksoil, mpi_get_address, mpi_reduce, mpi_type_commit, mpi_type_create_hvector, mpi_type_create_struct, mpi_type_free, mpi_type_get_extent, mpi_type_size, nlitter, nlittermin, nmindep, nminfix, nminleach, nminloss, nminuptake, nplant, nsimm, nsmin, nsnet, nsoil, nsoilmin, nupland, nwoodprod, phase, phasespin, plabuptake, plitter, pplant, psoil, psoillab, psoilocc, psoilsorb, psorbmax, pwoodprod, rationclitter, rationcplant, rationcsoil, ratiopclitter, ratiopcplant, ratiopcsoil, sapwood_area, sumcbal, sumnbal, sumpbal
master_casaonly_luc calls grid, mpi_send, pop_grid, master_receive, master_receive_pop, master_send_input, pop_io, pop_luc_casa_transfer, popluc_set_patchfrac, write_casa_restart_nc, write_luc_output_grid_nc, write_luc_output_nc, write_luc_restart_nc, cgppspin, cplant, crmplantspin_1, crmplantspin_2, crmplantspin_3, doyphasespin_1, doyphasespin_2, doyphasespin_3, doyphasespin_4, frac_forest, ilu, input, iwood, moistspin_1, moistspin_2, moistspin_3, moistspin_4, moistspin_5, moistspin_6, mtempspin, phasespin, prim_only, primf, pop_init_single, popluc_weights_transfer, poplucstep, read_casa_dump, read_luh2, rationcplantmin, ratiopcplantmin, tairkspin, tsoilspin_1, tsoilspin_2, tsoilspin_3, tsoilspin_4, tsoilspin_5, tsoilspin_6
master_climate_types calls mpi_abort, mpi_waitall, aevap, agdd0, agdd5, alpha_pt, alpha_pt_20, atemp_mean, biome, chilldays, dmoist, dmoist_31, dtemp, dtemp_31, dtemp_91, evap_pt, gdd0, gdd5, mmoist, mpi_get_address, mpi_isend, mpi_reduce, mpi_type_commit, mpi_type_create_hvector, mpi_type_create_struct, mpi_type_get_extent, mpi_type_size, mtemp, mtemp_max, mtemp_max20, mtemp_max_20, mtemp_min, mtemp_min20, mtemp_min_20, climate_init, read_climate_restart_nc, qtemp, qtemp_max, qtemp_max_last_year
master_decomp calls mpi_abort, mpi_send, mpi_comm_size
master_end calls mpi_type_free
master_intypes calls fld, fsd, mpi_abort, pmb, precip, precip_sn, qv, tk, ua, year, ca, coszen, doy, hod, moy, mpi_get_address, mpi_reduce, mpi_type_commit, mpi_type_create_hvector, mpi_type_create_struct, mpi_type_get_extent, mpi_type_size, ndep, vlai
master_outtypes calls fe, fld, fsd, fvlai, fwsoil, ga, gwwb, mpi_abort, pmb, potev, precip, precip_sn, qv, tgg, tk, ua, vlaiw, wb, albedo, albsoil, albsoilsn, bch, c3, ca, canst1, cansto, cdtq, cduv, cexpkbm, cexpkdm, clay, cls, cmolar, cnsd, coszen, css, da, ddq_dtg, deciduous, delwc, delwcol, dewmm, dfe_ddq, dfe_dtg, dfh_dtg, dfn_dtg, dgdtg, dleaf, drybal, dsatdk, dtmlt, dva, ejmax, epot, epsi, evap, evapfbl, evapsn, extkb, extkbm, extkd, extkd2, extkdm, extkn, fbeam, fes, fes_cor, fesp, fess, fev, fevc, fevw, fevw_pot, fh, fhs, fhs_cor, fhv, fhvw, flws, fnee, fnpp, fns, fns_cor, fnv, fpn, frac4, frday, froot, frp, frpr, frpw, frs, fwet, fwtop, fwtop1, fwtop2, fwtop3, ga_cor, gammzz, ghflux, gradis, gswx, gswx_t, h0, hc, hsbh, hyds, i2bp3, ibp2, isflag, isoilm, lwabv, meth, mpi_get_address, mpi_reduce, mpi_type_commit, mpi_type_create_hindexed, mpi_type_create_hvector, mpi_type_create_struct, mpi_type_get_extent, mpi_type_size, nsnow, nsteps, osnowd, osnowd0, otss, otss_0, owetfac, precis, psyc, pudsmx, pudsto, pwb_min, qcan, qrecharge, qsat, qscrn, qssabs, qstss, qvair, reffbm, reffdf, refl, rghlai, rho, rhocbm, rhocdf, rhosoil, rlam, rnet, rniso, rnof1, rnof2, rp20, rpcoef, rs20, rtsoil, runoff, s, sand, satfrac, scalex, sconds, sdepth, segg, sfc, sghflux, shelrb, silt, sinfil, smass, smelt, snage, snowd, snowliq, spill, ssat, ssdn, ssdnn, sucs, swilt, t_snwlr, taul, tggav, tggsn, thetai, through, tmaxvj, tminvj, trad, transb, transd, tscrn, tsoil, tss, tsurface, tv, tvair, tvrad, us, uscrn, vbeta, vcmax, vegcf, visc, vlai, volm, wai, wb_lake, wbfice, wbice, wblf, wbtot, wbtot0, wcint, wetbal, wetfac, wetfac_cs, wtd, xalbnir, xfang, zetar
master_pop_types calls mpi_send, pop_grid, create_pop_gridcell_type
master_receive calls mpi_waitall, mpi_irecv
master_receive_pop calls pop_grid, mpi_recv
master_restart_types calls mpi_abort, cduv, cmolar, dewmm, dgdtg, dsatdk, epsi, evapfbl, fnv, frpr, frpw, mpi_get_address, mpi_reduce, mpi_type_commit, mpi_type_create_hvector, mpi_type_create_struct, mpi_type_free, mpi_type_get_extent, mpi_type_size, psyc, qsat, rho, visc, volm
master_send_input calls mpi_waitall, mpi_isend
master_spincasacnp calls master_receive, master_receive_pop, master_send_input, pop_io, write_casa_restart_nc, cgppspin, crmplantspin_1, crmplantspin_2, crmplantspin_3, doyphasespin_1, doyphasespin_2, doyphasespin_3, doyphasespin_4, moistspin_1, moistspin_2, moistspin_3, moistspin_4, moistspin_5, moistspin_6, mtempspin, phasespin, casa_poolout, read_casa_dump, tairkspin, tsoilspin_1, tsoilspin_2, tsoilspin_3, tsoilspin_4, tsoilspin_5, tsoilspin_6
open_met_file calls is_leapyear, co2air, elev, lwdown, nf90_get_att, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_inquire_variable, nf90_open, doysod2ymdhms, find_metvarid, handle_err, nc_abort, ymdhms2doysod, psurf, qair, rainf, swdown, tair, wind
open_output_file calls fwsoil, albedo, area, autoresp, averaging, baresoilt, canopint, cant, co2air, dcdt, ebal, ecanop, esoil, evap, gpp, gwmoist, heteroresp, hsoil, hveg, define_ovar, write_ovar, lai, landuseflux, leafresp, littcarbcwd, littcarbmetabolic, littcarbstructural, lwdown, lwnet, nbp, nee, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_put_att, nf90_put_var, nf90_redef, niralbedo, npp, plantcarbfineroot, plantcarbleaf, plantcarbwood, plantturnover, plantturnoverfineroot, plantturnoverleaf, plantturnoverwood, plantturnoverwoodcrowding, plantturnoverwooddist, plantturnoverwoodresourcelim, nc_abort, psurf, qair, qg, qh, qle, qmom, qrecharge, qs, qsb, qscrn, radt, rainf, rnet, rnetsoil, rootresp, satfrac, snowdepth, snowf, snowmelt, snowt, soilcarbfast, soilcarbpassive, soilcarbslow, soilmoist, soilmoistice, soiltemp, stemresp, swdown, swe, swnet, tair, tdaymn, tdaymx, tmn, tmx, tnn, totlittcarb, totlivbiomass, totsoilcarb, tscrn, tveg, txx, vegt, visalbedo, wattable, wbal, wind
plume_mip_get_met calls precip, avg_lwdn, coszen, doy, f_id, hod, metfile, nf90_close, phild, phisd, doysod2ymdhms, file_switch, get_plume_co2, handle_err, open_plume_met, plume_get_daily_met, wgen_daily_constants, wgen_init, wgen_subdiurnal_met, temp
plume_mip_init calls avg_lwdn, met, nf90_close, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_open, get_unit, handle_err
pop_io calls pop_grid, lat, lon, nf90_close, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_open, nf90_put_att, nf90_put_var, nf90_redef, handle_err
pop_luc_casa_transfer calls pop_grid, 1166, clabile, clearprod, clearprodloss, clitter, cplant, csoil, ctransferluc, fclearance, fcneeyear, fharvest, fracclearprod, fracclearresid, fracharvprod, fracharvresid, fracharvsecresid, grass, harvprod, harvprodloss, iwood, nlitter, nplant, nsoil, nsoilmin, plitter, pplant, prim_only, psoil, smharv, syharv
popluc_set_patchfrac calls grass, prim_only, primf
preparefiles calls renamefiles
write_casa_dump calls doyphase, nf90_close, nf90_create, nf90_enddef, def_dims, def_vars, put_var_ncr1, put_var_ncr2, put_var_ncr3, stderr_nc
write_casa_output_nc calls fcrgrowyear, fcrmleafyear, fcrmrootyear, fcrmwoodyear, nf90_close, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_inq_dimid, nf90_inq_varid, nf90_open, nf90_put_att, nf90_put_var, nf90_redef, handle_err
write_casa_restart_nc calls doyphase, nf90_close, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_put_att, nf90_put_var, nf90_redef, handle_err
write_climate_restart_nc calls nf90_close, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_put_att, nf90_put_var, nf90_redef, handle_err
write_landuse_casa_restart_nc calls nf90_close, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_put_att, nf90_put_var, nf90_redef, handle_err
write_luc_output_grid_nc calls cbiomass, clearprod, clearprodloss, clitt, csoil, fclearance, fharvest, fnep, ftransfergross, ftransfernet, harvprod, harvprodloss, nf90_close, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_put_att, nf90_put_var, nf90_redef, handle_err
write_luc_output_nc calls nf90_close, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_put_att, nf90_put_var, nf90_redef, handle_err
write_luc_restart_nc calls nf90_close, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_put_att, nf90_put_var, nf90_redef, handle_err
write_output calls fsd, is_leapyear, tgg, year, albedo, averaging, clitter, cplant, cplant_turnover, crmplant, csoil, write_ovar, nf90_put_var, nf90_sync, energy_balance, mass_balance, nc_abort, qcan, tdaymn, tdaymx, tggsn, tnn, tscrn, txx
define_ovar calls define_output_parameter_r1, define_output_parameter_r2, define_output_variable_r1, define_output_variable_r2
write_ovar calls write_output_parameter_r1, write_output_parameter_r1d, write_output_parameter_r2, write_output_parameter_r2d, write_output_variable_r1, write_output_variable_r2
alloc_canopy_type calls sublayer_dz
alloc_casavariable calls precip, areacell, btran, cbalance, cgpp, cgppspin, clabile, clabilelast, clabloss, clitter, clitterlast, cnep, cnpp, cplant, cplant_turnover, cplant_turnover_crowding, cplant_turnover_disturbance, cplant_turnover_resource_limitation, cplantlast, crgplant, crmplant, crmplantspin_1, crmplantspin_2, crmplantspin_3, crp, crsoil, csoil, csoillast, ctot, ctot_0, ctransferluc, cwoodprod, dclabiledt, dclitterdt, dcplantdt, dcsoildt, dnlitterdt, dnplantdt, dnsoildt, dnsoilmindt, dplitterdt, dpplantdt, dpsoildt, dpsoillabdt, dpsoiloccdt, dpsoilsorbdt, fcgppyear, fcneeyear, fcnppyear, fcrgrowyear, fcrmleafyear, fcrmrootyear, fcrmwoodyear, fcrpyear, fcrsyear, fluxctoco2, fluxctolitter, fluxctosoil, fluxntolitter, fluxntosoil, fluxptolitter, fluxptosoil, fndepyear, fnfixyear, fnleachyear, fnlossyear, fnminleach, fnminloss, fnsnetyear, fnupyear, fpdustyear, fpleach, fpleachyear, fplossyear, fpsnetyear, fpupyear, fpweayear, frac_sapwood, fraccalloc, fracclabile, fracnalloc, fracpalloc, fromltoco2, fromltos, fromptol, fromstoco2, fromstos, glai, glaimon, glaimonx, ijgcm, isorder, iveg2, klitter, kmlabp, kplab, kplant, kpocc, kpsorb, ksoil, lat, lnonwood, lon, moist, moistavg, moistspin_1, moistspin_2, moistspin_3, moistspin_4, moistspin_5, moistspin_6, mtempspin, nbalance, nlitter, nlitterlast, nlittermin, nmindep, nminfix, nminleach, nminloss, nminuptake, nplant, nplantlast, nsimm, nsmin, nsnet, nsoil, nsoillast, nsoilmin, nsoilminlast, nupland, nwoodprod, pbalance, pdep, plabuptake, pleach, plitter, plitterlast, plittermin, ploss, pplant, pplantlast, psimm, psmin, psnet, psoil, psoillab, psoillablast, psoillast, psoilocc, psoilocclast, psoilsorb, psoilsorblast, psorbmax, pupland, pwea, pwoodprod, rationclitter, rationcplant, rationcplantmin, rationcsoil, rationcsoilmax, rationcsoilmin, rationcsoilnew, rationplitter, rationpplant, rationpsoil, ratiopclitter, ratiopcplant, ratiopcplantmin, ratiopcsoil, sapwood_area, sla, sumcbal, sumnbal, sumpbal, tairk, tairkspin, tsoil, tsoilavg, tsoilspin_1, tsoilspin_2, tsoilspin_3, tsoilspin_4, tsoilspin_5, tsoilspin_6, cleafmean, costnpup, crootmean, dcdtyear, fluxctoclear, fluxctohwp, fluxntoclear, fluxntohwp, fluxptoclear, fluxptohwp, fraclabile, fraclignin, fracligninplant, fracnpptop, ftransnptol, ftranspptol, glaimax, glaimin, ivt2, kclabrate, kminn, kroot, krootlen, kuplabp, kuptake, laimax, litterrate, maxcwd, maxfinelitter, meangpp, meanrleaf, nintercept, nslope, plantrate, prodptase, q10soil, ratiofrootleaf, rationcplantmax, rationpplantmax, rationpplantmin, ratiopcplantmax, rmplant, rootdepth, soilrate, stemnpp, xkleafcoldexp, xkleafcoldmax, xkleafdryexp, xkleafdrymax, xkoptlitter, xkoptsoil, xkplab, xkpocc, xkpsorb, xnpmax
alloc_phenvariable calls aphen, doyphase, doyphasespin_1, doyphasespin_2, doyphasespin_3, doyphasespin_4, phase, phasespin, tkshed
alloc_soil_parameter_type calls bch_vec, elev, gwbch_vec, gwdz, gwhyds_vec, gwssat_vec, gwsucs_vec, gwwatr, gwz, hyds_vec, sfc_vec, slope, slope_std, ssat_vec, sucs_vec, swilt_vec, watr, clay_vec, drain_dens, elev_std, gwrhosoil_vec, org_vec, rhosoil_vec, sand_vec, silt_vec
alloc_soil_snow_type calls gwwb, evapfbl, fland, ifland, otss, otss_0, owetfac, qasrf, qfsrf, qrecharge, qssrf, qstss, satfrac, sinfil, t_snwlr, tevap, tggav, tilefrac, totenbal, totenbal2, tprecip, trnoff, wb_lake, wbfice, wbtot, wbtot1, wetfac, wtd, dhkdw, dsmpdw, fracice, gwdhkdw, gwdsmpdw, gwhk, gwsmp, gwwbeq, gwzq, hk, icefrac, otgg, qhlev, qhz, rh_srf, rt_qh_sublayer, rtevap_sat, rtevap_unsat, smp, totwblake, wbeq, wbliq, wbtot2, wmice, wmliq, wmtot, zq
alloc_sum_casavariable calls cgpp, clabile, clabloss, clitter, cnep, cnpp, cplant, cplant_turnover, cplant_turnover_crowding, cplant_turnover_disturbance, cplant_turnover_resource_limitation, crgplant, crmplant, crp, crsoil, csoil, dclabiledt, dclitterdt, dcplantdt, dcsoildt, dnlitterdt, dnplantdt, dnsoildt, dnsoilmindt, dplitterdt, dpplantdt, dpsoildt, dpsoillabdt, dpsoiloccdt, dpsoilsorbdt, fluxctoco2, fluxctolitter, fluxctosoil, fluxntolitter, fluxntosoil, fluxptolitter, fluxptosoil, fnminleach, fnminloss, fpleach, frac_sapwood, fraccalloc, fracclabile, fracnalloc, fracpalloc, fromltoco2, fromltos, fromptol, fromstoco2, fromstos, klitter, kmlabp, kplab, kplant, kpocc, kpsorb, ksoil, nlitter, nlittermin, nmindep, nminfix, nminleach, nminloss, nminuptake, nplant, nsimm, nsmin, nsnet, nsoil, nsoilmin, nupland, pdep, plabuptake, pleach, plitter, plittermin, ploss, pplant, psimm, psmin, psnet, psoil, psoillab, psoilocc, psoilsorb, psorbmax, pupland, pwea, rationclitter, rationcplant, rationcsoil, rationcsoilmax, rationcsoilmin, rationcsoilnew, rationplitter, rationpplant, rationpsoil, ratiopclitter, ratiopcplant, ratiopcsoil, sapwood_area, stemnpp
alloc_veg_parameter_type calls a1gs, alpha, cfrd, conkc0, conko0, convex, d0gs, deciduous, ekc, eko, extkn, froot, gswmin, refl, taul, vlaimax, wai
allocate_cable_vars calls alloc_cbm_var
casa_init calls 100, 5, rationcplant, rationcsoil, rationpsoil, 2, read_casa_restart_nc
casa_poolout calls 100, 5, aphen, areacell, doyphase, frac_sapwood, glai, isoilm, isorder, iveg, iveg2, kmlabp, lat, lon, phase, psorbmax, rationclitter, rationcplant, rationcsoil, rationplitter, rationpplant, rationpsoil, sapwood_area, sla, sumcbal, sumnbal, sumpbal, 2
casa_readbiome calls clitter, cplant, csoil, isorder, iveg, iveg2, kmlabp, nlitter, psoillab, psorbmax, rationclitter, rationcplant, rationcplantmin, rationcsoil, rationcsoilmax, ratiopclitter, ratiopcplant, ratiopcplantmin, ratiopcsoil, sla, fracligninplant, fracnpptop, ftransnptol, ftranspptol, glaimax, glaimin, ivt2, kminn, kroot, krootlen, kuplabp, kuptake, rationcplantmax, rationpplantmin, rmplant, rootdepth, tkshed, xkleafcoldexp, xkleafdryexp, zse
casa_readphen calls doyphase, iveg, lat
check_parameter_values calls clay, froot, isoilm, iveg, sand, sfc, silt, ssat, swilt
climate_init calls alloc_cbm_var, read_climate_restart_nc
create_pop_gridcell_type calls mpi_abort, mpi_get_address, mpi_type_commit, mpi_type_create_struct, mpi_type_create_resized, create_patch
cru_get_daily_met calls f_id, met, metfile, nf90_close, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_open, handle_err, v_id, var_name, cru_get_filename
decomp_types calls mpi_get_address, mpi_type_commit, mpi_type_create_struct, mpi_type_create_resized
def_dims calls nf90_def_dim, stderr_nc
def_vars calls nf90_def_var, stderr_nc
derived_parameters calls wb, bch_vec, hyds_vec, iveg, sfc, sfc_vec, slope, slope_std, ssat_vec, sucs_vec, swilt, swilt_vec, watr, wbice, clay_vec, org_vec, sand_vec, zse
doysod2ymdhms calls is_leapyear
energy_balance calls fsd, albedo, qcan
find_metvarid calls nf90_inq_varid
get_cru_co2 calls get_unit, co2vals
get_cru_ndep calls nf90_get_var, nf90_inq_varid, nf90_open, handle_err
get_default_params calls cable_pft_params, cable_soil_params, countpatch, get_land_index, luc_expt_set_tiles, read_gridinfo, read_soilcolor, spatialsoil
get_parameters_met calls nf90_inq_varid, readpar
get_plume_co2 calls get_unit, co2vals
get_restart_data calls nf90_close, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nc_abort, readpar, extrarestart
handle_err calls nf90_strerror
landuse_allocate_mland calls patchfrac_y, albedo_x, albedo_y, albsoil_x, albsoil_y, albsoilsn_x, albsoilsn_y, aphen_x, aphen_y, atransit, cansto_x, cansto_y, clabile_x, clabile_y, clitter_x, clitter_y, cplant_x, cplant_y, cplantx_x, cplantx_y, csoil_x, csoil_y, csoilx_x, csoilx_y, cwoodprod_x, cwoodprod_y, dgdtg_x, dgdtg_y, doyphase3_x, doyphase3_y, fes_x, fes_y, fev_x, fev_y, fharvw, fhs_x, fhs_y, frac_sapwood_x, frac_sapwood_y, ga_x, ga_y, gammzz_x, gammzz_y, ghflux_x, ghflux_y, gwwb_x, gwwb_y, isflag_x, isflag_y, isoil_x, isoil_y, iveg_x, iveg_y, lai_x, lai_y, nlitter_x, nlitter_y, nplant_x, nplant_y, nsoil_x, nsoil_y, nsoilmin_x, nsoilmin_y, nwoodprod_x, nwoodprod_y, osnowd0_x, osnowd0_y, osnowd_x, osnowd_y, patchfrac_x, pftfrac, phase_x, phase_y, phen_x, phen_y, plitter_x, plitter_y, pplant_x, pplant_y, psoil_x, psoil_y, psoillab_x, psoillab_y, psoilocc_x, psoilocc_y, psoilsorb_x, psoilsorb_y, pwoodprod_x, pwoodprod_y, rnof1_x, rnof1_y, rnof2_x, rnof2_y, rtsoil_x, rtsoil_y, runoff_x, runoff_y, sapwood_area_x, sapwood_area_y, sdepth_x, sdepth_y, sghflux_x, sghflux_y, sla_x, sla_y, smass_x, smass_y, snage_x, snage_y, snowd_x, snowd_y, soilorder_x, soilorder_y, ssdn_x, ssdn_y, ssdnn_x, ssdnn_y, tgg_x, tgg_y, tggsn_x, tggsn_y, trad_x, trad_y, tss_x, tss_y, wb_x, wb_y, wbice_x, wbice_y, wbtot0_x, wbtot0_y, xluh2cable
landuse_allocate_mp calls ga, gwwb, patchfrac, tgg, wb, albedo, albsoil, albsoilsn, aphen, areacell, cansto, clabile, clitter, cplant, csoil, cwoodprod, dgdtg, fes, fev, fhs, frac_sapwood, gammzz, ghflux, isflag, iveg, lai, lat, lon, nlitter, nplant, nsoil, nsoilmin, nwoodprod, osnowd, osnowd0, phase, plitter, pplant, psoil, psoillab, psoilocc, psoilsorb, pwoodprod, rnof1, rnof2, rtsoil, runoff, sapwood_area, sdepth, sghflux, sla, smass, snage, snowd, ssdn, ssdnn, sumcbal, sumnbal, sumpbal, tggsn, trad, tss, wbice, wbtot0, cplantx, csoilx, doyphase3, isoil, phen, soilorder
landuse_checks calls patchfrac_y, 20, clabile_y, clitter_y, cplant_y, csoil_y, cwoodprod_y, nlitter_y, nplant_y, nsoil_y, nsoilmin_y, nwoodprod_y, plitter_y, pplant_y, psoil_y, psoillab_y, psoilocc_y, psoilsorb_y, pwoodprod_y
landuse_getdata calls nf90_close, nf90_get_var, nf90_inq_varid, nf90_open
landuse_getxluh2 calls nf90_close, nf90_get_var, nf90_inq_varid, nf90_open
landuse_land2mpx calls patchfrac_y, albedo_y, albsoil_y, albsoilsn_y, aphen_y, cansto_y, clabile_y, clitter_y, cplant_y, cplantx_y, csoil_y, csoilx_y, cwoodprod_y, dgdtg_y, doyphase3_y, fes_y, fev_y, fhs_y, frac_sapwood_y, ga_y, gammzz_y, ghflux_y, gwwb_y, isflag_y, isoil_y, lai_y, nlitter_y, nplant_y, nsoil_y, nsoilmin_y, nwoodprod_y, osnowd0_y, osnowd_y, patchfrac_x, phase_y, phen_y, plitter_y, pplant_y, psoil_y, psoillab_y, psoilocc_y, psoilsorb_y, pwoodprod_y, rnof1_y, rnof2_y, rtsoil_y, runoff_y, sapwood_area_y, sdepth_y, sghflux_y, sla_y, smass_y, snage_y, snowd_y, soilorder_y, ssdn_y, ssdnn_y, tgg_y, tggsn_y, trad_y, tss_y, wb_y, wbice_y, wbtot0_y
landuse_mp2land calls ga, gwwb, patchfrac, tgg, wb, albedo, albsoil, albsoilsn, aphen, cansto, clabile, clitter, cplant, csoil, cwoodprod, dgdtg, fes, fev, fhs, frac_sapwood, gammzz, ghflux, isflag, iveg, lai, nlitter, nplant, nsoil, nsoilmin, nwoodprod, osnowd, osnowd0, phase, plitter, pplant, psoil, psoillab, psoilocc, psoilsorb, pwoodprod, rnof1, rnof2, rtsoil, runoff, sapwood_area, sdepth, sghflux, sla, smass, snage, snowd, ssdn, ssdnn, tggsn, trad, tss, wbice, wbtot0, cplantx, csoilx, doyphase3, isoil, phen, soilorder
landuse_transitx calls patchfrac_y, albedo_x, albsoil_x, albsoilsn_x, aphen_x, atransit, cansto_x, clabile_x, clitter_x, cplant_x, cplant_y, cplantx_x, csoil_x, csoilx_x, cwoodprod_x, dgdtg_x, doyphase3_x, doyphase3_y, fes_x, fev_x, fharvw, fhs_x, frac_sapwood_x, fracligninplant, ftransnptol, ga_x, gammzz_x, ghflux_x, gwwb_x, isoil_x, isoil_y, nlitter_x, nplant_x, nplant_y, nsoil_x, nsoilmin_x, nwoodprod_x, osnowd0_x, osnowd_x, patchfrac_x, phase_x, phase_y, phen_x, plitter_x, pplant_x, landuse_redistribution, psoil_x, psoillab_x, psoilocc_x, psoilsorb_x, pwoodprod_x, rationcplantmax, rationpplantmin, rnof1_x, rnof2_x, rtsoil_x, runoff_x, sapwood_area_x, sdepth_x, sghflux_x, sla_x, sla_y, smass_x, smass_y, snage_x, snowd_x, soilorder_x, soilorder_y, ssdn_x, ssdnn_x, tgg_x, tggsn_x, trad_x, tss_x, wb_x, wbice_x, wbtot0_x, xluh2cable
nc_abort calls nf90_strerror
open_cru_met calls f_id, metfile, nf90_inq_varid, nf90_open, handle_err, v_id, var_name, cru_get_filename
open_plume_met calls f_id, metfile, nf90_get_att, nf90_inq_varid, nf90_open, handle_err, v_id, var_name, leap_day, plume_get_filename
plume_get_daily_met calls f_id, met, metfile, nf90_close, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_open, handle_err, v_id, var_name, plume_get_filename
pop_init calls alloc_pop, initpop2d_poisson, layer_recruitment_single_patch, zeropop
pop_init_single calls initpop2d_poisson, layer_recruitment_single_patch, zeropop
popluc_init calls cplant, iwood, prim_only, pop_init_single, rationcplantmin, ratiopcplantmin, alloc_popluc, popluc_set_params, read_luc_restart_nc, zeropopluc
popluc_weights_transfer calls iwood, prim_only, freq_age_secondary
poplucstep calls primf, freq_age_secondary, gtop, gtos, execute_luc_event, increment_age, ptog, ptos, stog
put_var_ncr1 calls nf90_inq_varid, nf90_put_var, stderr_nc
put_var_ncr2 calls nf90_inq_varid, nf90_put_var, stderr_nc
put_var_ncr3 calls nf90_inq_varid, nf90_put_var, stderr_nc
read_casa_dump calls nf90_close, nf90_open, stderr_nc, get_var_ncr2, get_var_ncr3
read_climate_restart_nc calls nf90_close, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_open, handle_err
read_climatefile calls nf90_close, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_open, handle_err
read_luh2 calls f_id, input, nf90_get_var, handle_err, transfile, v_id
report_parameters calls tgg, wb, a1gs, albsoil, albsoilsn, areacell, bch, canst1, cansto, clabile, clay, clitter, cplant, csoil, css, d0gs, dleaf, ejmax, frac4, froot, glai, hc, hyds, isflag, isoilm, isorder, iveg, iveg2, nlitter, nmindep, nminfix, nplant, nsoil, nsoilmin, osnowd, pdep, phase, plitter, pplant, psoil, psoillab, psoilocc, psoilsorb, pwea, rhosoil, rnof1, rnof2, rp20, rpcoef, rs20, rtsoil, runoff, sand, sfc, shelrb, silt, smass, snage, snowd, ssat, ssdn, ssdnn, sucs, swilt, tggsn, tmaxvj, tminvj, vbeta, vcmax, wbice, xalbnir, xfang, za_tq, za_uv, cable_pft_params, cable_soil_params, ratecp, ratecs
rh_sh calls svp
stderr_nc calls nf90_strerror
wgen_init calls pmb, precip, coszen, phild, phisd, temp, wind, daylength, latdeg, latrad, pmbday, precipday, snow, snowday, solarmjday, solarnorm, tempmaxday, tempmaxdayprev, tempminday, tempmindaynext, tempnightrate, tempnightrateprev, temprangeaft, temprangeday, tempsunset, tempsunsetprev, timemaxtemp, timesunrise, timesunset, timesunsetprev, vappmb, winddark, windday, windlite
write_cnp_params calls iveg, nmindep, pdep
write_default_params calls tgg, wb, bch, clay, css, hyds, isoilm, iveg, rhosoil, sand, sfc, silt, snowd, ssat, sucs, swilt, vcmax, watr, cplant1, cplant2, cplant3, csoil1, csoil2, init_veg_from_vegin, ratecp1, ratecp2, ratecp3, ratecs1, ratecs2
ymdhms2doysod calls is_leapyear
readpar calls readpar_i, readpar_r, readpar_r2, readpar_r2d, readpar_rd
alloc_pop calls pop_grid, iwood, it_pop
alloc_popluc calls cbiomass, clearprod, clearprodloss, clitt, csoil, fclearance, fharvest, fnep, frac_forest, frac_primf, fracclearprod, fracclearresid, fracharvprod, fracharvresid, fracharvsecresid, ftransfergross, ftransfernet, grass, harvprod, harvprodloss, primf, secdf, smharv, syharv, freq_age_secondary, gtop, age_history_secdf, area_history_secdf, biomass_age_primary, biomass_age_secondary, freq_age_primary, latitude, longitude, pharv
create_patch calls mpi_abort, mpi_get_address, mpi_type_commit, mpi_type_create_struct, mpi_type_create_resized, create_layer
define_output_parameter_r1 calls grid, nf90_def_var, nf90_put_att, nc_abort
define_output_parameter_r2 calls grid, nf90_def_var, nf90_put_att, nc_abort
define_output_variable_r1 calls grid, nf90_def_var, nf90_put_att, nc_abort
define_output_variable_r2 calls grid, nf90_def_var, nf90_put_att, nc_abort
execute_luc_event calls frac_forest, primf, freq_age_secondary, ptog, ptos, stog, n_event
extrarestart calls nf90_get_var, nf90_inq_varid, nc_abort, readpar, redistr_i, redistr_r, redistr_r2, redistr_r2d, redistr_rd
get_var_ncr2 calls nf90_get_var, nf90_inq_varid, stderr_nc
get_var_ncr3 calls nf90_get_var, nf90_inq_varid, stderr_nc
increment_age calls smharv, syharv, freq_age_secondary
init_veg_from_vegin calls a1gs, alpha, canst1, cfrd, clitt, conkc0, conko0, convex, d0gs, dleaf, ejmax, ekc, eko, extkn, frac4, froot, g0, g1, gswmin, hc, iveg, rp20, rpcoef, rs20, shelrb, tmaxvj, tminvj, vbeta, vcmax, vegcf, wai, xalbnir, xfang, zr, refl1, refl2, rootbeta, taul1, taul2
initpop2d_poisson calls pop_grid, cumexponential, exponential
layer_recruitment_single_patch calls pop_grid, get_allometry
leap_day calls is_leapyear
luc_expt_set_tiles calls 1166, grass, ivegp, mtemp_min20, prim_only, primaryf, secdf
popluc_set_params calls biome, fracharvresid, fracharvsecresid, ivegp
read_casa_restart_nc calls nf90_close, nf90_get_att, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_open, handle_err
read_gridinfo calls nf90_close, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_open, nc_abort
read_luc_restart_nc calls nf90_close, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_open, handle_err, 1000
read_soilcolor calls nf90_close, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_open, nc_abort
spatialsoil calls nf90_close, nf90_get_var, nf90_inq_varid, nf90_open, nc_abort
write_output_parameter_r1 calls grid, nf90_put_var, nc_abort
write_output_parameter_r1d calls nf90_put_var, nc_abort
write_output_parameter_r2 calls grid, nf90_put_var, nc_abort
write_output_parameter_r2d calls nf90_put_var, nc_abort
write_output_variable_r1 calls grid, nf90_put_var, nc_abort, range_abort
write_output_variable_r2 calls grid, nf90_put_var, nc_abort, range_abort
create_layer calls mpi_abort, mpi_get_address, mpi_type_commit, mpi_type_create_struct, mpi_type_create_resized, create_cohort
get_allometry calls allometry, getheight, williams_allometry
range_abort calls year, doy, hod
readpar_i calls nf90_get_var, nf90_inq_varid, nf90_inquire_variable, nc_abort
readpar_r calls nf90_get_var, nf90_inq_varid, nf90_inquire_variable, nc_abort
readpar_r2 calls nf90_get_var, nf90_inq_varid, nf90_inquire_variable, nc_abort
readpar_r2d calls nf90_get_var, nf90_inq_varid, nf90_inquire_variable, nc_abort
readpar_rd calls nf90_get_var, nf90_inq_varid, nf90_inquire_variable, nc_abort
redistr_r calls float
redistr_r2 calls float
redistr_r2d calls float
redistr_rd calls float
create_cohort calls mpi_abort, mpi_get_address, mpi_type_commit, mpi_type_create_struct, mpi_type_create_resized
mpi_driver calls mpidrv_master