nc_abort – CABLE
nc_abort Subroutine
8 statements
Source File
public subroutine nc_abort(ok, message)
Uses
netcdf
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ok
character(len=*), intent(in) :: message
Calls
Called by
Contents
Call graph
nc_abort calls nf90_strerror
close_met_file calls nc_abort
close_output_file calls nc_abort
create_landuse_cable_restart calls nc_abort, define_ovar, write_ovar
create_new_gridinfo calls nc_abort
create_restart calls nc_abort, define_ovar, write_ovar
define_output_parameter_r1 calls nc_abort
define_output_parameter_r2 calls nc_abort
define_output_variable_r1 calls nc_abort
define_output_variable_r2 calls nc_abort
extrarestart calls nc_abort, readpar
get_default_lai calls nc_abort
get_met_data calls nc_abort
get_restart_data calls nc_abort, extrarestart, readpar
landuse_data calls nc_abort
load_parameters calls nc_abort, get_restart_data, get_default_params, get_parameters_met
open_met_file calls nc_abort
open_output_file calls nc_abort, define_ovar, write_ovar
read_gridinfo calls nc_abort
read_soilcolor calls nc_abort
readpar_i calls nc_abort
readpar_r calls nc_abort
readpar_r2 calls nc_abort
readpar_r2d calls nc_abort
readpar_rd calls nc_abort
spatialsoil calls nc_abort
write_output calls nc_abort, write_ovar
write_output_parameter_r1 calls nc_abort
write_output_parameter_r1d calls nc_abort
write_output_parameter_r2 calls nc_abort
write_output_parameter_r2d calls nc_abort
write_output_variable_r1 calls nc_abort
write_output_variable_r2 calls nc_abort
define_ovar calls define_output_parameter_r1, define_output_parameter_r2, define_output_variable_r1, define_output_variable_r2
readpar calls readpar_i, readpar_r, readpar_r2, readpar_r2d, readpar_rd
write_ovar calls write_output_parameter_r1, write_output_parameter_r1d, write_output_parameter_r2, write_output_parameter_r2d, write_output_variable_r1, write_output_variable_r2
get_default_params calls read_gridinfo, read_soilcolor, spatialsoil
mpidrv_master calls close_met_file, close_output_file, create_landuse_cable_restart, create_new_gridinfo, create_restart, get_met_data, landuse_data, load_parameters, open_met_file, open_output_file, write_output
cable_offline_driver calls close_met_file, close_output_file, create_landuse_cable_restart, create_new_gridinfo, create_restart, get_met_data, landuse_data, load_parameters, open_met_file, open_output_file, write_output
get_parameters_met calls readpar
mpi_driver calls mpidrv_master