open_output_file – CABLE
open_output_file Subroutine
610 statements
Source File
public subroutine open_output_file(dels, soil, veg, bgc, rough)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: dels
type(soil_parameter_type), intent(in) :: soil
type(veg_parameter_type), intent(in) :: veg
type(bgc_pool_type), intent(in) :: bgc
type(roughness_type), intent(in) :: rough
Calls
Called by
Contents
Call graph
open_output_file calls albedo, area, autoresp, averaging, baresoilt, canopint, cant, co2air, dcdt, ebal, ecanop, esoil, evap, fwsoil, gpp, gwmoist, heteroresp, hsoil, hveg, define_ovar, write_ovar, lai, landuseflux, leafresp, littcarbcwd, littcarbmetabolic, littcarbstructural, lwdown, lwnet, nbp, nee, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_put_att, nf90_put_var, nf90_redef, niralbedo, npp, plantcarbfineroot, plantcarbleaf, plantcarbwood, plantturnover, plantturnoverfineroot, plantturnoverleaf, plantturnoverwood, plantturnoverwoodcrowding, plantturnoverwooddist, plantturnoverwoodresourcelim, nc_abort, psurf, qair, qg, qh, qle, qmom, qrecharge, qs, qsb, qscrn, radt, rainf, rnet, rnetsoil, rootresp, satfrac, snowdepth, snowf, snowmelt, snowt, soilcarbfast, soilcarbpassive, soilcarbslow, soilmoist, soilmoistice, soiltemp, stemresp, swdown, swe, swnet, tair, tdaymn, tdaymx, tmn, tmx, tnn, totlittcarb, totlivbiomass, totsoilcarb, tscrn, tveg, txx, vegt, visalbedo, wattable, wbal, wind
define_ovar calls define_output_parameter_r1, define_output_parameter_r2, define_output_variable_r1, define_output_variable_r2
write_ovar calls write_output_parameter_r1, write_output_parameter_r1d, write_output_parameter_r2, write_output_parameter_r2d, write_output_variable_r1, write_output_variable_r2
nc_abort calls nf90_strerror
define_output_parameter_r1 calls nf90_def_var, nf90_put_att, nc_abort, grid
define_output_parameter_r2 calls nf90_def_var, nf90_put_att, nc_abort, grid
define_output_variable_r1 calls nf90_def_var, nf90_put_att, nc_abort, grid
define_output_variable_r2 calls nf90_def_var, nf90_put_att, nc_abort, grid
write_output_parameter_r1 calls nf90_put_var, nc_abort, grid
write_output_parameter_r1d calls nf90_put_var, nc_abort
write_output_parameter_r2 calls nf90_put_var, nc_abort, grid
write_output_parameter_r2d calls nf90_put_var, nc_abort
write_output_variable_r1 calls nf90_put_var, nc_abort, grid, range_abort
write_output_variable_r2 calls nf90_put_var, nc_abort, grid, range_abort
range_abort calls doy, hod, year
mpidrv_master calls open_output_file
cable_offline_driver calls open_output_file
mpi_driver calls mpidrv_master