open_met_file – CABLE
open_met_file Subroutine
738 statements
Source File
public subroutine open_met_file(dels, koffset, kend, spinup, TFRZ)
Uses
casa_ncdf_module
cable_common_module
CABLE_METUTILS_MODULE
Arguments
Type Intent Optional Attributes Name
real, intent(out) :: dels
integer, intent(inout) :: koffset
integer, intent(out) :: kend
logical, intent(in) :: spinup
real, intent(in) :: TFRZ
Calls
Called by
Contents
Call graph
open_met_file calls co2air, elev, lwdown, nf90_get_att, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_inquire_variable, nf90_open, doysod2ymdhms, find_metvarid, handle_err, is_leapyear, nc_abort, ymdhms2doysod, psurf, qair, rainf, swdown, tair, wind
doysod2ymdhms calls is_leapyear
find_metvarid calls nf90_inq_varid
handle_err calls nf90_strerror
nc_abort calls nf90_strerror
ymdhms2doysod calls is_leapyear
mpidrv_master calls open_met_file
cable_offline_driver calls open_met_file
mpi_driver calls mpidrv_master