OPEN_CRU_MET – CABLE
OPEN_CRU_MET Subroutine
58 statements
Source File
public subroutine OPEN_CRU_MET(CRU)
Uses
cable_IO_vars_module
Arguments
Type Intent Optional Attributes Name
type(CRU_TYPE), intent(inout) :: CRU
Calls
Called by
Contents
Call graph
open_cru_met calls f_id, metfile, nf90_inq_varid, nf90_open, cru_get_filename, handle_err, v_id, var_name
handle_err calls nf90_strerror
cru_get_subdiurnal_met calls open_cru_met
mpidrv_master calls cru_get_subdiurnal_met
cable_offline_driver calls cru_get_subdiurnal_met
mpi_driver calls mpidrv_master