OPEN_PLUME_MET – CABLE
OPEN_PLUME_MET Subroutine
35 statements
Source File
public subroutine OPEN_PLUME_MET(PLUME)
Uses
cable_IO_vars_module
Arguments
Type Intent Optional Attributes Name
type(PLUME_MIP_TYPE) :: PLUME
Calls
Called by
Contents
Call graph
open_plume_met calls f_id, metfile, nf90_get_att, nf90_inq_varid, nf90_open, handle_err, leap_day, plume_get_filename, v_id, var_name
handle_err calls nf90_strerror
leap_day calls is_leapyear
plume_mip_get_met calls open_plume_met
mpidrv_master calls plume_mip_get_met
cable_offline_driver calls plume_mip_get_met
mpi_driver calls mpidrv_master