or_soil_evap_resistance – CABLE
or_soil_evap_resistance Subroutine
70 statements
Source File
public subroutine or_soil_evap_resistance(soil, air, met, canopy, ssnow, veg, rough)
Arguments
Type Intent Optional Attributes Name
type(soil_parameter_type), intent(inout) :: soil
type(air_type), intent(inout) :: air
type(met_type), intent(inout) :: met
type(canopy_type), intent(inout) :: canopy
type(soil_snow_type), intent(inout) :: ssnow
type(veg_parameter_type), intent(inout) :: veg
type(roughness_type), intent(inout) :: rough
Calls
Contents
Call graph
or_soil_evap_resistance calls bch_vec, coexp, hruff, hyds_vec, isflag, iveg, my_gamma, rtevap_sat, rtsoil, satfrac, snowd, ssat_vec, sucs_vec, tk, us, visc, watr, wb, wbice, z0soil
my_gamma calls my_gamma