Patch_disturb – CABLE
Patch_disturb Subroutine
84 statements
Source File
public subroutine Patch_disturb(POP, idisturb, precip)
Arguments
Type Intent Optional Attributes Name
type(POP_TYPE), intent(inout) :: POP
integer(kind=i4b), intent(in) :: idisturb
real(kind=dp), intent(in), optional :: precip(:)
Calls
Called by
Contents
Call graph
patch_disturb calls pop_grid, layer_recruitment_single_patch
layer_recruitment_single_patch calls pop_grid, get_allometry
get_allometry calls allometry, getheight, williams_allometry
popstep calls patch_disturb
popdriver calls popstep
casaonly_luc calls popdriver
mpidrv_worker calls popdriver, worker_casaonly_luc, worker_spincasacnp
spincasacnp calls popdriver
worker_casaonly_luc calls popdriver
worker_spincasacnp calls popdriver
cable_offline_driver calls popdriver, casaonly_luc, spincasacnp
mpi_driver calls mpidrv_worker