PLUME_MIP_INIT – CABLE
PLUME_MIP_INIT Subroutine
265 statements
Source File
public subroutine PLUME_MIP_INIT(PLUME)
Uses
cable_def_types_mod
cable_IO_vars_module
Arguments
Type Intent Optional Attributes Name
type(PLUME_MIP_TYPE) :: PLUME
Calls
Called by
Contents
Call graph
plume_mip_init calls avg_lwdn, met, nf90_close, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_open, get_unit, handle_err
handle_err calls nf90_strerror
mpidrv_master calls plume_mip_init
cable_offline_driver calls plume_mip_init
mpi_driver calls mpidrv_master