PLUME_MIP_GET_MET – CABLE
PLUME_MIP_GET_MET Subroutine
77 statements
Source File
public subroutine PLUME_MIP_GET_MET(PLUME, MET, CurYear, ktau, kend, islast)
Uses
CABLE_WEATHERGENERATOR
cable_checks_module
casa_ncdf_module
cable_def_types_mod
cable_IO_vars_module
Arguments
Type Intent Optional Attributes Name
type(PLUME_MIP_TYPE) :: PLUME
type(met_type) :: MET
integer, intent(in) :: CurYear
integer, intent(in) :: ktau
integer, intent(in) :: kend
logical, intent(in) :: islast
Calls
Called by
Contents
Call graph
plume_mip_get_met calls avg_lwdn, coszen, doy, f_id, hod, metfile, nf90_close, phild, phisd, precip, doysod2ymdhms, file_switch, get_plume_co2, handle_err, open_plume_met, plume_get_daily_met, wgen_daily_constants, wgen_init, wgen_subdiurnal_met, temp
doysod2ymdhms calls is_leapyear
get_plume_co2 calls co2vals, get_unit
handle_err calls nf90_strerror
open_plume_met calls f_id, metfile, handle_err, nf90_get_att, nf90_inq_varid, nf90_open, leap_day, plume_get_filename, v_id, var_name
plume_get_daily_met calls f_id, metfile, nf90_close, handle_err, met, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_open, plume_get_filename, v_id, var_name
wgen_init calls coszen, phild, phisd, precip, temp, daylength, latdeg, latrad, pmb, pmbday, precipday, snow, snowday, solarmjday, solarnorm, tempmaxday, tempmaxdayprev, tempminday, tempmindaynext, tempnightrate, tempnightrateprev, temprangeaft, temprangeday, tempsunset, tempsunsetprev, timemaxtemp, timesunrise, timesunset, timesunsetprev, vappmb, wind, winddark, windday, windlite
leap_day calls is_leapyear
mpidrv_master calls plume_mip_get_met
cable_offline_driver calls plume_mip_get_met
mpi_driver calls mpidrv_master