PLUME_GET_DAILY_MET – CABLE
PLUME_GET_DAILY_MET Subroutine
122 statements
Source File
public subroutine PLUME_GET_DAILY_MET(PLUME, TminFlag, islast)
Arguments
Type Intent Optional Attributes Name
type(PLUME_MIP_TYPE) :: PLUME
logical, intent(in) :: TminFlag
logical, intent(in) :: islast
Calls
Called by
Contents
Call graph
plume_get_daily_met calls f_id, met, metfile, nf90_close, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_open, handle_err, plume_get_filename, v_id, var_name
handle_err calls nf90_strerror
plume_mip_get_met calls plume_get_daily_met
mpidrv_master calls plume_mip_get_met
cable_offline_driver calls plume_mip_get_met
mpi_driver calls mpidrv_master