POP_init_single – CABLE
POP_init_single Subroutine
22 statements
Source File
public subroutine POP_init_single(POP, disturbance_interval, n, precip)
Uses
TypeDef
POP_Types
Arguments
Type Intent Optional Attributes Name
type(POP_TYPE), intent(inout) :: POP
integer(kind=i4b), intent(in) :: disturbance_interval(:,:)
integer(kind=i4b), intent(in) :: n
real(kind=dp), intent(in), optional :: precip(:)
Calls
Called by
Contents
Call graph
pop_init_single calls initpop2d_poisson, layer_recruitment_single_patch, zeropop
initpop2d_poisson calls pop_grid, cumexponential, exponential
layer_recruitment_single_patch calls pop_grid, get_allometry
get_allometry calls allometry, getheight, williams_allometry
casaonly_luc calls pop_init_single
lucdriver calls pop_init_single
master_casaonly_luc calls pop_init_single
popluc_init calls pop_init_single
load_parameters calls popluc_init
mpidrv_master calls lucdriver, master_casaonly_luc, load_parameters
cable_offline_driver calls casaonly_luc, lucdriver, load_parameters
mpi_driver calls mpidrv_master