POP_IO – CABLE
POP_IO Subroutine
1125 statements
Source File
subroutine POP_IO(POP, casamet, YEAR, ACTION, CF)
Uses
netcdf
POP_Constants
casa_ncdf_module
POP_Types
cable_common_module
casavariable
Arguments
Type Intent Optional Attributes Name
type(POP_TYPE), intent(inout) :: POP
type(casa_met), intent(in) :: casamet
integer, intent(in) :: YEAR
character(len=9), intent(in) :: ACTION
logical, intent(in) :: CF
Calls
Called by
Contents
Call graph
pop_io calls lat, lon, nf90_close, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_open, nf90_put_att, nf90_put_var, nf90_redef, pop_grid, handle_err
handle_err calls nf90_strerror
casaonly_luc calls pop_io
load_parameters calls pop_io
master_casaonly_luc calls pop_io
master_spincasacnp calls pop_io
mpidrv_master calls pop_io, load_parameters, master_casaonly_luc, master_spincasacnp
cable_offline_driver calls pop_io, casaonly_luc, load_parameters
mpi_driver calls mpidrv_master