POP_LUC_CASA_transfer – CABLE
POP_LUC_CASA_transfer Subroutine
351 statements
Source File
public subroutine POP_LUC_CASA_transfer(POPLUC, POP, LUC_EXPT, casapool, casabal, casaflux, ktauday)
Arguments
Type Intent Optional Attributes Name
type(POPLUC_TYPE), intent(inout) :: POPLUC
type(POP_TYPE), intent(in) :: POP
type(LUC_EXPT_TYPE), intent(in) :: LUC_EXPT
type(casa_pool), intent(inout) :: casapool
type(casa_balance), intent(inout) :: casabal
type(casa_flux), intent(inout) :: casaflux
integer, intent(in) :: ktauday
Calls
Called by
Contents
Call graph
pop_luc_casa_transfer calls 1166, clabile, clearprod, clearprodloss, clitter, cplant, csoil, ctransferluc, fclearance, fcneeyear, fharvest, fracclearprod, fracclearresid, fracharvprod, fracharvresid, fracharvsecresid, grass, harvprod, harvprodloss, iwood, nlitter, nplant, nsoil, nsoilmin, plitter, pop_grid, pplant, prim_only, psoil, smharv, syharv
casaonly_luc calls pop_luc_casa_transfer
master_casaonly_luc calls pop_luc_casa_transfer
mpidrv_master calls pop_luc_casa_transfer, master_casaonly_luc
cable_offline_driver calls pop_luc_casa_transfer, casaonly_luc
mpi_driver calls mpidrv_master