POPdriver – CABLE
POPdriver Subroutine
44 statements
Source File
public subroutine POPdriver(casaflux, casabal, veg, POP)
Uses
cable_common_module
casaparm
casadimension
phenvariable
cable_def_types_mod
casavariable
POP_Types
TypeDef
POPModule
Arguments
Type Intent Optional Attributes Name
type(casa_flux), intent(in) :: casaflux
type(casa_balance), intent(in) :: casabal
type(veg_parameter_type), intent(in) :: veg
type(POP_TYPE), intent(inout) :: POP
Calls
Called by
Contents
Call graph
popdriver calls disturbance_intensity, disturbance_interval, popstep
popstep calls pop_grid, getdiagnostics, getpatchfrequencies, getuniqueagefrequencies, patch_disturb, patch_partial_disturb, patch_partial_disturb2, patchannualdynamics
getdiagnostics calls pop_grid, get_allometry, interpolate_biomass_1d, interpolate_biomass_2d, smooth_flux
getpatchfrequencies calls pop_grid
getuniqueagefrequencies calls pop_grid, cumexponential, realexponential
patch_disturb calls pop_grid, layer_recruitment_single_patch
patch_partial_disturb calls pop_grid
patch_partial_disturb2 calls pop_grid
patchannualdynamics calls pop_grid, get_allometry, layer_recruitment
get_allometry calls allometry, getheight, williams_allometry
interpolate_biomass_1d calls pop_grid, realexponential
interpolate_biomass_2d calls pop_grid, realexponential, area_triangle
layer_recruitment calls pop_grid, get_allometry
layer_recruitment_single_patch calls pop_grid, get_allometry
smooth_flux calls pop_grid, regress
casaonly_luc calls popdriver
mpidrv_worker calls popdriver, worker_casaonly_luc, worker_spincasacnp
spincasacnp calls popdriver
worker_casaonly_luc calls popdriver
worker_spincasacnp calls popdriver
cable_offline_driver calls popdriver, casaonly_luc, spincasacnp
mpi_driver calls mpidrv_worker