POPLUC_set_patchfrac – CABLE
POPLUC_set_patchfrac Subroutine
15 statements
Source File
public subroutine POPLUC_set_patchfrac(POPLUC, LUC_EXPT)
Arguments
Type Intent Optional Attributes Name
type(POPLUC_TYPE), intent(in) :: POPLUC
type(LUC_EXPT_TYPE), intent(in) :: LUC_EXPT
Calls
Called by
Contents
Call graph
popluc_set_patchfrac calls grass, prim_only, primf
casaonly_luc calls popluc_set_patchfrac
master_casaonly_luc calls popluc_set_patchfrac
mpidrv_master calls popluc_set_patchfrac, master_casaonly_luc
cable_offline_driver calls popluc_set_patchfrac, casaonly_luc
mpi_driver calls mpidrv_master