POPLUC_weights_transfer – CABLE
POPLUC_weights_transfer Subroutine
24 statements
Source File
public subroutine POPLUC_weights_transfer(POPLUC, POP, LUC_EXPT)
Arguments
Type Intent Optional Attributes Name
type(POPLUC_TYPE), intent(in) :: POPLUC
type(POP_TYPE), intent(inout) :: POP
type(LUC_EXPT_TYPE), intent(in) :: LUC_EXPT
Calls
Called by
Contents
Call graph
popluc_weights_transfer calls freq_age_secondary, iwood, prim_only
casaonly_luc calls popluc_weights_transfer
lucdriver calls popluc_weights_transfer
master_casaonly_luc calls popluc_weights_transfer
mpidrv_master calls lucdriver, master_casaonly_luc
cable_offline_driver calls casaonly_luc, lucdriver
mpi_driver calls mpidrv_master