POPLUCStep – CABLE
POPLUCStep Subroutine
23 statements
Source File
public subroutine POPLUCStep(POPLUC, year)
Arguments
Type Intent Optional Attributes Name
type(POPLUC_TYPE), intent(inout) :: POPLUC
integer(kind=i4b), intent(in) :: year
Calls
Called by
Contents
Call graph
poplucstep calls freq_age_secondary, gtop, gtos, primf, execute_luc_event, increment_age, ptog, ptos, stog
execute_luc_event calls freq_age_secondary, primf, ptog, ptos, stog, frac_forest, n_event
increment_age calls freq_age_secondary, smharv, syharv
casaonly_luc calls poplucstep
lucdriver calls poplucstep
master_casaonly_luc calls poplucstep
mpidrv_master calls lucdriver, master_casaonly_luc
cable_offline_driver calls casaonly_luc, lucdriver
mpi_driver calls mpidrv_master