POPStep – CABLE
POPStep Subroutine
70 statements
Source File
public subroutine POPStep(POP, StemNPP, disturbance_interval, disturbance_intensity, LAI, Cleaf, Croot, NPPtoGPP, StemNPP_av, frac_intensity1, precip)
Arguments
Type Intent Optional Attributes Name
type(POP_TYPE), intent(inout) :: POP
real(kind=dp), intent(in) :: StemNPP(:,:)
integer(kind=i4b), intent(in) :: disturbance_interval(:,:)
real(kind=dp), intent(in) :: disturbance_intensity(:,:)
real(kind=dp), intent(in) :: LAI(:)
real(kind=dp), intent(in) :: Cleaf(:)
real(kind=dp), intent(in) :: Croot(:)
real(kind=dp), intent(in) :: NPPtoGPP(:)
real(kind=dp), intent(in), optional :: StemNPP_av(:)
real(kind=dp), intent(in), optional :: frac_intensity1(:)
real(kind=dp), intent(in), optional :: precip(:)
Calls
Called by
Contents
Call graph
popstep calls pop_grid, getdiagnostics, getpatchfrequencies, getuniqueagefrequencies, patch_disturb, patch_partial_disturb, patch_partial_disturb2, patchannualdynamics
getdiagnostics calls pop_grid, get_allometry, interpolate_biomass_1d, interpolate_biomass_2d, smooth_flux
getpatchfrequencies calls pop_grid
getuniqueagefrequencies calls pop_grid, cumexponential, realexponential
patch_disturb calls pop_grid, layer_recruitment_single_patch
patch_partial_disturb calls pop_grid
patch_partial_disturb2 calls pop_grid
patchannualdynamics calls pop_grid, get_allometry, layer_recruitment
get_allometry calls allometry, getheight, williams_allometry
interpolate_biomass_1d calls pop_grid, realexponential
interpolate_biomass_2d calls pop_grid, realexponential, area_triangle
layer_recruitment calls pop_grid, get_allometry
layer_recruitment_single_patch calls pop_grid, get_allometry
smooth_flux calls pop_grid, regress
popdriver calls popstep
casaonly_luc calls popdriver
mpidrv_worker calls popdriver, worker_casaonly_luc, worker_spincasacnp
spincasacnp calls popdriver
worker_casaonly_luc calls popdriver
worker_spincasacnp calls popdriver
cable_offline_driver calls popdriver, casaonly_luc, spincasacnp
mpi_driver calls mpidrv_worker