pore_space_relative_humidity – CABLE
pore_space_relative_humidity Subroutine
20 statements
Source File
public subroutine pore_space_relative_humidity(ssnow, soil, veg)
Arguments
Type Intent Optional Attributes Name
type(soil_snow_type), intent(inout) :: ssnow
type(soil_parameter_type), intent(inout) :: soil
type(veg_parameter_type), intent(inout) :: veg
Calls
Contents
Call graph
pore_space_relative_humidity calls bch_vec, isoilm, iveg, satfrac, snowd, ssat_vec, sucs_vec, tgg, watr, wb