psim – CABLE
psim Function
13 statements
Source File
public function psim(zeta, mp, CPI_C) result(r)
Purpose
Evaluates the integrated similarity function for momentum transfer, .
Method
Uses the Businger-Dyer form for unstable conditions () and the Beljaars-Holtslag form for stable conditions ().
This function is used in the evaluation of the friction velocity in comp_friction_vel.
References
Beljaars and Holtslag (1991)
Businger et al. (1971)
Dyer (1974)
Arguments
Type Intent Optional Attributes Name
real, intent(in), DIMENSION(mp) :: zeta
current value of stability parameter (-)
integer, intent(in) :: mp
size of cable vector of land points (-)
real, intent(in) :: CPI_C
(-)
Return Value real, DIMENSION(mp)
Calls
Called by
Contents
Call graph
psim calls alog
comp_friction_vel calls psim
define_canopy calls psim, comp_friction_vel
cbm calls define_canopy
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker