qsatfjh – CABLE
qsatfjh Subroutine
11 statements
Source File
public subroutine qsatfjh(mp, var, CRMH2o, Crmair, CTETENA, CTETENB, CTETENC, tair, pmb)
Purpose
This SUBROUTINE evaluates the specific humidity (water vapour mixing ratio) at saturation (in kgkg), at a given air temperature (in C) and air pressure (in hPa) for an array of size mp.
Method
The Teten's formula for specific humidity at saturation is used, based on the values for the mass of a mole of water,CRMH2o, mass of a mole of dry air Crmair, and the Teten constants.
Reference
Murray F. W., 1967
Arguments
Type Intent Optional Attributes Name
integer :: mp
size of array of land points (-)
real, intent(out) :: var(mp)
specific humidity at saturation (kgkg)
real :: CRMH2o
real :: Crmair
real :: CTETENA
real :: CTETENB
real :: CTETENC
real, intent(in) :: tair(mp)
air temperature (C) surface air pressure (hPa)
real, intent(in) :: pmb(mp)
air temperature (C) surface air pressure (hPa)
Called by
Contents
Call graph
define_canopy calls qsatfjh, penman_monteith
penman_monteith calls qsatfjh
cbm calls define_canopy
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker