radiation – CABLE
radiation Subroutine
65 statements
Source File
public subroutine radiation(ssnow, veg, air, met, rad, canopy, sunlit_veg_mask, CLAI_thresh, CSboltz, Cemsoil, Cemleaf, Ccapp)
Uses
cable_def_types_mod
cable_other_constants_mod
Arguments
Type Intent Optional Attributes Name
type(soil_snow_type), intent(inout) :: ssnow
type(veg_parameter_type), intent(in) :: veg
type(air_type), intent(in) :: air
type(met_type), intent(inout) :: met
type(radiation_type), intent(inout) :: rad
type(canopy_type), intent(in) :: canopy
logical :: sunlit_veg_mask(mp)
real :: CLAI_thresh
real :: CSboltz
real :: Cemsoil
real :: Cemleaf
real :: Ccapp
Calls
Called by
Contents
Call graph
radiation calls albsoilsn, cexpkbm, cexpkdm, extkbm, extkdm, fbeam, fsd, fvlai, gradis, qcan, reffbm, reffdf, refl, scalex, taul
define_canopy calls radiation
cbm calls define_canopy
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker