range_abort – CABLE
range_abort Subroutine
22 statements
Source File
public subroutine range_abort(message, ktau, met, value, var_range, i, xx, yy)
Uses
cable_IO_vars_module
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: message
integer, intent(in) :: ktau
type(met_type), intent(in) :: met
real, intent(in) :: value
real, intent(in), DIMENSION(2) :: var_range
integer, intent(in) :: i
integer, intent(in), optional :: xx
integer, intent(in), optional :: yy
Calls
Called by
Contents
Call graph
range_abort calls doy, hod, year
write_output_variable_r1 calls range_abort
write_output_variable_r2 calls range_abort
write_ovar calls write_output_variable_r1, write_output_variable_r2
create_landuse_cable_restart calls write_ovar
create_restart calls write_ovar
open_output_file calls write_ovar
write_output calls write_ovar
mpidrv_master calls create_landuse_cable_restart, create_restart, open_output_file, write_output
cable_offline_driver calls create_landuse_cable_restart, create_restart, open_output_file, write_output
mpi_driver calls mpidrv_master