rangechk2 – CABLE
rangechk2 Subroutine
17 statements
Source File
subroutine rangechk2(mlon, mlat, landmask, varx2, xmin, xmax)
Uses
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
integer :: mlon
integer :: mlat
integer, dimension(mlon,mlat) :: landmask
real(kind=r_2), dimension(mlon,mlat) :: varx2
real :: xmin
real :: xmax
Called by
Contents
Call graph
create_new_gridinfo calls rangechk2
mpidrv_master calls create_new_gridinfo
cable_offline_driver calls create_new_gridinfo
mpi_driver calls mpidrv_master