read_casa_dump – CABLE
read_casa_dump Subroutine
122 statements
Source File
public subroutine read_casa_dump(ncfile, casamet, casaflux, phen, climate, ncall, kend, allATonce)
Uses
phenvariable
casa_ncdf_module
cable_def_types_mod
casadimension
netcdf
cable_common_module
casavariable
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: ncfile
type(casa_met), intent(inout) :: casamet
type(casa_flux), intent(inout) :: casaflux
type(phen_variable), intent(inout) :: phen
type(climate_type), intent(inout) :: climate
integer, intent(in) :: ncall
integer, intent(in) :: kend
logical, intent(in) :: allATonce
Calls
Called by
Contents
Call graph
read_casa_dump calls nf90_close, nf90_open, get_var_ncr2, get_var_ncr3, stderr_nc
get_var_ncr2 calls stderr_nc, nf90_get_var, nf90_inq_varid
get_var_ncr3 calls stderr_nc, nf90_get_var, nf90_inq_varid
stderr_nc calls nf90_strerror
casaonly_luc calls read_casa_dump
master_casaonly_luc calls read_casa_dump
master_spincasacnp calls read_casa_dump
spincasacnp calls read_casa_dump
cable_offline_driver calls read_casa_dump, casaonly_luc, spincasacnp
mpidrv_master calls master_casaonly_luc, master_spincasacnp
mpi_driver calls mpidrv_master