readpar_rd – CABLE
readpar_rd Subroutine
97 statements
Source File
private subroutine readpar_rd(ncid, parname, completeSet, var_rd, filename, npatch, dimswitch, from_restart, INpatch)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncid
character(len=*), intent(in) :: parname
logical, intent(inout) :: completeSet
real(kind=r_2), intent(inout), DIMENSION(:) :: var_rd
character(len=*), intent(in) :: filename
integer, intent(in) :: npatch
character(len=*), intent(in) :: dimswitch
logical, intent(in), optional :: from_restart
integer, intent(in), optional :: INpatch
Calls
Called by
Contents
Call graph
readpar_rd calls nf90_get_var, nf90_inq_varid, nf90_inquire_variable, nc_abort
nc_abort calls nf90_strerror
readpar calls readpar_rd
extrarestart calls readpar
get_parameters_met calls readpar
get_restart_data calls readpar, extrarestart
load_parameters calls get_parameters_met, get_restart_data
mpidrv_master calls load_parameters
cable_offline_driver calls load_parameters
mpi_driver calls mpidrv_master