READ_LUH2 – CABLE
READ_LUH2 Subroutine
57 statements
Source File
public subroutine READ_LUH2(LUC_EXPT)
Arguments
Type Intent Optional Attributes Name
type(LUC_EXPT_TYPE), intent(inout) :: LUC_EXPT
Calls
Called by
Contents
Call graph
read_luh2 calls f_id, input, nf90_get_var, handle_err, transfile, v_id
handle_err calls nf90_strerror
casaonly_luc calls read_luh2
lucdriver calls read_luh2
master_casaonly_luc calls read_luh2
mpidrv_master calls lucdriver, master_casaonly_luc
cable_offline_driver calls casaonly_luc, lucdriver
mpi_driver calls mpidrv_master