READ_ClimateFile – CABLE
READ_ClimateFile Subroutine
79 statements
Source File
public subroutine READ_ClimateFile(LUC_EXPT)
Uses
netcdf
Arguments
Type Intent Optional Attributes Name
type(LUC_EXPT_TYPE), intent(inout) :: LUC_EXPT
Calls
Called by
Contents
Call graph
read_climatefile calls nf90_close, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_open, handle_err
handle_err calls nf90_strerror
luc_expt_init calls read_climatefile
mpidrv_master calls luc_expt_init
cable_offline_driver calls luc_expt_init
mpi_driver calls mpidrv_master