remove_transGW – CABLE
remove_transGW Subroutine
52 statements
Source File
private subroutine remove_transGW(dels, soil, ssnow, canopy, veg)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: dels
type(soil_parameter_type), intent(inout) :: soil
type(soil_snow_type), intent(inout) :: ssnow
type(canopy_type), intent(inout) :: canopy
type(veg_parameter_type), intent(inout) :: veg
Calls
Called by
Contents
Call graph
remove_transgw calls evapfbl, fevc, froot, swilt_vec, wbice, wbliq, wmice, wmliq, zse_vec
soil_snow_gw calls remove_transgw