report_parameters – CABLE
report_parameters Subroutine
218 statements
Source File
public subroutine report_parameters(logn, soil, veg, bgc, rough, ssnow, canopy, casamet, casapool, casaflux, phen, vegparmnew, verbose)
Uses
cable_pft_params_mod
cable_soil_params_mod
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: logn
type(soil_parameter_type), intent(in) :: soil
type(veg_parameter_type), intent(in) :: veg
type(bgc_pool_type), intent(in) :: bgc
type(roughness_type), intent(in) :: rough
type(soil_snow_type), intent(in) :: ssnow
type(canopy_type), intent(in) :: canopy
type(casa_met), intent(in) :: casamet
type(casa_pool), intent(in) :: casapool
type(casa_flux), intent(in) :: casaflux
type(phen_variable), intent(in) :: phen
logical, intent(in) :: vegparmnew
logical, intent(in) :: verbose
Calls
Called by
Contents
Call graph
report_parameters calls a1gs, albsoil, albsoilsn, areacell, bch, canst1, cansto, clabile, clay, clitter, cplant, csoil, css, d0gs, dleaf, ejmax, frac4, froot, glai, hc, hyds, isflag, isoilm, isorder, iveg, iveg2, nlitter, nmindep, nminfix, nplant, nsoil, nsoilmin, osnowd, pdep, phase, plitter, pplant, cable_pft_params, cable_soil_params, psoil, psoillab, psoilocc, psoilsorb, pwea, ratecp, ratecs, rhosoil, rnof1, rnof2, rp20, rpcoef, rs20, rtsoil, runoff, sand, sfc, shelrb, silt, smass, snage, snowd, ssat, ssdn, ssdnn, sucs, swilt, tgg, tggsn, tmaxvj, tminvj, vbeta, vcmax, wb, wbice, xalbnir, xfang, za_tq, za_uv
load_parameters calls report_parameters
mpidrv_master calls load_parameters
cable_offline_driver calls load_parameters
mpi_driver calls mpidrv_master