rh0_sol – CABLE
rh0_sol Function
6 statements
Source File
public pure elemental function rh0_sol(hr0, solin)
Arguments
Type Intent Optional Attributes Name
real(kind=r_2), intent(in) :: hr0
type(solve_type), intent(in) :: solin
Return Value real(kind=r_2)
Calls
Called by
Contents
Call graph
rh0_sol calls csat, phi, slope_csat
rtbis_rh0 calls rh0_sol