saturated_fraction – CABLE
saturated_fraction Subroutine
23 statements
Source File
private subroutine saturated_fraction(ssnow, soil, veg)
Arguments
Type Intent Optional Attributes Name
type(soil_snow_type), intent(inout) :: ssnow
type(soil_parameter_type), intent(in) :: soil
type(veg_parameter_type), intent(in) :: veg
Calls
Called by
Contents
Call graph
saturated_fraction calls iveg, my_erf, slope_std, ssat_vec, watr, wb, wbice, zse, zse_vec
calc_srf_wet_fraction calls saturated_fraction