SEB – CABLE
SEB Subroutine
188 statements
Source File
public subroutine SEB(n, par, vmet, vsnow, var, qprec, qprec_snow, dx, h0, Tsoil, Tsurface, G0, lE0, Epot, qsurface, qevap, qliq, qv, qyb, qTb, qlyb, qvyb, qlTb, qvTb, qh, qadv, qhyb, qhTb, qadvyb, qadvTb, irec)
Arguments
Type Intent Optional Attributes Name
integer(kind=i_d), intent(in) :: n
type(params), intent(in), DIMENSION(1:n) :: par
type(vars_met), intent(in) :: vmet
type(vars_snow), intent(in) :: vsnow
type(vars), intent(in), DIMENSION(1:n) :: var
real(kind=r_2), intent(in) :: qprec
real(kind=r_2), intent(in) :: qprec_snow
real(kind=r_2), intent(in), DIMENSION(1:n) :: dx
real(kind=r_2), intent(in) :: h0
real(kind=r_2), intent(in), DIMENSION(1:n) :: Tsoil
real(kind=r_2), intent(out) :: Tsurface
real(kind=r_2), intent(out) :: G0
real(kind=r_2), intent(out) :: lE0
real(kind=r_2), intent(out) :: Epot
real(kind=r_2), intent(out) :: qsurface
real(kind=r_2), intent(out) :: qevap
real(kind=r_2), intent(out) :: qliq
real(kind=r_2), intent(out) :: qv
real(kind=r_2), intent(out) :: qyb
real(kind=r_2), intent(out) :: qTb
real(kind=r_2), intent(out) :: qlyb
real(kind=r_2), intent(out) :: qvyb
real(kind=r_2), intent(out) :: qlTb
real(kind=r_2), intent(out) :: qvTb
real(kind=r_2), intent(out) :: qh
real(kind=r_2), intent(out) :: qadv
real(kind=r_2), intent(out) :: qhyb
real(kind=r_2), intent(out) :: qhTb
real(kind=r_2), intent(out) :: qadvyb
real(kind=r_2), intent(out) :: qadvTb
integer(kind=i_d), intent(in) :: irec
Calls
Called by
Contents
Call graph
seb calls depth, hliq, kth, hyofh, potential_evap, slope_csat, tsn
potential_evap calls slope_esat, slope_esat_ice
get_fluxes_and_derivs calls seb
sli_main calls seb, solve
iflux_loop calls get_fluxes_and_derivs
timestep_loop calls iflux_loop
solve calls timestep_loop