setpar – CABLE
setpar Subroutine
33 statements
Source File
public subroutine setpar(mp, ms, soil, index)
Arguments
Type Intent Optional Attributes Name
integer(kind=i_d), intent(in) :: mp
integer(kind=i_d), intent(in) :: ms
type(soil_parameter_type), intent(in) :: soil
integer(kind=i_d), intent(in), DIMENSION(:) :: index
Calls
Called by
Contents
Call graph
setpar calls bch, clay, cnsd, css, fsatmax, hyds, ishorizon, rhosoil, sfc, ssat, sucs, swilt, zeta
sli_main calls setpar