simple_wtd – CABLE
simple_wtd Subroutine
26 statements
Source File
private subroutine simple_wtd(ssnow, soil, veg)
Arguments
Type Intent Optional Attributes Name
type(soil_snow_type), intent(inout) :: ssnow
type(soil_parameter_type), intent(inout) :: soil
type(veg_parameter_type), intent(inout) :: veg
Calls
Contents
Call graph
simple_wtd calls gwdz, gwssat_vec, gwwb, ssat_vec, watr, wb, zse