site_GET_CO2_Ndep – CABLE
site_GET_CO2_Ndep Subroutine
30 statements
Source File
public subroutine site_GET_CO2_Ndep(site)
Arguments
Type Intent Optional Attributes Name
type(site_TYPE) :: site
Calls
Called by
Contents
Call graph
site_get_co2_ndep calls co2vals, ndepvals, pdepvals, get_unit
cable_offline_driver calls site_get_co2_ndep