sli_main – CABLE
sli_main Subroutine
506 statements
Source File
public subroutine sli_main(ktau, dt, veg, soil, ssnow, met, canopy, air, rad, SEB_only)
Uses
sli_roots
sli_solve
sli_utils
cable_def_types_mod
sli_numbers
cable_IO_vars_module
cable_common_module
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ktau
real, intent(in) :: dt
type(veg_parameter_type), intent(inout) :: veg
type(soil_parameter_type), intent(inout) :: soil
type(soil_snow_type), intent(inout) :: ssnow
type(met_type), intent(inout) :: met
type(canopy_type), intent(inout) :: canopy
type(air_type), intent(inout) :: air
type(radiation_type), intent(in) :: rad
integer, intent(in) :: SEB_only
Calls
Contents
Call graph
sli_main calls albsoilsn, gammzz, gwdz, gwssat_vec, gwwatr, gwwb, getrex, setroots, latitude, longitude, nsnow, esat, esat_ice, hyofs, seb, setlitterpar, setpar, setpar_loetsch, setx, slope_esat_ice, solve, tfrz, thetalmax, qhlev, qrecharge, rex, rtevap_sat, rtevap_unsat, satfrac, sconds, sdepth, smass, snowd, snowliq, ssdn, sublayer_dz, tggsn, wb
getrex calls getrex_1d, getrex_2d
setroots calls setroots_1d, setroots_2d
hyofs calls tfrz, dthetalmaxdt, igamma, slope_esat
seb calls depth, hliq, kth, hyofh, potential_evap, slope_csat, tsn
setlitterpar calls clitt
setpar calls bch, clay, cnsd, css, fsatmax, hyds, ishorizon, rhosoil, sfc, ssat, sucs, swilt, zeta
setx calls zse
solve calls hyofs, hyofh, litter_props, setsol, sofh, timestep_loop, zerovars
thetalmax calls tfrz
dthetalmaxdt calls tfrz
getrex_2d calls getrex_1d
igamma calls gammln, gcf, gser
litter_props calls slope_esat
potential_evap calls slope_esat_ice, slope_esat
setroots_2d calls setroots_1d
timestep_loop calls litter_props, iflux_loop, isotope_vap
gcf calls gammln
gser calls gammln
iflux_loop calls hyofs, litter_props, estimate_timestep, get_and_solve_eqn, get_fluxes_and_derivs, snow_adjust, update_s_t, update_unknowns
isotope_vap calls tri
tri calls tri_1d, tri_2d
get_and_solve_eqn calls tfrz, massman_sparse
get_fluxes_and_derivs calls seb, zerovars, getfluxes_vp, getheatfluxes, flux
snow_adjust calls esat_ice, slope_esat_ice, tfrz, thetalmax, gtfrozen, jsoillayer, rtbis_tfrozen
update_s_t calls tfrz, thetalmax, dthetalmaxdth, gtfrozen, jsoillayer, rtbis_tfrozen
update_unknowns calls jsoillayer
getfluxes_vp calls getfluxes_vp_1d, getfluxes_vp_2d
getheatfluxes calls getheatfluxes_1d, getheatfluxes_2d
massman_sparse calls massman_sparse_1d, massman_sparse_2d
dthetalmaxdth calls tfrz
flux calls weight
gtfrozen calls tfrz
jsoillayer calls tfrz
rtbis_tfrozen calls gtfrozen
getfluxes_vp_1d calls hyofh, zerovars, flux
getfluxes_vp_2d calls hyofh, zerovars, flux
massman_sparse_1d calls generic_thomas
massman_sparse_2d calls generic_thomas
weight calls hyofh
generic_thomas calls generic_thomas_1d, generic_thomas_2d