sli_hydrology – CABLE
sli_hydrology Subroutine
19 statements
Source File
public subroutine sli_hydrology(dels, ssnow, soil, veg, canopy)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: dels
type(soil_snow_type), intent(inout) :: ssnow
type(soil_parameter_type), intent(inout) :: soil
type(veg_parameter_type), intent(inout) :: veg
type(canopy_type), intent(inout) :: canopy
Calls
Contents
Call graph
sli_hydrology calls gwdz, aquifer_recharge, calc_soil_hydraulic_props, iterative_wtd, ovrlndflx, subsurface_drainage, zse
aquifer_recharge calls gwhk, hk, isoilm, iveg, smp, wtd, zq, zse_vec
calc_soil_hydraulic_props calls bch_vec, drain_dens, fracice, gwbch_vec, gwhk, gwhyds_vec, gwsmp, gwssat_vec, gwsucs_vec, gwwatr, gwwb, hyds_vec, icefrac, isoilm, smp, ssat_vec, sucs_vec, watr, wb, wbice, wbliq, wtd
iterative_wtd calls gwdz, zse, bch_vec, gwssat_vec, gwwb, isoilm, iveg, ssat_vec, sucs_vec, wbice, wbliq, wtd
ovrlndflx calls zse, bch_vec, fwtop, gammzz, hyds_vec, iveg, rnof1, satfrac, sdepth, smass, ssat_vec, ssdn, sucs_vec, tgg, through, through_sn, wb, wbice, wbliq
subsurface_drainage calls gwdz, drain_dens, fracice, gwwb, isoilm, iveg, qhlev, qhz, slope, watr, wb, wbice, wbliq, wtd, zse_vec