slope_esat – CABLE
slope_esat Function
8 statements
Source File
public pure elemental function slope_esat(T)
Uses
sli_numbers
Arguments
Type Intent Optional Attributes Name
real(kind=r_2), intent(in) :: T
Return Value real(kind=r_2)
Called by
Contents
Call graph
hyofs calls slope_esat
litter_props calls slope_esat
potential_evap calls slope_esat
iflux_loop calls hyofs, litter_props, get_fluxes_and_derivs
seb calls potential_evap
seb_fr calls potential_evap
sli_main calls hyofs, seb, solve
solve calls hyofs, litter_props, timestep_loop
timestep_loop calls litter_props, iflux_loop
get_fluxes_and_derivs calls seb