slope_csat – CABLE
slope_csat Function
8 statements
Source File
public pure elemental function slope_csat(T)
Uses
sli_numbers
Arguments
Type Intent Optional Attributes Name
real(kind=r_2), intent(in) :: T
Return Value real(kind=r_2)
Called by
Contents
Call graph
rh0_sol calls slope_csat
seb calls slope_csat
seb_fr calls slope_csat
get_fluxes_and_derivs calls seb
rtbis_rh0 calls rh0_sol
sli_main calls seb, solve
iflux_loop calls get_fluxes_and_derivs
timestep_loop calls iflux_loop
solve calls timestep_loop