smoisturev – CABLE
smoisturev Subroutine
185 statements
Source File
public subroutine smoisturev(dels, ssnow, soil, veg)
Uses
cable_common_module
trimb_mod
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: dels
type(soil_snow_type), intent(inout) :: ssnow
type(soil_parameter_type), intent(inout) :: soil
type(veg_parameter_type), intent(in) :: veg
Calls
Called by
Contents
Call graph
smoisturev calls trimb, sfc, ssat, wb, wbfice, wbice, wblf, zse, zshh
surfbv calls smoisturev
soil_snow calls surfbv
cbm calls soil_snow
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker