smoistgw – CABLE
smoistgw Subroutine
190 statements
Source File
private subroutine smoistgw(dels, ktau, ssnow, soil, veg, canopy)
Uses
cable_common_module
trimb_mod
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: dels
integer, intent(in) :: ktau
type(soil_snow_type), intent(inout) :: ssnow
type(soil_parameter_type), intent(inout) :: soil
type(veg_parameter_type), intent(inout) :: veg
type(canopy_type), intent(inout) :: canopy
Calls
Called by
Contents
Call graph
smoistgw calls dhkdw, dsmpdw, gwdz, gwsmp, gwssat_vec, gwwb, gwzq, hk, isoilm, aquifer_recharge, calc_equilibrium_water_content, calc_soil_hydraulic_props, subsurface_drainage, trimb, qhlev, qhz, qrecharge, sinfil, smp, ssat_vec, wb, wbice, wbliq, wmice, wmliq, zq, zse, zse_vec
aquifer_recharge calls hk, isoilm, smp, zq, zse_vec, gwhk, iveg, wtd
calc_equilibrium_water_content calls gwdz, gwssat_vec, gwzq, ssat_vec, wbice, zse, bch_vec, gwbch_vec, gwsucs_vec, gwwatr, gwwbeq, sucs_vec, watr, wbeq, wtd
calc_soil_hydraulic_props calls gwsmp, gwssat_vec, gwwb, isoilm, smp, ssat_vec, wb, wbice, wbliq, bch_vec, drain_dens, fracice, gwbch_vec, gwhk, gwhyds_vec, gwsucs_vec, gwwatr, hyds_vec, icefrac, sucs_vec, watr, wtd
subsurface_drainage calls gwdz, gwwb, isoilm, qhlev, qhz, wb, wbice, wbliq, zse_vec, drain_dens, fracice, iveg, slope, watr, wtd
soil_snow_gw calls smoistgw