snow_processes_soil_thermal – CABLE
snow_processes_soil_thermal Subroutine
30 statements
Source File
public subroutine snow_processes_soil_thermal(dels, ssnow, soil, veg, canopy, met, bal, snowmlt)
Uses
snowcheck_mod
snowdensity_mod
snowl_adjust_mod
snow_accum_mod
GWstempv_mod
snow_melting_mod
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: dels
type(soil_snow_type), intent(inout) :: ssnow
type(soil_parameter_type), intent(inout) :: soil
type(veg_parameter_type), intent(inout) :: veg
type(canopy_type), intent(inout) :: canopy
type(met_type), intent(inout) :: met
type(balances_type), intent(inout) :: bal
real, intent(inout), DIMENSION(:) :: snowmlt
Calls
Called by
Contents
Call graph
snow_processes_soil_thermal calls isflag, gwstempv, snow_accum, snow_melting, snowcheck, snowdensity, snowl_adjust, smelt, tgg, tggsn
gwstempv calls tgg, tggsn, css_vec, gammzz, old_soil_conductivity, total_soil_conductivity, trimb, rhosoil_vec, sconds, sdepth, ssat_vec, ssdn, wbfice, wblf, zse, zse_vec
snow_accum calls isflag, tgg, tggsn, cls, evapsn, fes_cor, fess, gammzz, isoilm, osnowd, precip_sn, precis, sdepth, smass, snowd, ssdn
snow_melting calls isflag, tgg, tggsn, dtmlt, gammzz, sdepth, smass, snowd, ssdn
snowcheck calls isflag, tgg, tggsn, smass, snowd, ssdn, ssdnn, t_snwlr
snowdensity calls tgg, tggsn, sconds, smass, ssdn
snowl_adjust calls isflag, tggsn, sdepth, smass, snowd, ssdn
old_soil_conductivity calls isoilm, wbfice, wblf, cnsd, ssat
total_soil_conductivity calls isflag, tgg, isoilm, snowd, ssat_vec, cnsd_vec, sand_vec, watr, wb, wbice, wbliq
soil_snow_gw calls snow_processes_soil_thermal