snow_melting – CABLE
snow_melting Subroutine
51 statements
Source File
public subroutine snow_melting(dels, snowmlt, ssnow, soil)
Uses
cable_common_module
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: dels
real, intent(out), DIMENSION(mp) :: snowmlt
type(soil_snow_type), intent(inout) :: ssnow
type(soil_parameter_type), intent(inout) :: soil
Calls
Called by
Contents
Call graph
snow_melting calls dtmlt, gammzz, isflag, sdepth, smass, snowd, ssdn, tgg, tggsn
snow_processes_soil_thermal calls snow_melting
soil_snow calls snow_melting
cbm calls soil_snow
soil_snow_gw calls snow_processes_soil_thermal
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker