soil_snow_gw – CABLE
soil_snow_gw Subroutine
115 statements
Source File
public subroutine soil_snow_gw(dels, soil, ssnow, canopy, met, bal, veg)
Uses
cable_IO_vars_module
cable_common_module
snow_processes_soil_thermal_mod
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: dels
type(soil_parameter_type), intent(inout) :: soil
type(soil_snow_type), intent(inout) :: ssnow
type(canopy_type), intent(inout) :: canopy
type(met_type), intent(inout) :: met
type(balances_type), intent(inout) :: bal
type(veg_parameter_type), intent(inout) :: veg
Calls
Contents
Call graph
soil_snow_gw calls css_vec, dtmlt, fevc, gwdz, gwwb, heat_cap_lower_limit, isflag, gwsoilfreeze, iterative_wtd, ovrlndflx, remove_transgw, smoistgw, snow_processes_soil_thermal, rhosoil_vec, rnof1, rnof2, sinfil, smelt, snowd, ssat_vec, swilt_vec, tgg, tggsn, wb, wbice, wbliq, wmice, wmliq, zse
gwsoilfreeze calls css_vec, heat_cap_lower_limit, isflag, rhosoil_vec, snowd, ssat_vec, tgg, wb, wbice, wbliq, gammzz, isoilm, zse_vec
iterative_wtd calls gwdz, gwwb, ssat_vec, wbice, wbliq, zse, bch_vec, gwssat_vec, isoilm, iveg, sucs_vec, wtd
ovrlndflx calls rnof1, ssat_vec, tgg, wb, wbice, wbliq, zse, bch_vec, fwtop, gammzz, hyds_vec, iveg, satfrac, sdepth, smass, ssdn, sucs_vec, through, through_sn
remove_transgw calls fevc, swilt_vec, wbice, wbliq, wmice, wmliq, evapfbl, froot, zse_vec
smoistgw calls gwdz, gwwb, sinfil, ssat_vec, wb, wbice, wbliq, wmice, wmliq, zse, dhkdw, dsmpdw, gwsmp, gwssat_vec, gwzq, hk, isoilm, aquifer_recharge, calc_equilibrium_water_content, calc_soil_hydraulic_props, subsurface_drainage, trimb, qhlev, qhz, qrecharge, smp, zq, zse_vec
snow_processes_soil_thermal calls isflag, smelt, tgg, tggsn, gwstempv, snow_accum, snow_melting, snowcheck, snowdensity, snowl_adjust
aquifer_recharge calls hk, isoilm, iveg, smp, wtd, zq, zse_vec, gwhk
calc_equilibrium_water_content calls gwdz, ssat_vec, wbice, zse, bch_vec, gwssat_vec, gwzq, sucs_vec, wtd, gwbch_vec, gwsucs_vec, gwwatr, gwwbeq, watr, wbeq
calc_soil_hydraulic_props calls gwwb, ssat_vec, wb, wbice, wbliq, bch_vec, gwsmp, gwssat_vec, hyds_vec, isoilm, smp, sucs_vec, wtd, drain_dens, fracice, gwbch_vec, gwhk, gwhyds_vec, gwsucs_vec, gwwatr, icefrac, watr
gwstempv calls css_vec, rhosoil_vec, ssat_vec, tgg, tggsn, zse, gammzz, trimb, sdepth, ssdn, zse_vec, old_soil_conductivity, total_soil_conductivity, sconds, wbfice, wblf
snow_accum calls isflag, snowd, tgg, tggsn, gammzz, isoilm, sdepth, smass, ssdn, cls, evapsn, fes_cor, fess, osnowd, precip_sn, precis
snow_melting calls dtmlt, isflag, snowd, tgg, tggsn, gammzz, sdepth, smass, ssdn
snowcheck calls isflag, snowd, tgg, tggsn, smass, ssdn, ssdnn, t_snwlr
snowdensity calls tgg, tggsn, smass, ssdn, sconds
snowl_adjust calls isflag, snowd, tggsn, sdepth, smass, ssdn
subsurface_drainage calls gwdz, gwwb, wb, wbice, wbliq, isoilm, iveg, qhlev, qhz, wtd, zse_vec, drain_dens, fracice, slope, watr
old_soil_conductivity calls isoilm, wbfice, wblf, cnsd, ssat
total_soil_conductivity calls isflag, snowd, ssat_vec, tgg, wb, wbice, wbliq, isoilm, watr, cnsd_vec, sand_vec