soil_snow – CABLE
soil_snow Subroutine
109 statements
Source File
public subroutine soil_snow(dels, soil, ssnow, canopy, met, bal, veg)
Uses
snowcheck_mod
snowl_adjust_mod
snowdensity_mod
cable_common_module
surfbv_mod
remove_trans_mod
stempv_mod
snow_accum_mod
hydraulic_redistribution_mod
snow_melting_mod
soilfreeze_mod
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: dels
type(soil_parameter_type), intent(inout) :: soil
type(soil_snow_type), intent(inout) :: ssnow
type(canopy_type), intent(inout) :: canopy
type(met_type), intent(inout) :: met
type(balances_type), intent(inout) :: bal
type(veg_parameter_type), intent(inout) :: veg
Calls
Called by
Contents
Call graph
soil_snow calls css, dtmlt, gammzz, hydraulic_redistribution, remove_trans, snow_accum, snow_melting, snowcheck, snowdensity, snowl_adjust, soilfreeze, stempv, surfbv, rhosoil, tgg, tggsn, wb, wbice, zse
hydraulic_redistribution calls wb, wbice, zse, froot, sfc, ssat, swilt
remove_trans calls wb, zse, evapfbl, froot
snow_accum calls gammzz, tgg, tggsn, cls, evapsn, fes_cor, fess, isflag, isoilm, osnowd, precip_sn, precis, sdepth, smass, snowd, ssdn
snow_melting calls dtmlt, gammzz, tgg, tggsn, isflag, sdepth, smass, snowd, ssdn
snowcheck calls tgg, tggsn, isflag, smass, snowd, ssdn, ssdnn, t_snwlr
snowdensity calls tgg, tggsn, sconds, smass, ssdn
snowl_adjust calls tggsn, isflag, sdepth, smass, snowd, ssdn
soilfreeze calls gammzz, tgg, wb, wbice, zse
stempv calls gammzz, tgg, tggsn, zse, old_soil_conductivity, total_soil_conductivity, trimb, sconds, sdepth, ssdn, wbfice, wblf
surfbv calls gammzz, tgg, wb, zse, smoisturev, sdepth, sfc, smass, ssdn
old_soil_conductivity calls isoilm, ssat, wbfice, wblf, cnsd
smoisturev calls wb, wbice, zse, trimb, sfc, ssat, wbfice, wblf, zshh
total_soil_conductivity calls tgg, wb, wbice, isflag, isoilm, snowd, cnsd_vec, sand_vec, ssat_vec, watr, wbliq
cbm calls soil_snow
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker