soilfreeze – CABLE
soilfreeze Subroutine
34 statements
Source File
public subroutine soilfreeze(dels, soil, ssnow, heat_cap_lower_limit)
Uses
cable_common_module
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: dels
type(soil_parameter_type), intent(inout) :: soil
type(soil_snow_type), intent(inout) :: ssnow
real :: heat_cap_lower_limit(mp,ms)
Calls
Called by
Contents
Call graph
soilfreeze calls gammzz, tgg, wb, wbice, zse
soil_snow calls soilfreeze
cbm calls soil_snow
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker