spec_init_soil_snow – CABLE
spec_init_soil_snow Subroutine
59 statements
Source File
public subroutine spec_init_soil_snow(dels, soil, ssnow, canopy, met, bal, veg, heat_cap_lower_limit)
Uses
cable_common_module
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: dels
type(soil_parameter_type), intent(inout) :: soil
type(soil_snow_type), intent(inout) :: ssnow
type(canopy_type), intent(inout) :: canopy
type(met_type), intent(inout) :: met
type(balances_type), intent(inout) :: bal
type(veg_parameter_type), intent(inout) :: veg
real :: heat_cap_lower_limit(mp,ms)
Calls
Called by
Contents
Call graph
spec_init_soil_snow calls tgg, wb, wbice, zse
mpidrv_worker calls spec_init_soil_snow
cable_offline_driver calls spec_init_soil_snow
mpi_driver calls mpidrv_worker