stempv – CABLE
stempv Subroutine
118 statements
Source File
public subroutine stempv(dels, canopy, ssnow, soil, heat_cap_lower_limit)
Uses
total_soil_conductivity_mod
old_soil_conductivity_mod
trimb_mod
cable_common_module
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: dels
type(canopy_type), intent(inout) :: canopy
type(soil_snow_type), intent(inout) :: ssnow
type(soil_parameter_type), intent(inout) :: soil
real :: heat_cap_lower_limit(mp,ms)
Calls
Called by
Contents
Call graph
stempv calls gammzz, old_soil_conductivity, total_soil_conductivity, trimb, sconds, sdepth, ssdn, tgg, tggsn, wbfice, wblf, zse
old_soil_conductivity calls wbfice, wblf, cnsd, isoilm, ssat
total_soil_conductivity calls tgg, cnsd_vec, isflag, isoilm, sand_vec, snowd, ssat_vec, watr, wb, wbice, wbliq
soil_snow calls stempv
cbm calls soil_snow
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker