subsurface_drainage – CABLE
subsurface_drainage Subroutine
85 statements
Source File
private subroutine subsurface_drainage(ssnow, soil, veg, dzmm)
Uses
cable_common_module
Arguments
Type Intent Optional Attributes Name
type(soil_snow_type), intent(inout) :: ssnow
type(soil_parameter_type), intent(inout) :: soil
type(veg_parameter_type), intent(inout) :: veg
real(kind=r_2), intent(in), DIMENSION(:) :: dzmm
Calls
Called by
Contents
Call graph
subsurface_drainage calls drain_dens, fracice, gwdz, gwwb, isoilm, iveg, qhlev, qhz, slope, watr, wb, wbice, wbliq, wtd, zse_vec
sli_hydrology calls subsurface_drainage
smoistgw calls subsurface_drainage
soil_snow_gw calls smoistgw