sumcflux – CABLE
sumcflux Subroutine
58 statements
Source File
public subroutine sumcflux(ktau, kstart, kend, dels, bgc, canopy, soil, ssnow, sum_flux, veg, met, casaflux, l_vcmaxFeedbk)
Uses
casadimension
casaparm
cable_carbon_module
casavariable
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ktau
integer, intent(in) :: kstart
integer, intent(in) :: kend
real, intent(in) :: dels
type(bgc_pool_type), intent(inout) :: bgc
type(canopy_type), intent(inout) :: canopy
type(soil_parameter_type), intent(inout) :: soil
type(soil_snow_type), intent(inout) :: ssnow
type(sum_flux_type), intent(inout) :: sum_flux
type(veg_parameter_type), intent(inout) :: veg
type(met_type), intent(in) :: met
type(casa_flux), intent(inout) :: casaflux
logical, intent(in) :: l_vcmaxFeedbk
Calls
Called by
Contents
Call graph
sumcflux calls clabloss, crgplant, crsoil
mpidrv_worker calls sumcflux
cable_offline_driver calls sumcflux
mpi_driver calls mpidrv_worker