surfbv – CABLE
surfbv Subroutine
72 statements
Source File
public subroutine surfbv(dels, met, ssnow, soil, veg, canopy)
Uses
smoisturev_mod
cable_common_module
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: dels
type(met_type), intent(inout) :: met
type(soil_snow_type), intent(inout) :: ssnow
type(soil_parameter_type), intent(inout) :: soil
type(veg_parameter_type), intent(in) :: veg
type(canopy_type), intent(in) :: canopy
Calls
Called by
Contents
Call graph
surfbv calls gammzz, smoisturev, sdepth, sfc, smass, ssdn, tgg, wb, zse
smoisturev calls sfc, wb, zse, trimb, ssat, wbfice, wbice, wblf, zshh
soil_snow calls surfbv
cbm calls soil_snow
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker