Tfrz – CABLE
Tfrz Function
10 statements
Source File
public pure elemental function Tfrz(S, he, b)
Uses
sli_numbers
Arguments
Type Intent Optional Attributes Name
real(kind=r_2), intent(in) :: S
real(kind=r_2), intent(in) :: he
real(kind=r_2), intent(in) :: b
Return Value real(kind=r_2)
Called by
Contents
Call graph
dthetalmaxdt calls tfrz
dthetalmaxdth calls tfrz
get_and_solve_eqn calls tfrz
gtfrozen calls tfrz
hyofs calls tfrz, dthetalmaxdt
jsoillayer calls tfrz
sli_main calls tfrz, hyofs, thetalmax, solve
snow_adjust calls tfrz, gtfrozen, jsoillayer, thetalmax, rtbis_tfrozen
thetalmax calls tfrz
tthetalmax calls tfrz
update_s_t calls tfrz, dthetalmaxdth, gtfrozen, jsoillayer, thetalmax, rtbis_tfrozen
iflux_loop calls get_and_solve_eqn, hyofs, snow_adjust, update_s_t, update_unknowns
rtbis_tfrozen calls gtfrozen
solve calls hyofs, timestep_loop
update_unknowns calls jsoillayer
timestep_loop calls iflux_loop