thetalmax – CABLE
thetalmax Function
12 statements
Source File
public pure elemental function thetalmax(Tin, S, he, b, thre, the)
Uses
sli_numbers
Arguments
Type Intent Optional Attributes Name
real(kind=r_2), intent(in) :: Tin
real(kind=r_2), intent(in) :: S
real(kind=r_2), intent(in) :: he
real(kind=r_2), intent(in) :: b
real(kind=r_2), intent(in) :: thre
real(kind=r_2), intent(in) :: the
Return Value real(kind=r_2)
Calls
Called by
Contents
Call graph
thetalmax calls tfrz
sli_main calls thetalmax, solve
snow_adjust calls thetalmax
update_s_t calls thetalmax
iflux_loop calls snow_adjust, update_s_t
timestep_loop calls iflux_loop
solve calls timestep_loop