total_soil_conductivity – CABLE
total_soil_conductivity Function
44 statements
Source File
public function total_soil_conductivity(ssnow, soil)
Arguments
Type Intent Optional Attributes Name
type(soil_snow_type), intent(inout) :: ssnow
type(soil_parameter_type), intent(inout) :: soil
Return Value real(kind=r_2), DIMENSION(mp,ms)
Calls
Called by
Contents
Call graph
total_soil_conductivity calls cnsd_vec, isflag, isoilm, sand_vec, snowd, ssat_vec, tgg, watr, wb, wbice, wbliq
gwstempv calls total_soil_conductivity
stempv calls total_soil_conductivity
snow_processes_soil_thermal calls gwstempv
soil_snow calls stempv
cbm calls soil_snow
soil_snow_gw calls snow_processes_soil_thermal
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker