totcnppools – CABLE
totcnppools Subroutine
63 statements
Source File
public subroutine totcnppools(kloop, veg, casamet, casapool, bmcplant, bmnplant, bmpplant, bmclitter, bmnlitter, bmplitter, bmcsoil, bmnsoil, bmpsoil, bmnsoilmin, bmpsoillab, bmpsoilsorb, bmpsoilocc, bmarea)
Uses
casaparm
casadimension
casavariable
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: kloop
type(veg_parameter_type), intent(in) :: veg
type(casa_met), intent(in) :: casamet
type(casa_pool), intent(in) :: casapool
real, dimension(5,mvtype,mplant) :: bmcplant
real, dimension(5,mvtype,mplant) :: bmnplant
real, dimension(5,mvtype,mplant) :: bmpplant
real, dimension(5,mvtype,mlitter) :: bmclitter
real, dimension(5,mvtype,mlitter) :: bmnlitter
real, dimension(5,mvtype,mlitter) :: bmplitter
real, dimension(5,mvtype,msoil) :: bmcsoil
real, dimension(5,mvtype,msoil) :: bmnsoil
real, dimension(5,mvtype,msoil) :: bmpsoil
real, dimension(5,mvtype) :: bmnsoilmin
real, dimension(5,mvtype) :: bmpsoillab
real, dimension(5,mvtype) :: bmpsoilsorb
real, dimension(5,mvtype) :: bmpsoilocc
real, dimension(mvtype) :: bmarea
Calls
Contents
Call graph
totcnppools calls areacell, clitter, cplant, csoil, iveg, nlitter, nplant, nsoil, nsoilmin, plitter, pplant, psoil, psoillab, psoilocc, psoilsorb