trimb – CABLE
trimb Subroutine
21 statements
Source File
public subroutine trimb(a, b, c, rhs, kmax)
Arguments
Type Intent Optional Attributes Name
real(kind=r_2), intent(in), DIMENSION(:,:) :: a
real(kind=r_2), intent(in), DIMENSION(:,:) :: b
real(kind=r_2), intent(in), DIMENSION(:,:) :: c
real(kind=r_2), intent(inout), DIMENSION(:,:) :: rhs
integer, intent(in) :: kmax
Called by
Contents
Call graph
gwstempv calls trimb
smoistgw calls trimb
smoisturev calls trimb
stempv calls trimb
snow_processes_soil_thermal calls gwstempv
soil_snow calls stempv, surfbv
soil_snow_gw calls smoistgw, snow_processes_soil_thermal
surfbv calls smoisturev
cbm calls soil_snow
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker