wetLeaf – CABLE
wetLeaf Subroutine
40 statements
Source File
public subroutine wetLeaf(mp, CLAI_thresh, CCAPP, Crmair, dels, rad, rough, air, met, veg, canopy, cansat, tlfy, gbhu, gbhf, ghwet)
Uses
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: mp
real, intent(in) :: CLAI_thresh
real, intent(in) :: CCAPP
real, intent(in) :: Crmair
real, intent(in) :: dels
type(radiation_type), intent(inout) :: rad
type(roughness_type), intent(inout) :: rough
type(air_type), intent(inout) :: air
type(met_type), intent(inout) :: met
type(veg_parameter_type), intent(inout) :: veg
type(canopy_type), intent(inout) :: canopy
real, intent(in), DIMENSION(:) :: cansat
real, intent(in), DIMENSION(:) :: tlfy
real(kind=r_2), intent(in), DIMENSION(:,:) :: gbhu
real(kind=r_2), intent(in), DIMENSION(:,:) :: gbhf
real(kind=r_2), intent(out), DIMENSION(:) :: ghwet
Calls
Called by
Contents
Call graph
wetleaf calls cansto, dsatdk, dva, fevw, fwet, psyc, rlam, tk, tvair, vlaiw
define_canopy calls wetleaf
cbm calls define_canopy
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker