WGEN_INIT – CABLE
WGEN_INIT Subroutine
44 statements
Source File
public subroutine WGEN_INIT(WG, np, latitude, dels)
Arguments
Type Intent Optional Attributes Name
type(WEATHER_GENERATOR_TYPE) :: WG
integer, intent(in) :: np
real, intent(in) :: latitude(np)
real, intent(in) :: dels
Calls
Called by
Contents
Call graph
wgen_init calls coszen, daylength, latdeg, latrad, phild, phisd, pmb, pmbday, precip, precipday, snow, snowday, solarmjday, solarnorm, temp, tempmaxday, tempmaxdayprev, tempminday, tempmindaynext, tempnightrate, tempnightrateprev, temprangeaft, temprangeday, tempsunset, tempsunsetprev, timemaxtemp, timesunrise, timesunset, timesunsetprev, vappmb, wind, winddark, windday, windlite
cru_get_subdiurnal_met calls wgen_init
plume_mip_get_met calls wgen_init
mpidrv_master calls cru_get_subdiurnal_met, plume_mip_get_met
cable_offline_driver calls cru_get_subdiurnal_met, plume_mip_get_met
mpi_driver calls mpidrv_master