within_canopy – CABLE
within_canopy Subroutine
57 statements
Source File
public subroutine within_canopy(mp, CRMH2o, Crmair, CTETENA, CTETENB, CTETENC, CLAI_thresh, CCAPP, CTFRZ, rad, rough, air, met, veg, canopy, ssnow, gbhu, gbhf, qstvair, rt0, rhlitt, relitt)
Uses
cbl_qsat_module
cable_def_types_mod
cable_common_module
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: mp
real, intent(in) :: CRMH2o
real, intent(in) :: Crmair
real, intent(in) :: CTETENA
real, intent(in) :: CTETENB
real, intent(in) :: CTETENC
real, intent(in) :: CLAI_thresh
real, intent(in) :: CCAPP
real, intent(in) :: CTFRZ
type(radiation_type), intent(inout) :: rad
type(roughness_type), intent(inout) :: rough
type(air_type), intent(inout) :: air
type(met_type), intent(inout) :: met
type(veg_parameter_type), intent(inout) :: veg
type(canopy_type), intent(inout) :: canopy
type(soil_snow_type), intent(inout) :: ssnow
real(kind=r_2), intent(in), DIMENSION(:,:) :: gbhu
real(kind=r_2), intent(in), DIMENSION(:,:) :: gbhf
real, intent(inout) :: qstvair(mp)
real, intent(in), DIMENSION(mp) :: rt0
real, intent(in), DIMENSION(mp) :: rhlitt
real, intent(in), DIMENSION(mp) :: relitt
Calls
Called by
Contents
Call graph
within_canopy calls cls, epsi, fes, fev, fhs, fhv, hruff, meth, pmb, qsatfjh2, qstss, qv, qvair, rho, rlam, rt1, rtevap_sat, rtevap_unsat, satfrac, tk, tss, tvair, vlaiw, wetfac, z0soilsn
define_canopy calls within_canopy
cbm calls define_canopy
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker