worker_cable_params – CABLE
worker_cable_params Subroutine
1072 statements
Source File
private subroutine worker_cable_params(comm, met, air, ssnow, veg, bgc, soil, canopy, rough, rad, sum_flux, bal)
Uses
cable_def_types_mod
cable_IO_vars_module
cable_input_module
cable_common_module
mpi
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
type(met_type), intent(out) :: met
type(air_type), intent(out) :: air
type(soil_snow_type), intent(out) :: ssnow
type(veg_parameter_type), intent(out) :: veg
type(bgc_pool_type), intent(out) :: bgc
type(soil_parameter_type), intent(out) :: soil
type(canopy_type), intent(out) :: canopy
type(roughness_type), intent(out) :: rough
type(radiation_type), intent(out) :: rad
type(sum_flux_type), intent(out) :: sum_flux
type(balances_type), intent(out) :: bal
Calls
Called by
Contents
Call graph
worker_cable_params calls mpi_abort, mpi_comm_rank, mpi_get_address, mpi_get_count, mpi_recv, mpi_reduce, mpi_type_commit, mpi_type_create_struct, mpi_type_free, mpi_type_get_extent, mpi_type_size, mpi_unpack, allocate_cable_vars, decomp_types
allocate_cable_vars calls alloc_cbm_var
decomp_types calls mpi_get_address, mpi_type_commit, mpi_type_create_struct, mpi_type_create_resized
alloc_cbm_var calls alloc_air_type, alloc_balances_type, alloc_bgc_pool_type, alloc_canopy_type, alloc_climate_type, alloc_met_type, alloc_radiation_type, alloc_roughness_type, alloc_soil_parameter_type, alloc_soil_snow_type, alloc_sum_flux_type, alloc_veg_parameter_type
alloc_canopy_type calls sublayer_dz
alloc_soil_parameter_type calls bch_vec, clay_vec, drain_dens, elev, elev_std, gwbch_vec, gwdz, gwhyds_vec, gwrhosoil_vec, gwssat_vec, gwsucs_vec, gwwatr, gwz, hyds_vec, org_vec, rhosoil_vec, sand_vec, sfc_vec, silt_vec, slope, slope_std, ssat_vec, sucs_vec, swilt_vec, watr
alloc_soil_snow_type calls dhkdw, dsmpdw, evapfbl, fland, fracice, gwdhkdw, gwdsmpdw, gwhk, gwsmp, gwwb, gwwbeq, gwzq, hk, icefrac, ifland, otgg, otss, otss_0, owetfac, qasrf, qfsrf, qhlev, qhz, qrecharge, qssrf, qstss, rh_srf, rt_qh_sublayer, rtevap_sat, rtevap_unsat, satfrac, sinfil, smp, t_snwlr, tevap, tggav, tilefrac, totenbal, totenbal2, totwblake, tprecip, trnoff, wb_lake, wbeq, wbfice, wbliq, wbtot, wbtot1, wbtot2, wetfac, wmice, wmliq, wmtot, wtd, zq
alloc_veg_parameter_type calls a1gs, alpha, cfrd, conkc0, conko0, convex, d0gs, deciduous, ekc, eko, extkn, froot, gswmin, refl, taul, vlaimax, wai
mpidrv_worker calls worker_cable_params
mpi_driver calls mpidrv_worker