worker_time_update – CABLE
worker_time_update Subroutine
164 statements
Source File
private subroutine worker_time_update(met, kend, dels)
Uses
cable_IO_vars_module
cable_common_module
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
type(met_type), intent(inout) :: met
integer, intent(in) :: kend
real, intent(in) :: dels
Calls
Contents
Call graph
worker_time_update calls doy, hod, moy, year