worker_send_pop – CABLE
worker_send_pop Subroutine
11 statements
Source File
private subroutine worker_send_pop(pop, comm)
Uses
mpi
POP_Types
pop_mpi
Arguments
Type Intent Optional Attributes Name
type(POP_TYPE), intent(in) :: pop
integer, intent(in) :: comm
Calls
Called by
Contents
Call graph
worker_send_pop calls mpi_send, pop_grid
mpidrv_worker calls worker_send_pop, worker_casaonly_luc, worker_spincasacnp
worker_casaonly_luc calls worker_send_pop
worker_spincasacnp calls worker_send_pop
mpi_driver calls mpidrv_worker