worker_restart_type – CABLE
worker_restart_type Subroutine
91 statements
Source File
private subroutine worker_restart_type(comm, canopy, air)
Uses
cable_def_types_mod
mpi
Arguments
Type Intent Optional Attributes Name
integer :: comm
type(canopy_type), intent(in) :: canopy
type(air_type), intent(in) :: air
Calls
Called by
Contents
Call graph
worker_restart_type calls cduv, cmolar, dewmm, dgdtg, dsatdk, epsi, evapfbl, fnv, frpr, frpw, mpi_abort, mpi_comm_rank, mpi_get_address, mpi_reduce, mpi_type_commit, mpi_type_create_struct, mpi_type_get_extent, mpi_type_size, psyc, qsat, rho, visc, volm
mpidrv_worker calls worker_restart_type
mpi_driver calls mpidrv_worker