worker_casa_type – CABLE
worker_casa_type Subroutine
358 statements
Source File
private subroutine worker_casa_type(comm, casapool, casaflux, casamet, casabal, phen)
Uses
cable_def_types_mod
mpi
casadimension
phenvariable
casavariable
Arguments
Type Intent Optional Attributes Name
integer :: comm
type(casa_pool), intent(inout) :: casapool
type(casa_flux), intent(inout) :: casaflux
type(casa_met), intent(inout) :: casamet
type(casa_balance), intent(inout) :: casabal
type(phen_variable), intent(inout) :: phen
Calls
Called by
Contents
Call graph
worker_casa_type calls aphen, cgpp, clabile, clabloss, clitter, cnep, cnpp, cplant, cplant_turnover, cplant_turnover_crowding, cplant_turnover_disturbance, cplant_turnover_resource_limitation, crgplant, crp, crsoil, csoil, ctot, ctot_0, cwoodprod, doyphase, doyphasespin_1, doyphasespin_2, doyphasespin_3, doyphasespin_4, fcgppyear, fcneeyear, fcnppyear, fcrgrowyear, fcrmleafyear, fcrmrootyear, fcrmwoodyear, fcrpyear, fcrsyear, fndepyear, fnfixyear, fnleachyear, fnlossyear, fnsnetyear, fnupyear, fpdustyear, fpleachyear, fplossyear, fpsnetyear, fpupyear, fpweayear, frac_sapwood, fracclabile, glai, mpi_abort, mpi_get_address, mpi_reduce, mpi_type_commit, mpi_type_create_struct, mpi_type_get_extent, mpi_type_size, nlitter, nlittermin, nmindep, nminfix, nminleach, nminloss, nminuptake, nplant, nsimm, nsmin, nsnet, nsoil, nsoilmin, nupland, nwoodprod, phase, phasespin, plabuptake, plitter, pplant, psoil, psoillab, psoilocc, psoilsorb, psorbmax, pwoodprod, rationclitter, rationcplant, rationcsoil, ratiopclitter, ratiopcplant, ratiopcsoil, sapwood_area, sumcbal, sumnbal, sumpbal
mpidrv_worker calls worker_casa_type
mpi_driver calls mpidrv_worker