worker_casa_LUC_types – CABLE
worker_casa_LUC_types Subroutine
79 statements
Source File
private subroutine worker_casa_LUC_types(comm, casapool, casabal)
Uses
mpi
casavariable
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
type(casa_pool), intent(in) :: casapool
type(casa_balance), intent(in) :: casabal
Calls
Called by
Contents
Call graph
worker_casa_luc_types calls clabile, clitter, cplant, csoil, fcneeyear, mpi_abort, mpi_comm_rank, mpi_get_address, mpi_reduce, mpi_type_commit, mpi_type_create_struct, mpi_type_get_extent, mpi_type_size, nlitter, nplant, nsoil, nsoilmin, plitter, pplant, psoil
mpidrv_worker calls worker_casa_luc_types
mpi_driver calls mpidrv_worker