worker_spincasacnp – CABLE
worker_spincasacnp Subroutine
254 statements
Source File
private subroutine worker_spincasacnp(dels, kstart, kend, mloop, veg, soil, casabiome, casapool, casaflux, casamet, casabal, phen, POP, climate, LALLOC, icomm, ocomm)
Uses
cable_IO_vars_module
TypeDef
POP_Types
cable_carbon_module
phenvariable
POPModule
biogeochem_mod
cable_common_module
cable_def_types_mod
casadimension
mpi
casavariable
casaparm
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: dels
integer, intent(in) :: kstart
integer, intent(in) :: kend
integer, intent(in) :: mloop
type(veg_parameter_type), intent(inout) :: veg
type(soil_parameter_type), intent(inout) :: soil
type(casa_biome), intent(inout) :: casabiome
type(casa_pool), intent(inout) :: casapool
type(casa_flux), intent(inout) :: casaflux
type(casa_met), intent(inout) :: casamet
type(casa_balance), intent(inout) :: casabal
type(phen_variable), intent(inout) :: phen
type(POP_TYPE), intent(inout) :: POP
type(climate_type), intent(inout) :: climate
integer, intent(in) :: LALLOC
integer, intent(in) :: icomm
integer, intent(in) :: ocomm
Calls
Called by
Contents
Call graph
worker_spincasacnp calls cplant, fraccalloc, kplant, mpi_recv, mpi_send, analyticpool, biogeochem, popdriver, worker_send_pop, rationcsoilnew
analyticpool calls clay, clitter, csoil, fracligninplant, fromltos, fromstos, isorder, iveg, iveg2, klitter, kmlabp, ksoil, litterrate, nlitter, nsoil, psoillab, psorbmax, rationclitter, rationcsoil, rationplitter, rationpsoil, silt, soilrate
biogeochem calls cplant_turnover, disturbance_interval, klitter, pop_grid, avgsoil, casa_allocation, casa_cnpbal, casa_cnpcycle, casa_cnpflux, casa_coeffplant, casa_coeffsoil, casa_delplant, casa_delsoil, casa_ndummy, casa_nuptake, casa_pdummy, casa_puptake, casa_rplant, casa_rplant1, casa_xkn, casa_xnp, casa_xrateplant, casa_xratesoil, phenology
popdriver calls disturbance_intensity, disturbance_interval, popstep
worker_send_pop calls mpi_send, pop_grid
avgsoil calls btran, moist, moistavg, sfc, swilt, tsoilavg
casa_allocation calls cplant, fraccalloc, kplant, iveg, 1166, btran, crmplant, fracnpptop, glai, glaimax, glaimin, moistavg, casa_wolf, sfc, sla, swilt, tsoilavg
casa_cnpbal calls cplant, fraccalloc, kplant, iveg2, psoillab, 100, cbalance, cgpp, clabile, clabilelast, cnpp, cplantlast, crgplant, crmplant, crsoil, dclabiledt, dcplantdt, lat, lon, nmindep, nminfix, nminleach, nminloss, nminuptake, nsoilmin, nsoilminlast, nupland, pdep, plabuptake, pleach, ploss, psoillablast, psoilocc, psoilocclast, psoilsorb, psoilsorblast, pupland, pwea
casa_cnpcycle calls cplant, clitter, csoil, iveg, iveg2, kmlabp, nlitter, nsoil, psoillab, psorbmax, clabile, cwoodprod, dclabiledt, dclitterdt, dcplantdt, dcsoildt, dnlitterdt, dnplantdt, dnsoildt, dnsoilmindt, dplitterdt, dpplantdt, dpsoildt, dpsoillabdt, dpsoiloccdt, glai, glaimax, glaimin, lat, lon, nplant, nsoilmin, nwoodprod, plitter, pplant, casa_poolzero, psoil, psoilocc, pwoodprod, sla
casa_cnpflux calls crgplant, crmplant, fcrmleafyear, fcrmrootyear, fcrmwoodyear
casa_coeffplant calls cplant, kplant, fracligninplant, iveg, fromptol, ftransnptol, glai, glaimin, nplant, plantrate
casa_coeffsoil calls clay, fracligninplant, fromltos, fromstos, isorder, iveg, iveg2, ksoil, litterrate, silt, soilrate, fromltoco2, fromstoco2, xkplab, xkpocc, xkpsorb
casa_delplant calls cplant, fraccalloc, kplant, iveg, iveg2, cgpp, clabloss, cnpp, crgplant, crmplant, dcplantdt, dnplantdt, dpplantdt, fluxctolitter, fluxntolitter, fluxptolitter, fracclabile, fracnalloc, fracpalloc, fromptol, ftransnptol, ftranspptol, lnonwood, nminuptake, nplant, plabuptake, pplant
casa_delsoil calls rationcsoilnew, clitter, csoil, fromltos, fromstos, iveg, iveg2, klitter, kmlabp, ksoil, nlitter, nsoil, psoillab, psorbmax, 20, cnpp, costnpup, crsoil, dpsoillabdt, fluxctoco2, fluxctolitter, fluxctosoil, fluxntolitter, fluxntosoil, fluxptolitter, fluxptosoil, fnminleach, fnminloss, fpleach, fromltoco2, fromstoco2, kpocc, kpsorb, nlittermin, nmindep, nminfix, nminleach, nminloss, nsimm, nsmin, nsnet, nsoilmin, nupland, pdep, pleach, plitter, plittermin, prodptase, psimm, psmin, psnet, psoil, psoilocc, psoilsorb, pupland, pwea, ratiopcsoil, tsoilavg
casa_ndummy calls cplant, clitter, csoil, rationclitter, rationcsoil, rationcplant
casa_nuptake calls iveg, iveg2, 100, kminn, nminuptake, nsoilmin, casa_nrequire
casa_pdummy calls cplant, clitter, csoil, isorder, ratiopclitter, ratiopcplant, ratiopcsoil
casa_puptake calls iveg, psoillab, kuplabp, plabuptake, casa_prequire
casa_rplant calls cplant, iveg, cgpp, clabile, clabloss, cnpp, crgplant, crmplant, frac_sapwood, kclabrate, nplant, vcmax_np, qtemp_max_last_year, rationcplantmax, ratiopcplantmax, rmplant, sla, tairk, tsoilavg
casa_rplant1 calls cplant, iveg, cgpp, clabile, clabloss, cnpp, crgplant, crmplant, kclabrate, nplant, rationpplantmin, rmplant, tairk, tsoilavg
casa_xkn calls rationcsoilnew, clitter, csoil, fromltos, fromstos, iveg, iveg2, klitter, ksoil, nlitter, nsoil, maxcwd, maxfinelitter, nsoilmin, rationcsoilmax, rationcsoilmin
casa_xnp calls cplant, iveg, iveg2, psoillab, 20, cgpp, cnpp, fracclabile, nplant, nsoilmin, pplant, casa_nrequire, casa_prequire, xnpmax
casa_xrateplant calls iveg, iveg2, btran, phase, tairk, tkshed, xkleafcoldexp, xkleafcoldmax, xkleafdryexp, xkleafdrymax
casa_xratesoil calls iveg, iveg2, moistavg, q10soil, ssat, tsoilavg, xkoptlitter, xkoptsoil
phenology calls doyphase, phase
popstep calls pop_grid, getdiagnostics, getpatchfrequencies, getuniqueagefrequencies, patch_disturb, patch_partial_disturb, patch_partial_disturb2, patchannualdynamics
casa_nrequire calls cplant, fraccalloc, kplant, iveg, iveg2, ftransnptol, nplant, nsoilmin, rationcplantmax, rationcplantmin
casa_poolzero calls cplant, clitter, csoil, nlitter, nsoil, nplant
casa_prequire calls cplant, fraccalloc, kplant, iveg, iveg2, ftranspptol, pplant, ratiopcplantmax, ratiopcplantmin
casa_wolf calls cplant, iveg, iveg2, cnpp, fracnpptop
getdiagnostics calls pop_grid, get_allometry, interpolate_biomass_1d, interpolate_biomass_2d, smooth_flux
getpatchfrequencies calls pop_grid
getuniqueagefrequencies calls pop_grid, cumexponential, realexponential
patch_disturb calls pop_grid, layer_recruitment_single_patch
patch_partial_disturb calls pop_grid
patch_partial_disturb2 calls pop_grid
patchannualdynamics calls pop_grid, get_allometry, layer_recruitment
get_allometry calls allometry, getheight, williams_allometry
interpolate_biomass_1d calls pop_grid, realexponential
interpolate_biomass_2d calls pop_grid, realexponential, area_triangle
layer_recruitment calls pop_grid, get_allometry
layer_recruitment_single_patch calls pop_grid, get_allometry
smooth_flux calls pop_grid, regress
mpidrv_worker calls worker_spincasacnp
mpi_driver calls mpidrv_worker