worker_CASAONLY_LUC – CABLE
worker_CASAONLY_LUC Subroutine
110 statements
Source File
private subroutine worker_CASAONLY_LUC(dels, kstart, kend, veg, soil, casabiome, casapool, casaflux, casamet, casabal, phen, POP, climate, LALLOC, icomm, ocomm)
Uses
cable_def_types_mod
mpi
casadimension
TypeDef
phenvariable
POP_Types
cable_IO_vars_module
cable_carbon_module
cable_common_module
casavariable
biogeochem_mod
POPModule
casaparm
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: dels
integer, intent(in) :: kstart
integer, intent(in) :: kend
type(veg_parameter_type), intent(inout) :: veg
type(soil_parameter_type), intent(inout) :: soil
type(casa_biome), intent(inout) :: casabiome
type(casa_pool), intent(inout) :: casapool
type(casa_flux), intent(inout) :: casaflux
type(casa_met), intent(inout) :: casamet
type(casa_balance), intent(inout) :: casabal
type(phen_variable), intent(inout) :: phen
type(POP_TYPE), intent(inout) :: POP
type(climate_type), intent(inout) :: climate
integer, intent(in) :: LALLOC
integer, intent(in) :: icomm
integer, intent(in) :: ocomm
Calls
Called by
Contents
Call graph
worker_casaonly_luc calls cplant, fraccalloc, mpi_comm_rank, mpi_recv, mpi_send, pop_grid, biogeochem, popdriver, worker_send_pop
biogeochem calls pop_grid, cplant_turnover, disturbance_interval, klitter, avgsoil, casa_allocation, casa_cnpbal, casa_cnpcycle, casa_cnpflux, casa_coeffplant, casa_coeffsoil, casa_delplant, casa_delsoil, casa_ndummy, casa_nuptake, casa_pdummy, casa_puptake, casa_rplant, casa_rplant1, casa_xkn, casa_xnp, casa_xrateplant, casa_xratesoil, phenology
popdriver calls disturbance_intensity, disturbance_interval, popstep
worker_send_pop calls mpi_send, pop_grid
avgsoil calls btran, moist, moistavg, sfc, swilt, tsoilavg
casa_allocation calls cplant, fraccalloc, 1166, btran, crmplant, fracnpptop, glai, glaimax, glaimin, iveg, kplant, moistavg, casa_wolf, sfc, sla, swilt, tsoilavg
casa_cnpbal calls cplant, fraccalloc, 100, cbalance, cgpp, clabile, clabilelast, cnpp, cplantlast, crgplant, crmplant, crsoil, dclabiledt, dcplantdt, iveg2, kplant, lat, lon, nmindep, nminfix, nminleach, nminloss, nminuptake, nsoilmin, nsoilminlast, nupland, pdep, plabuptake, pleach, ploss, psoillab, psoillablast, psoilocc, psoilocclast, psoilsorb, psoilsorblast, pupland, pwea
casa_cnpcycle calls cplant, clabile, clitter, csoil, cwoodprod, dclabiledt, dclitterdt, dcplantdt, dcsoildt, dnlitterdt, dnplantdt, dnsoildt, dnsoilmindt, dplitterdt, dpplantdt, dpsoildt, dpsoillabdt, dpsoiloccdt, glai, glaimax, glaimin, iveg, iveg2, kmlabp, lat, lon, nlitter, nplant, nsoil, nsoilmin, nwoodprod, plitter, pplant, casa_poolzero, psoil, psoillab, psoilocc, psorbmax, pwoodprod, sla
casa_cnpflux calls crgplant, crmplant, fcrmleafyear, fcrmrootyear, fcrmwoodyear
casa_coeffplant calls cplant, fracligninplant, fromptol, ftransnptol, glai, glaimin, iveg, kplant, nplant, plantrate
casa_coeffsoil calls clay, fracligninplant, fromltoco2, fromltos, fromstoco2, fromstos, isorder, iveg, iveg2, ksoil, litterrate, silt, soilrate, xkplab, xkpocc, xkpsorb
casa_delplant calls cplant, fraccalloc, cgpp, clabloss, cnpp, crgplant, crmplant, dcplantdt, dnplantdt, dpplantdt, fluxctolitter, fluxntolitter, fluxptolitter, fracclabile, fracnalloc, fracpalloc, fromptol, ftransnptol, ftranspptol, iveg, iveg2, kplant, lnonwood, nminuptake, nplant, plabuptake, pplant
casa_delsoil calls klitter, 20, clitter, cnpp, costnpup, crsoil, csoil, dpsoillabdt, fluxctoco2, fluxctolitter, fluxctosoil, fluxntolitter, fluxntosoil, fluxptolitter, fluxptosoil, fnminleach, fnminloss, fpleach, fromltoco2, fromltos, fromstoco2, fromstos, iveg, iveg2, kmlabp, kpocc, kpsorb, ksoil, nlitter, nlittermin, nmindep, nminfix, nminleach, nminloss, nsimm, nsmin, nsnet, nsoil, nsoilmin, nupland, pdep, pleach, plitter, plittermin, prodptase, psimm, psmin, psnet, psoil, psoillab, psoilocc, psoilsorb, psorbmax, pupland, pwea, rationcsoilnew, ratiopcsoil, tsoilavg
casa_ndummy calls cplant, clitter, csoil, rationclitter, rationcplant, rationcsoil
casa_nuptake calls 100, iveg, iveg2, kminn, nminuptake, nsoilmin, casa_nrequire
casa_pdummy calls cplant, clitter, csoil, isorder, ratiopclitter, ratiopcplant, ratiopcsoil
casa_puptake calls iveg, kuplabp, plabuptake, casa_prequire, psoillab
casa_rplant calls cplant, cgpp, clabile, clabloss, cnpp, crgplant, crmplant, frac_sapwood, iveg, kclabrate, nplant, vcmax_np, qtemp_max_last_year, rationcplantmax, ratiopcplantmax, rmplant, sla, tairk, tsoilavg
casa_rplant1 calls cplant, cgpp, clabile, clabloss, cnpp, crgplant, crmplant, iveg, kclabrate, nplant, rationpplantmin, rmplant, tairk, tsoilavg
casa_xkn calls klitter, clitter, csoil, fromltos, fromstos, iveg, iveg2, ksoil, maxcwd, maxfinelitter, nlitter, nsoil, nsoilmin, rationcsoilmax, rationcsoilmin, rationcsoilnew
casa_xnp calls cplant, 20, cgpp, cnpp, fracclabile, iveg, iveg2, nplant, nsoilmin, pplant, casa_nrequire, casa_prequire, psoillab, xnpmax
casa_xrateplant calls btran, iveg, iveg2, phase, tairk, tkshed, xkleafcoldexp, xkleafcoldmax, xkleafdryexp, xkleafdrymax
casa_xratesoil calls iveg, iveg2, moistavg, q10soil, ssat, tsoilavg, xkoptlitter, xkoptsoil
phenology calls doyphase, phase
popstep calls pop_grid, getdiagnostics, getpatchfrequencies, getuniqueagefrequencies, patch_disturb, patch_partial_disturb, patch_partial_disturb2, patchannualdynamics
casa_nrequire calls cplant, fraccalloc, ftransnptol, iveg, iveg2, kplant, nplant, nsoilmin, rationcplantmax, rationcplantmin
casa_poolzero calls cplant, clitter, csoil, nlitter, nplant, nsoil
casa_prequire calls cplant, fraccalloc, ftranspptol, iveg, iveg2, kplant, pplant, ratiopcplantmax, ratiopcplantmin
casa_wolf calls cplant, cnpp, fracnpptop, iveg, iveg2
getdiagnostics calls pop_grid, get_allometry, interpolate_biomass_1d, interpolate_biomass_2d, smooth_flux
getpatchfrequencies calls pop_grid
getuniqueagefrequencies calls pop_grid, cumexponential, realexponential
patch_disturb calls pop_grid, layer_recruitment_single_patch
patch_partial_disturb calls pop_grid
patch_partial_disturb2 calls pop_grid
patchannualdynamics calls pop_grid, get_allometry, layer_recruitment
get_allometry calls allometry, getheight, williams_allometry
interpolate_biomass_1d calls pop_grid, realexponential
interpolate_biomass_2d calls pop_grid, realexponential, area_triangle
layer_recruitment calls pop_grid, get_allometry
layer_recruitment_single_patch calls pop_grid, get_allometry
smooth_flux calls pop_grid, regress
mpidrv_worker calls worker_casaonly_luc
mpi_driver calls mpidrv_worker