worker_pop_types – CABLE
worker_pop_types Subroutine
49 statements
Source File
private subroutine worker_pop_types(comm, veg, casamet, pop)
Uses
POP_Types
casavariable
cable_def_types_mod
cable_common_module
POPModule
mpi
pop_mpi
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
type(veg_parameter_type), intent(in) :: veg
type(casa_met), intent(in) :: casamet
type(POP_TYPE), intent(inout) :: pop
Calls
Called by
Contents
Call graph
worker_pop_types calls mpi_comm_rank, mpi_recv, pop_grid, create_pop_gridcell_type, pop_init
create_pop_gridcell_type calls mpi_abort, mpi_get_address, mpi_type_commit, mpi_type_create_resized, mpi_type_create_struct, create_patch
pop_init calls alloc_pop, initpop2d_poisson, layer_recruitment_single_patch, zeropop
alloc_pop calls pop_grid, it_pop, iwood
create_patch calls mpi_abort, mpi_get_address, mpi_type_commit, mpi_type_create_resized, mpi_type_create_struct, create_layer
initpop2d_poisson calls pop_grid, cumexponential, exponential
layer_recruitment_single_patch calls pop_grid, get_allometry
create_layer calls mpi_abort, mpi_get_address, mpi_type_commit, mpi_type_create_resized, mpi_type_create_struct, create_cohort
get_allometry calls allometry, getheight, williams_allometry
create_cohort calls mpi_abort, mpi_get_address, mpi_type_commit, mpi_type_create_resized, mpi_type_create_struct
mpidrv_worker calls worker_pop_types
mpi_driver calls mpidrv_worker