worker_outtype – CABLE
worker_outtype Subroutine
704 statements
Source File
private subroutine worker_outtype(comm, met, canopy, ssnow, rad, bal, air, soil, veg)
Uses
cable_def_types_mod
mpi
Arguments
Type Intent Optional Attributes Name
integer :: comm
type(met_type), intent(in) :: met
type(canopy_type), intent(in) :: canopy
type(soil_snow_type), intent(in) :: ssnow
type(radiation_type), intent(in) :: rad
type(balances_type), intent(inout) :: bal
type(air_type), intent(in) :: air
type(soil_parameter_type), intent(in) :: soil
type(veg_parameter_type), intent(in) :: veg
Calls
Called by
Contents
Call graph
worker_outtype calls albedo, albsoil, albsoilsn, bch, c3, ca, canst1, cansto, cdtq, cduv, cexpkbm, cexpkdm, clay, cls, cmolar, cnsd, coszen, css, da, ddq_dtg, deciduous, delwc, delwcol, dewmm, dfe_ddq, dfe_dtg, dfh_dtg, dfn_dtg, dgdtg, dleaf, drybal, dsatdk, dtmlt, dva, ejmax, epot, epsi, evap, evapfbl, evapsn, extkb, extkbm, extkd, extkd2, extkdm, extkn, fbeam, fe, fes, fes_cor, fesp, fess, fev, fevc, fevw, fevw_pot, fh, fhs, fhs_cor, fhv, fhvw, fld, flws, fnee, fnpp, fns, fns_cor, fnv, fpn, frac4, frday, froot, frp, frpr, frpw, frs, fsd, fvlai, fwet, fwsoil, fwtop, fwtop1, fwtop2, fwtop3, ga, ga_cor, gammzz, ghflux, gradis, gswx, gswx_t, gwwb, h0, hc, hsbh, hyds, i2bp3, ibp2, isflag, isoilm, iveg, lwabv, meth, mpi_abort, mpi_comm_rank, mpi_get_address, mpi_reduce, mpi_type_commit, mpi_type_create_struct, mpi_type_get_extent, mpi_type_size, nsnow, nsteps, osnowd, osnowd0, otss, otss_0, owetfac, pmb, potev, precip, precip_sn, precis, find_extents, psyc, pudsmx, pudsto, pwb_min, qcan, qrecharge, qsat, qscrn, qssabs, qstss, qv, qvair, reffbm, reffdf, refl, rghlai, rho, rhocbm, rhocdf, rhosoil, rlam, rnet, rniso, rnof1, rnof2, rp20, rpcoef, rs20, rtsoil, runoff, s, sand, satfrac, scalex, sconds, sdepth, segg, sfc, sghflux, shelrb, silt, sinfil, smass, smelt, snage, snowd, snowliq, spill, ssat, ssdn, ssdnn, sucs, swilt, t_snwlr, taul, tgg, tggav, tggsn, thetai, through, tk, tmaxvj, tminvj, trad, transb, transd, tscrn, tsoil, tss, tsurface, tv, tvair, tvrad, ua, us, uscrn, vbeta, vcmax, vegcf, visc, vlai, vlaiw, volm, wai, wb, wb_lake, wbfice, wbice, wblf, wbtot, wbtot0, wcint, wetbal, wetfac, wetfac_cs, wtd, xalbnir, xfang, zetar
find_extents calls mpi_get_address
mpidrv_worker calls worker_outtype
mpi_driver calls mpidrv_worker