worker_casa_params – CABLE
worker_casa_params Subroutine
709 statements
Source File
private subroutine worker_casa_params(comm, casabiome, casapool, casaflux, casamet, casabal, phen)
Uses
cable_def_types_mod
mpi
phenvariable
casavariable
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
type(casa_biome), intent(out) :: casabiome
type(casa_pool), intent(out) :: casapool
type(casa_flux), intent(out) :: casaflux
type(casa_met), intent(out) :: casamet
type(casa_balance), intent(out) :: casabal
type(phen_variable), intent(out) :: phen
Calls
Called by
Contents
Call graph
worker_casa_params calls aphen, doyphasespin_1, doyphasespin_2, doyphasespin_3, doyphasespin_4, mpi_abort, mpi_barrier, mpi_comm_rank, mpi_get_address, mpi_get_count, mpi_recv, mpi_reduce, mpi_type_commit, mpi_type_create_struct, mpi_type_free, mpi_type_get_extent, mpi_type_size, mpi_unpack, phasespin, alloc_casavariable, alloc_phenvariable
alloc_casavariable calls areacell, btran, cbalance, cgpp, cgppspin, clabile, clabilelast, clabloss, cleafmean, clitter, clitterlast, cnep, cnpp, costnpup, cplant, cplant_turnover, cplant_turnover_crowding, cplant_turnover_disturbance, cplant_turnover_resource_limitation, cplantlast, crgplant, crmplant, crmplantspin_1, crmplantspin_2, crmplantspin_3, crootmean, crp, crsoil, csoil, csoillast, ctot, ctot_0, ctransferluc, cwoodprod, dcdtyear, dclabiledt, dclitterdt, dcplantdt, dcsoildt, dnlitterdt, dnplantdt, dnsoildt, dnsoilmindt, dplitterdt, dpplantdt, dpsoildt, dpsoillabdt, dpsoiloccdt, dpsoilsorbdt, fcgppyear, fcneeyear, fcnppyear, fcrgrowyear, fcrmleafyear, fcrmrootyear, fcrmwoodyear, fcrpyear, fcrsyear, fluxctoclear, fluxctoco2, fluxctohwp, fluxctolitter, fluxctosoil, fluxntoclear, fluxntohwp, fluxntolitter, fluxntosoil, fluxptoclear, fluxptohwp, fluxptolitter, fluxptosoil, fndepyear, fnfixyear, fnleachyear, fnlossyear, fnminleach, fnminloss, fnsnetyear, fnupyear, fpdustyear, fpleach, fpleachyear, fplossyear, fpsnetyear, fpupyear, fpweayear, frac_sapwood, fraccalloc, fracclabile, fraclabile, fraclignin, fracligninplant, fracnalloc, fracnpptop, fracpalloc, fromltoco2, fromltos, fromptol, fromstoco2, fromstos, ftransnptol, ftranspptol, glai, glaimax, glaimin, glaimon, glaimonx, ijgcm, isorder, iveg2, ivt2, kclabrate, klitter, kminn, kmlabp, kplab, kplant, kpocc, kpsorb, kroot, krootlen, ksoil, kuplabp, kuptake, laimax, lat, litterrate, lnonwood, lon, maxcwd, maxfinelitter, meangpp, meanrleaf, moist, moistavg, moistspin_1, moistspin_2, moistspin_3, moistspin_4, moistspin_5, moistspin_6, mtempspin, nbalance, nintercept, nlitter, nlitterlast, nlittermin, nmindep, nminfix, nminleach, nminloss, nminuptake, nplant, nplantlast, nsimm, nslope, nsmin, nsnet, nsoil, nsoillast, nsoilmin, nsoilminlast, nupland, nwoodprod, pbalance, pdep, plabuptake, plantrate, pleach, plitter, plitterlast, plittermin, ploss, pplant, pplantlast, precip, prodptase, psimm, psmin, psnet, psoil, psoillab, psoillablast, psoillast, psoilocc, psoilocclast, psoilsorb, psoilsorblast, psorbmax, pupland, pwea, pwoodprod, q10soil, ratiofrootleaf, rationclitter, rationcplant, rationcplantmax, rationcplantmin, rationcsoil, rationcsoilmax, rationcsoilmin, rationcsoilnew, rationplitter, rationpplant, rationpplantmax, rationpplantmin, rationpsoil, ratiopclitter, ratiopcplant, ratiopcplantmax, ratiopcplantmin, ratiopcsoil, rmplant, rootdepth, sapwood_area, sla, soilrate, stemnpp, sumcbal, sumnbal, sumpbal, tairk, tairkspin, tsoil, tsoilavg, tsoilspin_1, tsoilspin_2, tsoilspin_3, tsoilspin_4, tsoilspin_5, tsoilspin_6, xkleafcoldexp, xkleafcoldmax, xkleafdryexp, xkleafdrymax, xkoptlitter, xkoptsoil, xkplab, xkpocc, xkpsorb, xnpmax
alloc_phenvariable calls aphen, doyphasespin_1, doyphasespin_2, doyphasespin_3, doyphasespin_4, phasespin, doyphase, phase, tkshed
mpidrv_worker calls worker_casa_params
mpi_driver calls mpidrv_worker