WRITE_LUC_RESTART_NC – CABLE
WRITE_LUC_RESTART_NC Subroutine
88 statements
Source File
public subroutine WRITE_LUC_RESTART_NC(POPLUC, ctime)
Uses
netcdf
casa_ncdf_module
cable_common_module
Arguments
Type Intent Optional Attributes Name
type(POPLUC_TYPE), intent(in) :: POPLUC
integer, intent(in) :: ctime
Calls
Called by
Contents
Call graph
write_luc_restart_nc calls nf90_close, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_put_att, nf90_put_var, nf90_redef, handle_err
handle_err calls nf90_strerror
casaonly_luc calls write_luc_restart_nc
master_casaonly_luc calls write_luc_restart_nc
mpidrv_master calls write_luc_restart_nc, master_casaonly_luc
cable_offline_driver calls write_luc_restart_nc, casaonly_luc
mpi_driver calls mpidrv_master