write_output_variable_r1 – CABLE
write_output_variable_r1 Subroutine
73 statements
Source File
private subroutine write_output_variable_r1(ktau, ncid, varID, vname, var_r1, vrange, writepatch, dimswitch, met)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ktau
integer, intent(in) :: ncid
integer, intent(in) :: varID
character(len=*), intent(in) :: vname
real(kind=4), intent(in), DIMENSION(:) :: var_r1
real, intent(in), DIMENSION(2) :: vrange
logical, intent(in) :: writepatch
character(len=*), intent(in) :: dimswitch
type(met_type), intent(in) :: met
Calls
Called by
Contents
Call graph
write_output_variable_r1 calls grid, nf90_put_var, nc_abort, range_abort
nc_abort calls nf90_strerror
range_abort calls doy, hod, year
write_ovar calls write_output_variable_r1
create_landuse_cable_restart calls write_ovar
create_restart calls write_ovar
open_output_file calls write_ovar
write_output calls write_ovar
mpidrv_master calls create_landuse_cable_restart, create_restart, open_output_file, write_output
cable_offline_driver calls create_landuse_cable_restart, create_restart, open_output_file, write_output
mpi_driver calls mpidrv_master