WRITE_CLIMATE_RESTART_NC – CABLE
WRITE_CLIMATE_RESTART_NC Subroutine
155 statements
Source File
public subroutine WRITE_CLIMATE_RESTART_NC(climate, ktauday)
Uses
netcdf
Arguments
Type Intent Optional Attributes Name
type(climate_type), intent(in) :: climate
integer, intent(in) :: ktauday
Calls
Called by
Contents
Call graph
write_climate_restart_nc calls nf90_close, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_put_att, nf90_put_var, nf90_redef, handle_err
handle_err calls nf90_strerror
mpidrv_master calls write_climate_restart_nc
cable_offline_driver calls write_climate_restart_nc
mpi_driver calls mpidrv_master