write_casa_dump – CABLE
write_casa_dump Subroutine
67 statements
Source File
public subroutine write_casa_dump(ncfile, casamet, casaflux, phen, climate, n_call, kend)
Uses
netcdf
cable_def_types_mod
casavariable
casadimension
phenvariable
cable_common_module
casa_ncdf_module
Arguments
Type Intent Optional Attributes Name
character(len=*) :: ncfile
type(casa_met), intent(in) :: casamet
type(casa_flux), intent(in) :: casaflux
type(phen_variable), intent(in) :: phen
type(climate_type), intent(in) :: climate
integer, intent(in) :: n_call
integer, intent(in) :: kend
Calls
Called by
Contents
Call graph
write_casa_dump calls doyphase, nf90_close, nf90_create, nf90_enddef, def_dims, def_vars, put_var_ncr1, put_var_ncr2, put_var_ncr3, stderr_nc
def_dims calls stderr_nc, nf90_def_dim
def_vars calls stderr_nc, nf90_def_var
put_var_ncr1 calls stderr_nc, nf90_inq_varid, nf90_put_var
put_var_ncr2 calls stderr_nc, nf90_inq_varid, nf90_put_var
put_var_ncr3 calls stderr_nc, nf90_inq_varid, nf90_put_var
stderr_nc calls nf90_strerror
mpidrv_master calls write_casa_dump
cable_offline_driver calls write_casa_dump
mpi_driver calls mpidrv_master