write_output – CABLE
write_output Subroutine
772 statements
Source File
public subroutine write_output(dels, ktau, met, canopy, casaflux, casapool, casamet, ssnow, rad, bal, air, soil, veg, SBOLTZ, EMLEAF, EMSOIL)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: dels
integer, intent(in) :: ktau
type(met_type), intent(in) :: met
type(canopy_type), intent(in) :: canopy
type(casa_flux), intent(in) :: casaflux
type(casa_pool), intent(in) :: casapool
type(casa_met), intent(in) :: casamet
type(soil_snow_type), intent(in) :: ssnow
type(radiation_type), intent(in) :: rad
type(balances_type), intent(inout) :: bal
type(air_type), intent(in) :: air
type(soil_parameter_type), intent(in) :: soil
type(veg_parameter_type), intent(in) :: veg
real, intent(in) :: SBOLTZ
real, intent(in) :: EMLEAF
real, intent(in) :: EMSOIL
Calls
Called by
Contents
Call graph
write_output calls albedo, averaging, clitter, cplant, cplant_turnover, crmplant, csoil, fsd, write_ovar, nf90_put_var, nf90_sync, energy_balance, is_leapyear, mass_balance, nc_abort, qcan, tdaymn, tdaymx, tgg, tggsn, tnn, tscrn, txx, year
write_ovar calls write_output_parameter_r1, write_output_parameter_r1d, write_output_parameter_r2, write_output_parameter_r2d, write_output_variable_r1, write_output_variable_r2
energy_balance calls albedo, fsd, qcan
nc_abort calls nf90_strerror
write_output_parameter_r1 calls nf90_put_var, nc_abort, grid
write_output_parameter_r1d calls nf90_put_var, nc_abort
write_output_parameter_r2 calls nf90_put_var, nc_abort, grid
write_output_parameter_r2d calls nf90_put_var, nc_abort
write_output_variable_r1 calls nf90_put_var, nc_abort, grid, range_abort
write_output_variable_r2 calls nf90_put_var, nc_abort, grid, range_abort
range_abort calls year, doy, hod
mpidrv_master calls write_output
cable_offline_driver calls write_output
mpi_driver calls mpidrv_master