WRITE_LUC_OUTPUT_GRID_NC – CABLE
WRITE_LUC_OUTPUT_GRID_NC Subroutine
319 statements
Source File
public subroutine WRITE_LUC_OUTPUT_GRID_NC(POPLUC, ctime, FINAL)
Uses
cable_common_module
cable_IO_vars_module
casa_ncdf_module
netcdf
Arguments
Type Intent Optional Attributes Name
type(POPLUC_TYPE), intent(in) :: POPLUC
integer, intent(in) :: ctime
logical, intent(in) :: FINAL
Calls
Called by
Contents
Call graph
write_luc_output_grid_nc calls cbiomass, clearprod, clearprodloss, clitt, csoil, fclearance, fharvest, fnep, ftransfergross, ftransfernet, harvprod, harvprodloss, nf90_close, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_put_att, nf90_put_var, nf90_redef, handle_err
handle_err calls nf90_strerror
casaonly_luc calls write_luc_output_grid_nc
master_casaonly_luc calls write_luc_output_grid_nc
mpidrv_master calls write_luc_output_grid_nc, master_casaonly_luc
cable_offline_driver calls casaonly_luc
mpi_driver calls mpidrv_master