write_default_params – CABLE
write_default_params Subroutine
310 statements
Source File
public subroutine write_default_params(met, air, ssnow, veg, bgc, soil, canopy, rough, rad, logn, vegparmnew, month, TFRZ, LUC_EXPT)
Uses
cable_common_module
Arguments
Type Intent Optional Attributes Name
type(met_type), intent(inout) :: met
type(air_type), intent(inout) :: air
type(soil_snow_type), intent(inout) :: ssnow
type(veg_parameter_type), intent(inout) :: veg
type(bgc_pool_type), intent(inout) :: bgc
type(soil_parameter_type), intent(inout) :: soil
type(canopy_type), intent(inout) :: canopy
type(roughness_type), intent(inout) :: rough
type(radiation_type), intent(inout) :: rad
integer, intent(in) :: logn
logical, intent(in) :: vegparmnew
integer, intent(in) :: month
real, intent(in) :: TFRZ
type(LUC_EXPT_TYPE), intent(in) :: LUC_EXPT
Calls
Called by
Contents
Call graph
write_default_params calls bch, clay, cplant1, cplant2, cplant3, csoil1, csoil2, css, hyds, isoilm, iveg, init_veg_from_vegin, ratecp1, ratecp2, ratecp3, ratecs1, ratecs2, rhosoil, sand, sfc, silt, snowd, ssat, sucs, swilt, tgg, vcmax, watr, wb
init_veg_from_vegin calls iveg, vcmax, a1gs, alpha, canst1, cfrd, clitt, conkc0, conko0, convex, d0gs, dleaf, ejmax, ekc, eko, extkn, frac4, froot, g0, g1, gswmin, hc, refl1, refl2, rootbeta, rp20, rpcoef, rs20, shelrb, taul1, taul2, tmaxvj, tminvj, vbeta, vegcf, wai, xalbnir, xfang, zr
load_parameters calls write_default_params
mpidrv_master calls load_parameters
cable_offline_driver calls load_parameters
mpi_driver calls mpidrv_master