WRITE_CASA_OUTPUT_NC – CABLE
WRITE_CASA_OUTPUT_NC Subroutine
628 statements
Source File
public subroutine WRITE_CASA_OUTPUT_NC(veg, casamet, casapool, casabal, casaflux, CASAONLY, ctime, FINAL)
Uses
cable_def_types_mod
casavariable
casa_ncdf_module
cable_common_module
netcdf
Arguments
Type Intent Optional Attributes Name
type(veg_parameter_type), intent(in) :: veg
type(casa_met), intent(in) :: casamet
type(casa_pool), intent(in) :: casapool
type(casa_balance), intent(in) :: casabal
type(casa_flux), intent(in) :: casaflux
logical :: CASAONLY
integer :: ctime
logical :: FINAL
Calls
Called by
Contents
Call graph
write_casa_output_nc calls fcrgrowyear, fcrmleafyear, fcrmrootyear, fcrmwoodyear, nf90_close, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_inq_dimid, nf90_inq_varid, nf90_open, nf90_put_att, nf90_put_var, nf90_redef, handle_err
handle_err calls nf90_strerror
casaonly_luc calls write_casa_output_nc
mpidrv_master calls write_casa_output_nc
cable_offline_driver calls write_casa_output_nc, casaonly_luc
mpi_driver calls mpidrv_master