write_cnp_params – CABLE
write_cnp_params Subroutine
29 statements
Source File
public subroutine write_cnp_params(veg, casaflux, casamet)
Uses
casaparm
Arguments
Type Intent Optional Attributes Name
type(veg_parameter_type), intent(in) :: veg
type(casa_flux), intent(inout) :: casaflux
type(casa_met), intent(inout) :: casamet
Calls
Called by
Contents
Call graph
write_cnp_params calls iveg, nmindep, pdep
load_parameters calls write_cnp_params
mpidrv_master calls load_parameters
cable_offline_driver calls load_parameters
mpi_driver calls mpidrv_master