zerovars – CABLE
zerovars Function
42 statements
Source File
public function zerovars()
Arguments
None
Return Value type(vars)
Called by
Contents
None
Call graph
get_fluxes_and_derivs calls zerovars, getfluxes_vp
getfluxes_vp_1d calls zerovars
getfluxes_vp_2d calls zerovars
solve calls zerovars, timestep_loop
getfluxes_vp calls getfluxes_vp_1d, getfluxes_vp_2d
iflux_loop calls get_fluxes_and_derivs
sli_main calls solve
timestep_loop calls iflux_loop